const defs={
 public:{role:'자료 담당자',input:'공개 정책보고서·공식 통계·허용된 뉴스·공개 정책의견',action:'자료의 기간·원출처·이용조건을 확인해 반입 대상을 고른다.',output:'출처 목록과 반입 파일',human:'원문 이용권과 공개 범위를 확인한다.',exception:'이용권 미확인 또는 비공개 민원은 반입 대기.',screen:'자료함',doc:'F01',data:'Source: 출처·기간·권리·원문 위치'},
 internal:{role:'업무부서 자료 소유자',input:'TS 사업계획·기존 계약·검수·업무 현황 자료',action:'정책 의제와 관련된 자료를 부서 접근권한에 맞게 제공한다.',output:'권한이 붙은 내부 자료 묶음',human:'제공 범위와 개인정보 처리를 확인한다.',exception:'다른 부서의 원문 접근권한을 자동 부여하지 않는다.',screen:'자료함',doc:'F01',data:'Source: 소유부서·접근등급·유효일'},
 intake:{role:'업무·기획 담당자',input:'검토할 의제, 대상 국민·업무, 기간, 허용 자료',action:'무엇을 알아보려는지와 자료 범위를 등록한다.',output:'검토 의제와 조사 질문',human:'의제의 범위와 담당자를 확인한다.',exception:'의제가 넓으면 대상·기간을 줄여 다시 등록.',screen:'자료함',doc:'F01',data:'Issue.seed + Source IDs'},
 ingest:{role:'권한·반입 규칙',input:'전자문서와 자료별 권한·기간·원출처',action:'형식·권한을 검사하고 원문 위치를 보존한다. 전재·재배포 문서는 같은 자료군으로 연결한다.',output:'분석 가능한 문서와 자료군 ID',human:'격리·중복 후보를 검토하고 허용 여부를 결정한다.',exception:'스캔·비인가·읽기 실패 자료는 사유를 표시하고 별도로 보완.',screen:'자료함',doc:'F01',data:'Source, SourceGroup, AccessPolicy'},
 claim:{role:'NOA + 로컬 LLM',input:'허용된 자료 구간과 분석 질문',action:'사실·의견·가설을 구분하고 주장별 지지·반대 근거와 원문 위치를 연결한다.',output:'근거 카드와 조사 공백',human:'숫자의 분모·기간과 인용이 원문에 맞는지 확인한다.',exception:'기사 건수를 독립 근거 수로 일반화하지 않으며 원인이 불명확하면 가설로 남긴다.',screen:'문제 카드',doc:'F01',data:'Claim, EvidenceRef, SourceGroup'},
 problem:{role:'NOA 초안 + 업무 담당 검토',input:'근거 카드, 대상, 불편·위험, 현황',action:'누가 어떤 과정에서 어떤 불이익을 겪는지 작성하고 현상·원인 가설·조사 필요를 나눈다.',output:'문제정의 카드',human:'문제의 타당성·원인 가설·반대 의견을 확인한다.',exception:'근거가 부족하면 추가조사 또는 유보. AI 문장을 검증된 원인으로 확정하지 않는다.',screen:'문제 카드',doc:'F01',data:'Issue, Claim IDs, review_status'},
 scopecheck:{role:'업무·기획 담당자',input:'문제 카드, TS 소관 근거, 현행 사업·계약',action:'TS 단독·협업·타기관·미확인을 구분하고 기존 수행 범위와 추가할 일을 비교한다.',output:'소관·기존사업 중복 검토',human:'실제 업무 소관과 계약 추가분을 판단한다.',exception:'타기관 소관이면 협업·인계안을 검토하고 TS 단독 신규사업으로 확정하지 않는다.',screen:'대안 비교',doc:'F01',data:'MandateRef, ExistingProjectRef, ScopeDelta'},
 alternative:{role:'NOA 초안 + 기획 담당자',input:'확인된 문제·소관·기존 대응·제약',action:'현행 유지·운영 개선·기구축 고도화·신규 도입을 효과·비용·기간·의존성으로 비교한다.',output:'대안 비교표와 선택 사유',human:'어떤 대안을 추진·유보할지 결정한다.',exception:'AI 도입을 미리 정답으로 두지 않는다. 불확실한 효과는 검증 가설로 표시.',screen:'대안 비교',doc:'F01',data:'Alternative, Decision, Scope'},
 project:{role:'기획·업무·정보화 담당자',input:'선택한 대안·수행 주체·기존 자산·검수 목표',action:'목표·대상·포함/제외 범위·요구사항·일정·비용 항목을 같은 사업 ID에 연결한다.',output:'공통 사업원장 버전',human:'범위·실행 가능성·책임자를 확인한다.',exception:'현행 API·사용권·서버 여력이 미확인이면 선행조건으로 남긴다.',screen:'사업 작업대',doc:'F02',data:'Project, Scope, Requirement, Acceptance'},
 budget:{role:'계산 규칙 + 예산 담당자',input:'수량·단가·공수·연차·VAT·운영비·근거',action:'산식으로 비용과 증감을 계산하고 누락 연차를 표시한다. 요구액·승인액·계약액을 구분한다.',output:'예산 요구 시나리오와 불완전 항목',human:'재원·제출 경로·비목·비용 인정범위를 확인한다.',exception:'미확인을 0원으로 바꾸지 않는다. 감액 시 범위·일정·검수를 다시 검토.',screen:'예산 작업대',doc:'F02',data:'CostLine, BudgetScenario, requested/approved'},
 budgetreview:{role:'기획·예산 담당자',input:'요구자료, 실제 심의 질의·회신·결과',action:'질의에 필요한 근거를 찾아 답변 초안을 만들고 실제 결과를 등록한다.',output:'보완표·실제 심의 결과 참조',human:'회신 내용과 예산 결과 증빙을 확인한다.',exception:'버튼을 눌렀다는 이유로 예산 확보·승인 상태를 만들지 않는다.',screen:'검토·인계',doc:'F06',data:'ReviewQuestion, Response, DecisionRef'},
 template:{role:'양식 규칙 + 서식 담당자',input:'수신기관·재원·연도와 승인된 양식',action:'문서 프로필을 선택하고 공통 원장 필드를 양식의 항목·표·슬롯에 매핑한다.',output:'버전이 명시된 필드 매핑표',human:'실제 제출 양식과 필수 항목을 확인한다.',exception:'양식 연도·수신처 불일치, 미매핑 필드는 보완 대상으로 표시.',screen:'문서 작업대',doc:'F03',data:'TemplateProfile, FieldMapping, template_hash'},
 generate:{role:'로컬 LLM + 문서 출력 규칙',input:'검토된 원장 버전, 양식 프로필, 허용 근거',action:'문서 목적에 맞는 문장을 작성하고 금액·표·참조를 규칙으로 넣는다.',output:'F01–F06 문서 초안과 근거 참조',human:'수치·범위·문체·표·쪽나눔·공개 적합성을 검토한다.',exception:'빈 근거·승인액·협의 결과를 지어내지 않는다. 고정 HWPX 출력은 실제 연동·렌더 검증 필요.',screen:'문서 작업대',doc:'F04',data:'Artifact, source_version, project_version'},
 contract:{role:'업무·정보화·계약 담당자',input:'실제 예산 근거, 범위 버전, 요구사항·검수, 공개본',action:'사업목적을 발주 요구사항으로 바꾸고 계약조건과 공개할 첨부를 확인한다.',output:'RFP·공고 준비용 검토본',human:'계약 방식·참가요건·평가·일정·공개 여부를 확정한다.',exception:'실제 예산·계약조건 미확인 또는 변경 영향 미해결이면 인계 준비를 보류.',screen:'검토·인계',doc:'F05',data:'Requirement, Acceptance, ReleaseDraft'},
 handoff:{role:'기관의 권한 있는 담당자',input:'검토된 문서, 실제 승인 근거, 제출 조건',action:'기관의 공식 절차에서 별도로 제출·발주를 처리하고 확인된 결과를 등록한다.',output:'공식 처리 결과 참조와 다음 검토 의제',human:'실제 제출·공고 권한과 최종 내용은 담당자에게 있다.',exception:'본 설명 페이지는 외부 시스템에 제출하거나 공고하지 않는다.',screen:'검토·인계',doc:'F05',data:'ExternalReceiptRef, OutcomeRef'},
 noa:{role:'기존 NOA + 로컬 LLM + 추가 업무 구성',input:'허용 자료·문제 틀·사업원장·문서 프로필',action:'근거 정리 → 문제·대안 초안 → 문서 초안을 지원한다. 권한·계산·상태·양식 처리는 SW 규칙과 연결한다.',output:'부서가 검토할 문제·사업·예산·발주 초안',human:'정책·예산·안전·계약의 공식 판단을 수행한다.',exception:'현재 도식은 제안 설계. 실제 NOA API·제품 재사용·HWPX 출력은 확인 필요.',screen:'문제 카드',doc:'F01',data:'NOA tasks, evidence refs, artifact versions'},
 llm:{role:'기존 로컬 LLM',input:'권한으로 필터링한 근거 구간과 작업 지시',action:'문서의 의미를 파악하고 근거에 연결된 서술·대안·초안을 생성한다.',output:'구조화된 초안과 근거 ID',human:'사실·인과·정책 판단의 타당성을 검토한다.',exception:'자료 속 지시문은 실행 명령으로 취급하지 않는다. 부족한 사실을 추정해 채우지 않는다.',screen:'문제 카드',doc:'F01',data:'Model task, prompt_version, evidence_ids'},
 search:{role:'권한 필터 + 근거 검색',input:'요청자 권한·의제·기간·검색 질문',action:'허용된 원문·인덱스에서 관련 구간을 찾아 출처 위치와 함께 반환한다.',output:'검색 근거 묶음',human:'검색 결과의 충분성·상충 자료를 확인한다.',exception:'검색 실패·권한 거부·철회된 근거는 빈 결과 사유와 함께 표시.',screen:'자료함',doc:'F01',data:'AccessPolicy, Index, EvidenceRef'},
 access:{role:'기관 인증·자료 권한 규칙',input:'사용자·부서·자료별 권한과 작업 요청',action:'검색·생성·원문 열람·내보내기에 같은 접근 조건을 적용한다.',output:'허용된 자료·작업 범위',human:'기관 권한체계·역할·공개 가능 범위를 확정한다.',exception:'원문 접근 가능과 외부 공개 가능을 같은 권한으로 취급하지 않는다.',screen:'자료함',doc:'F01',data:'UserRole, AccessPolicy, ExportPolicy'},
 raw:{role:'D1 원문 저장소',input:'반입 검사를 통과한 원문과 메타정보',action:'원문·해시·기간·자료군·이용권·접근정책·철회 상태를 보관한다.',output:'권한 조건에 맞는 원문 참조',human:'보존·삭제·반입 정책을 확인한다.',exception:'원문 철회 시 검색 인덱스·캐시·생성물 참조까지 영향 조사.',screen:'자료함',doc:'F01',data:'Source, hash, location, rights, status'},
 evidence:{role:'D2 근거 저장소',input:'주장·원문 위치·지지/반대 관계·독립 자료군',action:'문제정의에서 주장한 내용이 어느 원문에 근거하는지 유지한다.',output:'근거 카드와 원문 추적 경로',human:'출처 일치와 주장 표현의 정확성을 검토한다.',exception:'철회·정정·접근 회수 시 참조된 문제 카드 재검토.',screen:'문제 카드',doc:'F01',data:'Claim, EvidenceRef, SourceGroup'},
 ledger:{role:'D3 공통 사업원장',input:'문제·대안·범위·요구사항·비용·검토 이력',action:'버전별로 확정·미확인·변경 내용을 기록하고 출력 문서가 사용한 버전을 연결한다.',output:'정책·예산·RFP가 공유하는 사업 정보',human:'사업 범위와 예산 시나리오의 채택 여부를 결정한다.',exception:'변경 시 이전 검토본은 보존하고 새 버전과 영향 문서를 생성.',screen:'사업 작업대',doc:'F02',data:'Project, Scope, CostLine, Decision'},
 artifacts:{role:'D4 문서·검토 기록',input:'생성 초안·근거/원장/양식 버전·검토 결과',action:'어떤 데이터로 문서를 작성했는지 기록하고 공개본·내부본을 구분한다.',output:'추적 가능한 문서 파일과 검토 이력',human:'내용과 공개 적합성을 확인한다.',exception:'수동 수정본을 자동 덮어쓰지 않으며 오래된 버전은 재검토 표시.',screen:'문서 작업대',doc:'F04',data:'Artifact, version_refs, review_status'},
 impact:{role:'변경 영향 규칙 + 담당자',input:'근거 철회·예산 감액·범위 변경 이벤트',action:'참조 그래프에서 영향받는 문제·비용·요구사항·문서를 찾고 재검토 목록을 만든다.',output:'변경 전후 비교와 재검토 대상',human:'조정할 범위와 새 문서 내용을 확인한다.',exception:'자동 감액만으로 기존 범위가 수행 가능하다고 표시하지 않는다.',screen:'검토·인계',doc:'F06',data:'ChangeEvent, DependencyRef, ChangeImpact'},
 need:{role:'담당자 보완·유보',input:'검토를 막는 누락·불일치·반대 근거',action:'필요한 자료·담당자·검토 조건을 적고 확인할 단계로 돌아간다.',output:'보완 요청 또는 유보 사유',human:'조사·협업·재검토 여부를 결정한다.',exception:'그럴듯한 문장으로 공백을 숨기지 않는다.',screen:'검토·인계',doc:'F06',data:'ReviewIssue, Owner, required_evidence'},
 ui:{role:'업무·기획·예산·계약 담당자',input:'허용 의제·자료와 현재 검토 단계',action:'자료함·문제 카드·대안·예산·문서·변경 작업대에서 필요한 근거와 결과를 함께 본다.',output:'의제별 검토·보완·인계 요청',human:'각 역할의 검토 사유를 기록한다.',exception:'로딩·빈 결과·권한 거부·시간 초과·부분 성공을 구분한다.',screen:'자료함',doc:'F01',data:'Workspace, UserRole, ReviewTask'}
};
const graphs=[];
const n=(id,key,title,sub,x,y,w=300,h=130,type)=>({id,key,title,sub,x,y,w,h,type:type||(['public','internal','intake','handoff'].includes(key)?'external':['raw','evidence','ledger','artifacts'].includes(key)?'store':['budget','template','ingest','access','search','impact'].includes(key)?'rule':['contract','budgetreview','scopecheck','need'].includes(key)?'human':'ai')});
const e=(from,to,label='',opts={})=>({from,to,label,...opts});
const g=(id,title,question,summary,width,height,nodes,edges,groups=[])=>{const x={id,title,question,summary,width,height,nodes,edges,groups};graphs.push(x);return x;};
g('concept','01 컨셉도','이 서비스는 누구의 어떤 일을 돕는가?','허용된 자료를 검토 가능한 근거로 만들고, 정책·예산·발주 문서에 연결한다.',1400,1030,[
 n('C01','public','정책·통계·국민 의견','문제의 규모·맥락·원출처',45,160,285,140),n('C02','internal','TS 업무·기존 사업','소관·현황·계약·성과',45,385,285,140),n('C03','intake','담당자의 조사 질문','대상·기간·불편·위험',45,610,285,140),
 n('C04','noa','NOA 정책기획 작업대','근거·문제 → 대안·사업 → 예산·문서',470,335,430,210),
 n('C05','problem','문제·정책 검토서','F01 · 근거·가설·대안',1060,160,295,140),n('C06','budget','예산 요구·설명자료','F02·F03·F06 · 산식·보완',1060,385,295,140),n('C07','generate','RFP·공고 준비자료','F04·F05 · 요구·검수·인계',1060,610,295,140),
 n('C08','contract','담당자 검토와 공식 인계','정책·예산·계약의 판단 사유를 보존',470,800,430,140,'human')
],[e('C01','C04','허용 자료',{fromSide:'right',toSide:'left',via:[[380,230],[380,440]]}),e('C02','C04','업무 맥락',{fromSide:'right',toSide:'left'}),e('C03','C04','검토 목표',{fromSide:'right',toSide:'left',via:[[415,680],[415,440]]}),e('C04','C05','문제·근거',{fromSide:'right',toSide:'left',via:[[975,440],[975,230]]}),e('C04','C06','사업·비용',{fromSide:'right',toSide:'left'}),e('C04','C07','범위·요구',{fromSide:'right',toSide:'left',via:[[1010,440],[1010,680]]}),e('C04','C08','초안·미확인 사항',{fromSide:'bottom',toSide:'top'})],
 [{x:440,y:245,w:490,h:360,label:'기존 로컬 서버 · NOA + LLM + 업무 규칙'}]);
g('service','02 서비스 흐름도','입력한 자료가 어떤 검토를 거쳐 문서가 되는가?','행은 업무 단계, 열은 입력·시스템·담당자와 결과다. 1단계의 결과를 다음 단계에서 재사용한다.',1400,1120,[
 n('S01','intake','01 자료·질문 등록','정책 의제·허용 자료·검토 기간',40,175,380,130,'external'),n('S02','claim','근거 추출·문제 초안','중복·사실·가설·반대 근거',510,175,380,130),n('S03','problem','문제 확인 → F01','업무 담당: 사실·조사 공백 확인',980,175,380,130,'human'),
 n('S04','scopecheck','02 소관·기존사업 대조','문제 카드·법정 역할·계약 범위',40,410,380,130,'human'),n('S05','alternative','대안 비교·사업 구성','운영 개선·기존 고도화·신규',510,410,380,130),n('S06','project','사업범위 검토 → 원장','기획·정보화: 범위·요구·성과',980,410,380,130,'human'),
 n('S07','budget','03 재원·연차·단가 입력','미확인 금액은 미확인으로 유지',40,645,380,130,'human'),n('S08','budget','비용 검증·예산문서 초안','산식·증감·서식·질의 답변',510,645,380,130,'rule'),n('S09','budgetreview','예산 검토 → F02·F03·F06','예산 담당: 요구·실제 결과 확인',980,645,380,130,'human'),
 n('S10','project','04 실제 결과·범위 재확인','감액·유보·범위 변경 반영',40,880,380,130,'human'),n('S11','generate','RFP·공고 준비 초안','요구사항·검수·공개본 구성',510,880,380,130),n('S12','contract','발주 검토 → F04·F05','계약 담당 검토 후 공식 절차 인계',980,880,380,130,'human')
],[...[[1,2],[2,3],[4,5],[5,6],[7,8],[8,9],[10,11],[11,12]].map(([a,b])=>e('S'+String(a).padStart(2,'0'),'S'+String(b).padStart(2,'0'),a%3===1?'입력':'초안')),
 e('S03','S04','확인된 문제',{fromSide:'bottom',toSide:'top',via:[[1170,355],[230,355]]}),e('S06','S07','검토된 범위',{fromSide:'bottom',toSide:'top',via:[[1170,590],[230,590]]}),e('S09','S10','실제 결과와 보완사항',{fromSide:'bottom',toSide:'top',via:[[1170,825],[230,825]]})],
 [{x:40,y:100,w:380,h:50,label:'입력·등록',header:true},{x:510,y:100,w:380,h:50,label:'NOA + 로컬 LLM / 규칙 처리',header:true},{x:980,y:100,w:380,h:50,label:'담당자 검토·산출물',header:true}]);
g('architecture','03 전체 아키텍처','LLM·업무 규칙·문서 출력·저장소는 어떻게 연결되는가?','기존 서버의 논리 구성이다. 문장 생성, 계산·권한, 문서 출력, 사람 검토를 구분한다.',1460,1270,[
 n('A01','public','승인된 외부 자료','제공 파일·허용 수집 경로',35,335,270,140,'external'),n('A02','ui','부서별 기획 작업대','자료함·문제·대안·예산·문서·변경',535,150,520,130,'external'),
 n('A03','access','권한·반입 검증','검색·열람·출력에 권한 적용',375,365,280,140),n('A04','noa','NOA 작업 실행 구성','작업 상태·허용 도구·실패 처리',740,365,290,140),n('A05','contract','검토·변경 관리','역할·사유·실제 결과 참조',1105,365,290,140,'human'),
 n('A06','search','근거 검색','원문 위치·기간·접근 필터',375,630,280,140),n('A07','llm','기존 로컬 LLM','추출·가설·비교·문장 초안',740,630,290,140),n('A08','budget','산술·양식 규칙','금액·단위·필수값·버전 검사',1105,630,290,140),
 n('A09','raw','원문·근거 저장','자료·원문 위치·검색 인덱스',375,895,280,140,'store'),n('A10','ledger','사업·예산 원장','범위·비용·검토·참조 버전',740,895,290,140,'store'),n('A11','generate','문서 출력 어댑터','HTML/MD · 고정 HWPX 검증 필요',1105,895,290,140,'rule'),
 n('A12','handoff','기관의 공식 예산·발주 절차','담당자가 별도로 제출·처리 · 본 시연 연계 없음',715,1120,680,100,'external')
],[e('A01','A03','반입'),e('A02','A04','업무 요청',{fromSide:'bottom',toSide:'top'}),e('A03','A04','권한'),e('A04','A05','검토'),e('A04','A07','추론 요청',{fromSide:'bottom',toSide:'top'}),e('A07','A04','초안·근거 ID',{fromSide:'right',toSide:'right',via:[[1065,700],[1065,435]],labelAt:[1070,600]}),e('A06','A07','근거'),e('A09','A06','검색 참조',{fromSide:'top',toSide:'bottom'}),e('A03','A09','검증 후 저장',{fromSide:'left',toSide:'left',via:[[345,435],[345,965]]}),e('A04','A06','검색 질문',{fromSide:'left',toSide:'top',via:[[700,435],[700,575],[515,575]]}),e('A04','A08','규칙 호출',{fromSide:'bottom',toSide:'top',via:[[885,560],[1250,560]]}),e('A04','A10','작업 결과',{fromSide:'left',toSide:'left',via:[[685,435],[685,965]]}),e('A10','A11','원장'),e('A08','A11','검증 결과',{fromSide:'bottom',toSide:'top'}),e('A05','A11','검토 상태',{fromSide:'right',toSide:'right',via:[[1425,435],[1425,965]],labelAt:[1390,580]}),e('A11','A12','검토 파일 인계',{fromSide:'bottom',toSide:'top',dashed:true})],
 [{x:325,y:305,w:1115,h:770,label:'TS 로컬 서버 영역'}]);
g('data','04 데이터 흐름도','원문 한 건이 어떤 데이터와 문서로 남는가?','E=자료 제공·이용 주체, P=처리, D=저장소. 화살표는 전달되는 데이터다.',1460,1210,[
 n('E1','public','E1 외부 허용 자료','정책·통계·뉴스·공개 의견',35,170,265,135,'external'),n('E2','internal','E2 TS 내부 자료','계획·계약·성과·업무 현황',35,470,265,135,'external'),
 n('P1','ingest','P1 반입·권한·중복','원문 위치와 자료군 보존',385,170,280,135,'rule'),n('D1','raw','D1 원문·접근정책','Source + 권리 + 철회 상태',765,170,280,135,'store'),n('P2','claim','P2 주장·근거 추출','요청자 권한으로 원문 필터',1145,170,280,135),
 n('D2','evidence','D2 근거 카드','주장·위치·지지/반대·자료군',1145,470,280,135,'store'),n('P3','project','P3 문제·대안·사업 검토','근거를 범위·요구사항에 연결',765,470,280,135,'human'),n('D3','ledger','D3 공통 사업원장','문제·범위·비용·검토 버전',385,470,280,135,'store'),
 n('D5','template','D5 승인 양식 프로필','기관·연도·슬롯·버전',35,800,280,135,'store'),n('P4','budget','P4 산식·필드 검증','단위·누락·변경·매핑 확인',385,800,280,135,'rule'),n('P5','generate','P5 문서 생성','공통 필드 + 근거 + 양식',765,800,280,135),n('D4','artifacts','D4 문서·검토 기록','초안 + 참조 버전 + 공개 구분',1145,800,280,135,'store'),
 n('E3','contract','E3 담당자 검토·인계','미해결 항목·승인 근거·공개 적합성',1015,1045,410,110,'external')
],[e('E1','P1','원문'),e('E2','P1','부서 권한',{fromSide:'right',toSide:'bottom',via:[[335,537],[335,360],[525,360]]}),e('P1','D1','자료'),e('D1','P2','원문'),e('P2','D2','Claim·위치',{fromSide:'bottom',toSide:'top'}),e('D2','P3','근거'),e('P3','D3','검토'),e('D3','P4','범위·비용',{fromSide:'bottom',toSide:'top'}),e('D5','P4','양식'),e('P4','P5','필드'),e('P5','D4','초안'),e('D4','E3','검토 파일',{fromSide:'bottom',toSide:'top'}),e('E3','D3','검토 사유·새 버전',{fromSide:'left',toSide:'bottom',via:[[705,1100],[705,705],[560,705]],dashed:true})]);
g('logic','05 판단·예외 로직','근거가 부족하거나 예산이 바뀌면 어디로 돌아가는가?','초안 생성과 다음 단계의 검토 준비를 분리한다. 유보·보완·타기관 협업 경로를 함께 표시한다.',1450,1130,[
 n('L00','intake','의제·허용 자료','기획 검토 시작',35,175,260,130,'external'),n('L01','problem','근거·문제 확인?','담당자 검토',455,150,285,180,'decision'),n('L02','scopecheck','소관·추가 범위 확인?','TS 역할·기존 계약 대조',1025,150,330,180,'decision'),
 n('L11','need','추가조사·문제 수정','원문·현황·반대근거 확보',440,425,320,130,'error'),n('L12','scopecheck','소관·협업·중복 보완','타기관 인계·범위 조정·유보',1010,425,370,130,'error'),
 n('L03','budgetreview','예산 결과·범위 일치?','실제 증빙·감액 반영 확인',1025,665,330,180,'decision'),n('L04','contract','양식·계약 검토 완료?','연도·필수값·공개본 확인',455,665,330,180,'decision'),n('L05','handoff','검토 파일 인계 준비','실제 제출은 담당자 공식 절차',35,690,300,130,'external'),
 n('L13','impact','범위·예산 재설계','요구사항·일정·검수 조정',1010,965,370,110,'error'),n('L14','template','양식·계약조건 보완','미확정 값·공개본·서식 수정',440,965,370,110,'error')
],[e('L00','L01','검토'),e('L01','L02','확인됨'),e('L01','L11','부족·상충',{fromSide:'bottom',toSide:'top',error:true}),e('L11','L01','재검토',{fromSide:'left',toSide:'left',via:[[395,490],[395,240]],dashed:true}),e('L02','L12','미확인·중복',{fromSide:'bottom',toSide:'top',error:true}),e('L02','L03','확인 후 예산 검토',{fromSide:'right',toSide:'right',via:[[1415,240],[1415,755]],labelAt:[1395,605]}),e('L03','L04','실제 결과 반영'),e('L03','L13','미확인·감액 미반영',{fromSide:'bottom',toSide:'top',error:true}),e('L13','L03','조정 후 재검토',{fromSide:'right',toSide:'right',via:[[1415,1020],[1415,755]],labelAt:[1395,910],dashed:true}),e('L04','L05','검토됨'),e('L04','L14','불일치·미완료',{fromSide:'bottom',toSide:'top',error:true}),e('L14','L04','보완 후 재검토',{fromSide:'left',toSide:'left',via:[[390,1020],[390,755]],dashed:true}),e('L12','L02','범위 확인',{fromSide:'left',toSide:'left',via:[[965,490],[965,240]],dashed:true})]);
g('impact','06 변경·문서 추적','원장과 근거가 바뀌면 어떤 문서를 다시 봐야 하는가?','한 가상 의제의 참조 관계다. 변경은 새 버전으로 기록하며 과거 검토본을 자동 덮어쓰지 않는다.',1440,1090,[
 n('V01','public','SRC-01 근거 원문','설명용 가상 자료 · 실제 조사 아님',40,170,380,130,'external'),n('V02','evidence','CL-01 근거 카드','SRC-01의 원문 위치 참조',530,170,380,130,'store'),n('V03','problem','ISS-01 문제 카드','주장·원인가설·반대근거 연결',1020,170,380,130),
 n('V04','project','PRJ-01 사업원장 v1 → v2','범위·요구·일정·검수 재검토',1020,470,380,155,'store'),n('V05','budget','요구예산 가정 100 → 70백만원','승인액 미확인 · 감소 시 범위 재검토',530,470,380,155,'rule'),n('V06','impact','변경 영향 검토','참조 문서·검토자·사유를 추적',40,470,380,155,'rule'),
 n('V07','problem','F01 문제·정책 검토서','근거·문제·선택 대안',40,820,280,150),n('V08','budget','F02·F03 예산 자료','요구액·범위·연차·미확인',400,820,280,150),n('V09','generate','F04 RFP 초안','요구사항·일정·검수',760,820,280,150),n('V10','contract','F05·F06 인계·보완','공개본·검토 결과·수정 근거',1120,820,280,150,'human')
],[e('V01','V02','원문 참조'),e('V02','V03','주장 근거'),e('V03','V04','사업화 검토',{fromSide:'bottom',toSide:'top'}),e('V04','V05','범위·수량'),e('V05','V06','금액 변경'),e('V01','V06','철회·정정 이벤트',{fromSide:'bottom',toSide:'top',error:true,dashed:true}),...['V07','V08','V09','V10'].map((id,i)=>e('V06',id,'재검토',{fromSide:'bottom',toSide:'top',via:[[230,720],[180+i*360,720]],dashed:true}))]);
const scenarios={normal:{label:'기본 검토',message:'설계상 기본 경로입니다. 각 담당자가 근거·범위·예산·양식을 확인한 경우의 흐름이며 실제 기관 승인 상태가 아닙니다.',keys:['problem','alternative','project','budget','generate','contract']},insufficient:{label:'근거 부족',message:'원인·규모를 확인할 자료가 부족한 가상 상황입니다. 문제 카드를 보완·유보하고 추가 근거를 확보합니다.',keys:['claim','problem','need','search','evidence']},reduced:{label:'예산 감액',message:'가상 요구예산 100→70백만원. 실제 승인액은 미확인입니다. 범위·요구사항·일정·검수와 예산·RFP 문서를 함께 재검토합니다.',keys:['budget','budgetreview','project','ledger','impact','generate','contract']},withdrawn:{label:'근거 철회',message:'원문이 철회된 가상 상황입니다. 검색·인덱스·근거 카드의 사용을 중지하고 이를 참조한 문제·사업·문서를 다시 검토합니다.',keys:['public','raw','ingest','search','evidence','problem','impact','artifacts']}};
const stages=[
 {name:'자료함',step:'01',title:'어떤 자료를 함께 볼 것인가',task:'의제·기간·자료 접근 범위를 등록',input:'가상 의제: 자동차검사 예약 탐색의 불편',cards:[['SRC-01','이용자가 날짜·검사소를 반복 확인한다는 의견','사용자 경험을 바탕으로 만든 설명 예시'],['SRC-02','실제 예약 조회·이동 로그','미확보 · 담당자 제공 필요'],['SRC-03','현행 기능·계약 범위 자료','미확보 · 중복 판단 전 확인 필요']],result:'3개 항목은 설명용 등록 예시입니다. 실제 조사 자료·연결 결과가 아닙니다.',key:'ingest'},
 {name:'문제 카드',step:'02',title:'현상·원인 가설·반대 근거를 나누어 본다',task:'원문을 대조하고 부족한 조사를 확인',input:'자료함의 근거 카드와 검토 질문',cards:[['현상','가용 일정을 찾는 과정이 번거롭다는 이용 경험','검사소·날짜 이동의 불편'],['원인 가설','화면 구성·상태 표시 또는 가용 슬롯 부족','실제 원인 미확인'],['추가조사','화면 이동·조회 상태·슬롯 현황 확인','근거 확보 전 원인 확정 보류']],result:'ISS-01 문제 초안 → 업무 담당자의 확인·보완',key:'problem'},
 {name:'대안 비교',step:'03',title:'어떤 방법이 문제를 줄일 수 있는가',task:'운영 개선·기존 고도화·신규 도입 비교',input:'검토된 문제 + TS 소관 + 기존 수행 범위',cards:[['대안 A','화면·조회 동선 개선','실제 조회 인터페이스 확인 필요'],['대안 B','일정 안내·운영 방식 개선','슬롯 부족 여부 확인 필요'],['대안 C','근거를 더 확보한 후 판단','현재 자료 부족 시 선택 가능']],result:'자동으로 AI 도입을 선택하지 않습니다. 담당자가 선택 사유를 남깁니다.',key:'alternative'},
 {name:'사업 작업대',step:'04',title:'선택한 대안을 수행범위로 구체화한다',task:'요구사항·데이터·기간·검수 연결',input:'선택 대안과 실제 제공 가능한 자산',cards:[['포함 검토','차량·날짜·지역 조건 유지 및 가용상태 표시','범위 확정 전 API 확인'],['요구사항 연결','문제 → 기능 → 데이터 → 검수','가상 REQ-01 · 실제 RFP 아님'],['전제','기존 시스템·자료 제공·운영환경 확인','미확인 항목을 원장에 보존']],result:'PRJ-01 공통 원장 초안. 개별 사업 구현비는 P23 플랫폼 개발비와 별도입니다.',key:'project'},
 {name:'예산 작업대',step:'05',title:'범위와 산출 근거가 맞는지 확인한다',task:'요구액·승인액·연차·미확인 항목 구분',input:'범위·수량·단가·연차·VAT·근거',cards:[['요구액 가정','100백만원 → 감액 예시 70백만원','설명용 금액 · 실제 승인액 미확인'],['미확정 비용','연차별 운영비·이용권·기타 경비','미확인을 0원으로 계산하지 않음'],['감액 대응','필수 유지·축소·단계 분리 대안','범위·일정·검수 다시 확인']],result:'F02·F03 예산자료 초안 + F06 보완표',key:'budget'},
 {name:'문서 작업대',step:'06',title:'같은 사업정보로 제출 목적에 맞는 초안을 만든다',task:'필드 매핑·원장 버전·근거 위치 확인',input:'검토 원장 버전 + 실제 수신기관 양식',cards:[['공통 필드','사업목적·대상·범위·요구액·기간','F01·F02·F04에서 같은 버전 참조'],['양식 필드','제출연도·부처·비목·실제 의견조회','근거가 없으면 미확인'],['출력 결과','정책 검토·예산 설명·RFP 초안','고정 HWPX 실제 변환은 실증 전']],result:'작성된 초안과 근거를 담당자가 함께 확인합니다.',key:'generate'},
 {name:'검토·인계',step:'07',title:'미해결 사항과 문서 변경을 확인하고 인계한다',task:'실제 심의 결과·계약 검토·공개본 확인',input:'실제 승인 증빙·양식·계약조건·검토 의견',cards:[['예산 결과','실제 회신·승인액 확인 필요','미확인 상태를 승인 완료로 바꾸지 않음'],['변경 영향','문제·범위·예산·RFP의 재검토 목록','과거 검토본은 보존'],['공식 처리','권한 있는 담당자의 기존 시스템에서 별도 수행','이 시연에는 제출·공고 버튼 없음']],result:'F04·F05·F06 검토 파일 인계 준비. 화면 클릭은 실제 결재가 아닙니다.',key:'contract'}
];
module.exports={defs,graphs,scenarios,stages};
