const fs=require('fs'),path=require('path'),crypto=require('crypto'),{pathToFileURL,fileURLToPath}=require('url');const {chromium}=require('C:/Users/김희섭/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root='G:/내 드라이브/1. 업무영역/6. CCK/1. 사업관리/TS/bizops/[TS 사업기획]',parent=path.join(root,'05_통합사업기획/P23_정책기획_예산요구_발주전환_v1.1_2026-09-15'),out=path.join(parent,'시각설계_v1.2');
const q=JSON.parse(fs.readFileSync(path.join(out,'검증/자동검증.json'),'utf8'));if(q.failures.length)throw Error('검증 실패 보완 필요');
const changes=fs.existsSync(path.join(out,'변경기록.json'))?JSON.parse(fs.readFileSync(path.join(out,'변경기록.json'),'utf8')).existing_changed:[],hash=b=>crypto.createHash('sha256').update(b).digest('hex');function edit(f,fn){const b=fs.readFileSync(f),s=b.toString('utf8'),next=fn(s);if(next===s)return;const bak=path.join(out,'변경전_보존',path.relative(root,f));fs.mkdirSync(path.dirname(bak),{recursive:true});if(!fs.existsSync(bak))fs.writeFileSync(bak,b);fs.writeFileSync(f,next,'utf8');changes.push({path:f,backup:bak,before:hash(b),after:hash(Buffer.from(next))});}
const pages=[...fs.readdirSync(parent).filter(x=>x.endsWith('.html')).map(x=>path.join(parent,x)),...fs.readdirSync(path.join(parent,'서식')).filter(x=>x.endsWith('.html')).map(x=>path.join(parent,'서식',x))];
for(const f of pages){const base=path.relative(path.dirname(f),out).replace(/\\/g,'/');const links=[['00_서비스_로직맵','컨셉·로직맵'],['01_서비스_흐름도','서비스 흐름'],['03_데이터_흐름도','데이터 흐름'],['06_사용자화면_시연','사용자 화면']];const callout='<section data-visual-v12="true" style="padding:19px 21px;margin:0 0 25px;background:#e2f3ed;border:1px solid #a6cfc2;border-radius:9px"><strong style="display:block;font-size:19px;color:#15584e">서비스가 어떻게 동작하는지 도식으로 보기</strong><p style="margin:8px 0 13px;color:#3b615d;font-size:14px">각 단계를 선택하면 입력·처리·출력·담당자 판단과 보완 경로가 표시됩니다.</p><div style="display:flex;gap:8px;flex-wrap:wrap">'+links.map(([name,label])=>'<a style="display:inline-block;padding:8px 12px;border-radius:5px;background:#0b7164;color:white;text-decoration:none;font-size:14px" href="'+base+'/'+name+'.html">'+label+'</a>').join('')+'</div></section>';
 edit(f,s=>{if(s.includes('data-visual-v12="true"'))return s;return s.replace(/(<main\b[^>]*>)/,'$1'+callout).replace('<nav aria-label="설명자료 목차">','<nav aria-label="설명자료 목차"><a href="'+base+'/00_서비스_로직맵.html" style="background:#d4eeea;color:#123b42;font-weight:bold">서비스 로직맵 · v1.2</a>');});
 const md=f.replace(/\.html$/,'.md');if(fs.existsSync(md))edit(md,s=>s.includes('<!--VISUAL-V12-->')?s:s.replace(/^(# [^\r\n]+)\r?\n/,'$1\n\n<!--VISUAL-V12-->\n[서비스 로직맵·도식·사용자 화면 보기]('+base+'/00_서비스_로직맵.html) — 단계별 입력·처리·출력·판단·보완 경로.\n'));
}
const target=path.join(out,'00_서비스_로직맵.html');edit(path.join(root,'README.md'),s=>s.includes('<!--P23-VISUAL-V12-->')?s:s.replace(/^(# [^\r\n]+)\r?\n/,'$1\n\n<!--P23-VISUAL-V12-->\n[최신 P23 서비스 시각설계: 컨셉·흐름·데이터·판단 로직]('+path.relative(root,target).replace(/\\/g,'/')+') — 6종 선택형 도식·7단계 사용자 화면.\n'));
const linkChecks=[];for(const f of pages){const s=fs.readFileSync(f,'utf8'),block=s.match(/<section data-visual-v12="true"[\s\S]*?<\/section>/);if(!block)throw Error('안내 없음');for(const m of block[0].matchAll(/href="([^"]+)"/g)){const t=fileURLToPath(new URL(m[1],pathToFileURL(f)));const exists=fs.existsSync(t);linkChecks.push({page:f,target:t,exists});if(!exists)throw Error('안내 연결 실패');}}
fs.writeFileSync(path.join(out,'변경기록.json'),JSON.stringify({date:'2026-09-15',existing_changed:changes,added_links:linkChecks,deletions:[],deployments:[],note:'기존 기능·서식·비용 원문은 보존하고 시각설계 안내만 추가. 이전 파일 해시는 이전 검증 시점의 기록이다.'},null,2));
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true}),p=await b.newPage();for(const [id,name,w,h] of [['concept','컨셉도',1400,1030],['architecture','아키텍처',1460,1270],['data','데이터흐름',1460,1210],['logic','판단예외',1450,1130]]){await p.setViewportSize({width:w,height:h});await p.goto(pathToFileURL(path.join(out,'diagrams',id+'.svg')).href);await p.evaluate(()=>document.fonts.ready);const shot=path.join(__dirname,'p23v12_'+id+'_원본.png');await p.screenshot({path:shot,fullPage:false,timeout:20000});fs.copyFileSync(shot,path.join(out,'검증',name+'_원본확인.png'));}
const f01=path.join(parent,'서식/F01_문제정의_정책사업_검토서.html');for(const width of [1440,390]){await p.setViewportSize({width,height:1000});await p.goto(pathToFileURL(f01).href);if(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1))throw Error('기존 서식 안내 가로넘침');}await p.locator('[data-visual-v12] a').first().click();if(!p.url().includes('00_'))throw Error('시각설계 진입 실패');await p.locator('#nodeSelect').selectOption('C04');await p.screenshot({path:path.join(out,'검증/모바일_상세이동.png')});await b.close();
fs.writeFileSync(path.join(out,'검증기록.md'),`# P23 서비스 시각설계 v1.2 검증\n\n2026-09-15 / 기존 설명자료의 시각화 개선(M, Low). 시각 설계 → 선택형 프로토타입 → 경로·입출력·사용자 흐름 검증을 적용했다. 제품 구축·운영 인계 승인은 이번 범위가 아니다.\n\n## 피드백 반영\n\n사용자 피드백: 컨셉·서비스·데이터 흐름으로 실제 로직을 확인할 수 있어야 함. 기존에는 서식 화면에서 서비스 구조 진입이 어렵고 서로 다른 목적의 도식이 비슷한 순서도로 표현되어 있었음.\n\n수정: 컨셉·서비스·아키텍처·DFD·판단예외·변경추적의 6종 도식, 노드별 입출력·검토·보완 상세, 7단계 사용자 화면, 상황별 관련 단계 강조, 기존 모든15페이지에서의 바로가기를 추가했다.\n\n## 실행한 검증\n\n- [자동검사 결과](검증/자동검증.json): ${q.checks}건, 실패${q.failures.length}건.\n- HTML7페이지, 로컬 연결${q.links}개, 화면1440·768·390px 총${q.viewports}회 확인.\n- 도식6종·노드${q.nodes}개의 입력·출력·판단·보완 설명 연결 확인.\n- 연결선의 무관한 노드 관통, 노드 글자 경계, 연결 문구의 SVG 경계 잘림 검사 통과.\n- 기본 검토·근거 부족·예산 감액·근거 철회 관련 노드 강조 및 안내 확인.\n- 확대·기본 배율·키보드 노드 선택·본문 이동·7단계 화면 전환 확인.\n- 외부 네트워크 요청0, 브라우저 JavaScript 오류0.\n- 기존15개 페이지의 시각설계 링크60개 확인. F01에서 시각설계로 실제 이동하고 모바일 노드 선택 후 상세가 보이는지 확인.\n\n## 시각 검토와 보완\n\n실제 렌더에서 서비스 흐름·판단 로직·사용자 화면·모바일을 확인했다. 오른쪽 연결 문구 잘림을 발견해 위치를 조정하고 회귀 검사에 추가했다. 모바일은 도식 좌우 이동, 단계 목록, 선택 시 상세 이동, 도식 복귀를 제공한다. LLM의 초안·근거 ID 반환 경로도 명시했다.\n\n자체 정성 점검: 목적 적합성5, 정보계층4, 시각 일관성4(공식 CI 검증은 아님), 구도·여백4, 반응형4, 접근성3, 원본 SVG 표현 보존5, 왜곡·오류5 = 34/40. 이 점수는 정성 검토 기록이며 실제 사용자 평가·접근성 인증이 아니다.\n\n## 판정과 미검증\n\n설명자료 자체 검토: 사용 가능. 제품 도입·기관 제출용 판단: 실제 자료·권한·NOA·HWPX·서버 실증 필요. 독립 평가위원·실제 TS 직원 사용성 조사·전체 WCAG·스크린리더 검증은 수행하지 않았다. 제품 인수시험 실행0건이며 화면 시연과 구분한다. 실제 예산 제출·공고·배포·삭제 없음.\n\n## 다음 입력\n\n부서가 확인한 대표 의제·허용 자료·실제 양식으로 각 화면의 내용을 검증한 뒤 구현 범위를 확정한다. 이번 수정은 기존 P23 v1.1 기능의 설명 구조를 구체화한 것으로 예산을 새로 확정하거나 기구축 기능을 선언하지 않는다.\n`,'utf8');
for(const f of ['p23v12_finish.cjs','p23v12_visual.js','p23v12_polish.cjs','p23v12_lastfix.cjs'])fs.copyFileSync(path.join(__dirname,f),path.join(out,'작성자료',f));const files=[];function walk(d){for(const e of fs.readdirSync(d,{withFileTypes:true})){const f=path.join(d,e.name);if(e.isDirectory())walk(f);else if(e.name!=='파일목록_해시.json'){const bytes=fs.readFileSync(f);files.push({path:path.relative(out,f).replace(/\\/g,'/'),bytes:bytes.length,sha256:hash(bytes)});}}}walk(out);fs.writeFileSync(path.join(out,'파일목록_해시.json'),JSON.stringify({date:'2026-09-15',count:files.length,files},null,2));console.log(JSON.stringify({done:true,existing_changed:changes.length,entry_links:linkChecks.length,files:files.length,url:pathToFileURL(target).href}));})();
