const fs=require('fs'),path=require('path'),assert=require('assert');
const {pathToFileURL}=require('url');
const {marked}=require('C:/Users/김희섭/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/marked');
const root='G:/내 드라이브/1. 업무영역/6. CCK/1. 사업관리/TS/bizops/[TS 사업기획]';
const old=path.join(root,'04_기관리서치/한국교통안전공단_심층조사_2026-09-11');
const out=path.join(root,'05_통합사업기획/TS_22개업무_사업기획_2026-09-14');
const list=JSON.parse(fs.readFileSync(path.join(old,'한국교통안전공단_업무와_NOA_검토리스트_2026-09-14.json'),'utf8'));
const raw=require('./ts22_plan_data.cjs');assert(raw.length===22);
fs.mkdirSync(path.join(out,'개별기획서'),{recursive:true});fs.mkdirSync(path.join(out,'검증'),{recursive:true});
const originalSources=JSON.parse(fs.readFileSync(path.join(old,'근거원장.json'),'utf8')).sources;
const fresh=new Set([3,8,9,11,12,13,14,15,17,18,19,20,21,22,23,24,25,26,27,31,33,40,41]);
const sources=originalSources.map(s=>({...s,original_accessed_at:s.accessed_at,url:s.url.startsWith('http')?s.url:pathToFileURL(path.resolve(old,s.url)).href,accessed_at:fresh.has(s.number)?'2026-09-14':s.accessed_at,recheck_status:fresh.has(s.number)?'공식 본문 또는 공개 안내 재확인':'기존 조사 근거 유지; 이번에 재열람하지 않음'}));
const additions=[
 [42,'항공종사자/경량항공기조종사 자격증명 시험','한국교통안전공단','https://main.kotsa.or.kr/portal/contents.do?menuCode=02010200','자격 종류·공식 수행 업무·법령 안내 확인. 응시 세부 요건 전수 대조 아님'],
 [43,'TS AI RFP 72건 요구사항추적표 RTM v1.0','프로젝트 내부 정리자료','G:/내 드라이브/1. 업무영역/6. CCK/1. 교통안전공단/04. 수행폴더/TS_AI_RFP_72건_요구사항추적표_RTM_v1.0.md','SFR-001~009 행 확인. 최종 계약·승인 요구사항 원본을 대신하지 않음'],
 [44,'CCK 보유기술 대장 26.09','CCK 내부 아카이브','G:/내 드라이브/1. 업무영역/6. CCK/#. 회사정보/01. 아카이브/_ARCHIVE/01_TECH_ASSETS/00_TECH_CATALOG.md','관리 범위·기재 조건 열람. TA 명칭 관리와 제품 성능·구현 증명을 구별'],
 [45,'MASTER_INDEX 및 현재 정정','CCK 내부 아카이브','G:/내 드라이브/1. 업무영역/6. CCK/#. 회사정보/01. 아카이브/_ARCHIVE/00_INDEX/01_MASTER_INDEX.md','현재 적용조건 관련 절·정정 안내 확인; 코드·원성적서 재시험 없음'],
 [46,'현재 정정 기록','CCK 내부 아카이브','G:/내 드라이브/1. 업무영역/6. CCK/#. 회사정보/01. 아카이브/_ARCHIVE/10_DATA/current_corrections.json','기술·성능 수치 전용과 과거 인력 가용률 전용 금지 조건 확인'],
 [47,'국민체감형 AX 선정기준','프로젝트 기획 기준',path.join(root,'00_기획지침/국민체감형_AX_선정기준.md'),'국민 문제·AI 추가 가치·실제 처리·기존 과업 중복 기준 확인'],
 [48,'CCK 솔루션·로컬 LLM 적용 기준','프로젝트 기획 기준',path.join(root,'00_기획지침/CCK_로컬LLM_적용범위.md'),'주관 수행·기존 서버·신규 인프라 0원·기술 제외 범위 확인']
];
for(const [number,title,publisher,url,verified_scope]of additions)sources.push({number,id:'TS22-S'+number,title,publisher,url:url.startsWith('http')?url:pathToFileURL(url).href,accessed_at:'2026-09-14',publication_or_effective_date:number===42?'게시일 미표시':number===43?'2026-09-03 내부 정리':number<=46?'2026-09 내부 아카이브': '2026-09 프로젝트 기준',verified_scope,recheck_status:'본문 관련 범위 확인'});
const sm=new Map(sources.map(s=>[s.number,s]));
sm.get(34).recheck_status='2026-09-14 웹 도구 열람 실패; 2026-09-11 공급사 텍스트 확인 기록 유지';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const foot=nums=>'\n## 출처\n\n'+[...new Set(nums)].map(n=>{const s=sm.get(n);assert(s,'source '+n);return `[^${n}]: ${s.publisher}. [${s.title}](${s.url}). ${s.publication_or_effective_date}. 열람 ${s.accessed_at}. ${s.verified_scope}. ${s.recheck_status}.`}).join('\n\n')+'\n';
const refs=ns=>ns.map(n=>`[^${n}]`).join('');
const link=(name,href)=>`[${name}](<${href}>)`;
const plans=raw.map(p=>{const x=list.items.find(x=>x.id==='TS-L'+String(p.n).padStart(2,'0'));assert(x);return {...p,id:'TS-P'+String(p.n).padStart(2,'0'),source_item_id:x.id,category:x.category,verified_work:x.verified_work,filename:'TS-P'+String(p.n).padStart(2,'0')+'_'+p.title,verification:'핵심 업무의 공식 안내 확인; 수요·현행 법령 전체·최종 계약·제품 성능 미검증',registered_as_new_opportunity:false};});
const styles=`*{box-sizing:border-box}body{margin:0;background:#fff;color:#222;font:16px/1.85 'Malgun Gothic','Apple SD Gothic Neo',sans-serif;word-break:keep-all;overflow-wrap:anywhere}main{max-width:1120px;margin:auto;padding:48px 32px 80px;min-width:0}h1{font-size:34px;line-height:1.4;margin:0 0 30px;padding-bottom:24px;border-bottom:2px solid #333}h2{font-size:24px;line-height:1.5;margin-top:48px;padding-top:18px;border-top:1px solid #bbb}h3{font-size:19px;margin-top:30px}p{margin:0 0 20px}a{color:#333;text-underline-offset:3px}a:hover{color:#555}table{width:100%;min-width:730px;border-collapse:collapse;font-size:13px;line-height:1.8}th,td{padding:11px 10px;text-align:left;vertical-align:top;border-bottom:1px solid #ccc}th{background:#f1f1f1}.table-wrap{overflow-x:auto;margin:22px 0}.table-wrap:focus-visible,a:focus-visible,button:focus-visible,input:focus-visible,select:focus-visible{outline:3px solid #333;outline-offset:3px}.contents{margin:18px 0 28px;padding:12px 16px;border:1px solid #aaa}.contents summary{cursor:pointer;min-height:32px}.contents ol{columns:2;padding-left:22px}.contents li{break-inside:avoid;font-size:14px}.actions,.filters{display:flex;gap:12px;align-items:center;flex-wrap:wrap;margin:22px 0}.actions a,button,input,select{font:inherit;background:#fff;color:#222;border:1px solid #777;padding:8px 12px;min-height:44px}.actions a{text-decoration:none}button{cursor:pointer}.skip{position:absolute;left:10px;top:-70px;background:white;padding:10px}.skip:focus{top:10px}li{margin:8px 0}.sources{font-size:12px;line-height:1.8}.sources li{margin-bottom:16px}sup{font-size:10px;line-height:0}[hidden]{display:none!important}.small{font-size:13px;color:#555}.empty{padding:15px;background:#f3f3f3}.filters label{font-size:14px}#index-table{min-width:1000px}@media(max-width:640px){main{padding:28px 20px 55px}h1{font-size:27px}h2{font-size:21px}body{font-size:15px}.contents ol{columns:1}.filters{display:grid;grid-template-columns:1fr}.filters input,.filters select{width:100%}.table-wrap:before{content:'표는 좌우로 스크롤하여 확인할 수 있습니다.';position:sticky;left:0;display:block;font-size:12px;color:#555;margin-bottom:8px}}@media print{@page{size:A4;margin:16mm}.actions,.filters,.skip{display:none}main{max-width:none;padding:0}body{font-size:9.5pt;line-height:1.6}h1{font-size:21pt}h2{font-size:14pt;break-after:avoid}h3{font-size:11pt;break-after:avoid}.table-wrap{overflow:visible}.table-wrap:before{display:none}table,#index-table{min-width:0;font-size:7.5pt}th,td{padding:5px}thead{display:table-header-group}tr{break-inside:avoid}p{orphans:3;widows:3}.sources{font-size:7pt}[hidden]{display:table-row!important}}`;
function render(md){const definitions={};md=md.replace(/^\[\^(\d+)\]: (.+)$/gm,(_,n,t)=>{definitions[n]=t;return ''});md=md.replace(/\[\^(\d+)\]/g,(_,n)=>`<sup><a href="#source-${n}" aria-label="출처 ${n}">[${n}]</a></sup>`);let s=marked.parse(md);let i=0;s=s.replace(/<h2>/g,()=>`<h2 id="chapter-${++i}">`);s=s.replace(/<table>/g,'<div class="table-wrap" role="region" aria-label="표, 좌우 스크롤" tabindex="0"><table>').replace(/<\/table>/g,'</table></div>');if(Object.keys(definitions).length)s+='<ol class="sources">'+Object.entries(definitions).map(([n,t])=>`<li id="source-${n}" value="${n}">${marked.parseInline(t)}</li>`).join('')+'</ol>';return s;}
function html(title,md,nav='',extra=''){const chapters=[...md.matchAll(/^## (.+)$/gm)];if(chapters.length>7)nav+='<details class="contents"><summary>기획서 목차</summary><ol>'+chapters.map((m,i)=>'<li><a href="#chapter-'+(i+1)+'">'+esc(m[1])+'</a></li>').join('')+'</ol></details>';return '<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+esc(title)+'</title><style>'+styles+'</style></head><body><a class="skip" href="#main">본문 바로가기</a><main id="main" tabindex="-1">'+nav+render(md)+'</main>'+extra+'</body></html>';}
const trace=[];
function planMD(p){const dt=p.units,write=dt[3]>0;let m=`# ${p.id} ${p.title}\n\n`;
m+=`**${p.who}**이 겪는 문제를 ${p.title}로 줄이는 AX+SI 기획 초안이다. ${p.reason}.\n\n`;
m+=`| 구분 | 내용 |\n|---|---|\n| 업무 연결 | ${p.source_item_id} · ${p.category} · ${list.items[p.n-1].business} |\n| 검토 상태 | ${p.status}. ${p.verification} |\n| 대상 독자·발주 검토 | CCK 사업·기술·수행 책임자, TS 해당 업무부서. 실제 발주부서·재원 미확정 |\n| 기술·자원 전제 | NOA·로컬 LLM, 기존 서버, 신규 인프라 구매·임차·클라우드 비용 0원 |\n| 판정의 범위 | 별도 신규 사업 등록·사업 선정·CCK 주관 수행 확정 아님 |\n| 기준일 | 업무 재확인 2026-09-14. 개별 출처의 최초 조사일·재열람 여부는 각주 참조 |\n\n`;
m+='## 1. 실제 업무와 기획 대상\n\n';
m+=`**확인된 업무:** ${p.verified_work}. ${refs(p.sources)}\n\n`;
m+=`**수행 근거와 경계:** ${p.legal}. 업무의 존재와 새 AI 과업의 발주 필요성은 별도 판단이다. 페이지의 법령 인용은 조사 출발점이며 현행 법령·위탁·사무분장을 모두 대조한 법률 검토 결과가 아니다.\n\n`;
m+=`**공식 업무 중 이번 초기 범위:** ${p.scope}. 나머지 세부 업무는 이번 최소 구축 범위에 넣지 않고 동일 묶음의 후속 검토로 둔다.\n\n`;
m+='## 2. 국민·현업 문제와 WHY\n\n';
m+=`- 문제의 근거 수준: ${p.problem}.\n- 설명용 상황: ${p.scene}. 실제 관찰·면담 결과로 일반화하지 않는다.\n- 국민 가치: 잘못된 안내·보완 누락·처리 실패를 줄이고 근거를 확인할 수 있게 한다. 안전 업무에서는 검토의 질을 높이는 경로를 검증하며 사고 감소를 직접 보장하지 않는다.\n- 공공 개입 이유: 법정 절차·공공 안전서비스에서 이용자의 정보 격차와 업무 실패를 줄일 필요가 있다.\n- 왜 AI인가: ${p.baseline}만으로 해결되지 않는 자유 서술의 조건 해석·근거 연결이 있는지 비교한다. 같은 효과가 나면 AI 개발 범위를 줄이거나 제외한다.\n- 수요 확인: ${p.gate}.\n\n`;
m+='## 3. 현재 흐름과 변경할 행동\n\n';
m+=`현재 업무는 공식 안내에서 확인했지만 실제 화면 조작·처리시간·오류 발생률은 현장 확인 전이다. 아래 변경 흐름은 제안이다.\n\n`;
p.steps.forEach((s,i)=>m+=`${i+1}. ${s}.\n`);
m+=`\n최종 산출물은 **${p.output}**이다. LLM의 자연스러운 답변이나 문서 생성 자체를 업무 완료로 표시하지 않는다.\n\n`;
m+='## 4. 서비스 범위와 요구사항\n\n| 요구사항 ID | 수행할 기능 | 수용기준 초안 |\n|---|---|---|\n';
p.steps.forEach((s,i)=>{const rid=p.id+'-F'+(i+1),test=p.id+'-T'+(i+1);m+=`| ${rid} | ${s} | 입력·근거·사용자 또는 담당자 확인·결과 상태가 추적되고 미확인 값은 미확인으로 유지 |\n`;trace.push({requirement_id:rid,plan_id:p.id,user_goal:p.title,screen_id:p.id+'-UI'+Math.min(i+1,3),data:p.input,interface:p.si,authority:i===3?'권한 있는 사용자·담당자':'인증 사용자·허용 자료',test_id:test,test_status:'시험 설계; 실제 제품 시험 미수행'});});
m+=`\n- 핵심 입력: ${p.input}.\n- 결과: ${p.output}.\n- 초기 물량: ${dt[0]}개 문서 유형, ${dt[1]}개 규칙·지침 묶음, ${dt[2]}개 조회 인터페이스, ${dt[3]}개 처리·인계 인터페이스를 상한 가정으로 견적 확인한다. 실제 API 개수나 제공 사실이 아니다.\n- 제외: 비전·OCR·STT·TTS·센서·차량제어·검사설비, 자동 법적·안전 판정, 기관 간 원본 데이터의 포괄 통합.\n- 입력 제한: 텍스트 전자문서·승인된 정형 결과만 사용한다. 스캔·사진 필수자료는 기존 공식 제출경로에서 사람이 확인하며 전체 제출절차를 AI가 완결했다고 표시하지 않는다.\n\n`;
m+='## 5. 데이터·NOA·SI 및 책임\n\n| 계층 | 역할·범위 | 확보 상태 |\n|---|---|---|\n';
m+=`| 데이터 | ${p.input} | 담당부서 허용·표본·품질·용도 확인 전 |\n| NOA·로컬 LLM | 입력 서술의 구조화·검색·근거 설명·${p.output} 초안 | 공급사 설명과 내부 대장 참고; TS 버전·실행·사용권 검증 전 |\n| 업무 규칙·SI | ${p.si} | 인터페이스·권한·변경 협조 미확정 |\n| 사람 | 사실 정정, 보완·적격·안전·공개·발송의 최종 확인 | ${p.owner}와 실제 분장 협의 필요 |\n| CCK 주관 범위 | 요구사항·NOA 구성·업무 모듈·연계·검수·운영 인수 총괄 | 담당 인력·가용률·납품계약 확인 전 |\n\n`;
m+='NOA 공개 소개는 폐쇄망·업무 연결·감사·사람 검토를 설명한다. 특정 기능이 현재 TS 설치물에서 동작한다는 증거와는 다르다. 내부 대장의 기재와 현재 정정도 원 코드·사용권·실행 시험을 대신하지 않으므로, NL2SQL·승인 중단/재개·자동 재실행을 기본 보유 기능으로 확정하지 않는다.[^33][^44][^45][^46]\n\n';
m+=`기존 운영사에는 ${p.si}의 계약·인터페이스 협조를 요청하는 역할안을 둔다. 협력사 확보나 기관 협조가 완료됐다는 뜻은 아니다. ${write?'쓰기 연계가 허용되지 않으면 준비·조회·공식 화면 인계까지만 납품하고 신청 완료 기능과 비용을 축소한다.':'초기에는 조회·검토 결과 생성까지 제한하며 기존 시스템의 결정·상태 변경은 담당자가 수행한다.'}\n\n`;
m+='## 6. 대안·중복과 현재 판정\n\n| 대안 | 범위·효과 가설 | 비용·기간 영향 | 판단 |\n|---|---|---|---|\n';
m+=`| 현행 유지·운영 개선 | ${p.baseline} | 신규 구축 최소; 반복 문제 잔존 여부 확인 | 유효한 비교 기준 |\n| SI·규칙 개선 | 입력·식별자·상태·원문 검색 정비 | 연계·데이터 정비 필요, LLM 운영 부담 없음 | 같은 목표를 달성하면 우선 적용 |\n| NOA+SI | ${p.output}와 검토 흐름 | 문서 정비·AI 평가·연계·운영 비용 추가 | ${p.status} |\n\n`;
m+=`**중복 대조:** ${p.overlap}. 비교 단위는 업무·대상자·입력 데이터·기능·산출물·성과다. SFR-001~009 정리자료는 기존 플랫폼·자동차검사/자격시험/안전단속 특화·민원·전세버스 공시 기능을 명시한다. 계약 원문·승인된 직무 시나리오와 같은 범위이면 신규로 제안하지 않는다.[^43][^31]\n\n`;
m+=`**현재 판단:** ${p.status} — ${p.reason}. ${[17,22].includes(p.n)?'독립 사업의 구축·예산을 책정하지 않고 관련 기획서에 부속 과업으로 연결한다.':'비중복·제품·수요 검증 전에는 확정 후보나 발주 가능 사업으로 승격하지 않는다.'}\n\n`;
m+='## 7. 화면·예외·사용자 경험\n\n| 화면 ID | 목표·주요 행동 | 권한·표시 |\n|---|---|---|\n';
m+=`| ${p.id}-UI1 | 입력·자료·현재 상태 확인 | 본인 또는 담당 권한, 필수 입력·자료 미확보 표시 |\n| ${p.id}-UI2 | ${p.output} 검토 | 원문·버전·확인/미확인·상충을 함께 표시 |\n| ${p.id}-UI3 | 수정·확인·인계 결과 확인 | 사용자·담당자 승인 기록, 원천 접수·판정과 AI 초안을 구분 |\n\n`;
m+=`- 업무 예외: ${p.exception}.\n- 로딩: 문서·시스템 조회 중임을 표시하고 중복 실행을 막는다.\n- 빈 상태: 자료·결과가 없다는 사실과 다음 확인 항목을 표시한다.\n- 권한 없음: 자료 제목·요약도 노출하지 않고 허용된 문의 경로를 제시한다.\n- 일부 성공·타임아웃: 완료된 단계와 실패 단계를 나누고 마지막 확인시점·재시도 가능 여부를 표시한다.\n- 접근성 목표: WCAG 2.2 AA를 목표로 키보드·초점·레이블·확대·스크린리더를 설계 단계에서 검증한다. 이번 기획 문서 검사는 제품 접근성 인증이 아니다.\n- 개인정보·운영: 로그는 최소 식별자·상태 중심, 원문 접근은 별도 권한, 원본 변경·삭제를 검색 인덱스·캐시까지 반영한다. 보존기간은 업무 규정으로 확정한다.\n\n`;
m+='## 8. 성공지표와 시험 설계\n\n';
m+=`핵심 지표는 **${p.kpi}**다. 기준값은 미측정이며 임의의 달성률을 쓰지 않는다. 같은 업무 사례에서 현행/비AI와 NOA+SI를 비교하고 입력·모델·규칙·동시성·문서 버전을 기록한다. 표본과 목표 개선폭은 실제 자료와 피해 수준을 보고 실증 전에 정한다.\n\n`;
m+='| 시험 | Given / When / Then 요약 | 합격 기준 초안 | 상태 |\n|---|---|---|---|\n';
m+=`| ${p.id}-T1 정상 | 승인된 자료가 있을 때 해당 입력을 처리하면 ${p.output}와 원문 근거가 연결됨 | 필수 근거와 상태 연결 누락 없음 | 미수행 |\n| ${p.id}-T2 업무 예외 | ${p.exception} | 해당 예외에서 완료·적합·공개를 임의 확정하지 않음 | 미수행 |\n| ${p.id}-T3 권한·개정 | 권한 회수 또는 원문 개정 후 조회하면 제한·개정 상태가 반영됨 | 사전 정의한 시험 사례에서 무권한 노출 0건 | 미수행 |\n| ${p.id}-T4 인계·복구 | 승인·접수 실패 또는 중복 요청 시 결과를 확인하고 재처리 | 무승인 상태변경·허위 완료 표시·중복 처리 0건 | 미수행 |\n| ${p.id}-T5 가치 비교 | 동일 입력을 ${p.baseline}과 비교 | 중대한 품질 저하 없이 사전 합의한 국민·현업 지표 개선 | 미수행 |\n\n`;
m+='시험집의 실패 0건은 실제 운영 위험 0의 보증이 아니다. 안전·개인정보 결함은 빈도와 피해를 함께 검토하며 미해결 중대 결함이 남으면 확대하지 않는다. 개선시간을 감축 인원으로 환산하지 않는다. 현업 의견은 아직 수집하지 않았고, 검토 품질·교육·국민 지원에 확보 시간을 활용하는 방안을 협의한다.\n\n';
m+='## 9. 비용·일정·납품 범위\n\n';
m+=`견적 산정의 초기 입력은 ${p.scope}다. 이는 물량을 제한한 제안 가정이며 확보된 서버 성능·인력·공수의 실측값이 아니다.\n\n`;
m+='| 원가 항목 | 산정 입력 | 현재 금액 |\n|---|---|---|\n';
m+=`| 업무·데이터 정비 | ${dt[0]} 문서 유형 × 유형별 표본 확인·필드·버전 정비 공수 | 견적 필요 |\n| 규칙·지식 구성 | ${dt[1]} 규칙/지침 묶음 × 적용일·원문 위치·예외 정비 공수 | 견적 필요 |\n| 기능·화면 | 4개 요구기능과 3개 화면의 개발·접근성 검토 공수 | 견적 필요 |\n| 시스템 연계 | 조회 ${dt[2]}개 + 처리/인계 ${dt[3]}개 × 인증·계약·오류 복구 공수 | 제공 여부·견적 필요 |\n| NOA 사용·구성 | 기존 계약 사용권 확인 후 추가 모듈·사용료 여부 대조 | 기존분 재청구 금지, 증분만 견적 |\n| 검증·보안·전환·교육 | 시험자료·평가·배포 설정·복원 시험·운영 인수 | 견적 필요 |\n| 신규 인프라 | GPU·서버·저장·백업·망 장비 구매/임차·클라우드 | **0원** |\n| 지속 운영 | 기준·지식 변경, API 변경 대응, 모델 품질 점검, 문의·장애 처리 | 책임·주기·연간 공수 확인 후 산정 |\n\n`;
m+='계산식은 역할별 공수×검증된 단가 + 승인된 증분 SW/용역비이며 계약조건에 맞는 제경비·부가세 등을 별도로 확인한다. 시장 단가·라이선스 견적·실측 공수 없이 금액을 확정하지 않는다. 프로그램의 1차 7억·2차 추가 5억 원은 VAT 포함으로 해석한 목표 상한이며, 이 22건 각각의 예산이나 전부 구축 가능한 예산이 아니다.[^38][^48]\n\n';
m+='| 단계 | 기간 가정 | 책임·산출물 | 다음 단계 조건 |\n|---|---|---|---|\n| 범위·근거 확인 | 2~4주 | CCK+업무부서: 중복표·자료·업무규칙·서버 확인 | 계약·자료·사용권·수요 조건 충족 |\n| 제한된 시범 구축 | 6~10주 | CCK: 화면·문서/규칙팩·허용된 연계·로그 | 기능·보안 시험 준비 |\n| 현업 검증·인수 | 2~4주 | CCK+TS: 비교시험·오류정정·교육·운영문서 | 사전 수용기준·현업 인수 승인 |\n\n';
m+='기간은 인력·연계 협조가 확보된 한 업무의 예시 일정이며 계약 납기가 아니다. 자료·권한·API가 지연되면 무조건 병행 개발하지 않고 초기 범위와 일정을 재조정한다. 납품은 요구사항·데이터/규칙·화면·소프트웨어 구성·연계 명세·시험 결과·운영/복구 문서·교육을 포함한다.\n\n';
m+='## 10. 추진 조건·운영·확장\n\n';
m+=`- 다음 증거: ${p.gate}.\n- 운영 책임: ${p.owner}가 업무·규칙·승인을, CCK가 계약 범위의 소프트웨어 품질·변경·장애 대응을 담당하는 역할안이다. 실명·협력 계약·가용인력은 미확정이다.\n- 축소/중단 조건: 비중복 미입증, 허용 자료 부재, 비AI와 차별적 성과 없음, 기존 서버 품질 미달, 중대 결함 발생.\n- 복귀: AI 제안 기능을 끄고 기존 업무 화면·규칙·공식 처리 경로를 유지한다. 원본을 수정하지 않으며 배포 구성·규칙 버전을 되돌린다.\n- 확장: ${p.expand}. 기관 간 개인정보·업무자료 통합 권한을 확보했다는 뜻은 아니다.\n- 발주 전 절차: 사업 유형·재원·금액·시점에 따라 정보화·보안·개인정보·계약 관련 검토의 적용 여부를 TS 담당자와 확정한다. 모든 과제에 같은 심의를 요구한다고 단정하지 않는다.\n- 자체 기획 판정: **${p.status}**. 실제 실행 승인·외부 평가위원 판정은 미실시.\n\n`;
m+='## 11. 기획 기준 추적\n\n| 기준 | 이 기획서의 연결 | 남은 검증 |\n|---|---|---|\n';
m+=`| P01 국민 가치 | 2절의 수혜자·문제, 8절 ${p.kpi} | 실제 이용·현업 조사, 독립 R&D 아님 |\n| P02 조직·인력 | 8·10절 검토·교육·운영 역할 | 현업 수용성·가용인력 확인 |\n| P03 AX+SI | 4~6절 ${p.family} 및 ${p.si} | 비AI 비교·설치 버전·API 시험 |\n| P04 메가이슈 | ${p.family==='국민서비스 처리'?'디지털 접근성과 이동·행정서비스 이용 실패':'교통안전 책임성과 기준·증빙·교육의 일관성'}를 해당 TS 업무와 연결 | 문제 규모·인과효과는 미검증 |\n| P05 재사용 | 10절 ${p.expand} | 기관별 법령·데이터·운영 차이 |\n| P06 법정 역할 | 1절 공식 업무·법령 안내 | 현행 조문·위탁·실제 분장 확정 |\n| P07 WHY·재정·책임 | 2·6·8~10절 | 예산·수용기준·검토 절차 적용성 |\n\n`;
m+='[통합 기획 비교표](../00_사업기획_통합보기.html) · [공통 기술·비용·추진 설계](../01_공통_수행설계.md) · [검증 기록](../검증기록.md)\n';
m+=foot([...p.sources,33,44,45,46,43,31,38,48]);return m;}
for(const p of plans){const m=planMD(p);p.document='개별기획서/'+p.filename+'.md';p.html='개별기획서/'+p.filename+'.html';fs.writeFileSync(path.join(out,p.document),m);fs.writeFileSync(path.join(out,p.html),html(p.title,m,'<div class="actions"><a href="../00_사업기획_통합보기.html">22개 기획 비교</a><a download href="'+esc(p.filename)+'.md">Markdown</a></div>'));}
let common='# TS 업무별 AX 공통 수행 설계\n\n';
common+='22개 업무를 각각 검토하되 같은 검색·권한·연계·승인 기능을 22번 구축하지 않는 구조다. 데이터 주권을 공통 운영조건으로 두고 국민서비스 처리와 안전업무의 결과를 개선한다. CCK의 주관 수행은 제품 사용권·실행·인력·연계·납품·운영을 확인한 뒤 확정한다.\n\n';
common+='## 1. 아키텍처와 기술 재사용\n\n기관 인증·업무 권한 → 허용된 전자문서/정형 결과 → 규칙·버전 검증 → 로컬 검색·LLM → 근거가 있는 초안 → 사용자·담당자 확인 → 허용된 공식 API 또는 기존 화면 인계 → 결과·감사 이력의 순서로 구성한다. 이 구조는 설계 제안이며 구현 완료를 뜻하지 않는다.\n\n';
common+='| 계층 | 재사용 후보와 신규 작업 | 확인 증거 |\n|---|---|---|\n| NOA 실행 환경 | 기존 TS의 사용권·모델·문서처리·감사 기능 재사용 후보 | 설치 버전·사용 계약·폐쇄망 실행 로그 |\n| 문서/지식 | 텍스트 원본·규칙·출처·버전 관리, 업무별 정비 필요 | 실제 문서 형식·추출 누락·권한·개정 시험 |\n| 업무 모듈 | 증빙 대조·준비 지원·사례화 등 필요한 차이만 구성/개발 | 기존 기능 대조표·구체 요구사항·시연 |\n| SI 연계 | 공식 상태·조회·인계·승인·복구 | API 계약·인증·응답 스키마·중복/타임아웃 시험 |\n| 운영 | 변경·보안·평가·장애·교육·복귀 | 운영 책임자·주기·예산·인수 문서 |\n\n';
common+='공급사 공개 자료와 내부 기술 대장은 근거 종류가 다르다. NOA 소개의 폐쇄망·감사·문서 업무 설명은 제품 기능 주장으로 분류한다. 카탈로그의 TA 명칭·자사 TRL·다른 도메인 시험은 TS 설치물의 성능 보증이 아니다. 계획 단계 기술·자동 재실행·SQL 실행·스캔 인식을 필수 완성 기능으로 가정하지 않는다.[^33][^44][^45][^46]\n\n';
common+='## 2. 공통화할 다섯 기능 묶음\n\n| 기능 묶음 | 관련 기획 | 비용 중복 방지 |\n|---|---|---|\n| 증빙 대조 | P01·03·04·05·11·12, P17 연계 | 공통 대조·근거 UI 1회, 업무별 기준·필드·평가만 추가 |\n| 국민서비스 처리 | P02·07·09·10·15·18·19·20 | 본인확인·동의·상태·인계 패턴 재사용, 업무별 API와 규칙 별도 |\n| 보호된 안전사례 | P06·08 | 사례 초안 엔진 구조 재사용, 원본·권한·분류·전파 절차 분리 |\n| 기준 변경·준비 | P13·14 | 변경 영향 구조 재사용, 제작자 준비와 시험기관 문서 분리 |\n| 교육·결과 설명 | P16·21, P22 과정 모듈 | 교재·결과 근거 연결 1회, 과정별 승인 콘텐츠팩 추가 |\n\n';
common+='기능 묶음은 재사용 설계이며 예산 확보나 다섯 개 사업 선정이 아니다. 업무와 데이터가 같지 않은데 엔진이 같다는 이유로 모든 문서를 통합하지 않는다. P17은 P01의 COSAS 연결, P22는 P21의 이륜차 과정으로 통합하는 검토안이다.\n\n';
common+='## 3. 비중복 확인의 실제 순서\n\n1. 최종 계약·승인 RFP·추가합의·현재 납품 기능을 확보한다.\n2. SFR-003의 자동차검사·자격시험·안전단속 실제 시나리오를 구체적으로 대조한다.\n3. SFR-001~005의 데이터·지식·대화형 지원과 신규 업무 모듈의 차이를 산출물로 적는다.\n4. SFR-006~007 민원 범위와 새 신청·완료 확인 흐름을 비교한다. 민원이라는 명칭만으로 일괄 배제하지 않는다.\n5. SFR-008~009 전세버스 공시 과업은 신규로 재포장하지 않는다.\n6. 운영사 기능과 비교해 이미 구현된 기능이면 유지·고도화 또는 제외로 처리한다.[^43][^31]\n\n';
common+='## 4. 데이터·보안·실행 통제\n\n원본·임베딩·검색·재정렬·문서 변환·로그·백업·라이선스 호출·외부 모델 대체경로까지 데이터 흐름을 확인한다. 기관 내부 LLM 설치만으로 데이터 주권이 완성되는 것은 아니다. 권한 없는 문서가 검색 결과·요약·추론에 들어가지 않게 하고, 원본 회수·개정을 인덱스와 캐시에 반영한다.\n\n';
common+='예약·신청은 입력 준비, 사용자의 확인·동의, 정형 API 검증, 접수 상태 확인을 분리한다. API에 멱등성 기능이 없다면 애플리케이션의 요청ID·상태조회·재시도 잠금으로 중복을 통제하되 실제 계약 시험으로 확인한다. 성공 여부를 알 수 없는 타임아웃을 성공으로 표시하지 않는다. 안전·법적 판정과 보호자료 공개는 담당자가 책임진다.\n\n';
common+='## 5. 기존 서버·예산·일정\n\n1차 7억·2차 추가 5억 원은 VAT 포함으로 해석한 전체 프로그램 목표 상한이다. 22개 독립 사업이나 22개 전체 구축 견적이 아니다. GPU·서버·저장·백업·망 장비의 신규 구매·증설·임차, 클라우드 자원비, 기존 장비 유지보수·자원 증분은 이번 신규 사업비에서 제외한다. 기존 환경 배포 설정·SW 연계·복원 시험 공수는 구분한다.[^38][^48]\n\n';
common+='원가는 공통 기능 1회분 + 선정 업무별 증분 + 연계·검증·전환 + 확인된 증분 사용료로 계산한다. 운영·변경 비용도 따로 기록한다. 공식 단가·견적·가용인력·문서량·API 계약이 없으므로 이 단계에서 항목별 금액과 이익률을 확정하지 않는다. 범위를 정한 뒤 역할별 공수와 검증된 단가, 산정방식과 부가세를 대조한다.\n\n';
common+='기존 서버에서는 모델 버전·정밀도·문맥 길이·동시성·평균/최대 문서 길이·지식량·피크 사용시간을 기록하고 부하·응답·근거 품질을 함께 시험한다. 여력이 부족하면 대기열·배치·업무량·모델 설정·범위를 줄이고 재검증한다. 외부 클라우드 대체나 신규 장비 구매를 숨겨 넣지 않는다.\n\n';
common+='단일 업무의 예시 일정은 조건 확인 2~4주, 제한 시범 6~10주, 검증·인수 2~4주다. 실제 기간은 인력·문서·승인·API 협조에 달려 있으며 22건 동시 구축 계획이 아니다. 1차에는 근거가 확보된 소수 업무를 선택하고, 2차는 재사용 효과·추가 수요·서버 여력 확인 후 확대한다.\n\n';
common+='## 6. 먼저 확인할 업무와 결정 순서\n\n- **P13 자기인증:** TS가 제작자의 절차·서류 어려움을 공식 설명했다. 실제 보완 사례를 확보해 기존 영상·서식 안내와 비교하는 수요 검증을 먼저 시작할 근거가 있다.[^40]\n- **P04 철도 안전증빙 또는 P11 주차장 보완:** 기존 후보와 연결되므로 한 업무의 실제 자료·검토자·계약 경계를 확보한 후 선택한다. 수요 검증·데이터 확보 전 순위 확정은 하지 않는다.\n- **P06·P08 자율보고:** 핵심 업무 연결은 확인되지만 보호자료 이용 목적·권한·전문 검토 확보가 선행한다.\n- **P10 예약:** 최신 화면에서 불편을 재현하고 UI·API 개선으로 얻는 효과를 먼저 확인한다.\n- **P17·P22:** 독립사업으로 새 엔진과 예산을 잡지 않고 각각 P01·P21의 부속 과업으로만 검토한다.\n\n';
common+='## 7. 실제 시험·심의와 전달 준비\n\n사업화 판정은 문서의 완성도와 다르다. 실제 수요, 최종 계약 비중복, NOA 설치물, 사용권, 자료·API, 가용인력, 견적, 수용기준을 갖춰야 구축 착수가 가능하다. 법령·보안·개인정보·정보화·조달 관련 절차는 사업 유형·금액·재원·시점별 적용성을 확인한다. 특정 심의를 모든 안에 일률적으로 단정하지 않는다.\n\n';
common+='이번 단계의 시험계획은 실제 제품 시험 결과가 아니다. 문서 QA에서는 22개 ID의 대응, 출처·필수 항목, 금액·제외 조건, 중복 합산 방지, 링크·검색·필터·화면을 확인한다. 독립 평가위원·실제 사용자의 승인과 NOA 시험은 미수행 상태로 남긴다.\n';
common+=foot([33,44,45,46,43,31,38,48,40]);fs.writeFileSync(path.join(out,'01_공통_수행설계.md'),common);fs.writeFileSync(path.join(out,'01_공통_수행설계.html'),html('TS 업무별 AX 공통 수행 설계',common,'<div class="actions"><a href="00_사업기획_통합보기.html">22개 기획 비교</a></div>'));
let overview='# 한국교통안전공단 22개 업무별 사업기획\n\n';
overview+='TS 공식 주요사업의 7개 대분류에 연결한 22개 업무 묶음을 각각 사업기획 초안으로 구체화했다. 업무의 존재를 확인하고, 해결할 문제·NOA 역할·초기 범위·비AI 대안·중복·비용 입력·시험·운영·확장 조건을 연결했다. 22개는 공식 사업 총수나 선정 사업 수가 아니며 기존 후보대장에 합산하지 않는다.[^3]\n\n';
overview+='각 기획은 CCK 주관 수행, NOA·로컬 LLM, 기존 서버, 신규 인프라 투자 0원 조건이다. 공통플랫폼·기존 민원·전세버스 공시 AI의 범위를 새 사업으로 반복 제안하지 않는다. 민원 분야 전체를 배제하지 않고 동의한 실제 처리·완료 확인 단계의 차이를 검증한다.[^31][^48]\n\n';
overview+='## 검토 결과를 읽는 방법\n\n업무 확인은 공식 사업의 존재 확인이며 실제 수요나 최종 계약 비중복 확인과 다르다. **우선 수요검증**은 확인할 문제 근거가 비교적 구체적이라는 뜻이고 수주·사업선정 우선순위가 아니다. **중복 선확인·유보·비AI 우선**도 기획서를 작성하되 착수 조건을 달리 둔다. **통합**은 관련 기획에 부속해 중복 구축을 피한다.\n\n';
overview+='## 22개 기획 비교\n\n| ID | 대분류·업무 | 사업기획 | 현재 판단 | 초기 범위 |\n|---|---|---|---|---|\n';
for(const p of plans)overview+=`| ${p.id} | ${p.category} / ${list.items[p.n-1].business} | [${p.title}](<${p.html}>) · [MD](<${p.document}>) | ${p.status} | ${p.scope} |\n`;
overview+='\n## 추진 묶음과 예산 경계\n\n기술 구조는 증빙 대조, 국민서비스 처리, 보호된 안전사례, 기준 변경·준비, 교육·결과 설명의 다섯 묶음으로 재사용한다. P17은 P01, P22는 P21의 부속 범위로 검토한다. P13은 공식 제작자 불편 근거가 있어 먼저 수요·비AI 대조를 확인할 수 있다. 다만 모든 기획에 최종 계약·제품·자료·현업 검증이 남아 있다.[^40][^43]\n\n';
overview+='1차 7억·2차 추가 5억 원은 전체 프로그램 목표 상한이며 이 22개 전부의 구축 견적이 아니다. 개별 금액은 문서 유형·규칙팩·조회/처리 연계·역할별 공수·추가 사용권·운영비를 확인한 뒤 산정한다. 신규 인프라 비용 0원은 유지한다.[^38][^48]\n\n';
overview+='## 자료와 검증 범위\n\n- [공통 기술·비용·추진 설계](01_공통_수행설계.html) · [MD](01_공통_수행설계.md)\n- [업무별 확인 원장](02_업무별_확인원장.json)\n- [22개 기획 데이터](03_사업기획_원장.json)\n- [요구사항·화면·시험 추적표](04_요구사항_추적표.json)\n- [후속 확인 대기열](05_후속확인_대기열.md)\n- [검증 기록](검증기록.md)\n\n';
overview+='업무의 핵심 공식 안내는 2026-09-14에 재확인했다. 개별 보도자료·공고의 사건 날짜와 열람일을 구분하며, 이전 자료를 활용한 근거는 원장의 재확인 상태에 표시했다. 원법령·위탁관계·최종 계약·실제 이용자의 문제·NOA 동작·서버 부하·견적은 전체 검증되지 않았다. 자동차검사 예약 불편은 이용 경험을 토대로 하며 현재 화면에서 재현하지 않았다.\n';
overview+=foot([3,31,48,40,43,38]);
fs.writeFileSync(path.join(out,'00_사업기획_통합보기.md'),overview);
let oh=html('한국교통안전공단 22개 업무별 사업기획',overview,'<div class="actions"><a href="#chapter-2">22개 기획 비교표</a><a href="01_공통_수행설계.html">공통 수행설계</a><a download href="00_사업기획_통합보기.md">Markdown</a></div>');
const opts=[...new Set(plans.map(p=>p.status))];
const control='<div class="filters"><label for="cat">대분류</label><select id="cat"><option value="">전체</option>'+list.categories.map(c=>'<option>'+esc(c)+'</option>').join('')+'</select><label for="state">판단</label><select id="state"><option value="">전체</option>'+opts.map(c=>'<option>'+esc(c)+'</option>').join('')+'</select><label for="q">검색</label><input id="q" type="search" placeholder="업무·서비스·ID 검색"><button id="reset" type="button">초기화</button><span id="count" role="status" aria-live="polite">22개 기획</span></div>';
oh=oh.replace(/(<h2[^>]+>22개 기획 비교<\/h2>)/,'$1'+control).replace('<table>','<table id="index-table">');
oh=oh.replace('</body>','<script>const rows=[...document.querySelectorAll("#index-table tbody tr")],cat=document.getElementById("cat"),state=document.getElementById("state"),q=document.getElementById("q"),count=document.getElementById("count");const empty=document.createElement("p");empty.className="empty";empty.hidden=true;empty.textContent="조건에 맞는 기획이 없습니다. 조건을 바꾸거나 초기화하세요.";document.getElementById("index-table").parentElement.after(empty);function filter(){let n=0;for(const r of rows){const ok=(!cat.value||r.cells[1].textContent.startsWith(cat.value+" / "))&&(!state.value||r.cells[3].textContent===state.value)&&r.textContent.toLowerCase().includes(q.value.trim().toLowerCase());r.hidden=!ok;if(ok)n++}count.textContent=n+" / 22개 기획";empty.hidden=n!==0}for(const e of [cat,state])e.addEventListener("change",filter);q.addEventListener("input",filter);document.getElementById("reset").addEventListener("click",()=>{cat.value="";state.value="";q.value="";filter();q.focus()})</script></body>');
fs.writeFileSync(path.join(out,'00_사업기획_통합보기.html'),oh);
const used=[...new Set(plans.flatMap(p=>p.sources).concat([3,33,44,45,46,43,31,38,48]))];
fs.writeFileSync(path.join(out,'근거원장.json'),JSON.stringify({as_of:'2026-09-14',sources:used.map(n=>sm.get(n)),limitations:['공식 업무 안내의 법령 인용은 현행 조문·위탁 전체 검증 아님','내부 RTM은 최종 계약 원문 아님','NOA 소개·기술대장은 TS 설치·사용권·성능 보증 아님'],source_conflicts:[{source:27,description:'2026년 공고 본문에 신청기간 연도 2025 표기가 혼재. 현행 접수 일정으로 인용하지 않음'},{source:34,description:'2026-09-14 웹 열람 실패. 9월 11일 보존 공급사 텍스트만 참고'}]},null,2));
fs.writeFileSync(path.join(out,'02_업무별_확인원장.json'),JSON.stringify({checked_at:'2026-09-14',population:'기존 TS-L01~22 업무 묶음',items:plans.map(p=>({source_item_id:p.source_item_id,plan_id:p.id,category:p.category,business:list.items[p.n-1].business,verified_work:p.verified_work,source_ids:p.sources.map(n=>sm.get(n).id),verification_scope:p.verification,legal_pointer:p.legal,initial_scope:p.scope,source_date_notes:p.sources.map(n=>({id:sm.get(n).id,checked:sm.get(n).accessed_at,status:sm.get(n).recheck_status}))})),count:22,all_TS_leaf_businesses_reviewed:false,all_legal_delegations_verified:false,all_contracts_verified:false},null,2));
fs.writeFileSync(path.join(out,'03_사업기획_원장.json'),JSON.stringify({version:'0.1',prepared_at:'2026-09-14',plan_count:22,existing_candidate_count_unchanged:true,new_infrastructure_budget_won:0,program_caps_vat_included_assumption:{stage1_won:700000000,stage2_additional_won:500000000,status:'목표 상한 검토안; 22건 전체 견적 아님'},actual_product_test_runs:0,plans},null,2));
fs.writeFileSync(path.join(out,'04_요구사항_추적표.json'),JSON.stringify({type:'설계 추적표',actual_product_tests_run:0,requirements:trace},null,2));
let queue='# 업무별 후속 확인 대기열\n\n모든 항목의 책임자는 아래 역할안이다. 실제 담당자·기한은 자료 확보 협의에서 정한다.\n\n| 기획 | 우선 확보 자료·판단 | 확인 책임 역할 | 현재 상태 |\n|---|---|---|---|\n';
plans.forEach(p=>queue+=`| ${p.id} | ${p.gate} | ${p.owner} + CCK 기획/기술 담당 | 미확보·협의 전 |\n`);
queue+='\n공통 선행조건: 최종 계약·실제 특화직무 범위, NOA 설치 버전·사용권·로컬 처리 전체 경로, 가용인력·서버 부하, 실제 데이터 권한·API, 현행 법령·위탁·분장, 비AI 기준선·수용기준, 역할별 공수·단가·운영비.\n';fs.writeFileSync(path.join(out,'05_후속확인_대기열.md'),queue);
fs.writeFileSync(path.join(out,'검증기록.md'),'# TS 22개 업무 사업기획 검증 기록\n\n문서 기준: 2026-09-14. 실제 제품 시험·독립 평가위원 승인·외부 제출·배포는 미수행.\n\n기획 데이터 22건·기존 업무 ID 22개·요구사항 88개를 연결했다. 생성 이후 구조·동작·화면 검증 결과를 이 문서와 검증 폴더에 기록한다.\n');
fs.writeFileSync(path.join(out,'README.md'),'# TS 22개 업무별 사업기획\n\n- [통합 보기](00_사업기획_통합보기.html) · [통합 MD](00_사업기획_통합보기.md)\n- [공통 수행설계](01_공통_수행설계.html)\n- 개별기획서 폴더: TS-P01~22 HTML·MD\n- [업무 확인 원장](02_업무별_확인원장.json) · [기획 데이터](03_사업기획_원장.json) · [추적표](04_요구사항_추적표.json)\n- [후속 확인](05_후속확인_대기열.md) · [근거원장](근거원장.json) · [검증 기록](검증기록.md)\n\n각 기획은 검토 초안이며 기존 후보 수·예산 상태를 바꾸지 않는다. NOA·로컬 LLM, 기존 서버, 신규 인프라 0원 조건. 실제 사업 선정·제품 시험·견적 확정 전이다.\n');
for(const name of ['ts22_plan_data.cjs','ts22_plan_build.cjs'])fs.copyFileSync(path.join(__dirname,name),path.join(out,name));
console.log(JSON.stringify({output:out,plans:plans.length,categories:list.categories.length,requirements:trace.length,sources:used.length,files:fs.readdirSync(path.join(out,'개별기획서')).length,statuses:plans.reduce((a,p)=>(a[p.status]=(a[p.status]||0)+1,a),{})},null,2));
