const fs=require('fs'),path=require('path'),crypto=require('crypto');
const {pathToFileURL,fileURLToPath}=require('url');
const {chromium}=require(require.resolve('playwright',{paths:['C:/Users/김희섭/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules']}));
const root=__dirname, project=path.resolve(root,'../../..'), checks=[];
const d=JSON.parse(fs.readFileSync(path.join(root,'설명자료_데이터.json'),'utf8'));
const m=JSON.parse(fs.readFileSync(path.join(root,'생성기록.json'),'utf8'));
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const check=(name,pass,detail=null)=>checks.push({name,pass:!!pass,detail});
const near=(a,b)=>Math.abs(a-b)<1e-6;
(async()=>{
for(const [n,h] of Object.entries(m.outputs))check('산출물 무결성 '+n,sha(path.join(root,n))===h);
check('기존 원장·문서 보존',Object.entries(m.protected_hashes).every(([n,h])=>sha(path.join(project,n))===h));
check('생성 입력과 산출물의 일치',Object.entries(m.input_hashes).every(([n,h])=>sha(path.join(root,n))===h));
const old=JSON.parse(fs.readFileSync(path.join(root,'../대화원문_2차.json'),'utf8'));
check('기존 10건 발언·원본 ID 일치',old.turns.every(t=>d.turns.some(n=>n.id===t.id&&n.source_turn_id===t.source_turn_id&&n.user_text===t.user_text)));
check('15건 발언·신규 5건·기능 17건',d.turns.length===15&&new Set(d.turns.map(t=>t.id)).size===15&&d.new_requirements.length===5&&d.features.length===17);
const md=fs.readFileSync(path.join(root,'CCK_Public_AI_PMS_설명서.md'),'utf8');
check('Markdown의 기능·신규 요구 연결',d.features.every(f=>md.includes(f.id)&&md.includes(f.name))&&d.new_requirements.every(r=>md.includes(r.id)&&md.includes(r.turn)));
const browser=await chromium.launch({headless:true,channel:'msedge'});
try{
const page=await browser.newPage({viewport:{width:1500,height:1000},reducedMotion:'reduce'});
const errors=[],external=[];
page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))external.push(r.url())});
await page.goto(pathToFileURL(path.join(root,'CCK_Public_AI_PMS_설명서.html')).href);
check('제목·언어·핵심 정의',(await page.title()).includes('CCK Public AI-PMS')&&await page.getAttribute('html','lang')==='ko'&&(await page.locator('#overview').innerText()).includes('검사'));
check('기능 17개·단계 7개',await page.locator('.feature-table tbody tr').count()===17&&await page.locator('.step-panel').count()===7);
check('기본 계산 289시간·14,450만원·차이5,116.7만원',await page.locator('#net-hours').innerText()==='289'&&await page.locator('#annual-value').innerText()==='14,450만원'&&await page.locator('#annual-balance').innerText()==='+5,116.7만원');
for(let i=0;i<7;i++){await page.locator('[data-step="'+i+'"]').click();check('단계 선택 '+(i+1),await page.locator('#step-'+i).isVisible()&&await page.locator('[data-step="'+i+'"]').getAttribute('aria-pressed')==='true'&&await page.locator('.step-panel:visible').count()===1);}
await page.locator('[data-step="2"]').focus();await page.keyboard.press('Enter');check('키보드 단계 선택',await page.locator('#step-2').isVisible());
await page.selectOption('#case-select','failure');check('분석 실패 접수 유지 설명',(await page.locator('#case-note').innerText()).includes('제출시각·버전은 유지'));
await page.selectOption('#case-select','dispute');check('소명·정정 재사용 설명',(await page.locator('#case-note').innerText()).includes('수행이력과 인수인계'));
await page.fill('#calc-projects','20');check('사업 수 변경 반영',await page.locator('#annual-value').innerText()==='28,900만원');
await page.fill('#calc-extra_hours','500');check('추가업무가 큰 경우 음수 유지',await page.locator('#net-hours').innerText()==='-171'&&(await page.locator('#annual-balance').innerText()).startsWith('-'));
await page.fill('#calc-projects','0');check('사업 0건·비용만 남는 경우',await page.locator('#annual-value').innerText()==='0만원'&&(await page.locator('#annual-balance').innerText()).startsWith('-'));
await page.fill('#calc-years','0');check('배분기간 0 차단',await page.locator('#calc-error').isVisible()&&!await page.locator('#calc-values').isVisible());
await page.locator('#reset-calc').click();
await page.fill('#reduction-search','101');check('100% 초과 감소율 차단',await page.locator('#calc-error').isVisible());
await page.locator('#reset-calc').click();
await page.fill('#hours-search','');check('빈 입력 오류·이전 결과 숨김',await page.locator('#calc-error').isVisible()&&!await page.locator('#calc-values').isVisible());
await page.locator('#reset-calc').click();check('전체 초기화',await page.locator('#net-hours').innerText()==='289'&&await page.inputValue('#calc-projects')==='10'&&!await page.locator('#calc-error').isVisible());
const random=await page.evaluate(()=>{
const test=[];for(const scale of [0,0.5,1,3])for(const extra of [0,40,2000]){const x={tasks:[{hours:100*scale,reduction:10},{hours:200*scale,reduction:50}],extra_hours:extra,rate:50000,projects:2,opex_man:100,capex_man:300,years:3};const got=window.PMSExplain.compute(x);test.push(Math.abs(got.net-(110*scale-extra))<1e-8&&Math.abs(got.balance-((110*scale-extra)*100000-2000000))<1e-6);}return test;});
check('계산 산식 12개 조합 독립 대조',random.length===12&&random.every(Boolean));
const badLinks=await page.evaluate(()=>{const ids=new Set([...document.querySelectorAll('[id]')].map(e=>e.id));return [...document.querySelectorAll('a[href^="#"]')].map(a=>a.getAttribute('href').slice(1)).filter(id=>!ids.has(id));});
check('목차 내부 대상 존재',badLinks.length===0,badLinks);
const hrefs=await page.locator('a[href]').evaluateAll(es=>es.map(e=>e.getAttribute('href')).filter(h=>!h.startsWith('#')&&!/^[a-z]+:/.test(h)));
check('HTML 로컬 링크 존재',hrefs.every(h=>fs.existsSync(path.resolve(root,decodeURIComponent(h)))),hrefs.filter(h=>!fs.existsSync(path.resolve(root,h))));
const missingMD=[...md.matchAll(/\]\(([^)]+)\)/g)].map(m=>m[1]).filter(h=>!h.startsWith('#')&&!/^[a-z]+:/.test(h)&&!fs.existsSync(path.resolve(root,h)));
check('Markdown 로컬 링크 존재',missingMD.length===0,missingMD);
const dup=await page.evaluate(()=>{const a=[...document.querySelectorAll('[id]')].map(x=>x.id);return a.filter((s,i)=>a.indexOf(s)!==i)});
check('중복 ID 없음',dup.length===0,dup);
const unnamed=await page.locator('input,select,button').evaluateAll(es=>es.filter(e=>!(e.getAttribute('aria-label')||e.textContent.trim()||(e.labels&&e.labels.length))).map(e=>e.id));
check('입력·선택·버튼 접근 가능한 이름',unnamed.length===0,unnamed);
for(const width of [320,390,768,1500]){await page.setViewportSize({width,height:1000});await page.evaluate(()=>scrollTo(0,0));const sizes=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,body:document.body.scrollWidth}));check('가로 넘침 없음 '+width,sizes.scroll<=width+1&&sizes.body<=width+1,sizes);}
await page.setViewportSize({width:1500,height:1000});await page.evaluate(()=>{document.body.style.zoom='2'});const zoom=await page.evaluate(()=>({width:innerWidth,right:document.querySelector('main').getBoundingClientRect().right}));check('200% 확대 본문 범위',zoom.right<=zoom.width+2,zoom);await page.evaluate(()=>{document.body.style.zoom=''});
await page.locator('.sidebar nav a[href="#benefits"]').focus();await page.keyboard.press('Enter');check('키보드 목차 이동',new URL(page.url()).hash==='#benefits');
await page.locator('.sidebar nav a[href="#benefits"]').focus();await page.keyboard.press('Tab');
const outline=await page.locator(':focus-visible').evaluate(e=>({style:getComputedStyle(e).outlineStyle,width:getComputedStyle(e).outlineWidth}));check('키보드 포커스 표시',outline.style!=='none'&&parseFloat(outline.width)>=2,outline);
await page.evaluate(()=>dispatchEvent(new Event('beforeprint')));await page.emulateMedia({media:'print'});
check('인쇄 7단계 모두 표시',await page.locator('.step-panel:visible').count()===7);
check('인쇄 상세 내용 펼침',await page.locator('details:not([open])').count()===0);
check('인쇄 조작 버튼 숨김',!await page.locator('#print-button').isVisible()&&!await page.locator('.step-buttons').isVisible());
await page.emulateMedia({media:'screen'});await page.evaluate(()=>dispatchEvent(new Event('afterprint')));
check('인쇄 후 원래 상세상태 복원',await page.locator('details[open]').count()===0);
fs.mkdirSync(path.join(root,'검증화면'),{recursive:true});
await page.setViewportSize({width:1500,height:1000});await page.goto(pathToFileURL(path.join(root,'CCK_Public_AI_PMS_설명서.html')).href);
await page.screenshot({path:path.join(root,'검증화면','desktop.png')});
await page.locator('#flow').screenshot({path:path.join(root,'검증화면','flow.png')});
await page.locator('#audit').screenshot({path:path.join(root,'검증화면','audit.png')});
await page.locator('#architecture').screenshot({path:path.join(root,'검증화면','architecture.png')});
await page.locator('#benefits').screenshot({path:path.join(root,'검증화면','benefits.png')});
await page.setViewportSize({width:390,height:844});await page.evaluate(()=>scrollTo(0,0));
await page.waitForFunction(()=>document.querySelector('.sidebar nav a[aria-current="true"]')?.getAttribute('href')==='#overview');
check('모바일 상단 복귀 시 목차 동기화',await page.locator('.sidebar nav a[aria-current="true"]').getAttribute('href')==='#overview');
await page.screenshot({path:path.join(root,'검증화면','mobile.png')});
await page.locator('#architecture').screenshot({path:path.join(root,'검증화면','mobile-architecture.png')});
await page.locator('#benefits').screenshot({path:path.join(root,'검증화면','mobile-benefits.png')});
check('실행 중 외부 요청 없음',external.length===0,external);
check('JavaScript 오류 없음',errors.length===0,errors);
const nojs=await browser.newContext({javaScriptEnabled:false,viewport:{width:1280,height:900}});
const npage=await nojs.newPage();await npage.goto(pathToFileURL(path.join(root,'CCK_Public_AI_PMS_설명서.html')).href);
check('JavaScript 비활성 본문·7단계·고정 계산',await npage.locator('.step-panel:visible').count()===7&&(await npage.locator('noscript').innerText()).includes('기본 가정')&&(await npage.locator('#net-hours').innerText())==='289');
await nojs.close();
function lum(hex){const c=hex.match(/\w\w/g).map(h=>parseInt(h,16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return .2126*c[0]+.7152*c[1]+.0722*c[2];}
const pairs=[['16334a','f3f6fa'],['536a7b','ffffff'],['006f65','f3f6fa'],['c5d8e5','102b41'],['d9e6f0','102b41'],['805013','fff2dc']];
const contrast=pairs.map(([a,b])=>{const x=lum(a),y=lum(b);return {colors:[a,b],ratio:(Math.max(x,y)+.05)/(Math.min(x,y)+.05)}});
check('주요 본문·메타 색상 대비 4.5 이상',contrast.every(c=>c.ratio>=4.5),contrast);
}finally{await browser.close()}
const result={date:'2026-09-10',scope:'설명자료 기능·계산·참조·반응형 자체 검사. 실제 PMS·AI·감리·사회경제 효과 실증 아님.',browser:'Microsoft Edge / Playwright',passed:checks.every(c=>c.pass),count:checks.length,checks,visual_review:'스크린샷 생성 완료. 직접 시각 검토 결과는 설명자료_검증.md에 별도 기록.'};
fs.writeFileSync(path.join(root,'설명자료_검증.json'),JSON.stringify(result,null,2));
const report=['# 설명자료 제작·검증 결과','','검토일: 2026-09-10 / 자체 QA. 실제 PMS·AI 성능·기관 승인·독립 평가가 아니다.','','## 실행 검사','','- Microsoft Edge / Playwright로 설명자료를 파일에서 직접 열었다.','- 총 '+result.count+'개 검사: '+checks.filter(c=>c.pass).length+'개 통과, '+checks.filter(c=>!c.pass).length+'개 실패.','- 상세 결과: [검증 JSON](설명자료_검증.json).','- 대화·기능·문서 연결, 원본 보존, 계산·음수·잘못된 입력·초기화, 키보드·내부 링크·외부 요청·인쇄·JavaScript 비활성·모바일을 확인했다.','','## 판정','',''+(result.passed?'자동 검사 범위 통과.':'수정 필요: '+checks.filter(c=>!c.pass).map(c=>c.name).join(', ')),'','시각 검토는 생성된 화면을 확인한 뒤 아래에 별도 기록한다. 실제 스크린리더·다중 브라우저·기관 배포환경 시험과 독립 평가위원 검토는 수행하지 않았다.','','## 산출물','','[HTML](CCK_Public_AI_PMS_설명서.html) · [Markdown](CCK_Public_AI_PMS_설명서.md) · [아키텍처 SVG](CCK_Public_AI_PMS_아키텍처.svg) · [설계·수용기준](설명자료_설계.md)','','생성 스크립트는 한 데이터에서 HTML·Markdown을 작성한다. 원본 템플릿·스타일·동작을 바꾸면 재생성 및 관련 검증이 필요하다. 외부 공개·배포·업무자료 저장·유료 AI 호출은 수행하지 않았다.'].join('\n');
fs.writeFileSync(path.join(root,'설명자료_검증.md'),report,'utf8');
console.log(JSON.stringify({passed:result.passed,count:result.count,failed:checks.filter(c=>!c.pass)},null,2));process.exitCode=result.passed?0:1;
})().catch(e=>{console.error(e);process.exitCode=1});
