import {loadDependency} from '../공용_실행환경.mjs';
const {chromium} = await loadDependency('playwright');
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
const base=path.dirname(fileURLToPath(import.meta.url));
const browser=await chromium.launch({channel:'msedge',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(String(e)));
await page.goto(pathToFileURL(path.join(base,'00_산출물_안내.html')).href);
await page.screenshot({path:path.join(base,'검증','화면_데스크톱.png'),fullPage:false});
if(await page.locator('details').count()!==36)throw new Error('요구 개수 불일치');
await page.locator('#service').selectOption('X01');
if(await page.locator('details:visible').count()!==4)throw new Error('서비스 필터 실패');
await page.locator('details:visible').first().locator('summary').click();
if(await page.locator('details[open]').count()!==1)throw new Error('펼침 실패');
await page.locator('#collapse').click();
if(await page.locator('details[open]').count())throw new Error('접기 실패');
await page.locator('#search').fill('없는요구테스트');
if(!await page.locator('#empty').isVisible())throw new Error('빈 검색 상태 실패');
await page.locator('#search').fill('');await page.locator('#service').selectOption('');
await page.locator('#search').fill('SIR-001');
if(await page.locator('details:visible').count()!==1)throw new Error('ID 검색 실패');
await page.locator('#search').fill('');
const links=await page.locator('a[href]').evaluateAll(els=>els.map(a=>a.getAttribute('href')));
const bad=[];
for(const link of links){if(link.startsWith('http')||link.startsWith('#'))continue;const target=path.resolve(base,decodeURIComponent(link.split('#')[0]));try{await fs.access(target);}catch{bad.push(link);}}
if(bad.length)throw new Error('로컬 링크 없음 '+bad.join(','));
const desktopOverflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
await page.locator('#budget').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(base,'검증','화면_예산.png')});
await page.setViewportSize({width:390,height:844});await page.evaluate(()=>scrollTo(0,0));
await page.screenshot({path:path.join(base,'검증','화면_모바일.png')});
const mobileOverflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
await page.keyboard.press('Tab');
const focus=await page.evaluate(()=>document.activeElement.tagName);
if(desktopOverflow||mobileOverflow||errors.length)throw new Error('화면 오류');
await fs.writeFile(path.join(base,'검증','HTML_검증.json'),JSON.stringify({requirements:36,localLinks:links.filter(x=>!x.startsWith('http')&&!x.startsWith('#')).length,bad,desktopOverflow,mobileOverflow,filter:true,empty:true,expand:true,focus,errors},null,2));
console.log('HTML 링크·검색·필터·접기·빈 상태·데스크톱/모바일 폭 검사 완료');await browser.close();
