const fs=require('fs'),path=require('path'),crypto=require('crypto');
const root='G:/내 드라이브/1. 업무영역/6. CCK/1. 사업관리/TS/bizops/[TS 사업기획]';
const rel='05_통합사업기획/TS_22개업무_고도화보고서_2026-09-15',dir=path.join(root,rel);
const qa=JSON.parse(fs.readFileSync(path.join(dir,'검증/자동검증_결과.json'),'utf8'));
if(qa.summary.failed!==0)throw Error('문서 검증 미통과');
const src='C:/Users/Public/Documents/ESTsoft/CreatorTemp/';
for(const f of ['ts_enhance_qa.cjs','ts_enhance_finish.cjs'])fs.copyFileSync(path.join(src,f),path.join(dir,'작성자료',f));
const beforeDir=path.join(dir,'기준_변경전');fs.mkdirSync(beforeDir,{recursive:true});
const readme=path.join(root,'README.md'),before=fs.readFileSync(readme,'utf8');
if(!fs.existsSync(path.join(beforeDir,'README.md')))fs.writeFileSync(path.join(beforeDir,'README.md'),before,'utf8');
const row=`| TS 22개 업무별 고도화 보고서 v1.0 | [22개 보고서 통합보기](${rel}/00_고도화보고서_통합보기.html) · [Markdown](${rel}/00_고도화보고서_통합보기.md) · [공통 설계·추진·비용](${rel}/01_공통설계_추진계획_비용산정.html) | 기존 시스템·AI 기반 업무별 추가 기능, 논리 데이터·처리 상태, 132개 요구·154개 시험 설계(미실행), 단계·공수·비용 산식. 문서 검증 162개 통과. 기존 서버·신규 인프라 0원; 금액은 확정 견적 전 |`;
if(!before.includes(rel+'/00_고도화보고서_통합보기.html')){
 const marker='| TS 중복 검토·CCK AI 추가 적용 v0.2 |';if(!before.includes(marker))throw Error('README 최신자료 표 위치 확인 필요');
 fs.writeFileSync(readme,before.replace(marker,row+'\n'+marker),'utf8');
}
const report=`# 고도화 보고서 검증기록\n\n2026-09-15 최종 확인. 대상은 새 고도화 문서 패키지와 루트 README 연결이다.\n\n## 1. 결과\n\n**문서 산출물 자동검증 162개 통과·실패 0개.** 독립 평가위원 또는 TS 현업의 검수 승인으로 해석하지 않는다.\n\n- 개별 보고서 HTML·Markdown 각 22개. 통합·공통 보고서 HTML·Markdown 각 2개.\n- 7개 대분류, 요구사항 132개(기능 88·공통 비기능의 업무별 적용 44), 시험 설계 154개, 업무별 작업 88개.\n- 실제 기존 요구사항 ID 88개와 연결 확인. 요구→시험 ID의 누락·중복 없음.\n- 추가 업무 공수 531–874인일, 공통 구성 86–148인일, 합계 617–1,022인일의 산술 일치 확인. 모두 기획자 가정이며 확정 견적·통계 구간이 아님.\n- 24개 HTML의 한국어·제목·목차·표 구조 확인. 로컬 링크 685회·앵커 348회 검사에서 미해결 0개. 링크 횟수는 중복을 포함한다. 외부 URL의 현재 가용성을 모두 재점검한 것은 아님.\n- 24개 화면을 1440·768·390px에서 확인. 본문 가로 넘침 없음; 넓은 표는 내부 스크롤 및 안내 제공.\n- 검색, 대분류·기능군 필터, 빈 상태·초기화, 키보드 본문 이동, 목차 실제 도착, 모바일 표 내부 스크롤, 인쇄 시 탐색 숨김 확인.\n- 브라우저 실행 오류·HTML의 외부 네트워크 요청 관측 0개. 이는 보고서 파일의 관측 결과이며 NOA 제품의 데이터 주권 검증이 아님.\n\n## 2. 직접 화면 검토·수정 이력\n\n직접 확인한 대표 화면은 통합 데스크톱·모바일 검색·P10 요구사항·모바일 표·공통 예산 산식·모바일 목차 도착이다.\n\n1. 긴 페이지의 부드러운 목차 이동을 고정 500ms 뒤 검사해 도착 실패로 기록한 항목을 발견했다. 목표 위치 도착을 조건으로 기다리는 방식으로 재검증했다. 최종 모바일 도착 위치는 본문 상단 약 12px, 목차 해시는 일치했다.\n2. 직접 시각 검토에서 연속된 물결표 범위가 Markdown 취소선으로 해석되는 오류를 발견했다. 범위 표기를 en dash로 바꾸고 모든 HTML의 del/s 요소가 0개임을 구조 검증에 포함했다.\n3. 모바일 표의 좌우 이동 안내와 업무 내부 단계/프로그램 예산 차수의 구분을 보완했다. 전체 문서를 재생성하고 162개 검증을 다시 통과했다.\n4. 실제 이전 요구사항 ID가 F1–F4임을 확인해 초기 F01 형태 연결을 생성 단계에서 수정했다. 최종 88개 계보는 존재하는 ID와 일치한다.\n\n시각 품질은 문서용 정보계층·가독성·여백·반응형·초점 표시를 작성자가 확인했다. 정식 WCAG 2.2 AA 인증, 스크린리더 전수 시험, 인쇄물 전체 페이지의 수동 검수는 수행하지 않았다. 이미지 생성 자산은 사용하지 않았다.\n\n## 3. 방법론·품질 판정\n\n공공 AX+SI의 Stage-Gate·요구사항 추적·영향분석을 문서 작업에 적용했다. 요구·설계·작성·문서 검증·사용자 관점의 대표 화면 검토를 수행했다.\n\n- 산출물 QA 자체 판정: 문서 구조·연결·산술·대표 상호작용 통과.\n- 사업 적용 판정: 조건부 검토. 최종 계약·업무 수요·데이터·권한·NOA 사용권·성능·단가 확정 필요.\n- 독립 평가위원·실제 사용자 검수: 미실시.\n- 제품 구현·모델/API 시험·실증·운영 배포: 미실시. 시험 원장의 154개는 설계 사례이며 실행 0개.\n\n## 4. 보존·추적\n\n기존 v0.2와 회사 원본은 이번 작성 대상에서 제외하고 새 폴더에 결과를 생성했다. 루트 README는 기존 내용을 유지하면서 최신 고도화 행 1개를 추가했으며 변경 전 사본을 보존했다. 삭제·외부 전송·운영 배포를 수행하지 않았다.\n\n[자동검증 원장](검증/자동검증_결과.json) · [요구·시험 원장](03_요구사항_시험추적.json) · [공수 원장](04_작업분해_공수원장.json) · [변경파일 기록](변경파일_기록.json)\n\n다음 확인은 최종 계약·기존 기능표·사용권·현업 사례·상태/API·단가·가용인력이다. 고도화 범위와 견적을 업무별로 확정하고 실제 제품 시험으로 이어간다.\n`;
fs.writeFileSync(path.join(dir,'검증기록.md'),report,'utf8');
const qaFile=path.join(dir,'검증/자동검증_결과.json');qa.manual_visual_review={status:'작성자 대표 화면 직접 검토',files:['01_통합_데스크톱.png','02_검색_모바일.png','04_P10_요구사항.png','05_P10_모바일표.png','06_공통_예산산식.png','07_목차_모바일도착.png'],final_recheck:['05_P10_모바일표.png','07_목차_모바일도착.png'],not_performed:['독립 평가위원 승인','실제 사용자 조사','제품/모델/API 시험','정식 접근성 인증']};fs.writeFileSync(qaFile,JSON.stringify(qa,null,2));
function walk(p){return fs.readdirSync(p,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(p,e.name)):[path.join(p,e.name)])}
const files=walk(dir).filter(f=>path.basename(f)!=='변경파일_기록.json');const sha=f=>crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex');
fs.writeFileSync(path.join(dir,'변경파일_기록.json'),JSON.stringify({date:'2026-09-15',scope:'새 고도화 보고서 생성 및 루트 README 행 추가',created:files.map(f=>({path:path.relative(dir,f).replaceAll('\\','/'),bytes:fs.statSync(f).size,sha256:sha(f)})),modified:[{path:'README.md',before_backup:rel+'/기준_변경전/README.md',before_sha256:crypto.createHash('sha256').update(before).digest('hex'),after_sha256:sha(readme)}],deleted:[],product_deployed:false},null,2));
// 루트에 추가한 최신자료 링크와 모든 패키지 파일의 존재를 다시 확인한다.
const now=fs.readFileSync(readme,'utf8');const restored=now.replace(row+'\n','');if(restored!==before)throw Error('README 행 외 변경 발생');
for(const f of ['00_고도화보고서_통합보기.html','00_고도화보고서_통합보기.md','01_공통설계_추진계획_비용산정.html','검증기록.md'])if(!fs.existsSync(path.join(dir,f)))throw Error('최종 파일 누락');
console.log(JSON.stringify({completed:true,root_readme_added_rows:1,html:files.filter(f=>f.endsWith('.html')).length,individual_markdown:files.filter(f=>f.includes('개별보고서')&&f.endsWith('.md')).length,qa:qa.summary,entry:path.join(dir,'00_고도화보고서_통합보기.html')}));
