const fs=require('fs'),path=require('path'),{pathToFileURL}=require('url');
const {chromium}=require(require.resolve('playwright',{paths:['C:/Users/김희섭/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules']}));
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});const errors=[];page.on('pageerror',e=>errors.push(e.message));const checks=[];
 const assert=(x,message)=>{if(!x)throw new Error(message);checks.push(message)};
 await page.goto(pathToFileURL(path.join(__dirname,'기관법령_관계도.html')).href);await page.waitForFunction(()=>window.researchMap);
 assert(await page.locator('#focusTitle').textContent()==='한국교통안전공단','초기 TS 선택');
 assert(await page.locator('#chart .map-node').count()>5,'초기 관계도 노드 표시');
 assert((await page.locator('#chart').textContent()).includes('한국교통안전공단법'),'초기 관계도 설립법 표시');
 assert((await page.locator('#chart').textContent()).includes('국토교통부'),'초기 관계도 주무부처 표시');
 await page.locator('#edgeRows [data-evidence]').first().click();assert(await page.locator('#evidence').isVisible(),'관계 근거 열기');
 assert(await page.locator('#evidence a').count()>0,'근거에 공식 출처 링크');await page.locator('#closeEvidence').click();
 await page.locator('#search').fill('한국교통안전공단');assert(await page.locator('#results button').count()>0,'기관 검색');await page.locator('#search').fill('존재하지않는기관abcdefgh');assert(await page.locator('#results').textContent().then(t=>t.includes('없습니다')),'검색 결과 없는 상태');await page.locator('#search').fill('');
 await page.locator('[data-name="인공지능 및 데이터 기반 행정 활성화에 관한 법률"]').click();assert(await page.locator('#focusTitle').textContent()==='인공지능 및 데이터 기반 행정 활성화에 관한 법률','현행 공공 AI 법령 탐색');assert(await page.locator('#chart .map-node').count()>1,'공공 AI 법령 연결 표시');
 await page.locator('#back').click();assert(await page.locator('#focusTitle').textContent()==='한국교통안전공단','이전 선택 복귀');
 const countBefore=await page.locator('#edgeCount').textContent();await page.locator('#auto').check();assert(await page.locator('#edgeCount').textContent()!==countBefore,'자동 추출 관계 포함 상태 변경');await page.locator('#auto').uncheck();
 await page.locator('#level').selectOption('review');assert((await page.locator('#edgeRows .status').allTextContents()).every(x=>x==='조문검토'),'조문 검토 관계 필터');await page.locator('#level').selectOption('all');
 await page.locator('#search').fill('국가정보원');await page.locator('#results button').first().focus();await page.keyboard.press('Enter');assert(await page.locator('#focusTitle').textContent()==='국가정보원','키보드 기관 선택');await page.locator('[data-quick="A_C0019"]').click();await page.locator('#search').fill('');
 await page.screenshot({path:path.join(__dirname,'QA_데스크톱.png'),fullPage:true});
 await page.setViewportSize({width:390,height:844});await page.waitForTimeout(220);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'모바일 페이지 가로 넘침 없음');
 const overflow=await page.locator('.map-node').evaluateAll(es=>es.some(e=>e.getBoundingClientRect().right>innerWidth+1));assert(!overflow,'모바일 관계도 노드 경계');await page.screenshot({path:path.join(__dirname,'QA_모바일.png'),fullPage:true});
 await page.locator('#theme').click();await page.screenshot({path:path.join(__dirname,'QA_다크.png'),fullPage:true});
 assert(errors.length===0,'브라우저 JavaScript 오류 없음');fs.writeFileSync(path.join(__dirname,'뷰어_검증결과.json'),JSON.stringify({checked_at:'2026-09-09',checks,errors,browser:'Microsoft Edge · Playwright',viewports:['1440×1000','390×844'],limits:['스크린리더 실제 낭독 미검증','색 대비 자동 수치 검사 미실시','외부 출처 링크의 전수 재접속 미실시']},null,2));console.log(JSON.stringify({passed:checks.length,errors},null,2));await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
