(function(){'use strict';const C=window.TSCost,M=window.TS_MODEL,n=window.TS_SINGLE,fmt=x=>Math.round(x).toLocaleString('ko-KR')+'원',by=id=>document.getElementById(id),num=id=>Number(by(id).value),cell=(x)=>'<td>'+x+'</td>',row=(...xs)=>'<tr>'+xs.map(cell).join('')+'</tr>';
function show(){try{let cfg={scenario:by('scenario').value};for(const k of ['overhead','tech','vat','license','expenses','months','operatingFees'])cfg[k]=num(k);C.validate(cfg);let html='';
 if(n){let r=C.calc(M,[n],cfg);html='<p>포함 업무: '+r.included.map(v=>'P'+String(v).padStart(2,'0')).join(', ')+' / 공통 '+r.commonIds.join(', ')+'</p>'+(r.added.length?'<p class="note">선행 업무 '+r.added.map(v=>'P'+v).join(', ')+'를 자동 포함했습니다. 선행 기능이 이미 있다면 해당 증분은 제외하고 검토하세요.</p>':'')+'<div class="grid"><div>도입 소계 / VAT 포함<div class="stat">'+fmt(r.build.total)+'</div></div><div>업무 증분 / VAT 포함<div class="stat">'+fmt(C.charge(C.labor(M.plans.find(p=>p.n===n),cfg.scenario),cfg).total)+'</div></div><div>별도 운영 소계 / VAT 포함<div class="stat">'+fmt(r.operating.total)+'</div></div></div>'+detail(r.build)+'<p>총 '+r.days+'인일 / 운영 '+r.operatingDays+'인일 / 신규 인프라 0원</p>';window.TS_LAST=r;
 }else{let a=[],b=[];document.querySelectorAll('[data-phase]').forEach(s=>{if(s.value==='1')a.push(Number(s.dataset.phase));if(s.value==='2')b.push(Number(s.dataset.phase));});let r1=C.calc(M,a,cfg),all=C.calc(M,[...a,...b],cfg),adds=all.included.filter(v=>!r1.included.includes(v)),direct2=all.build.direct-r1.build.direct;let l2=num('license2'),e2=num('expenses2');if(!Number.isFinite(l2)||l2<0||!Number.isFinite(e2)||e2<0)throw Error('2차 금액은 0 이상의 숫자로 입력하세요.');let two=C.charge(direct2,cfg,adds.length?l2:0,adds.length?e2:0),total=r1.build.total+two.total;
 html='<p>1차 포함 '+(r1.included.map(v=>'P'+String(v).padStart(2,'0')).join(', ')||'없음')+'<br>2차 추가 '+(adds.map(v=>'P'+String(v).padStart(2,'0')).join(', ')||'없음')+'</p><p>선행 기능 자동 포함: '+([...new Set([...r1.added,...all.added])].map(v=>'P'+v).join(', ')||'없음')+' / P17→P01·P22→P21. 1차에 필요한 선행 기능은 2차 지정 여부와 무관하게 1차에 우선 포함.</p><div class="tablewrap"><table><thead><tr><th>구분</th><th>계산 소계 / VAT 포함</th><th>목표 상한</th><th>상한 대비</th></tr></thead><tbody>'+row('1차 구축',fmt(r1.build.total),'7억원',fmt(700000000-r1.build.total)+(r1.build.total>700000000?' 초과분 음수':' 잔여'))+row('2차 추가 구축',fmt(two.total),'5억원',fmt(500000000-two.total)+(two.total>500000000?' 초과분 음수':' 잔여'))+row('구축 합계',fmt(total),'12억원',fmt(1200000000-total))+row('전체 도입 후 별도 운영 '+cfg.months+'개월',fmt(all.operating.total),'계약 포함 여부 미정','공통 운영 1회')+row('구축+위 운영 합계',fmt(total+all.operating.total),'운영 포함 계약 시 검토',fmt(1200000000-total-all.operating.total))+'</tbody></table></div><p>선택 전체 '+all.days+'인일. 공통 모듈 '+(all.commonIds.join(', ')||'없음')+'를 각 최초 필요 단계에서 1회 산정.</p><h3>1차 세부 산식</h3>'+detail(r1.build)+'<h3>2차 추가 세부 산식</h3>'+detail(two);window.TS_LAST={stage1:r1,stage2:two,all,total,adds};
 }
 by('calc-error').textContent='';by('calc-output').innerHTML='<div class="summary">'+html+'</div>';
 }catch(e){by('calc-error').textContent=e.message;by('calc-output').innerHTML='';}}
function detail(r){return '<div class="tablewrap"><table><thead><tr><th>직접인건비</th><th>제경비</th><th>기술료</th><th>라이선스·직접경비</th><th>VAT</th><th>소계</th></tr></thead><tbody>'+row(fmt(r.direct),fmt(r.overhead),fmt(r.tech),fmt(r.license+r.expenses),fmt(r.vat),fmt(r.total))+'</tbody></table></div>';}
by('recalculate').addEventListener('click',show);document.querySelectorAll('#calculator input,#calculator select').forEach(x=>x.addEventListener('change',show));if(by('clear'))by('clear').addEventListener('click',()=>{document.querySelectorAll('[data-phase]').forEach(s=>s.value='0');show();});if(by('all1'))by('all1').addEventListener('click',()=>{document.querySelectorAll('[data-phase]').forEach(s=>s.value=s.dataset.phase==='23'?'0':'1');show();});show();})();
