const fs=require('fs'),path=require('path'),crypto=require('crypto');
const root='G:/내 드라이브/1. 업무영역/6. CCK/1. 사업관리/TS/bizops/[TS 사업기획]';
const rel='05_통합사업기획/P23_정책기획_예산요구_발주전환_v1.1_2026-09-15',dir=path.join(root,rel),target=path.join(dir,'00_기획_전체보기.html');
const old=path.join(root,'05_통합사업기획/TS_업무별_상세설계_산정_2026-09-15'),enh=path.join(root,'05_통합사업기획/TS_22개업무_고도화보고서_2026-09-15');
const hash=s=>crypto.createHash('sha256').update(s).digest('hex');const changed=[];
function mutate(file,fn){if(!fs.existsSync(file))throw Error('Missing '+file);const before=fs.readFileSync(file);const next=fn(before.toString('utf8'));if(next===before.toString('utf8'))return;const relpath=path.relative(root,file);const backup=path.join(dir,'기준_변경전',relpath);fs.mkdirSync(path.dirname(backup),{recursive:true});if(!fs.existsSync(backup))fs.writeFileSync(backup,before);fs.writeFileSync(file,next,'utf8');changed.push({path:file,backup,before_sha256:hash(before),after_sha256:hash(Buffer.from(next))});}
const forms=['F01_문제정의_정책사업_검토서','F02_예산요구_사업설명자료','F03_2027_신규사업_리스트','F04_발주기관_RFP_초안','F05_공고작성_인계서','F06_심의질의_답변보완표'];
const mdlinks='\n\n## 서식 바로가기\n\n'+forms.map(f=>'- ['+f.replace(/_/g,' ')+'](서식/'+f+'.html) · [Markdown](서식/'+f+'.md)').join('\n')+'\n';
const hlinks='<section aria-label="작성 서식"><h2>서식 바로가기</h2><ul>'+forms.map(f=>'<li><a href="서식/'+f+'.html">'+f.replace(/_/g,' ')+'</a> · <a href="서식/'+f+'.md">Markdown</a></li>').join('')+'</ul></section>';
for(const base of ['00_기획_전체보기','03_양식과_필드매핑']){const m=path.join(dir,base+'.md'),h=path.join(dir,base+'.html');fs.appendFileSync(m,mdlinks);fs.writeFileSync(h,fs.readFileSync(h,'utf8').replace('</main>',hlinks+'</main>'));}
const reuseMd='\n\n## 공공기관으로 재사용할 범위\n\n근거 카드·사업원장·예산 산식·검토 이력·양식 매핑은 공통 기능으로 구성하고, 기관 소관·예산 경로·문서 양식·전결권한·기존 시스템 연결은 기관별 설정으로 분리한다. TS에서 의제1개를 검증한 뒤 다른 부서·기관으로 확장할 수 있는 제품 구조를 제안한다. 타기관 연동·다기관 통합 운영까지 이번 비용에 포함한 것은 아니다.\n';
fs.appendFileSync(path.join(dir,'00_기획_전체보기.md'),reuseMd);fs.writeFileSync(path.join(dir,'00_기획_전체보기.html'),fs.readFileSync(path.join(dir,'00_기획_전체보기.html'),'utf8').replace('</main>','<h2>공공기관으로 재사용할 범위</h2><p>근거 카드·사업원장·예산 산식·검토 이력·양식 매핑은 공통 기능으로 구성하고, 기관 소관·예산 경로·문서 양식·전결권한·기존 시스템 연결은 기관별 설정으로 분리한다. TS의 의제1개를 검증한 뒤 다른 부서·기관으로 확장할 수 있는 제품 구조다. 타기관 연동·다기관 통합 운영은 이번 비용에 포함하지 않았다.</p></main>'));
const htmltargets=[path.join(enh,'00_고도화보고서_통합보기.html'),path.join(old,'00_상세설계_통합보기.html'),...fs.readdirSync(path.join(old,'추가후보/TS-P23')).filter(x=>x.endsWith('.html')).map(x=>path.join(old,'추가후보/TS-P23',x))];
for(const f of htmltargets){const link=path.relative(path.dirname(f),target).replace(/\\/g,'/');const text=f.includes('06_비용')?'기존 P23 소범위 산정입니다. 예산·양식·발주 전환 확장분은 별도 산정했습니다.':'P23 확장안: 부서별 문제정의 → 정책·사업 → 예산 요구 → RFP·공고 준비';const banner='<div data-p23x="1" style="padding:16px 22px;background:#e1f1ed;border-bottom:2px solid #0b756a;color:#163e43;font:15px/1.8 Malgun Gothic,sans-serif">'+text+' · <a style="color:#075d59;font-weight:bold" href="'+link+'">정책·예산·발주 기획지원 v1.1 보기</a></div>';mutate(f,s=>s.includes('data-p23x="1"')?s:s.replace(/(<body\b[^>]*>)/i,'$1'+banner));}
for(const f of [path.join(root,'README.md'),path.join(enh,'00_고도화보고서_통합보기.md'),path.join(old,'00_상세설계_통합보기.md')]){const link=path.relative(path.dirname(f),target).replace(/\\/g,'/');mutate(f,s=>s.includes('<!--P23X-LATEST-->')?s:s.replace(/^(# [^\r\n]+)\r?\n/,'$1\n\n<!--P23X-LATEST-->\n[추가 확장안: P23 정책·예산·발주 기획지원 v1.1]('+link+') — 근거·문제정의에서 예산 요구 및 RFP·공고 초안까지. 설명9페이지·서식6종·전환 시연.\n'));}
fs.writeFileSync(path.join(dir,'변경파일_기록.json'),JSON.stringify({date:'2026-09-15',existing_changed:changed,deletions:[],deployments:[],note:'기존 내용 보존·확장안 안내만 추가. 이전 패키지 검증 시점 이후의 안내 변경은 이 기록으로 관리한다.'},null,2));
fs.copyFileSync(__filename,path.join(dir,'작성자료/p23x_finish.cjs'));
console.log(JSON.stringify({existing_changed:changed.length,files:changed.map(c=>c.path)},null,2));
