const fs=require('fs'),path=require('path'),{pathToFileURL,fileURLToPath}=require('url'),assert=require('assert');
const {chromium}=require('C:/Users/김희섭/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const demo=require('./p23x_demo.js');
const root='G:/내 드라이브/1. 업무영역/6. CCK/1. 사업관리/TS/bizops/[TS 사업기획]';
const dir=path.join(root,'05_통합사업기획/P23_정책기획_예산요구_발주전환_v1.1_2026-09-15');
const qdir=path.join(dir,'검증');fs.mkdirSync(qdir,{recursive:true});
const checks=[],fail=[];function check(name,condition,detail=''){checks.push({name,pass:!!condition,detail});if(!condition)fail.push({name,detail});}
const files=[];function walk(p){for(const d of fs.readdirSync(p,{withFileTypes:true})){if(['검증','작성자료','기준_변경전'].includes(d.name))continue;const f=path.join(p,d.name);if(d.isDirectory())walk(f);else files.push(f);}}walk(dir);
const htmls=files.filter(f=>f.endsWith('.html'));check('HTML 15개',htmls.length===15);
for(const [a,b,want] of [['','100',null],['0','100',100000000],['30','70',40000000],['50','0',-50000000],['0.1','0.3',200000]]){const s=demo.evaluate({prior:a,request:b,year:2027,source:'active'});check('증감 '+a+'→'+b,s.difference_won===want);check('실제 승인 생성 금지 '+a+'→'+b,s.budget_approved_won===null&&s.consultation_result===null&&!s.official_submission);}
for(const bad of ['-1','NaN','Infinity','1000000001'])check('금액 오류 '+bad,demo.parseAmount(bad,'테스트').error);
let state=demo.evaluate({prior:'',request:'70',year:2028,source:'withdrawn'});for(const view of ['policy','budget','rfp','notice']){let s=demo.documentText(state,view);check('문서 간 값·상태 일관성 '+view,s.includes('70백만원')&&s.includes('양식 연도 불일치')&&s.includes('근거 철회')&&s.includes('RFP 재검토')&&s.includes('미확인'));}
check('빈 B와 확인된0 구분',demo.evaluate({request:'',year:2027}).requested_won===null&&demo.evaluate({request:'0',year:2027}).requested_won===0);
const cost=JSON.parse(fs.readFileSync(path.join(dir,'원장/비용산정.json'),'utf8'));
for(const sc of cost.scenarios){const ix=sc.scenario==='low'?2:3;let direct=0,days=0;for(const r of cost.wbs){const d=sc.scenario==='mid'?(r[2]+r[3])/2:r[ix];days+=d;const unit=Object.entries(r[4]).reduce((s,[k,w])=>s+cost.rates[k]*w,0);check('직무 가중치 합 '+sc.scenario+' '+r[0],Math.abs(Object.values(r[4]).reduce((a,b)=>a+b,0)-1)<1e-9);direct+=d*unit;}check('공수 합 '+sc.scenario,days===sc.extension_days);check('비용 산술 '+sc.scenario,Math.abs(direct*2.44*1.2*1.1-sc.extension.total)<0.01);check('기존+확장 금액 '+sc.scenario,Math.abs(sc.base_build+sc.extension.total-sc.standalone)<0.01);}
let linkCount=0;for(const f of htmls){const s=fs.readFileSync(f,'utf8');check('본문 제목 하나 '+path.basename(f),(s.match(/<h1[ >]/g)||[]).length===1);for(const m of s.matchAll(/(?:href|src)="([^"]+)"/g)){if(/^(https?:|mailto:|data:|blob:)/.test(m[1]))continue;const u=new URL(m[1],pathToFileURL(f));if(u.protocol==='file:'){linkCount++;check('로컬 연결 '+path.basename(f)+' '+m[1],fs.existsSync(fileURLToPath(u)));}}}
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage();const errors=[],external=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))external.push(r.url());});let viewportCount=0;
for(const f of htmls){for(const width of [1440,768,390]){await page.setViewportSize({width,height:1000});await page.goto(pathToFileURL(f).href);await page.evaluate(()=>document.fonts.ready);const result=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth+1,h1:document.querySelector('h1').textContent,images:[...document.images].every(x=>x.complete&&x.naturalWidth>0)}));check('반응형 '+path.basename(f)+' '+width,!result.overflow&&result.images,JSON.stringify(result));viewportCount++;}}
const graphs=JSON.parse(fs.readFileSync(path.join(dir,'원장/도식.json'),'utf8'));for(const g of graphs){await page.goto(pathToFileURL(path.join(dir,'자산',g.id.replace('P23X-','')+'.svg')).href);const bad=await page.evaluate(()=>[...document.querySelectorAll('[data-node]')].flatMap(n=>{const r=n.querySelector('rect').getBBox();return [...n.querySelectorAll('text')].flatMap(t=>{const b=t.getBBox();return b.x<r.x+5||b.x+b.width>r.x+r.width-5||b.y<r.y||b.y+b.height>r.y+r.height-5?[{node:n.getAttribute('data-node'),text:t.textContent,b:{x:b.x,y:b.y,w:b.width,h:b.height}}]:[];});}));check('SVG 글자 경계 '+g.id,bad.length===0,JSON.stringify(bad));}
const demoUrl=pathToFileURL(path.join(dir,'08_문서전환_시연.html')).href;await page.setViewportSize({width:1440,height:1100});await page.goto(demoUrl);await page.locator('#prior').fill('30');await page.locator('#request').fill('70');await page.locator('#year').selectOption('2028');await page.locator('#source').selectOption('withdrawn');for(const v of ['policy','budget','rfp','notice']){await page.locator('[data-view="'+v+'"]').click();const content=await page.locator('#preview').innerText();check('브라우저 문서전환 '+v,content.includes('40백만원')&&content.includes('70백만원')&&content.includes('근거 철회')&&content.includes('양식 연도 불일치'));}
await page.locator('#request').fill('-1');check('오류 다운로드 차단',await page.locator('#downloadMd').isDisabled()&&await page.locator('#downloadJson').isDisabled());await page.locator('#request').fill('70');await page.locator('[data-view="budget"]').click();
const dlPromise=page.waitForEvent('download');await page.locator('#downloadJson').click();const dl=await dlPromise;const dlfile=path.join(qdir,'가상시연_원장_다운로드검증.json');await dl.saveAs(dlfile);const downloaded=JSON.parse(fs.readFileSync(dlfile,'utf8'));check('원장 다운로드 내용',downloaded.requested_won===70000000&&downloaded.prior_won===30000000&&downloaded.budget_approved_won===null&&downloaded.synthetic&&!downloaded.official_submission);
await page.screenshot({path:path.join(qdir,'시연_변경영향_데스크톱.png'),fullPage:true});
await page.goto(pathToFileURL(path.join(dir,'00_기획_전체보기.html')).href);await page.keyboard.press('Tab');check('본문 이동 키보드 포커스',await page.evaluate(()=>document.activeElement.classList.contains('skip')));await page.keyboard.press('Enter');check('본문 이동 실행',await page.evaluate(()=>document.activeElement.id==='main'));await page.screenshot({path:path.join(qdir,'전체보기_데스크톱.png'),fullPage:true});await page.setViewportSize({width:390,height:844});await page.goto(demoUrl);await page.screenshot({path:path.join(qdir,'시연_모바일.png'),fullPage:true});await page.goto(pathToFileURL(path.join(dir,'서식/F03_2027_신규사업_리스트.html')).href);await page.setViewportSize({width:1440,height:1100});await page.screenshot({path:path.join(qdir,'공식필드_초안.png'),fullPage:true});
check('브라우저 JS 오류',errors.length===0,JSON.stringify(errors));check('오프라인 외부 요청 없음',external.length===0,JSON.stringify(external));await browser.close();
const report={date:'2026-09-15',html_pages:htmls.length,local_references:linkCount,viewports:viewportCount,svg:graphs.length,svg_nodes:graphs.reduce((a,g)=>a+g.nodes.length,0),checks:checks.length,failures:fail,results:checks,product_acceptance_tests_run:0,limitations:['실제 NOA·로컬 LLM·TS 데이터·HWPX 출력 미검증','전체 WCAG·스크린리더 검증 미수행','독립 외부 평가·실제 사용자 조사 미수행']};fs.writeFileSync(path.join(qdir,'자동검증_결과.json'),JSON.stringify(report,null,2));fs.copyFileSync(__filename,path.join(dir,'작성자료/p23x_qa.cjs'));console.log(JSON.stringify({...report,results:undefined},null,2));if(fail.length)process.exitCode=1;
})();
