const fs = require('fs');
const path = require('path');
const {marked} = require('C:/Users/김희섭/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/marked');
const base=__dirname;
const source=JSON.parse(fs.readFileSync(path.join(base,'근거원장.json'),'utf8')).sources;
let body=fs.readFileSync(path.join(base,'본문.md'),'utf8');
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
let seen={};
body=body.replace(/\[\^(\d+)\]/g,(_,n)=>{
 const s=source.find(s=>s.number==n); if(!s) throw new Error('Missing source '+n);
 seen[n]=(seen[n]||0)+1;
 return `<sup><a class="cite" id="cite-${n}-${seen[n]}" href="#source-${n}" aria-label="출처 ${n}: ${esc(s.title)}" title="${esc(s.publisher+' · '+s.title)}">[${n}]</a></sup>`;
});
let article=marked.parse(body,{gfm:true,breaks:false});
let toc=[],i=0;
article=article.replace(/<h2>(.*?)<\/h2>/g,(_,title)=>{
 const id='section-'+(++i);toc.push({id,title});return `<h2 id="${id}" tabindex="-1">${title}</h2>`;
});
article=article.replaceAll('<table>','<div class="table-scroll" role="region" tabindex="0" aria-label="가로로 스크롤할 수 있는 비교표"><table>').replaceAll('</table>','</table></div>');
article+=`<h2 id="sources" tabindex="-1">출처</h2><p>공식 자료의 표시 시점과 열람일은 구분합니다. 별도 표시가 없는 자료의 열람일은 2026-09-11입니다. 내부 문서는 범위·경험·가정을 확인하는 자료이며 외부 사실의 독립 검증을 대신하지 않습니다.</p><ol class="sources">`;
for(const s of source) article+=`<li id="source-${s.number}"><a href="${esc(s.url)}">${esc(s.title)}</a><p>${esc(s.publisher)} · ${esc(s.publication_or_effective_date)}.</p><p>${esc(s.verified_scope)}. <a class="back" href="#cite-${s.number}-1" aria-label="출처 ${s.number}의 본문 인용으로">본문 인용으로</a></p></li>`;
article+='</ol>';
const html=`<!doctype html>
<html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light"><title>한국교통안전공단 심층조사</title>
<style>
*{box-sizing:border-box}html{scroll-behavior:smooth;scroll-padding-top:28px}body{margin:0;background:#fff;color:#1a1a1a;font-family:'Malgun Gothic','Apple SD Gothic Neo',sans-serif;font-size:16px;line-height:1.95;word-break:keep-all;overflow-wrap:anywhere}a{color:#252525;text-decoration:underline;text-underline-offset:3px}a:hover{color:#666}a:focus-visible,button:focus-visible,summary:focus-visible,[tabindex="0"]:focus-visible{outline:3px solid #333;outline-offset:4px}h1,h2,h3{line-height:1.45;letter-spacing:-.035em;word-break:keep-all}h1{font-size:40px;font-weight:750;margin:0 0 36px;padding-bottom:30px;border-bottom:2px solid #222}h2{font-size:26px;margin:66px 0 25px;padding-top:24px;border-top:1px solid #bcbcbc}h3{font-size:20px;margin:37px 0 17px}p{margin:0 0 22px}strong{font-weight:750}.layout{display:grid;grid-template-columns:230px minmax(0,920px);gap:58px;max-width:1300px;margin:auto;padding:58px 36px 90px}.sidebar{position:sticky;top:25px;align-self:start;font-size:13px;line-height:1.65;max-height:calc(100vh - 50px);overflow:auto;padding:0 12px 10px 0}.sidebar summary{font-weight:bold;font-size:15px;cursor:pointer;padding:5px 0 16px}.sidebar ol{list-style:none;padding:0;margin:0}.sidebar li{margin:0 0 11px}.sidebar li a{display:block;text-decoration:none;padding:3px 0}.sidebar li a:hover{text-decoration:underline}.sidebar .actions{margin-top:22px;padding-top:20px;border-top:1px solid #ccc;display:flex;flex-wrap:wrap;gap:12px}.actions button,.actions a{background:#fff;color:#222;border:1px solid #888;padding:7px 11px;font:inherit;line-height:1.5;text-decoration:none;cursor:pointer;min-height:38px}.main{min-width:0}.cite{font-size:11px;line-height:1;white-space:nowrap;color:#555;text-decoration:none;padding:0 1px}sup{line-height:0}.table-scroll{overflow-x:auto;margin:25px 0 30px;padding-bottom:3px}table{width:100%;border-collapse:collapse;font-size:13px;line-height:1.8;min-width:640px}th,td{text-align:left;vertical-align:top;padding:12px 11px;border-bottom:1px solid #d0d0d0}th{background:#f2f2f2;border-top:1px solid #888;border-bottom:1px solid #888;font-weight:700}tr{break-inside:avoid}.sources{padding-left:24px;font-size:13px;line-height:1.8}.sources li{margin:0 0 23px;padding-left:5px}.sources p{margin:5px 0}.sources li:target{background:#f2f2f2;outline:2px solid #777;outline-offset:6px}.back{font-size:12px;color:#555}.skip{position:absolute;left:12px;top:-70px;background:white;padding:10px;z-index:5}.skip:focus{top:10px}li{margin-bottom:12px}code{font-size:.92em}.meta{font-size:12px;color:#555;margin-top:18px}
@media(max-width:1000px){.layout{grid-template-columns:190px minmax(0,1fr);gap:30px;padding:38px 25px}.sidebar{font-size:12px}h1{font-size:34px}}
@media(max-width:720px){body{font-size:16px;line-height:1.9}.layout{display:block;padding:25px 22px 55px}.sidebar{position:static;max-height:none;padding:0 0 22px;margin-bottom:25px;border-bottom:1px solid #bbb;font-size:14px}.sidebar summary{padding-bottom:10px}.sidebar .actions{margin-top:12px;padding-top:12px}.sidebar ol{columns:1}.meta{margin-top:12px}h1{font-size:30px;margin-bottom:26px;padding-bottom:24px}h2{font-size:23px;margin-top:47px}h3{font-size:19px}table{min-width:700px}.sources{padding-left:21px}.table-scroll:before{content:'표는 좌우로 스크롤하여 확인할 수 있습니다.';display:block;position:sticky;left:0;color:#555;font-size:12px;margin-bottom:8px}}
@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}}
@media print{@page{size:A4;margin:18mm 16mm}body{font-size:10pt;line-height:1.7}.layout{display:block;padding:0;max-width:none}.sidebar,.skip,.back{display:none}h1{font-size:24pt;margin-bottom:20px}h2{font-size:16pt;margin-top:28px;padding-top:14px;break-after:avoid}h3{font-size:12pt;break-after:avoid}p{margin-bottom:12px;orphans:3;widows:3}.table-scroll{overflow:visible;margin:16px 0}table{min-width:0!important;font-size:8pt;line-height:1.55}th,td{padding:6px}thead{display:table-header-group}.sources{font-size:8pt}.sources li{break-inside:avoid}a{text-decoration:none}.cite{font-size:7pt}.table-scroll:before{display:none}}
</style></head><body><a class="skip" href="#main">본문 바로가기</a><div class="layout"><aside class="sidebar"><nav aria-label="보고서 목차"><details open><summary>목차</summary><ol>${toc.map(t=>`<li><a href="#${t.id}">${t.title}</a></li>`).join('')}<li><a href="#sources">출처 41개</a></li></ol></details></nav><div class="actions"><a href="한국교통안전공단_심층조사.md" download>Markdown</a><button type="button" id="print">인쇄</button></div><p class="meta">기관 조사 · 사업화 검토용<br>제품 실증·발주 확정 전</p></aside><main id="main" class="main" tabindex="-1">${article}</main></div><script>document.getElementById('print').addEventListener('click',()=>window.print());if(window.matchMedia('(max-width:720px)').matches)document.querySelector('details').open=false;</script></body></html>`;
fs.writeFileSync(path.join(base,'한국교통안전공단_심층조사.html'),html,'utf8');
console.log(JSON.stringify({sections:toc.length,sources:source.length,characters:body.length,bytes:Buffer.byteLength(html)},null,2));
