const assert=require('node:assert/strict'),fs=require('node:fs'),doc=require('../src/document-data.cjs'),guide=require('../src/institution-guide.cjs'),nav=require('../src/reading-navigation.cjs'),registry=require('../src/navigation.cjs'),{departments,legal}=require('../src/data.json');
let checks=0;function check(v,m){assert(v,m);checks++}
const intro=doc.getDocument('about.html');check(guide.chapters.map(s=>s.id).join(',')==='purpose,mandate,strategy,organization,benefit','정의부터 제안까지 순서');check(intro.sections.length===5,'기관 소개 5개 장');check(intro.sections[0].paragraphs.join(' ').includes('위탁집행형 준정부기관'),'기관 정의');check(intro.sections.every(s=>s.paragraphs.length>=2&&s.links.length>=2),'연결된 설명과 근거');check(registry.locate('index.html').id==='home','홈 위치');check(registry.locate('index.html?view=map').id==='map','조직지도 분리');check(registry.locate('index.html?node=MR').id==='map','기존 조직 주소');check(nav.sections[3].children.every(s=>!s.children),'처별 중복 하위메뉴 제거');
for(const d of departments){const p=d.folder+'/01_사업정의.html',v=doc.getDocument(p);check(v.chapters.length===6,'큰 장 6개 '+d.code);check(v.sections.length===24,'원문 조각 통합 44→24 '+d.code);check(v.chapters.flatMap(c=>c.sections).length===v.sections.length,'본문 누락 없음 '+d.code);check(new Set(v.chapters.flatMap(c=>c.sections.map(s=>s.id))).size===v.sections.length,'본문 중복 배치 없음 '+d.code);check(v.sections.filter(s=>/-method-/.test(s.id)).length===0,'지표별 측정 조각 통합 '+d.code);
for(const c of nav.contextLinks(p).links){check(!!doc.targetFromRoute(c.to,v),'장 앵커 이동 '+c.to);}
for(const old of ['purpose','mandate','why',d.code+'-E01-method-4'])check(!!doc.targetFromRoute(p+'?slide='+old,v),'기존 별칭 '+old);
check(v.sections.filter(s=>s.diagram).length===5,'5종 도식 보존 '+d.code);}
for(const p of ['legal.html','solutions.html']){const v=doc.getDocument(p);assert.deepEqual(v.chapters.flatMap(c=>c.sections.map(s=>s.id)).sort(),v.sections.map(s=>s.id).sort());checks++;}
const l=doc.getDocument('legal.html');for(const g of l.chapters.filter(g=>g.id.startsWith('chapter-law-')&&g.id!=='chapter-law-overview')){check(g.sections.every(s=>legal.rows.find(r=>r.id===s.id)?.group===g.id.replace('chapter-law-','')),'법령 분야의 의미 보존');}
check(!fs.readFileSync('src/reading-structure.cjs','utf8').includes('Math.ceil'),'개수 기반 자동 분할 금지');
console.log(JSON.stringify({result:'통과',checks,introduction_chapters:5,proposal_chapters:6,sections_per_proposal:24,registry:registry.records.length}));
