const fs=require('fs'),path=require('path'),{pathToFileURL}=require('url'),assert=require('assert');
const {chromium}=require('C:/Users/김희섭/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root='G:/내 드라이브/1. 업무영역/6. CCK/1. 사업관리/TS/bizops/[TS 사업기획]/05_통합사업기획/TS_업무별_상세설계_산정_2026-09-15';
const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(d,e.name)):[path.join(d,e.name)]);
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1100}});let failures=[],nodeCount=0;const svgs=walk(root).filter(f=>f.endsWith('.svg'));
 for(const f of svgs){await page.goto(pathToFileURL(f).href);await page.evaluate(()=>document.fonts.ready);let r=await page.evaluate(()=>{let failures=[],n=0;document.querySelectorAll('g[data-node]').forEach(g=>{n++;const rect=g.querySelector('rect').getBBox();g.querySelectorAll('text').forEach(t=>{let b=t.getBBox();if(b.x<rect.x+3||b.y<rect.y+3||b.x+b.width>rect.x+rect.width-3||b.y+b.height>rect.y+rect.height-3)failures.push({node:g.dataset.node,text:t.textContent,b:{x:b.x,y:b.y,w:b.width,h:b.height},rect:{x:rect.x,y:rect.y,w:rect.width,h:rect.height}});});});return {n,failures};});nodeCount+=r.n;if(r.failures.length)failures.push({file:path.relative(root,f),issues:r.failures});}
 await page.goto(pathToFileURL(path.join(root,'00_상세설계_통합보기.html')).href);await page.keyboard.press('Tab');const firstFocus=await page.evaluate(()=>document.activeElement.textContent);assert.equal(firstFocus,'본문으로 이동');await page.keyboard.press('Enter');assert(page.url().endsWith('#main'));
 const dest='C:/Users/Public/Documents/ESTsoft/CreatorTemp/ts_pages_visual';await page.goto(pathToFileURL(path.join(root,'추가후보/TS-P23/06_비용_산정.html')).href);await page.locator('#calc-output').screenshot({path:path.join(dest,'p23-cost-results.png')});await page.setViewportSize({width:390,height:1000});await page.locator('#calc-output').screenshot({path:path.join(dest,'p23-cost-results-mobile.png')});
 const r={date:'2026-09-15',svg:svgs.length,nodeCount,failures,keyboard:'목록 화면 Tab→본문 이동 확인',actual_screenreader:'미실행',status:failures.length?'보완 필요':'도식 경계·키보드 확인 통과'};fs.writeFileSync(path.join(root,'검증/도식_경계_키보드_결과.json'),JSON.stringify(r,null,2));console.log(JSON.stringify(r,null,2));await browser.close();if(failures.length)process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1;});
