const fs=require('fs'),path=require('path'),crypto=require('crypto'),assert=require('assert'),{pathToFileURL,fileURLToPath}=require('url');
const root='G:/내 드라이브/1. 업무영역/6. CCK/1. 사업관리/TS/bizops/[TS 사업기획]',sub='05_통합사업기획/TS_업무별_상세설계_산정_2026-09-15',out=path.join(root,sub),old=path.join(root,'05_통합사업기획/TS_22개업무_고도화보고서_2026-09-15'),tmp='C:/Users/Public/Documents/ESTsoft/CreatorTemp';
const q=JSON.parse(fs.readFileSync(path.join(out,'검증/자동검증_결과.json'),'utf8')),v=JSON.parse(fs.readFileSync(path.join(out,'검증/도식_경계_키보드_결과.json'),'utf8'));assert.equal(q.errors.length,0);assert.equal(v.failures.length,0);
const marker='TS 업무별 상세설계·정책기획 후보 v1.0';const changed=[];
function edit(file,transform){let oldText=fs.readFileSync(file,'utf8'),newText=transform(oldText);if(newText===oldText)return;let rel=path.relative(root,file),backup=path.join(out,'기준_변경전',rel);fs.mkdirSync(path.dirname(backup),{recursive:true});if(!fs.existsSync(backup))fs.writeFileSync(backup,oldText);fs.writeFileSync(file,newText);changed.push({path:rel,before_sha256:crypto.createHash('sha256').update(oldText).digest('hex'),after_sha256:crypto.createHash('sha256').update(newText).digest('hex'),backup:path.relative(out,backup)});}
edit(path.join(root,'README.md'),s=>{if(s.includes(marker))return s;return s.replace('|---|---|---|','|---|---|---|\n| '+marker+' | [161개 주제 통합보기]('+sub+'/00_상세설계_통합보기.html) · [P23 정책기획 로직]('+sub+'/추가후보/TS-P23/01_서비스_컨셉.html) · [업무 선택·비용 계산]('+sub+'/02_통합_비용산정.html) · [MD]('+sub+'/00_상세설계_통합보기.md) | 기존 22개 × 7개 주제 + 추가 P23 × 7개. 컨셉·아키텍처·사용자/데이터 흐름·요구·산정·일정, SVG 93개. 공식 2026 임금 기반 가정 산정, 공통·선행 기능 중복 제거. 실제 제품·견적·효과 검증 전 |');});
const rel='../TS_업무별_상세설계_산정_2026-09-15/';
edit(path.join(old,'00_고도화보고서_통합보기.html'),s=>s.includes('id="latest-detail-pages"')?s:s.replace('<main id="main" tabindex="-1">','<main id="main" tabindex="-1"><section id="latest-detail-pages" style="background:#eaf5f2;border-left:4px solid #087f72;padding:16px 20px;margin-bottom:24px"><strong>상세 페이지·금액 산정·정책기획 후보 추가</strong><p>기존 22개 업무를 주제별 154페이지로 구체화하고, P23 정책기획 에이전트 7페이지를 별도 추가했습니다.</p><p><a href="'+rel+'00_상세설계_통합보기.html">최신 상세설계 통합보기 →</a> · <a href="'+rel+'추가후보/TS-P23/01_서비스_컨셉.html">P23 정책기획 로직</a> · <a href="'+rel+'02_통합_비용산정.html">단계별 비용 계산</a></p></section>'));
edit(path.join(old,'00_고도화보고서_통합보기.md'),s=>s.includes('상세 페이지·금액 산정·정책기획 후보 추가')?s:s.replace(/^(# .*?\r?\n)/,'$1\n> 상세 페이지·금액 산정·정책기획 후보 추가: [최신 상세설계 통합보기]('+rel+'00_상세설계_통합보기.html) · [P23 정책기획 로직]('+rel+'추가후보/TS-P23/01_서비스_컨셉.html) · [단계별 비용 계산]('+rel+'02_통합_비용산정.html)\n'));
let record=`# 문서·계산·화면 검증 기록\n\n- 일자: 2026-09-15\n- 대상: 기존 22개 상세 주제 154개 + P23 후보 주제 7개 + 공통 4개 = HTML 165개; 같은 주제의 Markdown 병행\n- 실제 NOA·LLM·원 시스템 제품 시험: **0회·미실행**\n\n## 방법과 결과\n\n1. 요구·원장·공수 승계, 손계산 벡터, 공통·선행 기능·중복 선택·빈 선택·음수·VAT·운영 산정, 도식 연결, HTML 구조·내부 링크 및 브라우저 상호작용: **${q.checks.length}개 검사 통과**.\n2. 로컬 링크·이미지·자산 참조 ${q.stats.links}건 확인.\n3. 165페이지 × 1440/768/390px = **495회 화면 검사**. 페이지 가로 넘침·깨진 이미지·중복 주 제목·계산 오류 0건. 표·도식 내부 가로 이동은 의도된 구성.\n4. SVG **${v.svg}개·${v.nodeCount}개 노드**의 연결·경계와 실제 렌더링 글자 경계 확인. 상자 밖 글자 0건.\n5. 실제 브라우저에서 검색(정책→P23), 단계 선택, P17→P01·P22→P21 선행 포함, 2차 신규 공통만 계상, 음수 거부, 도식 확대·복귀, 인쇄 도식 너비, 키보드 본문 이동 확인.\n6. 대표 컨셉·보호 데이터 아키텍처·연계 사용자 흐름·P23 데이터/컨셉·모바일 비용·목록·산정 결과 이미지를 직접 검토. 단어 줄바꿈·하단 여백 보정 후 재검증.\n\n## 내용 검토\n\n- TS와 KoROAD 구분, P23 추가 후보와 조사된 기존 22개 분류 구분.\n- 기존 시스템·기존 AI도 실제 추가 수행분을 고도화 대상으로 포함. 동일 납품·공통 기능은 중복 계상하지 않음.\n- NOA·로컬 LLM·기존 서버·신규 인프라 0원, 비전/OCR/음성/센서/물리제어 제외.\n- P23은 주장·근거·원인 가설·반대 근거·TS 소관·기존사업·대안·사람 검토를 연결. 뉴스·민원 수를 위험률·원인으로 단정하지 않음.\n- 임금·가이드와 가정 공수·직무 비중·선택 요율·미확인 라이선스를 구분.\n\n## 시각 자체 평가\n\n| 항목 | 점수 / 5 | 근거·한계 |\n| --- | --- | --- |\n| 목적 적합성 | 5 | 요청한 주제·금액·4종 도식 분리 |\n| 정보계층 | 4 | 번호별 탐색·상태·주제 구분 |\n| 색상·서식 일관성 | 4 | 기존/추가/승인/자료 색상 통일 |\n| 구도·여백 | 4 | 경계 검사·대표 이미지 검토 후 수정 |\n| 반응형 | 4 | 495회 검사, 큰 표·도식 내부 가로 이동 |\n| 접근성 | 4 | 레이블·대체텍스트·포커스·본문 이동 확인; 스크린리더 미실행 |\n| 원자료 보존 | 5 | 이전 보고서 보존, 새 도식과 원장 추적 |\n| 도식 오류·왜곡 | 4 | 93개 SVG·860노드 경계 통과, 대표 시각 검토 |\n\n합계 **34/40**. 자체 검토이며 독립 전문가·실사용자 평가를 대체하지 않는다.\n\n## 판정·남은 확인\n\n**문서 검토본: 조건부 합격(자체 검토)**. 요청한 주제·도식·산정·탐색 산출물은 작성·검증했다. 실제 사업·운영 배포·현업 인수 승인은 아니다. 독립 평가위원 판정은 미실행이다.\n\n자료 권한·뉴스 이용범위·기존 API·NOA 사용권·기존 자원 성능·실수요·공급사 견적·현업 검수·스크린리더 수동 검증은 남아 있다. 이 조건은 파일 열람을 막는 결함이 아니라 실제 서비스 계약·구현 전 확인 대상이다.\n\n## 변경·복귀\n\n새 상세 자료 폴더 생성과 루트 README·기존 통합보기 링크 추가만 수행했다. 삭제·외부 발송·운영 시스템 배포 없음. 변경 전 안내 파일은 기준_변경전에서 복원 가능하다.\n\n[자동검증 결과](검증/자동검증_결과.json) · [도식·키보드 결과](검증/도식_경계_키보드_결과.json)\n`;
fs.writeFileSync(path.join(out,'검증기록.md'),record);
const shots=path.join(tmp,'ts_pages_visual');for(const f of fs.readdirSync(shots))fs.copyFileSync(path.join(shots,f),path.join(out,'검증',f));
for(const f of ['ts_pages_qa.cjs','ts_pages_visual_qa.cjs','ts_pages_polish.cjs','ts_pages_fix.cjs','ts_pages_finish.cjs'])fs.copyFileSync(path.join(tmp,f),path.join(out,'작성자료',f));
const linkChecks=[];for(const f of [path.join(old,'00_고도화보고서_통합보기.html'),path.join(out,'00_상세설계_통합보기.html')]){const text=fs.readFileSync(f,'utf8');for(const m of text.matchAll(/href="([^\"]+)"/g)){if(/^(https?:|#)/.test(m[1]))continue;let u=new URL(m[1],pathToFileURL(f));if(u.protocol==='file:'){assert(fs.existsSync(fileURLToPath(u)),m[1]);linkChecks.push(m[1]);}}}
fs.writeFileSync(path.join(out,'검증/최신_안내_연결검증.json'),JSON.stringify({date:'2026-09-15',count:linkChecks.length,status:'통과',changed},null,2));
const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(d,e.name)):[path.join(d,e.name)]);const all=walk(out).filter(f=>!f.endsWith('변경파일_기록.json'));fs.writeFileSync(path.join(out,'변경파일_기록.json'),JSON.stringify({date:'2026-09-15',changed_existing:changed,created_package:all.map(f=>({path:path.relative(out,f),bytes:fs.statSync(f).size,sha256:crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex')})),delete_count:0,operational_deployment:false},null,2));
console.log(JSON.stringify({root:out,checks:q.checks.length,viewports:q.stats.viewports,svg:v.svg,nodeCount:v.nodeCount,latestLinks:linkChecks.length,changed:changed.map(c=>c.path),packageFiles:all.length+1},null,2));
