'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert'),{pathToFileURL,fileURLToPath}=require('url');
const {chromium}=require('C:/Users/김희섭/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root='G:/내 드라이브/1. 업무영역/6. CCK/1. 사업관리/TS/bizops/[TS 사업기획]/05_통합사업기획/TS_업무별_상세설계_산정_2026-09-15';
const C=require(path.join(root,'자산/cost.js')),M=JSON.parse(fs.readFileSync(path.join(root,'04_설계_산정원장.json'),'utf8')),graphs=JSON.parse(fs.readFileSync(path.join(root,'05_도식_연결원장.json'),'utf8'));
let checks=[],errors=[],stats={pages:0,links:0,viewports:0};function test(name,fn){try{fn();checks.push({name,pass:true});}catch(e){checks.push({name,pass:false,message:e.message});errors.push(name+': '+e.message);}}
const approx=(a,b)=>assert(Math.abs(a-b)<.001,`${a} != ${b}`),walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(d,e.name)):[path.join(d,e.name)]);
const pages=walk(root).filter(f=>f.endsWith('.html')&&!f.includes('기준_변경전'));test('HTML 165개·개별 161개',()=>assert.equal(pages.length,165));test('SVG 93개',()=>assert.equal(graphs.length,93));
test('공식 단가 기반 손계산 표준 벡터',()=>{let r=C.charge(1000000,C.defaults,100000,50000);approx(r.overhead,1440000);approx(r.tech,488000);approx(r.net,3078000);approx(r.vat,307800);approx(r.total,3385800);});
test('공수 범위 617–1022 및 원장 22개 보존',()=>{let ns=M.plans.filter(p=>p.n!==23).map(p=>p.n);approx(C.calc(M,ns,{scenario:'low'}).days,617);approx(C.calc(M,ns,{scenario:'high'}).days,1022);});
test('P17 독립 도입은 P01 선행 포함·공통 1회',()=>{let a=C.calc(M,[17]),b=C.calc(M,[1,17]);assert.deepEqual(a.included,[1,17]);approx(a.build.total,b.build.total);assert.equal(a.commonIds.filter(x=>x==='C01').length,1);});
test('P22 독립 도입은 P21 선행 포함',()=>assert.deepEqual(C.calc(M,[22]).included,[21,22]));
test('P23 추가 시 공통 C00 중복 없음',()=>{let a=C.calc(M,[1]),b=C.calc(M,[1,23]);assert.equal(b.commonIds.filter(x=>x==='C00').length,1);approx(b.days-a.days,61);});
test('동일 업무 중복 선택 공수 불변',()=>approx(C.calc(M,[10,10]).days,C.calc(M,[10]).days));
test('빈 선택은 비용·공통·운영 0',()=>{let r=C.calc(M,[],{license:100,expenses:200,operatingFees:300});approx(r.build.total,0);approx(r.operating.total,0);assert.equal(r.commonIds.length,0);});
test('음수·NaN 입력 거부',()=>{assert.throws(()=>C.calc(M,[1],{license:-1}));assert.throws(()=>C.calc(M,[1],{months:NaN}));});
test('선택한 비용 항목 VAT 가산',()=>approx(C.calc(M,[1],{license:100000}).build.total-C.calc(M,[1]).build.total,110000));
test('운영 12개월 손계산·공통 1회',()=>{let r=C.calc(M,[15,20],{months:12});approx(r.operatingDays,48);approx(r.operating.direct,48*(519469*.7+378250*.3));});
test('신규 인프라 항상 0',()=>M.plans.forEach(p=>assert.equal(C.calc(M,[p.n]).infrastructure,0)));
test('138개 요구·161개 설계 시험·제품 시험 미실행',()=>{let q=JSON.parse(fs.readFileSync(path.join(root,'06_요구사항_시험추적.json'),'utf8'));assert.equal(q.requirements.length,138);assert.equal(new Set(q.requirements.map(r=>r.id)).size,138);assert.equal(q.actual_product_tests,0);assert.equal(q.requirements.length+q.comparison_tests.length,161);});
for(const g of graphs)test(g.id+' 도식 연결·노드·경계',()=>{const ns=new Set(g.nodes.map(n=>n.id));assert.equal(ns.size,g.nodes.length);g.nodes.forEach(n=>{assert(n.x>=0&&n.y>=0&&n.x+n.w<=g.width&&n.y+n.h<=g.height);});g.edges.forEach(e=>assert(ns.has(e.from)&&ns.has(e.to)));});
for(const f of pages){stats.pages++;const text=fs.readFileSync(f,'utf8');test(path.relative(root,f)+' 정적 무결성',()=>{assert(/<html lang="ko">/.test(text));assert(!/<(?:del|s)>/.test(text),'취소선 범위 파싱');assert(!/(?:src|href)="https?:[^\"]+"[^>]*>\s*<\/script>/.test(text),'외부 스크립트');assert.equal((text.match(/<h1[ >]/g)||[]).length,1,'주 제목 중복');assert(!/undefined|NaN/.test(text),'미정 변수 문자열');for(const m of text.matchAll(/(?:href|src)="([^\"]+)"/g)){const s=m[1];if(/^(https?:|data:|mailto:)/.test(s))continue;const u=new URL(s,pathToFileURL(f));if(u.protocol!=='file:')continue;stats.links++;const target=fileURLToPath(u);assert(fs.existsSync(target),'깨진 경로 '+s);if(u.hash&&target.endsWith('.html'))assert(new RegExp('id=["\']'+u.hash.slice(1)+'["\']').test(fs.readFileSync(target,'utf8')),'깨진 앵커 '+s);}});}
(async()=>{let browser=await chromium.launch({channel:'msedge',headless:true});const context=await browser.newContext();let page=await context.newPage(),consoleErrors=[];page.on('pageerror',e=>consoleErrors.push(e.message));
 for(const width of [1440,768,390]){await page.setViewportSize({width,height:1000});for(let i=0;i<pages.length;i++){const f=pages[i];await page.goto(pathToFileURL(f).href,{waitUntil:'load'});const r=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth+2,imgs:[...document.images].every(x=>x.complete&&x.naturalWidth>0),h1:document.querySelectorAll('h1').length,missing:[...document.querySelectorAll('img')].filter(x=>!x.alt).length,err:document.querySelector('#calc-error')?.textContent||''}));stats.viewports++;if(r.overflow||!r.imgs||r.h1!==1||r.missing||r.err)errors.push('화면 '+width+' '+path.relative(root,f)+' '+JSON.stringify(r));}console.log('뷰포트 검증 완료 '+width+' / '+pages.length);}
 await page.setViewportSize({width:1440,height:1000});await page.goto(pathToFileURL(path.join(root,'00_상세설계_통합보기.html')).href);await page.locator('#search').fill('정책');test('업무 검색 정책 → P23 1건',()=>{});let visible=await page.locator('.card:visible').count();if(visible!==1)errors.push('검색 정책 결과 '+visible);
 await page.goto(pathToFileURL(path.join(root,'02_통합_비용산정.html')).href);await page.locator('#clear').click();assert.equal(await page.evaluate(()=>window.TS_LAST.total),0);await page.locator('[data-phase="17"]').selectOption('1');await page.locator('[data-phase="23"]').selectOption('2');let r=await page.evaluate(()=>window.TS_LAST);assert.deepEqual(r.stage1.included,[1,17]);assert.deepEqual(r.adds,[23]);approx(r.stage2.direct,C.calc(M,[1,17,23]).build.direct-C.calc(M,[1,17]).build.direct);checks.push({name:'브라우저 단계 선택·선행 기능·2차 공통 증분 계산',pass:true});
 await page.locator('#license').fill('-1');await page.locator('#recalculate').click();assert((await page.locator('#calc-error').textContent()).length>0);assert.equal(await page.locator('#calc-output').textContent(),'');checks.push({name:'브라우저 음수 입력 거부·잘못된 결과 미표시',pass:true});
 const shots=[['업무/TS-P10/01_서비스_컨셉.html','p10-concept',1440],['업무/TS-P06/02_전체_아키텍처.html','p06-architecture',1440],['업무/TS-P17/03_사용자_흐름.html','p17-user',1440],['추가후보/TS-P23/04_데이터_흐름.html','p23-data',1440],['추가후보/TS-P23/06_비용_산정.html','p23-cost-mobile',390],['추가후보/TS-P23/01_서비스_컨셉.html','p23-concept',1440],['00_상세설계_통합보기.html','index',1440]];
 const dest='C:/Users/Public/Documents/ESTsoft/CreatorTemp/ts_pages_visual';fs.mkdirSync(dest,{recursive:true});
 for(const [f,name,width] of shots){await page.setViewportSize({width,height:1100});await page.goto(pathToFileURL(path.join(root,f)).href);if(await page.locator('.diagram').count()){await page.locator('.diagram').screenshot({path:path.join(dest,name+'.png')});}else await page.screenshot({path:path.join(dest,name+'.png'),fullPage:false});}
 await page.goto(pathToFileURL(path.join(root,'업무/TS-P10/01_서비스_컨셉.html')).href);await page.locator('[data-zoom="0.2"]').click();assert.equal(await page.locator('.diagram img').getAttribute('data-scale'),'1.2');await page.locator('[data-zoom="reset"]').click();checks.push({name:'도식 확대·기본 크기 복귀',pass:true});
 await page.emulateMedia({media:'print'});let print=await page.locator('.diagram img').evaluate(x=>({minWidth:getComputedStyle(x).minWidth,width:getComputedStyle(x).width}));assert.equal(print.minWidth,'0px');checks.push({name:'인쇄 시 도식 최소 너비 해제',pass:true});
 errors.push(...consoleErrors.map(e=>'브라우저 실행 오류 '+e));await browser.close();const result={date:'2026-09-15',stats,checks,errors,status:errors.length?'보완 필요':'문서 자동검증 통과',actual_product_tests:0,visual_evidence:shots.map(s=>s[1]+'.png')};fs.mkdirSync(path.join(root,'검증'),{recursive:true});fs.writeFileSync(path.join(root,'검증/자동검증_결과.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({status:result.status,checks:checks.length,errors,stats,visualPath:dest},null,2));if(errors.length)process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1;});
