module.exports={
 1:{actor:'운수회사·TS 점검자',system:'점검 기록·COSAS',input:'지적사항·조치 설명·증빙',result:'보완 질문·검토 의견',gate:'대상·기간·필수 증빙 일치?',official:'점검자의 보완·종결',store:'지적·증빙 연결표',exception:'대상·기간 불일치 → 보완 요청'},
 2:{actor:'화물 자격 준비자',system:'검사·시험·교육·발급',input:'목표 자격·현재 단계',result:'다음 단계·준비자료',gate:'공식 요건 상태가 확인됐는가?',official:'공식 신청·접수 확인',store:'자격 규칙·단계 코드',exception:'조회 실패·유효기간 불명 → 확인 대기'},
 3:{actor:'운송업체·점검 담당자',system:'운송계획·점검·인계',input:'계획·차량·물질·수신 기록',result:'문서 상충·수신 누락',gate:'계획·점검·인계가 일치?',official:'담당자 인계·수신 확인',store:'운송건·문서 대응표',exception:'차량 불일치·수신 없음 → 인계 보완'},
 4:{actor:'운영기관·철도 검사관',system:'철도 안전관리체계 검사',input:'요건·절차서·이행 증빙',result:'요건별 증빙·보완 질문',gate:'서류·현장 확인이 충분?',official:'검사관의 검사 판단',store:'요건·보완·현장 이력',exception:'절차서만 존재 → 이행 증빙 보완'},
 5:{actor:'시험운행 검토 전문가',system:'시험운행 보고서 관리',input:'구간·조건·결과 보고서',result:'조건 보존 요약·검토 질의',gate:'대상 구간·버전·근거 일치?',official:'전문가 검토 의견 확정',store:'항목·조건·근거 위치',exception:'도면만 제출 → 전문가 수동 확인'},
 6:{actor:'철도 자율보고 분석자',system:'철도 자율보고 관리',input:'접근 허용 보고·승인 사례',result:'검토본·전파 초안',gate:'보호·의미 검토를 통과?',official:'전문가 전파 승인',store:'원본·검토·전파 구획',exception:'간접 식별 가능 → 전파 보류'},
 7:{actor:'항공 자격 신청자',system:'항공 자격·경력 접수',input:'경력 서술·발급 증빙',result:'경력 대응표·보완 질문',gate:'자격·단위·증빙 확인?',official:'공식 자격 심사·접수',store:'항공 요건·증빙 매핑',exception:'기간 중첩·증빙 없음 → 공식 확인'},
 8:{actor:'항공 자율보고 전문가',system:'항공 자율보고 관리',input:'보고 유형·운항 조건',result:'위해요인·유사사례 차이',gate:'보고 유형·보호·의미 확인?',official:'전문가 전파 승인',store:'항공 사례·승인 이력',exception:'의무보고 여부 불명 → 공식 확인'},
 9:{actor:'드론 소유권 이전 신청자',system:'기체 신고·접수',input:'기체·제원·이전 사건',result:'준비자료·누락 질문',gate:'기체·신고 조건이 확인?',official:'공식 신고 접수',store:'기체 신고 규칙·서식',exception:'제원 불명 → 면제 판단 보류'},
 10:{actor:'자동차검사 예약 이용자',system:'검사소·예약 시스템',input:'차량·지역·희망 날짜',result:'가능 시간·대안 목록',gate:'조건·가용상태·선택 확인?',official:'공식 예약 확정',store:'조건·슬롯 조회 시점',exception:'타임아웃 → 접수 재조회 후 재시도'},
 11:{actor:'시설 관리자·주차장 검사관',system:'기계식주차장 검사',input:'시설·지적·보수 증빙',result:'보수 대응표·재확인 목록',gate:'시설·부위·현장 확인 일치?',official:'검사관 재확인·종결',store:'시설·검사·보수 이력',exception:'사진만 존재 → 수동 확인'},
 12:{actor:'자동차 소유자·조사자',system:'결함 신고·수리 기록',input:'증상·수리·재발 진술',result:'사건표·상충 질문',gate:'같은 차량·사실 확인?',official:'공식 조사·검토 인계',store:'사건 순서·출처 참조',exception:'날짜 상충 → 소유자 확인'},
 13:{actor:'자동차 제작자·담당자',system:'자기인증 절차·서식',input:'제작자 유형·준비 서식',result:'보완 목록·개정 영향',gate:'유형·적용일·필수자료 확인?',official:'제작자 준비 확인·공식 절차',store:'기준·서식·준비 상태',exception:'시행 전 개정 → 적용 검토'},
 14:{actor:'안전기준·문서 담당자',system:'기준·시험계획·발행 관리',input:'개정 기준·관련 문서',result:'영향 후보·반영 이력',gate:'관할·적용일·영향 확인?',official:'문서 승인·발행 확인',store:'개정·영향·문서 버전',exception:'해외 기준 → 국내 적용 별도 검토'},
 15:{actor:'배터리 정보 확인 이용자',system:'제작사 공식 안내',input:'제작사·질문 목적',result:'공식 확인 경로·절차',gate:'승인 안내와 대상 일치?',official:'제작사 공식 확인 창구',store:'공개 안내·갱신 이력',exception:'미지원 제작사 → 공식 창구 안내'},
 16:{actor:'운전자·교육 담당자',system:'ETAS 확정 분석 결과',input:'지표·단위·기간·지침',result:'결과 설명·실천 질문',gate:'수치·비교조건·근거 확인?',official:'교육 담당자 사용 승인',store:'분석 참조·교재 버전',exception:'기간·단위 불일치 → 비교 보류'},
 17:{actor:'TS·지자체 COSAS 사용자',system:'COSAS 원 업무 상태',input:'점검키·역할·P01 결과',result:'해당 건의 검토 결과 표시',gate:'점검키·기관권한·버전 일치?',official:'원 시스템 상태 유지',store:'키 매핑·연계 감사',exception:'타 기관·구버전 → 차단·재조회'},
 18:{actor:'K-패스 이용자',system:'등록·카드·처리 상태',input:'본인확인·조회 목적',result:'상태 설명·정정 경로',gate:'공식 상태·동의 범위 확인?',official:'공식 정정·문의 접수',store:'상태코드·적용 규칙',exception:'사유 불명 → 원인 추정 금지'},
 19:{actor:'DRT 이용자·안내 직원',system:'지자체 DRT 예약·배차',input:'지역·출도착·희망 시각',result:'가능 대안·접수/배차 상태',gate:'장소·지역 규칙·선택 확인?',official:'운영사의 예약·배차',store:'지역 규칙·요청 이력',exception:'접수 성공·배차 대기 구분'},
 20:{actor:'데이터 이용 신청자',system:'개방센터 공개 카탈로그',input:'이용 목적·필요 항목',result:'자료 후보·신청 질문',gate:'제공 범위·이용 조건 일치?',official:'이용·반출 심사',store:'카탈로그·사전·이용 안내',exception:'없는 항목 → 제공 확인 요청'},
 21:{actor:'교육생·체험교육 강사',system:'교육과정·승인 교재',input:'학습목표·텍스트 상황',result:'상황 문답·실천 확인',gate:'수칙·근거·강사 승인?',official:'승인된 교육자료 사용',store:'과정·문답·승인 버전',exception:'교안 수정 → 재승인'},
 22:{actor:'배달업 이륜차 강사',system:'P21 교육 공통 기능',input:'이륜차 교재·배달 상황',result:'강사용 문항·교안 초안',gate:'이륜차 근거·안전 수칙 확인?',official:'교육 책임자 승인',store:'이륜차 콘텐츠·교안 이력',exception:'위험 운전 합리화 → 수정·반려'},
 23:{actor:'TS 정책·사업 기획자',system:'TMACS·정책·기존사업 자료',input:'민원·뉴스·정책보고·공식 현황',result:'문제정의·원인 가설·사업대안',gate:'근거·소관·중복·대안 검토?',official:'현업 검토·기획 채택',store:'문제·주장·근거·정책 결정',exception:'보도·민원 편향 → 추가 조사·유보'}
};
