const fs=require('fs'),path=require('path');
const root='G:/내 드라이브/1. 업무영역/6. CCK/1. 사업관리/TS/bizops/[TS 사업기획]/05_통합사업기획/TS_업무별_상세설계_산정_2026-09-15';
const tmp='C:/Users/Public/Documents/ESTsoft/CreatorTemp',file=path.join(tmp,'ts_pages_diagrams.cjs');
let s=fs.readFileSync(file,'utf8');const start=s.indexOf('function wrap('),end=s.indexOf('function node(',start);
s=s.slice(0,start)+`function wrap(s,max=18){let lines=[];const len=t=>[...t].reduce((a,c)=>a+(/[\\x00-\\x7f]/.test(c)?.56:1),0);for(const part of String(s).split('\\n')){let line='';for(const c of part){if(len(line+c)>max&&!/[?!.,]/.test(c)){let ix=Math.max(line.lastIndexOf(' '),line.lastIndexOf('·'));if(ix>line.length*.4){lines.push(line.slice(0,ix).trim());line=line.slice(ix+1);}else{lines.push(line);line='';}}line+=c;}if(line)lines.push(line.trim());}return lines;}\n`+s.slice(end);
s=s.replace('w=300,h=150','w=300,h=160').replace('w=1240,h=870','w=1240,h=930').replace("title='사용자 흐름 · 기본·대안·예외';h=1240;","title='사용자 흐름 · 기본·대안·예외';h=1290;");
s=s.replace("n('B',900,385,ts[1],'NOA 로컬 LLM + 업무 규칙');","n('B',900,385,ts[1],p.n===10?'공식 가용상태·UI/API':'NOA 로컬 LLM + 업무 규칙');");fs.writeFileSync(file,s);
const D=require(file),M=JSON.parse(fs.readFileSync(path.join(root,'04_설계_산정원장.json'),'utf8')),P=require(path.join(tmp,'ts_pages_profiles.cjs'));let graphs=[];
for(const p of M.plans){for(const k of ['concept','architecture','user','data']){let g=D.graph(p,P[p.n],k);graphs.push(g);let dir=path.join(root,p.n===23?'추가후보':'업무',p.id);fs.writeFileSync(path.join(dir,k+'.svg'),D.render(g));}}
let g=D.graph({id:'TS-COMMON',n:0,req:[['업무별 규칙 적용']],units:[0,0,0,0]},{actor:'국민·현업·정책 기획자',result:'22개 업무 + P23 후보',system:'TS 공식 업무·정책 원천',store:'업무별 승인 지식 구획'},'architecture');g.nodes.find(n=>n.id==='NOA').detail='C00 공통 / C01–C06 분야';g.nodes.find(n=>n.id==='UI').detail='분야별 화면·공식 결과 확인';graphs.push(g);fs.writeFileSync(path.join(root,'자산/common-architecture.svg'),D.render(g));fs.writeFileSync(path.join(root,'05_도식_연결원장.json'),JSON.stringify(graphs,null,2));fs.copyFileSync(file,path.join(root,'작성자료/ts_pages_diagrams.cjs'));
const C=require(path.join(tmp,'ts_pages_cost.js'));const sc=['low','mid','high'],m=x=>Math.round(x).toLocaleString('ko-KR')+'원';const amounts=sc.map(s=>{let p=M.plans.find(p=>p.n===23),c=M.common_modules.find(c=>c.id==='C06');return C.charge(C.labor(p,s)+C.point(c.days,s)*C.unit(C.commonWeight(c)),C.defaults).total;});
const md='\n## C00 공통 기반이 준비된 경우의 P23 추가 비용\n\n기존 NOA의 공통 환경·권한·근거·운영 구성(C00)까지 준비되어 재사용할 수 있으면 P23 업무 적용과 C06 정책기획 공통 기능만 더한다. 단순히 NOA가 설치되어 있다는 사실만으로 C00 완료를 가정하지 않는다.\n\n| 하한 | 중간 | 상한 |\n| --- | --- | --- |\n| '+amounts.map(m).join(' | ')+' |\n\nVAT 포함 기획 소계. 추가 라이선스·직접경비·운영은 별도이며 실측·확정 견적이 아니다.\n';
const {marked}=require('C:/Users/김희섭/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/marked');let html=marked.parse(md).replace('<table>','<div class="tablewrap" tabindex="0" aria-label="P23 공통 재사용 비용"><table>').replace('</table>','</table></div>');let dir=path.join(root,'추가후보/TS-P23/06_비용_산정');let a=fs.readFileSync(dir+'.md','utf8');if(!a.includes('## C00 공통 기반'))fs.writeFileSync(dir+'.md',a.replace('## 초기 범위·공수 가정',md+'\n## 초기 범위·공수 가정'));a=fs.readFileSync(dir+'.html','utf8');if(!a.includes('<h2>C00 공통 기반'))fs.writeFileSync(dir+'.html',a.replace('<article>','<article>'+html));
let cssfile=path.join(root,'자산/report.css');fs.appendFileSync(cssfile,'\nh1,h2,h3,.card p{word-break:keep-all;overflow-wrap:anywhere}\n');
let b=path.join(tmp,'ts_pages_build.cjs');let bs=fs.readFileSync(b,'utf8');bs=bs.replace("const css=`", "const css=`h1,h2,h3,.card p{word-break:keep-all;overflow-wrap:anywhere}");fs.writeFileSync(b,bs);fs.copyFileSync(b,path.join(root,'작성자료/ts_pages_build.cjs'));
console.log({diagrams:graphs.length,p23_C00_reused:amounts});
