import React,{useEffect} from 'react';
import{ChevronDown}from'lucide-react';
import hub from './planning-hub.cjs';
import './planning-hub.css';
import {Heading,Link,Out} from './core.jsx';
import data from './analysis-review.cjs';
import departments from './data.json';
import publication from './document-publication.cjs';
import {DepartmentDownloadLinks} from './DocumentLinks.jsx';
import './analysis-review.css';
import {IspReview} from './IspReview.jsx';
import {CostReview} from './CostReview.jsx';
import {ImplementationReview} from './ImplementationReview.jsx';
const plan=data.planning2027;
const name=code=>departments.departments.find(d=>d.code===code)?.name||code;
const route=code=>departments.departments.find(d=>d.code===code)?.folder+'/01_사업정의.html';
function Table({title,headers,rows}){return <div className="analysis-table" role="region" aria-label={title} tabIndex={0}><table><caption>{title}</caption><thead><tr>{headers.map(h=><th scope="col" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=>j===0?<th scope="row" key={j}>{v}</th>:<td data-label={headers[j]} key={j}>{v}</td>)}</tr>)}</tbody></table></div>}
function Fields({rows}){return <dl className="analysis-fields">{rows.map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>}
export function AnalysisDisposition({code}){const r=data.departments[code];if(!r)return null;return <aside className="analysis-disposition" data-analysis-department={code}><header><span>{data.updatedAt} · 2027년 편성·범위 재검토</span><h3>{r.status}</h3></header><Fields rows={[["달성할 목적",r.purpose],["왜 필요한가 · 검증할 한계",r.why],["CCK 기술로 해결할 처리",r.how],["확보할 실제 기록",r.records],["측정할 변화",r.measure],["편성·판단의 경계",r.exclude]]}/><p className="analysis-limit">{r.decision}. 원문 검토·정형 개선과 비교하여 잔여 문제가 확인된 범위만 추가 개발.</p><Link to="research-library.html?view=planning#analysis-departments">2027년 13처·DRT 편성 검토와 출처 확인 ↗</Link></aside>}
export function AnalysisRefinement({id}){const r=data.refinements.find(r=>r.ids.includes(id));return r?<aside className="analysis-disposition" data-analysis-refinement={id}><header><span>{data.date} · 기존 기획 보강</span><h3>{r.title}</h3></header><Fields rows={[["검증할 문제",r.problem],["구체적 처리",r.how],["필요한 원 기록",r.records],["중단·축소 기준",r.stop]]}/><p className="analysis-limit">추가 사업을 확정한 내용이 아닌 기존 제안의 검증 범위 보강.</p></aside>:null}
function Chapter({id,title,children}){return <section className="analysis-chapter" id={'analysis-'+id} tabIndex={-1}><h2>{title}</h2>{children}</section>}
function ReviewPanel({id,children}){const p=hub.review.panels.find(p=>p.id===id),n=hub.review.panels.indexOf(p)+1;return <details className="planning-review-panel" data-planning-panel={id} id={'planning-panel-'+id}><summary><span>{String(n).padStart(2,'0')}</span><div><h2>{p.title}</h2><p>{p.summary}</p><small>검토 기준 {p.date} · {p.status||'검토안 · 현업 확인 전'}</small></div><ChevronDown size={22}/></summary><div className="planning-review-panel-body">{children}</div></details>}
export function AnalysisReview(){useEffect(()=>{let saved=[];const before=()=>{saved=[...document.querySelectorAll('.planning-review-panel')].map(el=>[el,el.open]);saved.forEach(([el])=>el.open=true)},after=()=>saved.forEach(([el,open])=>el.open=open);addEventListener('beforeprint',before);addEventListener('afterprint',after);return()=>{removeEventListener('beforeprint',before);removeEventListener('afterprint',after)}},[]);function expand(open){document.querySelectorAll('.planning-review-panel').forEach(el=>el.open=open)}return <article className="page analysis-review-page" data-analysis-review={data.date}>
 <Heading label={'2027년 후속사업기획 · 검토 기준 '+hub.date} title={data.title} desc={plan.objective}/>
 <section className="planning-review-guide"><h2>어떤 근거로 어떤 범위의 후속사업을 편성할 것인가</h2><ul className="planning-review-questions">{hub.review.questions.map(q=><li key={q}>{q}</li>)}</ul><nav className="planning-review-actions" aria-label="주요 검토 영역"><Link to="research-library.html?view=planning#isp-start">01 ISP 시작</Link><Link to="research-library.html?view=planning#cost-bundles">02 업무 묶음·RFP</Link><Link to="research-library.html?view=planning#implementation-review">03 실현가능성·확인 질문</Link><Link to="planning-documents.html">04 한글 계획서·대가·도식</Link></nav><p><Link to="research-library.html?view=survey">현업 담당자 · 내 처의 병목 검토와 추가 의견 확인 ↗</Link></p><p className="analysis-limit">{hub.notice} 실제 제품·원자료·연계권한·기준선·현업 피드백 확인 전 기획 검토안.</p></section>
 <aside className="analysis-scope" data-planning-year={plan.year}><h2>이번 기획의 범위 · 2027년</h2><Fields rows={plan.scope}/><p className="analysis-limit">{plan.status}</p></aside>
 <div className="planning-review-tools"><p>4개 큰 검토 영역 · 필요한 영역을 펼쳐 연속 스크롤로 열람. 공유 링크 진입 시 해당 본문 자동 펼침.</p><div><button type="button" onClick={()=>expand(true)}>본문 모두 펼치기</button><button type="button" onClick={()=>expand(false)}>본문 모두 접기</button></div></div>
 <ReviewPanel id="isp"><IspReview/></ReviewPanel>
 <ReviewPanel id="cost"><CostReview/></ReviewPanel>
 <ReviewPanel id="implementation"><ImplementationReview/></ReviewPanel>
 <aside className="analysis-file-entry" data-planning-download-entry><h2>{publication.title}</h2><p>{publication.departments}개 처 · {publication.count}개 HWPX. {publication.lead}</p><div className="analysis-downloads"><Link to={publication.catalogue}>{publication.labels.catalogue} ↗</Link><Out url={publication.githubIndex}>{publication.labels.repository}</Out><a href="#analysis-departments">이전 13처 검토표·개별 문서 ↓</a></div><p className="analysis-limit">{publication.versionNote}</p></aside>
 <div className="planning-review-history"><h2>이전 검토와 근거를 함께 대조</h2><p>최신 ISP·묶음 편성의 검증을 보완하는 참고 이력. 이전 후보를 현재 확정 과업으로 간주하지 않는 기준.</p><nav className="analysis-toc" aria-label="사업 검토서 본문 목차">{[['departments','처별 편성'],['platform','공통 기술·범위'],['corrections','근거 해석 정정'],['candidates','신규 문제정의'],['gates','효과·착수 조건'],['sources','공식 출처']].map(([id,title])=><a key={id} href={'#analysis-'+id}>{title}</a>)}</nav></div>
 <ReviewPanel id="history"><p className="analysis-limit">{data.status}. {data.origin.scope} {data.origin.deepResearch}</p><aside className="analysis-objective" data-analysis-objective><h2>외부 문제에서 출발하는 신규 문제정의</h2><p>{data.definition.scope}</p><p>{data.origin.latestDirection}</p><p><b>대화 반영:</b> {plan.latest.direction}</p><p className="analysis-limit">{plan.latest.availability}</p><a href="#analysis-candidates">문제정의 기준·후보별 검증계획으로 이동 ↓</a></aside>
 <Chapter id="departments" title="1. 2027년 편성 검토 · 기존 제안과 신규 탐색의 관계"><p>기존 제안은 현행 업무를 확인하는 출발점. 부서마다 독립 플랫폼을 신규 발주하는 전제가 아닌, 실제 문제·기존 기능·계약 범위를 확인한 편성 권고.</p><Table title="처별 제안의 현재 검토 상태" headers={['담당 처·본문','편성 검토','목적·적용 모듈','착수 전 핵심 확인',publication.labels.column]} rows={Object.values(data.departments).map(r=>[<Link to={route(r.code)}>{name(r.code)}</Link>,r.status,r.purpose+' / '+r.module,r.why,<DepartmentDownloadLinks code={r.code}/>])}/>
 <Table title="2027년 편성에서 기존 자료를 사용하는 방법" headers={['검토 자료','현재의 역할','편성 시 적용']} rows={plan.portfolio}/>
 <h3>DRT · 전화 접수·기사 배정·운영계획의 조건부 실증</h3><Fields rows={[["검토 상태",data.drt.status],["목적",data.drt.purpose],["실제 처리",data.drt.how],["원 기록",data.drt.records],["효과 검증",data.drt.measure],["초기 범위",data.drt.exclude]]}/><p>{data.drt.why}</p><Table title="수동 처리의 원인별 해결 구분" headers={['원인 가설','확인할 것','적절한 대응']} rows={data.drt.causes}/><p><Link to="drt-assurance.html">기존 DRT 상세제안·설계·측정방법 ↗</Link></p></Chapter>
 <Chapter id="platform" title="2. 하나의 NOA 플랫폼에서 공통 기능 재사용"><p className="analysis-limit">아래 3개 모듈은 구현 기능의 재사용 구분. TS의 전체 문제영역이나 신규 문제의 필수 분류가 아님. 실제 문제와 원인을 먼저 확인한 뒤 적합한 기능에 연결.</p><Fields rows={[["초기 코어",data.platform.scope],["업무 상태",data.platform.state],["추가 개발·대가",data.platform.cost],["계약 확인",data.platform.contract],["품질 수락",data.platform.quality]]}/><div className="analysis-modules">{data.modules.map(m=><section key={m.id}><h3>{m.id} · {m.title}</h3><p><b>우선 검토:</b> {m.codes.map(name).join(' · ')}{m.optional.length>0&&' / 조건부 재사용: '+m.optional.map(name).join(' · ')}</p><Fields rows={[["기술 처리",m.how],["산출물",m.deliverables],["검증할 편익",m.metrics]]}/></section>)}</div><h3>신규 문제정의를 기구축 플랫폼의 스킬로 연결하는 방법</h3><Table title="문제정의 스킬의 처리·데이터·책임 설계" headers={['처리 단계','CCK·기존 기반의 적용안','입출력·검증 조건']} rows={data.definition.execution}/><p className="analysis-limit">{data.definition.constraints}</p><p className="analysis-limit">추가 적용 설계이며 실제 배포본 실행·성능 확인과 구분. {data.definition.privacy}</p><p><Link to="skill-pms.html#pms-direction">공통 플랫폼의 기술·연계·수락 설계 ↗</Link></p></Chapter>
 <Chapter id="corrections" title="3. 사업 필요성의 근거 해석 정정"><Table title="기존 주장을 사용할 때의 제한" headers={['검토 항목','철회·제한할 해석','현재 적용']} rows={data.corrections}/><p className="analysis-limit">{data.audit.status}. {data.audit.scope}</p><Table title="강한 주장과 반증·독립 판정" headers={['ID·원 주장','검토자 A','검토자 B','검토자 C','확인 결과·제한']} rows={data.audit.claims.map(([id,claim,a,b,c,why])=>[id+' · '+claim,a,b,c,why])}/><p>공개 CSV 재집계: {data.audit.csv.rows}행 중 재검일 기재 {data.audit.csv.datePresent}행·공란 {data.audit.csv.dateBlank}행. {data.audit.csv.definition} {data.audit.csv.ratio.toFixed(1)}%. {data.audit.csv.limit}</p><details><summary>CSV 재집계 방법·판본·파일 해시</summary><p>{data.audit.csv.fileTitle}</p><p>{data.audit.csv.method}</p><code>{data.audit.csv.sha256}</code></details></Chapter>
 <Chapter id="candidates" title="4. 외부 문제에서 신규 문제정의로 선별"><p>{data.definition.status}. 아래 6개는 업무·공식 절차를 확인한 탐색 가설. 실제 발생 규모·기존 AI 잔여 기능·구매수요·기준선은 미확인. 별도 상담 챗봇을 다시 제안하기 전에 기존 민원 AI와 정형 안내 개선을 비교.</p><h3>타당성이 높은 문제정의를 남기는 5개 관문</h3><Table title="2027년 신규 AX 과업의 편입 전 확인" headers={['관문','필요한 증거','통합·보류·제외 조건']} rows={plan.evidenceGates.map(([id,title,evidence,condition])=>[id+' · '+title,evidence,condition])}/><Table title="자료 확보 수준에 따른 판단" headers={['검증 상태','필요한 근거','허용할 판단·보류']} rows={data.definition.qualification}/><h3>문제정의서에 연결할 10개 항목</h3><ol className="analysis-definition-steps" data-definition-stages>{data.definition.stages.map(([id,title,question,evidence])=><li key={id}><small>{id}</small><h4>{title}</h4><p>{question}</p><p className="analysis-step-evidence">{evidence}</p></li>)}</ol>{data.candidates.map(c=><section className="analysis-candidate" id={'analysis-'+c.id} key={c.id} data-analysis-candidate={c.id}><header><span>{c.id} · {c.status}</span><h3>{c.title}</h3></header><Fields rows={[["업무 접점",c.owner],["공식 안내의 확인 사실",data.sources[c.primaryRef].fact],["문제정의 질문",c.problem],["확인할 외부 현상",c.verification.external],["현재 대응",c.verification.current],["검증할 잔여 문제",c.verification.remaining],["직접 원인 가설",c.verification.cause],["비AI·CCK 대안 비교",c.verification.alternative],["CCK 처리 적용안",c.how],["현장 확인 기록",c.records],["검증 방법",c.verification.validation],["측정 후보 3개",c.metrics.join(' · ')],["현재 편입 판단",c.verification.decision],["2027년 편성 판단",plan.candidateReviews[c.id].decision],["판단 전 필요한 근거",plan.candidateReviews[c.id].missing],["자료·판단 협의 대상",plan.candidateReviews[c.id].owner],["다음 검증·통합 조건",plan.candidateReviews[c.id].next],["중단·제외",c.stop]]}/><p className="analysis-limit">외부 현상은 확보해야 할 사례 유형이며 현재 확인된 사건을 뜻하지 않음. 기준선·목표 미설정. 아래 링크는 관련 기존 기획이며 본 후보의 신규 구축 확정을 의미하지 않음.</p><p>{c.refs.map(id=><a key={id} href={'#analysis-source-'+id}>{id} · {data.sources[id].title}　</a>)}</p><Link to={c.to}>관련 기존 제안·처리 범위 확인 ↗</Link></section>)}<h3>기존 4개 기획의 보강 · 신규 후보 수와 별도</h3>{data.refinements.map(r=><section className="analysis-candidate" key={r.title}><h4>{r.title}</h4><Fields rows={[["문제 가설",r.problem],["추가 처리",r.how],["필요 기록",r.records],["제외·중단",r.stop]]}/>{r.ids.map(id=><p key={id}><Link to={'proposal-links.html?unit='+id+'#proposal-'+id+'-how'}>해당 업무의 상세제안 ↗</Link></p>)}</section>)}</Chapter>
 <Chapter id="gates" title="5. 2027년 편성 판단·계획서·대가·검수의 연결"><Table title="편입·통합·보류·AI 제외의 판단 기준" headers={['판단','적용 조건','2027년 기획에 반영']} rows={plan.decisions}/><h3>선정된 문제를 사업 문서로 전환하는 순서</h3><Table title="문제정의에서 계획서·설계·RFP·대가·검수까지" headers={['문서','연결할 내용','필요 근거·완료조건']} rows={plan.trace}/><p className="analysis-limit">{plan.estimate.status}. 단계별 일정·투입 인월·총사업비는 선정 범위와 데이터·제품·발주 조건을 확인한 뒤 작성.</p><Table title="AI 없이 개선되는 범위와 NOA 추가 기여의 비교" headers={['비교안','동일 사건의 처리','판단할 결과']} rows={data.comparison}/><p>{data.measurement}</p><Table title="편성·실증 진입 조건" headers={['확인단계','필요한 증거','보류·축소 판단']} rows={data.gate}/><p className="analysis-limit">{data.documentNote}</p><p className="analysis-downloads">{[...plan.downloads,...data.downloads].map(d=><Link key={d.to} to={d.to} download>{d.title} ↓</Link>)}</p></Chapter>
 <Chapter id="sources" title="6. 공식 근거와 조사자료의 확인 한계"><section className="analysis-source" id="analysis-source-strategy" tabIndex={-1}><h3>2027년 사업의 배경 · <Out url={plan.reference.url}>{plan.reference.title}</Out></h3><small>게시일 미표시 · 확인 {plan.reference.checkedAt} · {plan.reference.locator}</small><p>{plan.reference.limit}</p><p><Link to="vision.html">공식 2026–2030 전략 보기 ↗</Link></p></section><Table title="자료 유형별 사용 범위" headers={['자료 유형','현재 확보 상태','사용·추가 확인 기준']} rows={data.definition.sourceQuality}/>{Object.entries(data.sources).map(([id,s])=><section className="analysis-source" id={'analysis-source-'+id} tabIndex={-1} key={id}><h3>{id} · <Out url={s.url}>{s.title}</Out></h3><small>게시 {s.published} · 확인 {s.checkedAt} · 위치 {s.locator}</small><Fields rows={[["확인한 사실",s.fact],["사용 한계",s.limit]]}/></section>)}<p><Link to="research-library.html">조사자료실 전체로 돌아가기 ↗</Link></p></Chapter>
 </ReviewPanel></article>}
