import React from 'react';
import {Heading,Link,Out} from './core.jsx';
import data from './analysis-review.cjs';
import departments from './data.json';
import './analysis-review.css';
const name=code=>departments.departments.find(d=>d.code===code)?.name||code;
const route=code=>departments.departments.find(d=>d.code===code)?.folder+'/01_사업정의.html';
function Table({title,headers,rows}){return <div className="analysis-table" role="region" aria-label={title} tabIndex={0}><table><caption>{title}</caption><thead><tr>{headers.map(h=><th scope="col" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=>j===0?<th scope="row" key={j}>{v}</th>:<td data-label={headers[j]} key={j}>{v}</td>)}</tr>)}</tbody></table></div>}
function Fields({rows}){return <dl className="analysis-fields">{rows.map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>}
export function AnalysisDisposition({code}){const r=data.departments[code];if(!r)return null;return <aside className="analysis-disposition" data-analysis-department={code}><header><span>{data.date} · 필요성·범위 재검토</span><h3>{r.status}</h3></header><Fields rows={[["달성할 목적",r.purpose],["왜 필요한가 · 검증할 한계",r.why],["CCK 기술로 해결할 처리",r.how],["확보할 실제 기록",r.records],["측정할 변화",r.measure],["편성·판단의 경계",r.exclude]]}/><p className="analysis-limit">{r.decision}. 원문 검토·정형 개선과 비교하여 잔여 문제가 확인된 범위만 추가 개발.</p><Link to="research-library.html?view=planning#analysis-departments">13처·DRT 검토와 출처 확인 ↗</Link></aside>}
export function AnalysisRefinement({id}){const r=data.refinements.find(r=>r.ids.includes(id));return r?<aside className="analysis-disposition" data-analysis-refinement={id}><header><span>{data.date} · 기존 기획 보강</span><h3>{r.title}</h3></header><Fields rows={[["검증할 문제",r.problem],["구체적 처리",r.how],["필요한 원 기록",r.records],["중단·축소 기준",r.stop]]}/><p className="analysis-limit">추가 사업을 확정한 내용이 아닌 기존 제안의 검증 범위 보강.</p></aside>:null}
function Chapter({id,title,children}){return <section className="analysis-chapter" id={'analysis-'+id} tabIndex={-1}><h2>{title}</h2>{children}</section>}
export function AnalysisReview(){return <article className="page analysis-review-page" data-analysis-review={data.date}>
 <Heading label={'자료실 · 대화 반영 검토 · '+data.date} title={data.title} desc={data.platform.lead}/>
 <p className="analysis-limit">{data.status}. {data.origin.scope} {data.origin.deepResearch}</p>
 <nav className="analysis-toc" aria-label="사업 검토서 본문 목차">{[['departments','처별 편성'],['platform','공통 기술·범위'],['corrections','근거 해석 정정'],['candidates','추가 문제 후보'],['gates','효과·착수 조건'],['sources','공식 출처']].map(([id,title])=><a key={id} href={'#analysis-'+id}>{title}</a>)}</nav>
 <Chapter id="departments" title="1. 기존 13처와 DRT의 적용범위 정리"><p>기존 제안은 현행 업무를 확인하는 출발점. 부서마다 독립 플랫폼을 신규 발주하는 전제가 아닌, 실제 문제·기존 기능·계약 범위를 확인한 편성 권고.</p><Table title="처별 제안의 현재 검토 상태" headers={['담당 처·본문','편성 검토','목적·적용 모듈','착수 전 핵심 확인']} rows={Object.values(data.departments).map(r=>[<Link to={route(r.code)}>{name(r.code)}</Link>,r.status,r.purpose+' / '+r.module,r.why])}/>
 <h3>DRT · 전화 접수·기사 배정·운영계획의 조건부 실증</h3><Fields rows={[["검토 상태",data.drt.status],["목적",data.drt.purpose],["실제 처리",data.drt.how],["원 기록",data.drt.records],["효과 검증",data.drt.measure],["초기 범위",data.drt.exclude]]}/><p>{data.drt.why}</p><Table title="수동 처리의 원인별 해결 구분" headers={['원인 가설','확인할 것','적절한 대응']} rows={data.drt.causes}/><p><Link to="drt-assurance.html">기존 DRT 상세제안·설계·측정방법 ↗</Link></p></Chapter>
 <Chapter id="platform" title="2. 하나의 NOA 플랫폼에서 공통 기능 재사용"><Fields rows={[["초기 코어",data.platform.scope],["업무 상태",data.platform.state],["추가 개발·대가",data.platform.cost],["계약 확인",data.platform.contract],["품질 수락",data.platform.quality]]}/><div className="analysis-modules">{data.modules.map(m=><section key={m.id}><h3>{m.id} · {m.title}</h3><p><b>우선 검토:</b> {m.codes.map(name).join(' · ')}{m.optional.length>0&&' / 조건부 재사용: '+m.optional.map(name).join(' · ')}</p><Fields rows={[["기술 처리",m.how],["산출물",m.deliverables],["검증할 편익",m.metrics]]}/></section>)}</div><p><Link to="skill-pms.html#pms-direction">공통 플랫폼의 기술·연계·수락 설계 ↗</Link></p></Chapter>
 <Chapter id="corrections" title="3. 사업 필요성의 근거 해석 정정"><Table title="기존 주장을 사용할 때의 제한" headers={['검토 항목','철회·제한할 해석','현재 적용']} rows={data.corrections}/><p className="analysis-limit">{data.audit.status}. {data.audit.scope}</p><Table title="강한 주장과 반증·독립 판정" headers={['ID·원 주장','검토자 A','검토자 B','검토자 C','확인 결과·제한']} rows={data.audit.claims.map(([id,claim,a,b,c,why])=>[id+' · '+claim,a,b,c,why])}/><p>공개 CSV 재집계: {data.audit.csv.rows}행 중 재검일 기재 {data.audit.csv.datePresent}행·공란 {data.audit.csv.dateBlank}행. {data.audit.csv.definition} {data.audit.csv.ratio.toFixed(1)}%. {data.audit.csv.limit}</p><details><summary>CSV 재집계 방법·판본·파일 해시</summary><p>{data.audit.csv.fileTitle}</p><p>{data.audit.csv.method}</p><code>{data.audit.csv.sha256}</code></details></Chapter>
 <Chapter id="candidates" title="4. 공식 업무에서 확인할 추가 문제 후보"><p>아래 6개는 업무·공식 절차를 확인한 탐색 가설. 실제 발생 규모·기존 AI 잔여 기능·구매수요·기준선은 미확인. 별도 상담 챗봇을 다시 제안하기 전에 기존 민원 AI와 정형 안내 개선을 비교.</p>{data.candidates.map(c=><section className="analysis-candidate" id={'analysis-'+c.id} key={c.id} data-analysis-candidate={c.id}><header><span>{c.id} · {c.status}</span><h3>{c.title}</h3></header><Fields rows={[["업무 접점",c.owner],["왜 검토하는가",c.problem],["어떻게 해결하는가",c.how],["현장 확인 기록",c.records],["측정 후보 3개",c.metrics.join(' · ')],["중단·제외",c.stop]]}/><p className="analysis-limit">기준선·목표 미설정. 아래 링크는 관련 기존 기획이며 본 후보의 신규 구축 확정을 의미하지 않음.</p><p>{c.refs.map(id=><a key={id} href={'#analysis-source-'+id}>{id} · {data.sources[id].title}　</a>)}</p><Link to={c.to}>관련 기존 제안·처리 범위 확인 ↗</Link></section>)}<h3>기존 4개 기획의 보강 · 신규 후보 수와 별도</h3>{data.refinements.map(r=><section className="analysis-candidate" key={r.title}><h4>{r.title}</h4><Fields rows={[["문제 가설",r.problem],["추가 처리",r.how],["필요 기록",r.records],["제외·중단",r.stop]]}/>{r.ids.map(id=><p key={id}><Link to={'proposal-links.html?unit='+id+'#proposal-'+id+'-how'}>해당 업무의 상세제안 ↗</Link></p>)}</section>)}</Chapter>
 <Chapter id="gates" title="5. 추가 편익과 실제 편성을 판단할 조건"><Table title="AI 없이 개선되는 범위와 NOA 추가 기여의 비교" headers={['비교안','동일 사건의 처리','판단할 결과']} rows={data.comparison}/><p>{data.measurement}</p><Table title="편성·실증 진입 조건" headers={['확인단계','필요한 증거','보류·축소 판단']} rows={data.gate}/><p className="analysis-limit">{data.documentNote}</p><p className="analysis-downloads">{data.downloads.map(d=><Link key={d.to} to={d.to} download>{d.title} ↓</Link>)}</p></Chapter>
 <Chapter id="sources" title="6. 공식 근거와 확인 한계">{Object.entries(data.sources).map(([id,s])=><section className="analysis-source" id={'analysis-source-'+id} tabIndex={-1} key={id}><h3>{id} · <Out url={s.url}>{s.title}</Out></h3><small>게시 {s.published} · 확인 {s.checkedAt} · 위치 {s.locator}</small><Fields rows={[["확인한 사실",s.fact],["사용 한계",s.limit]]}/></section>)}<p><Link to="research-library.html">조사자료실 전체로 돌아가기 ↗</Link></p></Chapter>
 </article>}
