import React,{useState,useEffect}from'react';import{Layers,Maximize2,Plus,Minus,RotateCcw,ArrowUpRight,ArrowRight,Database,Network,Server,Cpu,FileCheck2}from'lucide-react';
import{Heading,Badge,Link,Out,Modal,href,navigate}from'./core.jsx';import arch from'./architecture-v2.json';import'./architecture.css';
const tabs=[['modules','구성요소',Cpu],['interfaces','연계 계약',Network],['data','데이터·원장',Database],['runtime','배치·복구',Server],['trace','RFP 추적',FileCheck2]];
const img=u=>href('assets/architecture-v2/'+u.code+'_전체아키텍처.svg');
function GridTable({label,heads,rows,rowIds=[]}){return <div className="arch-table-scroll" role="region" aria-label={label} tabIndex={0}><table><caption>{label}</caption><thead><tr>{heads.map(h=><th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i} id={rowIds[i]} tabIndex={rowIds[i]?-1:undefined}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table></div>}
export function DetailedArchitecture({code}){const u=arch.units.find(x=>x.code===code)||arch.units[0],[tab,setTab]=useState(()=>{const value=new URLSearchParams(location.search).get('arch');return tabs.some(t=>t[0]===value)?value:'modules'}),[module,setModule]=useState(u.modules[0].id),[open,setOpen]=useState(false),[zoom,setZoom]=useState(1),[failed,setFailed]=useState(false);const nodes=[...u.modules,...arch.common],m=nodes.find(n=>n.id===module)||u.modules[0],requirements=u.requirements_mapping.filter(r=>r.module===m.id);
useEffect(()=>{const q=new URLSearchParams(location.search);if(q.has('arch'))requestAnimationFrame(()=>{const id=q.get('contract'),store=q.get('store');let el=id?document.getElementById(code+'-'+id):store?document.getElementById(code+'-'+store):document.querySelector('.arch-tabs');if(!el)el=document.querySelector('.arch-tabs');if(el?.tagName==='DETAILS'){el.open=true;el.querySelector('summary')?.focus({preventScroll:true})}else if(store)el?.focus({preventScroll:true});el?.scrollIntoView({block:'start',behavior:'instant'})})},[]);
function chooseTab(id,targetKey,targetId){const q=new URLSearchParams(location.search);q.set('arch',id);q.delete('slide');q.delete('contract');q.delete('store');if(targetKey)q.set(targetKey,targetId);navigate(decodeURI(location.pathname).slice(decodeURI(new URL(window.__TS_BASE__).pathname).length)+'?'+q.toString())}
function goContract(id){chooseTab('interfaces','contract',id)}
return <section className="arch-root" aria-label={u.name+' 상세 아키텍처'}>
<div className="arch-intro"><div><Badge>전체 아키텍처 v2 · 상세 설계안</Badge><h2>업무 모듈에서 실행·데이터 책임까지.</h2><p>{u.object} 단위의 처리와 공통 플랫폼을 연결한 구조.</p></div><div className="arch-counts"><span><strong>12</strong>공통 모듈</span><span><strong>4</strong>업무 모듈</span><span><strong>12</strong>연계 계약</span><span><strong>6</strong>논리 저장소</span></div></div>
<div className="diagram-toolbar"><span><Layers size={17}/>모듈·데이터·승인·기존 시스템의 상세 경계</span><div className="arch-toolbar-actions"><Link to={'downloads/architecture-v2/'+code+'_상세아키텍처.md'} download>업무 명세</Link><Link to="downloads/architecture-v2/00_공통아키텍처.md" download>공통 명세</Link><button onClick={()=>{setZoom(1);setOpen(true)}}><Maximize2 size={18}/>확대해서 보기</button></div></div>
<figure className="diagram-stage arch-stage" tabIndex={0} aria-label="전체 아키텍처 도식 스크롤 영역">{failed?<div className="empty"><p>도식을 불러오지 못했습니다.</p><a href={img(u)}>SVG 원본 열기</a></div>:<img src={img(u)} alt={u.name+' 상세 전체 아키텍처: 업무 4모듈, 공통 12모듈, 승인·기존 시스템·저장소 연결'} onError={()=>setFailed(true)}/>}</figure>
<div className="arch-caption"><span>파랑 · 공통 재사용 검토</span><span>초록 · 업무별 추가 설계</span><span>황색 · 승인·연계 관문</span><span>보라 · 논리 저장 경계</span><p>구성 관계도와 서비스 실행 순서의 구분. 제품·API·서버 배포 상태는 적용 전 확인 대상.</p></div>
<nav className="arch-tabs" aria-label="아키텍처 상세 관점">{tabs.map(([id,t,I])=><button key={id} aria-pressed={tab===id} className={tab===id?'active':''} onClick={()=>chooseTab(id)}><I size={18}/>{t}</button>)}</nav>
{tab==='modules'?<div className="arch-module-layout"><aside><h3>{u.name} 고유 모듈</h3><div className="arch-node-list">{u.modules.map(n=><button className={'arch-module-button '+(m.id===n.id?'active':'')} aria-pressed={m.id===n.id} key={n.id} onClick={()=>setModule(n.id)}><small>{n.id}</small>{n.name}</button>)}</div><h3>공통 플랫폼 모듈</h3><div className="arch-node-list common">{arch.common.map(n=><button className={'arch-module-button '+(m.id===n.id?'active':'')} aria-pressed={m.id===n.id} key={n.id} onClick={()=>setModule(n.id)}><small>{n.id}</small>{n.name}</button>)}</div></aside><article className="arch-module-detail" aria-live="polite"><div className="arch-detail-title"><span>{m.id}</span><h3>{m.name}</h3><p>{m.responsibility}</p></div><Badge>{m.status}</Badge><dl>{[['입력',m.input],['출력',m.output],['검증·인수 조건',m.acceptance],['재사용·추가 경계',m.reuse]].map(([t,c])=><div key={t}><dt>{t}</dt><dd>{c}</dd></div>)}</dl><h4>연계 계약으로 연결</h4><div className="arch-chip-row">{m.interfaces.map(id=><button key={id} onClick={()=>goContract(id)}>{id} <ArrowRight size={13}/></button>)}</div>{m.connections&&<><p className="micro">{m.connection_notice}</p><ul className="arch-connection-routes">{m.connections.map(c=><li key={c.id}><b>{c.id}</b> · {c.route}</li>)}</ul></>}<h4>연결 저장소</h4><div className="arch-chip-row">{m.stores.map(id=><button key={id} onClick={()=>chooseTab("data","store",id)}>{id} · {arch.stores.find(s=>s.id===id).name}</button>)}</div><h4>이 업무의 기존 요구 추적</h4>{requirements.length?<ul>{requirements.map(r=><li key={r.id}><b>{r.id}</b> · {r.name}<small>{r.test} / {r.acceptance}</small></li>)}</ul>:<p className="muted">{u.requirements.length?'이 모듈 단독의 기존 요구 직접 매핑 없음. 업무별 인수조건 및 AV2 공통 과업으로 추가 검토.':'KATRI는 신규 기획용 DRAFT 명세. 공식 RFP 요구·검수 미확정.'}</p>}</article></div>:
 tab==='interfaces'?<div className="arch-interface-view"><div className="arch-notice"><h3>연결선의 실제 의미</h3><p>{arch.interface_notice}</p><p><b>공통 필드 제안</b> · {arch.envelope.join(' · ')}</p></div><div className="arch-contracts">{arch.interfaces.map(i=><details className="arch-contract" key={i.id} id={code+'-'+i.id}><summary><span>{i.id}</span><b>{i.name}</b><small>{i.mode}</small></summary><div className="arch-contract-body"><p className="arch-direction">{i.from}<ArrowRight size={18}/>{i.to}</p><dl>{[['입력 필드',i.input],['출력 필드',i.output],['권한·실행 조건',i.permission],['오류·재시도·대안',i.failure],['현행 연결 확인',i.status]].map(([t,c])=><div key={t}><dt>{t}</dt><dd>{c}</dd></div>)}</dl></div></details>)}</div></div>:
 tab==='data'?<div><div className="arch-notice"><h3>사건 식별과 공식 원장의 구분</h3><p><b>{u.identity.key}</b></p><p>대상: {u.identity.target}</p><p>{u.identity.reference}</p></div><GridTable rowIds={arch.stores.map(s=>code+"-"+s.id)} label="논리 저장소·소유·생명주기" heads={['저장소','최소 데이터','소유·갱신자','원장 관계','보존·정정·회수']} rows={arch.stores.map(s=>[s.id+' '+s.name,s.fields,s.owner,s.authority,s.lifecycle])}/><div className="arch-domain-data"><h3>{u.name} 업무 데이터</h3><ul>{u.fields.map(t=><li key={t}>{t}</li>)}</ul><p>{u.authority}</p></div><h3>업무 상태와 완료조건</h3><div className="arch-states">{arch.states.map(([n,d],i)=><div key={n}><span>{String(i+1).padStart(2,'0')}</span><b>{n}</b><p>{d}</p></div>)}</div><p className="arch-notice"><b>이 업무의 종결 조건</b><br/>{u.done}<br/><b>예외</b> · {u.exception}</p></div>:
 tab==='runtime'?<div><div className="arch-notice"><h3>기존 서버 자원 안의 논리 배치</h3><p>{arch.deployment_notice}</p></div><div className="arch-runtime">{arch.runtime.map(([id,n,mod,d])=><article key={id}><span>{id}</span><Server size={26}/><h3>{n}</h3><b>{mod}</b><p>{d}</p></article>)}</div><GridTable label="장애·예외별 중단과 재개" heads={['실패 사례','감지 모듈','중단·대기 상태','재개 조건']} rows={arch.failures}/><div className="arch-ops">{arch.operations.map(([t,p])=><article key={t}><h3>{t}</h3><p>{p}</p></article>)}</div></div>:
 <div><div className="arch-notice"><h3>기존 요구와 상세 구성의 연결</h3><p>{u.mapping_notice}</p><p>{arch.cost_notice}</p></div>{u.requirements_mapping.length?<GridTable label="기존 요구사항 → 상세 모듈 → 시험" heads={['기존 요구ID','요구사항','상세 모듈','기존 시험','수용 기준']} rows={u.requirements_mapping.map(r=>[r.id,r.name,r.module,r.test,r.acceptance])}/>:<GridTable label="KATRI 신규 기획 명세" heads={['기획ID','모듈','수용 기준']} rows={u.modules.map(m=>[m.requirement_refs.join(', '),m.name,m.acceptance])}/>}<GridTable label="공통·업무별 개발범위" heads={['작업ID','과업','연결 구성','재사용·증분 검토']} rows={arch.workpackages}/><p className="note">동일 공통 엔진을 처마다 중복 산정하지 않음. UI·데이터·도구·연계·규칙·검증의 추가 작업량은 실제 범위 확정 후 산정.</p></div>}
<div className="arch-boundaries"><div><h3>공식 판단·인계 경계</h3><p>{u.excluded}</p><p>{u.action}</p></div><div><h3>기획 근거·확인 상태</h3><p>{u.source_status}</p><div className="arch-source-links">{u.refs.map(s=>s.url.startsWith('http')?<Out key={s.url} url={s.url}>{s.title}</Out>:<Link key={s.url} to={s.url}>{s.title} ↗</Link>)}<Link to="08_CCK_제품근거_재사용설계.html">CCK 재사용 근거 ↗</Link></div></div></div>
<Modal open={open} onClose={()=>setOpen(false)} title={u.name+' · 상세 전체 아키텍처'} wide><div className="zoom-tools"><button className="icon-button" onClick={()=>setZoom(z=>Math.max(.5,z-.25))} disabled={zoom<=.5} aria-label="축소"><Minus/></button><output aria-live="polite">{Math.round(zoom*100)}%</output><button className="icon-button" onClick={()=>setZoom(z=>Math.min(3,z+.25))} disabled={zoom>=3} aria-label="확대"><Plus/></button><button onClick={()=>setZoom(1)} className="reset-zoom"><RotateCcw size={17}/>화면 맞춤</button><a href={img(u)} download>SVG 내려받기</a></div><div className="zoom-canvas" tabIndex={0} aria-label="확대 도식 스크롤 영역"><img style={{width:zoom*100+'%',maxWidth:'none'}} src={img(u)} alt={u.name+' 확대 아키텍처'}/></div></Modal>
</section>}
export function ArchitectureHub(){const requested=new URLSearchParams(location.search).get('unit'),u=arch.units.find(u=>u.code===requested)||arch.units.find(u=>u.code==='DF');return <div className="page architecture-page"><Heading label="ARCHITECTURE · 구성과 책임" title={u.name+" 상세 아키텍처"} desc="처별 업무 모듈 · 공통 플랫폼 · 데이터 · 연계 계약 · 로컬 배치·복구의 연결."><label className="arch-unit-label">상세 설계 대상<select aria-label="아키텍처 대상" value={u.code} onChange={e=>navigate('architecture.html?unit='+e.target.value)}>{arch.units.map(x=><option key={x.code} value={x.code}>{x.code} · {x.name}</option>)}</select></label></Heading><DetailedArchitecture key={u.code} code={u.code}/></div>}