import mandates from './law-mapping.cjs';
import supplement from './proposal-links.cjs';
import React,{useEffect,useRef}from'react';import{ArrowUpRight,X,ShieldCheck,CarFront,BusFront,Network,Activity,Building2,TrainFront,Plane}from'lucide-react';import data from'./data.json';
export const{departments:depts,legal}=data;export const base=window.__TS_BASE__;
export const href=p=>new URL(p,base).href;
export const deptPath=(d,view=0)=>d.folder+'/'+['01_사업정의','02_UI시제품','03_아키텍처_흐름'][view]+'.html';
export const asset=(d,v=0)=>href(v===0?'assets/isometric-v1/'+d.code+'_컨셉도.png':'assets/'+d.code+'_'+['컨셉도','서비스흐름도','아키텍처'][v]+'.svg');
export const source=id=>legal.sources.find(s=>s.id===id);
export const readRoute=()=>decodeURI(location.pathname).slice(decodeURI(new URL(base).pathname).length)||'index.html';
const direct=['skill-pms.html','research-library.html','planning-documents.html','drt-assurance.html','proposal-links.html','associations.html','registry.html','websites.html','architecture.html','katri.html','ars.html','updates.html','discovery.html','index.html','react/index.html','about.html','vision.html','organization.html','solutions.html','inspection.html','legal.html','10_세대화_통합검토.html','11_중장기목표_처별성과.html','16_조직도_수행업무_분석.html','17_조직별_AX_전환제안.html'];
export function isReact(to){return direct.includes(to.split(/[?#]/)[0])||/^legal\/[^/]+\.html/.test(to)||/^처별\/[^/]+\/0[123]_/.test(to)}
export function navigate(to){if(location.protocol==='file:'||!isReact(to)){location.assign(href(to));return}history.pushState({},'',href(to));window.dispatchEvent(new PopStateEvent('popstate'));}
export function Link({to,children,className='',onClick,...props}){return <a href={href(to)} className={className} onClick={e=>{onClick?.(e);if(!e.defaultPrevented&&!e.ctrlKey&&!e.metaKey&&!e.shiftKey&&!e.altKey&&e.button===0&&isReact(to)&&!props.download){e.preventDefault();navigate(to)}}} {...props}>{children}</a>}
export function Out({url,children}){return <a href={url} target="_blank" rel="noopener noreferrer" className="external">{children}<ArrowUpRight size={15}/></a>}
export function Icon({index=0,...props}){const C=[ShieldCheck,CarFront,BusFront,Network,Activity,Building2,TrainFront,Plane][index];return <C {...props}/>}
export function Modal({open,onClose,title,children,wide=false}){const ref=useRef();useEffect(()=>{const el=ref.current;if(open){el.showModal();document.body.style.overflow='hidden'}else if(el.open)el.close();return()=>{document.body.style.overflow=''}},[open]);return <dialog ref={ref} className={'modal '+(wide?'wide':'')} onCancel={e=>{e.preventDefault();onClose()}} onClick={e=>{if(e.target===ref.current)onClose()}} aria-label={title}><div className="modal-inner"><header className="modal-header"><h2>{title}</h2><button onClick={onClose} className="icon-button" aria-label="닫기"><X/></button></header>{children}</div></dialog>}
export function Heading({label,title,desc,children}){return <div className="page-heading"><div><div className="eyebrow">{label}</div><h1>{title}</h1>{desc&&<p>{desc}</p>}</div>{children}</div>}
export function Badge({children}){return <span className="badge">{children}</span>}
export function LawDetails({row:r}){if(!r)return null;return <div className="law-detail"><Badge>{r.mode}</Badge><p className="law-reference">{r.law}</p><ol className="law-responsibility">{[['원 권한·의뢰 주체',r.principal],['TS 수행업무',r.work],['연결 조직',r.org]].map(([t,c],i)=><li key={t}><span>0{i+1}</span><div><h3>{t}</h3><p>{c}</p></div></li>)}</ol><div className="callout"><h3>권한·적용의 경계</h3><p>{r.boundary}</p></div><div className="law-idea"><h3>이 업무에서 출발하는 AX 제안</h3><p>{r.proposal}</p><div className="link-list vertical">{mandates.forLaw(r.id).map(b=><div key={b.id}><strong>{b.task} · {b.owner}</strong>{b.concepts.map(c=><Link to={mandates.mappingPath(c.code)} key={c.code}>{c.department.name} · {c.label}<ArrowUpRight size={16}/></Link>)}{supplement.forLaw(b.id)?.profiles.map(id=><Link to={supplement.path(id)} key={id}>{supplement.profileById[id].name} · {supplement.profileById[id].title}<ArrowUpRight size={16}/></Link>)}</div>)}<Link to={"legal/mapping.html?mode=law&law="+r.id}>하위 업무·담당 근거·컨셉 전체 매핑 ↗</Link></div></div><h3 className="source-heading">원문과 확인 상태</h3><p className="muted">{r.status}</p><ul className="sources">{r.refs.map(id=>{const s=source(id);return <li key={id}><Out url={s.url}>{s.name}</Out><small>{s.effective}</small></li>})}{r.official&&<li><Out url={r.official}>TS 공식 업무안내</Out></li>}</ul><p className="micro">조사일 {legal.date} · 조직 연결은 내부 전결·예산권의 확정과 구분</p></div>}
