const revision=require('./revision47.cjs'),input=require('./delivery-spec47.json'),measurement=require('./measurement-contract47.json'),evidenceMap=require('./delivery-evidence47.json');
const status=input.status,verification='시험 설계 · 미수행 · 실제 TS 및 제품 기능 검증 전';
const controlSpecs=[
['근거·결손 구분','사실·추론·미확인·상충을 구분하고 원문 위치·판본·확인 수준을 보존해야 한다.','유효 원문을 주면 산출 사실에서 동일 원문 위치와 판본으로 역추적 가능','필수 근거를 제거하거나 상충 판본을 주면 해당 판단이 보완·미확인으로 전환되고 0·정상·완료로 대입되지 않음','원문목록·사실대조·결손/상충 결과','자료관리자·업무 검토자'],
['변경·승인 유효성','대상·판본·수신자·행위·인자가 바뀌면 영향을 받는 계획과 승인의 유효성을 다시 확인해야 한다.','승인 범위와 실행 인자가 같은 요청만 지정된 실행 경로로 전달','승인 뒤 대상·기준판본을 변경하면 해당 실행을 보류하고 재검토 이력을 남김','계획판본·승인범위·변경영향·실행차단 기록','업무 승인자·연계 담당자'],
['중복 요청 대사','같은 업무 행위의 재요청을 식별하고 원천 결과와 대사해야 한다. 동일 파일만으로 별개 사건을 삭제해서는 안 된다.','같은 멱등키·행위의 반복 요청을 기존 요청·반영 결과와 연결','원천의 중복 식별을 확인할 수 없으면 재실행 대기. 파일 해시가 같아도 대상 사건이 다르면 별도 유지','사건·행위 식별·멱등키·원천 조회 기록','연계 담당자·원천 운영자'],
['접근·제공 경계','기관·역할·사건·문서·행위 권한을 원문·검색·요약·내보내기·도구 실행에 적용해야 한다.','허용된 사용자는 맡은 사건의 허용 항목만 열람·검토','권한 밖 계정이 요약·검색·직접주소·내보내기로 제한 정보를 요청해도 노출 없이 차단','허용/차단 시험·권한판본·결정근거','정보보호·자료 소유부서'],
['응답 유실·복구','요청 접수·실제 반영·반영 확인을 다른 상태로 관리하고 결과 미확인 시 원천 대사 후 재시도를 결정해야 한다.','접수 참조와 원천 결과 참조가 일치할 때 반영 확인 상태로 전환','응답 유실을 주입하면 성공/실패를 단정하거나 무조건 재전송하지 않고 미확인·조회대사 상태 유지','요청ID·접수응답·재조회·복구 순서','연계 담당자·업무 담당자'],
['개인정보·로컬 처리','필요한 문맥만 허용된 로컬 모델에 제공하고 정정·권한회수·보존 및 파기 결정을 파생 데이터에 반영해야 한다.','목적·권한에 맞는 최소 자료로 처리하고 정정 후 관련 색인·출력 후보의 영향을 확인','로컬 모델 장애 시 외부 모델로 자동 전송하지 않으며 권한회수 자료가 검색·캐시·내보내기로 재노출되지 않음','필드 최소화·경로 차단·정정/회수·복구 확인','정보보호·개인정보·플랫폼 운영'],
['측정·감사 재현','코호트·지표판본·관측기간·분모·결측·중복 및 집계 코드를 기록하여 결과를 재현할 수 있어야 한다.','같은 고정 시험기록·지표판본에서 같은 집계와 미완료 목록 재현','결측·미확인·관측기간 미도래를 성공이나 정상으로 바꾸거나 분모에서 숨기지 않음','원장 참조·집계 코드·분자/분모·결측 보고','현업 자료확인자·독립 평가자'],
['문서 내 지시·도구 호출 검증','수집 문서의 지시문을 실행 권한으로 취급하지 않고 허용 도구·인자·수신자·승인 범위를 검증해야 한다.','업무자료의 사실을 추출하되 도구 호출은 사전에 정한 업무권한과 승인 조건에 따름','첨부문서에 외부 전송·권한 무시·자동 승인 지시를 넣어도 도구를 실행하지 않고 의심 내용과 근거를 분리','공격 시험문서·호출 차단·검토 이력','플랫폼 개발·정보보호·업무 검토자']
];
const controls=controlSpecs.map((a,i)=>({id:'R47-C0'+(i+1),title:a[0],statement:a[1],owner:a[5],artifact:a[4],tests:[{id:'T-R47-C0'+(i+1)+'-N',kind:'정상',expected:a[2],status:verification},{id:'T-R47-C0'+(i+1)+'-X',kind:'예외',expected:a[3],status:verification}]}));
const environments=[
['기능 확인','허용된 가상·비식별 시험자료와 모의 응답','추출·규칙·상태·누락/변경/차단 동작 확인','실제 API 연계·현업 수용·개선효과 완료와 구분'],
['연계 확인','승인된 시험 인터페이스와 허용 계정','요청·응답·권한·중복·유실·반영 대사 확인','연계 명세·접근 권한 확보 전 미수행'],
['업무 수용','현업이 확인한 정상·보완·변경 사례','공식 판단 경계·결과품질·복구 가능성 확인','정답·예외 해석의 확인자와 미결사항 기록'],
['효과 검증','조건을 맞춘 현행 A·규칙/SI B·B+AI C 관측','R 지표 변화·품질·오탐·재작업 부담 평가','모의 시험 통과만으로 개선율 확정 금지']
];
const measures=[
['자료 물량','문서 형식·판본·월 발생량·쪽/표 구성·결손 유형','허용된 표본과 원천 목록','자료별 물량 미확정'],
['업무 변형','정상·보완·변경·인계·취소·재개 유형 및 빈도','업무 사건 표본·수정 이유','유형별 추가 처리와 검증 범위 미확정'],
['연계 범위','원천별 조회·등록 행위·응답·권한·시험환경','승인된 연계 명세·접근 조건','API 개수·구현 난도 미확정'],
['제품 재사용','배포판·사용권·스킬·권한·상태·도구 제공범위','실제 설치본·설정·동작 증거','재사용/설정/추가 개발 구분 전'],
['검증·운영','코호트·평가자료·결측·동시업무·서버 가용여력','현업·정보화 확인 결과','공수·금액·확정 일정 미산정']
];
function get(code){const r=revision.get(code),p=input.profiles[code];if(!r||!p)return null;const references=r.facts.flatMap(f=>f.sources.map(s=>({id:s.id,title:s.title,url:s.url,grade:s.grade,source_level:s.source_level,note:s.note,verification_scope:s.verification_scope,scope:r.facts.filter(x=>x.ids.includes(s.id)).map(x=>x.review).filter((x,i,a)=>a.indexOf(x)===i).join(' / '),role:s.grade==='UNKNOWN'?'확인보류':s.source_level==='2차'||s.type!=='법령'?'배경근거':'직접 연결근거',use:s.grade==='UNKNOWN'?'기능 정당화 근거에서 제외. 잘못된 법적 인용을 막기 위한 확인대상.':'업무 맥락의 출처. 설계 기능을 법정 의무 또는 검증된 제품 기능으로 확정하는 근거 아님.'}))).filter((s,i,a)=>a.findIndex(t=>t.id===s.id)===i);
const requirements=r.detail.steps.map((s,i)=>{const id='R47-'+code+'-F0'+(i+1);return {id,title:s[0],status,reason:r.detail.why[i<2?0:1],evidenceRefs:evidenceMap[code][i].filter(id=>references.find(x=>x.id===id)?.grade!=='UNKNOWN'),evidenceLinks:evidenceMap[code][i].map(id=>references.find(x=>x.id===id)),evidenceUse:'단계별 연결 출처와 역할 표시. 확인보류 자료는 기능 정당화 근거에서 제외. 아래 기능·시험은 이번 설계이며 법정 의무의 직접 전사가 아님.',statement:'시스템은 다음 동작과 결과 확인을 지원해야 한다: '+p.accept[i]+'.',input:s[1],output:s[3],acceptance:p.accept[i],module:p.modules[i],screenId:code+'-47-UI0'+(i+1),screen:['자료·근거 대조','검토·과업 구성','담당자 판단·확인','결과·잔여과업 대사'][i],entityFields:p.fields,product:'CCK NOA·로컬 LLM 및 규칙도구 적용안. 실제 제공 기능·버전·재사용 범위 확인 전.',implementation:'기존 제품 재사용 후보 + 업무별 설정·연계·검증 추가 범위. 개별 구현 완료 미확인.',decision:p.decision,controlRefs:controls.map(c=>c.id),metricRefs:p.metrics[i].map(n=>code+'-R0'+n),dependsOn:i?['R47-'+code+'-F0'+i]:[],tests:[{id:'T-'+id+'-N',kind:'정상',given:'허용 자료의 대상·판본·필수조건과 독립 검토자의 예상 결과를 사전 고정한 시험 묶음',when:s[0]+' 수행',then:p.accept[i],evidence:s[3]+'·입력판본·처리이력·독립 대조 결과',status:verification},{id:'T-'+id+'-X',kind:'결손·상충',given:s[1]+'의 필수 대상 식별 또는 유효판본 일부를 제거/상충시킨 시험 묶음',when:s[0]+' 수행',then:'영향받는 결과를 미확인·보완 상태로 유지하고 관련 근거와 필요한 확인사항 제시. 다른 유효 항목은 상태를 분리해 보존.',evidence:'변경한 시험 입력·결손/상충 표시·상태전이·차단/보완 기록',status:verification}]};});
const counter={id:'T-R47-'+code+'-CASE',kind:'처별 반례',given:p.edge[0],when:p.edge[1],then:p.edge[2],evidence:p.edge[3],status:verification};
const iface={id:'R47-'+code+'-IF01',name:p.read,read:p.read,proposedWrite:p.write,owner:p.decision,status:'연계 계약 확인 전 · 현재 사이트는 정적 설명자료',endpoint:null,auth:null,schema:null,writePermission:null,idempotency:null,fields:[...p.fields,'case_id','source_ref','source_version','request_id','receipt_ref','result_ref','status','reason_code'],fallback:'승인된 파일 반입·담당자 수기 결과 대조로 기능 검토 가능. 실제 연계·업무효과 완료로 집계하지 않음.',unavailable:'조회 실패·권한 거부·응답 지연 시 현재 공식 결과 미확인으로 유지. 캐시의 시점·유효범위를 표시하고 허용되지 않은 쓰기 실행 보류.'};
const measurementContracts=r.detail.metrics.map((m,i)=>{const a=measurement.profiles[code][i];return {id:code+'-R0'+(i+1),name:m[0],formula:m[1],fields:a[0].split(', '),source:a[1],stage:a[2],owner:a[3],blocked:a[4],status:measurement.status,requirementRefs:requirements.filter(q=>q.metricRefs.includes(code+'-R0'+(i+1))).map(q=>q.id)};});
return {code,date:input.date,title:r.title,name:r.name,status,measurementContracts,measurementCommonFields:measurement.commonFields,measurementRule:measurement.commonRule,requirements,controls:controls.map(c=>c.id),references,counter,interface:iface,questions:p.questions,eventFields:['event_id','case_id','stage_id','source_version','plan_version','actor_role','state_from','state_to','event_time','result_ref','reason_code'],eventPolicy:'사건·판본·역할·상태 참조 중심의 최소 로그. 주민번호·연락처·전체 프롬프트·원문·인증정보의 무차별 기록 제외.',environments,measures};
}
function markdown(code){const s=get(code),out=['# '+s.name+' · 요구사항·연계·검수 명세','','작성일: '+s.date,'',status,'','실제 공고의 요구사항·배점·일정에 아직 매핑하지 않은 초안. 특정 제품명은 구현 설명이며 아래 기능 요구의 필수 구매조건이 아님. 기능시험·연계시험·업무수용·효과검증을 구분.','','## 1. 기능요구·검수 추적'];for(const q of s.requirements){out.push('','### '+q.id+' · '+q.title,'',q.statement,'','- 입력: '+q.input,'- 출력: '+q.output,'- 구현 모듈: '+q.module,'- 화면: '+q.screenId+' / '+q.screen,'- 핵심 필드(설계): '+q.entityFields.join(', '),'- 담당 판단: '+q.decision,'- 제품 상태: '+q.product,'- 구현 구분: '+q.implementation,'- 선행 기능: '+(q.dependsOn.join(', ')||'사건·권한·자료 범위 확인'),'- 공통통제: '+q.controlRefs.join(', '),'- 효과지표: '+q.metricRefs.join(', '),'- 근거 연결: '+q.evidenceLinks.map(x=>x.id+' ['+x.role+' · '+x.source_level+' · '+x.grade+'] '+(x.note||x.scope)).join(' / '),'- 근거 해석: '+q.evidenceUse);for(const t of q.tests)out.push('','#### '+t.id+' · '+t.kind,'','- Given: '+t.given,'- When: '+t.when,'- Then: '+t.then,'- 증거: '+t.evidence,'- 상태: '+t.status);}
out.push('','## 2. 처별 반례 수용시험','',...Object.entries(s.counter).map(([k,v])=>'- '+k+': '+v),'','## 3. 연계 계약 확인표','',...Object.entries(s.interface).map(([k,v])=>'- '+k+': '+(v==null?'미확인':Array.isArray(v)?v.join(', '):v)),'','## 4. 공통통제');for(const c of controls){out.push('','### '+c.id+' · '+c.title,'',c.statement,'- 책임 협의: '+c.owner,'- 증거: '+c.artifact);for(const t of c.tests)out.push('- '+t.id+' / '+t.kind+': '+t.expected+' ['+t.status+']');}
out.push('','## 5. 지표별 최소 수집계약','',s.measurementRule,'공통 필드: '+s.measurementCommonFields.join(', '));for(const m of s.measurementContracts)out.push('','### '+m.id+' · '+m.name,'','- 산식: '+m.formula,'- 필드: '+m.fields.join(', '),'- 원천: '+m.source,'- 단계: '+m.stage,'- 책임 협의: '+m.owner,'- 산출불가 조건: '+m.blocked,'- 연결 기능: '+m.requirementRefs.join(', '),'- 상태: '+m.status);
out.push('','## 6. 기능 확인부터 효과 검증까지','',...environments.map(a=>'- '+a.join(' / ')),'','이벤트 필드(설계): '+s.eventFields.join(', '),s.eventPolicy,'','## 7. 산정 전 확인·인수 협의','',...measures.map(a=>'- '+a.join(' / ')),...s.questions.map(a=>'- 현업 확인: '+a),'','## 8. 연결 근거','',...s.references.map(x=>'- ['+x.id+' · '+x.title+']('+x.url+') / '+x.grade+' / '+x.source_level+' / '+x.role+' / '+x.scope+' / '+x.note+' / '+x.use+' / '+x.verification_scope));
return out.join('\n');}
module.exports={status,verification,controls,environments,measures,get,markdown};
