import React,{useState}from'react';
import{Link,Out}from'./core.jsx';
import review from'./department-coverage.cjs';
const l=review.labels;
export function DepartmentCoverage(){const[q,setQ]=useState(''),[filter,setFilter]=useState('all');const rows=review.rows.filter(r=>(filter==='all'||(filter==='missing'?!r.code:r.scope===filter))&&[r.name,r.parent,r.code||'',r.note].join(' ').toLowerCase().includes(q.trim().toLowerCase()));return <section className="pms-coverage" id="pms-department-review" tabIndex={-1}>
 <header><h3>{review.title}</h3><p>{l.summary}</p><p className="pms-coverage-limit">{l.scopeNote}</p></header>
 <div className="pms-coverage-counts">{Object.entries(review.counts).filter(([key])=>['headquarters','katri','headquartersAndKatri'].includes(key)).map(([key,c])=><div key={key}><strong>{key==='headquarters'?l.filters[2][1]:key==='katri'?l.filters[3][1]:l.tableCaption}</strong><span>{c.linked} / {c.official}</span><small>{review.rows.find(r=>!r.code)?.statusLabel} {c.missing}</small></div>)}</div>
 <form className="pms-search" role="search" onSubmit={e=>e.preventDefault()}><label htmlFor="pms-coverage-search">{l.search}</label><input id="pms-coverage-search" type="search" value={q} onChange={e=>setQ(e.target.value)} placeholder={l.placeholder}/><button type="button" onClick={()=>{setQ('');setFilter('all')}}>{l.reset}</button><p role="status">{rows.length} / {review.rows.length}</p></form>
 <div className="pms-coverage-filters" role="group" aria-label={l.title||review.title}>{l.filters.map(([value,label])=><button key={value} type="button" aria-pressed={filter===value} onClick={()=>setFilter(value)}>{label}</button>)}</div>
 {rows.length?<div className="pms-table pms-coverage-table" role="region" aria-label={l.tableCaption} tabIndex={0}><table><caption>{l.tableCaption}</caption><thead><tr>{l.headers.map(t=><th scope="col" key={t}>{t}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id} id={r.anchor} tabIndex={-1} data-coverage-department={r.id} data-coverage-status={r.status}><th scope="row"><small>{r.parent}</small><strong>{r.name}</strong><Link to={'index.html?view=map&node='+r.id}>{l.map} ↗</Link></th><td><span className={'pms-coverage-status '+(r.code?'linked':'missing')}>{r.statusLabel}</span>{r.planTo&&<Link to={r.planTo} data-coverage-plan={r.code}>{r.code} · {l.plan} ↗</Link>}</td><td>{r.note}{r.relatedTo&&<Link to={r.relatedTo}>{r.relatedLabel} ↗</Link>}<a href={'#coverage-source-'+r.sourceId}>{r.sourceId} ↗</a></td></tr>)}</tbody></table></div>:<p className="pms-coverage-empty" role="status">{l.empty}</p>}
 <h4>{l.regional}</h4><div className="pms-coverage-regional">{review.regionalTypes.map(r=><article key={r.id} id={r.anchor} tabIndex={-1} data-coverage-regional={r.id}><h4>{r.name}</h4><strong>{r.statusLabel}</strong><p>{r.note}</p><Link to={'index.html?view=map&node='+r.id}>{l.map} ↗</Link><Link to={r.relatedTo}>{r.relatedLabel} ↗</Link><a href={'#coverage-source-'+r.sourceId}>{r.sourceId} ↗</a></article>)}</div>
 <h4>{l.other}</h4><dl className="pms-coverage-other">{review.supplementary.map(r=><div key={r.type}><dt>{r.type}</dt><dd>{r.names.join(' · ')}<p>{r.note}</p></dd></div>)}</dl>
 <h4>{l.findings}</h4><div className="pms-coverage-findings">{review.findings.map(r=><article key={r.title}><h4>{r.title}</h4><p>{r.result}</p><p className="pms-coverage-limit">{r.limit}</p></article>)}</div>
 <h4>{l.sourceTitle}</h4><div className="pms-coverage-sources">{review.sources.map(s=><article key={s.id} id={'coverage-source-'+s.id} tabIndex={-1}><h4>{s.id} · {s.title}</h4><p>{s.published} / {s.checkedAt}</p><p>{s.location}</p><p>{s.scope}</p><Out url={s.url}>{s.title} ↗</Out></article>)}</div>
 <p className="pms-links"><Link to="downloads/department-coverage.md" download>{l.downloadMd} ↓</Link><Link to="downloads/department-coverage.json" download>{l.downloadJson} ↓</Link></p>
 </section>}
