import React,{useState}from'react';
import{ArrowRight,Search,FileText,Layers}from'lucide-react';
import{Heading,Link}from'./core.jsx';
import content from'./ux-content.cjs';
import hub from './planning-hub.cjs';
const l=content.directory;
export function DepartmentDirectory(){const params=new URLSearchParams(location.search),[q,setQ]=useState(params.get('q')||''),[filter,setFilter]=useState(l.filters.some(([k])=>k===params.get('scope'))?params.get('scope'):'all');const rows=content.rows.filter(r=>(filter==='all'||(filter==='missing'?!r.code:r.scope===filter))&&q.trim().toLowerCase().split(/\s+/).every(w=>[r.name,r.parent,r.code||'',r.title,r.goal,...r.projects.flatMap(p=>[p.id,p.title]),hub.departmentSearchText(r.code)].join(' ').toLowerCase().includes(w)));
 function change(nextQ,nextFilter){setQ(nextQ);setFilter(nextFilter);const u=new URL(location.href);nextQ.trim()?u.searchParams.set('q',nextQ):u.searchParams.delete('q');nextFilter==='all'?u.searchParams.delete('scope'):u.searchParams.set('scope',nextFilter);history.replaceState({},'',u);}
 return <div className="page ux-directory"><Heading label={l.label} title={l.title} desc={l.lead}/><div className="ux-directory-overview"><div className="ux-directory-counts">{l.counts.map(([label,n])=><span key={label}>{label}<strong>{n}</strong></span>)}</div><p>{l.scope}</p></div>
 <section className="ux-directory-controls" aria-label="처별 제안 검색"><form role="search" onSubmit={e=>e.preventDefault()}><label htmlFor="ux-department-query">{l.search}</label><div className="ux-search-field"><Search size={19}/><input id="ux-department-query" type="search" value={q} onChange={e=>change(e.target.value,filter)} placeholder={l.placeholder}/></div></form><div className="ux-filters" role="group" aria-label="소속·작성 상태">{l.filters.map(([key,label])=><button key={key} aria-pressed={filter===key} onClick={()=>change(q,key)}>{label}</button>)}</div><div className="ux-search-status"><p role="status">{rows.length}개 처 · 제안 연결 {rows.filter(r=>r.code).length}개 · 미작성 {rows.filter(r=>!r.code).length}개</p><button onClick={()=>change('','all')}>검색 초기화</button></div></section>
 <p className="ux-reading-tip">{l.step}</p>{rows.length?<div className="ux-department-grid">{rows.map(r=><article key={r.id} data-ux-department={r.id} className={'ux-department '+(!r.code?'is-missing':'')}><header><small>{r.scope==='headquarters'?'본사':'자동차안전연구원'} · {r.parent}</small><h2>{r.name}</h2><span className={'ux-state '+(!r.code?'pending':'')}>{r.code?(r.reviewStatus||l.status):l.missing}</span>{r.code&&<small className="ux-review-date">ISP 기준 {r.reviewDate}{r.previousReview&&' / 이전 편성: '+r.previousReview.status+' · '+r.previousReview.date}</small>}</header><p className="ux-proposal-title">{r.title}</p><p className="ux-proposal-goal">{r.goal}</p>{r.code?<>{r.projects.length>1&&<nav className="ux-project-links" aria-label={r.name+' 개별 기획항목'}>{r.projects.map(p=><Link to={p.to} key={p.id}>{p.title}<ArrowRight size={14}/></Link>)}</nav>}<p className="ux-project-count">{r.projects.length}개 기획항목 · 한글 문서 {r.document.documents.length}종{r.projects.length>1?' · 처별 통합 계획서 공유':''}</p><nav aria-label={r.name+' 제안과 자료'}><Link className="ux-proposal-link" to={r.proposalTo}>{l.actions.proposal}<ArrowRight size={16}/></Link><Link to={r.architectureTo}><Layers size={15}/>{l.actions.architecture}</Link><Link to={r.documentsTo}><FileText size={15}/>{l.actions.documents}</Link></nav></>:<nav aria-label={r.name+' 확인 자료'}><Link to={'skill-pms.html?view=coverage#'+r.anchor}>조직·작성 상태 확인<ArrowRight size={16}/></Link></nav>}</article>)}</div>:<div className="ux-empty" role="status"><h2>검색 결과 없음</h2><p>{l.empty}</p><button onClick={()=>change('','all')}>전체 처 다시 보기</button></div>}
 <nav className="ux-related-links" aria-label="조직·설계 관련 자료">{l.related.map(([title,to])=><Link key={to} to={to}>{title}<ArrowRight size={16}/></Link>)}</nav></div>
}
