import React,{useState}from'react';
import{ArrowRight,Search,FileText,Layers}from'lucide-react';
import{Heading,Link}from'./core.jsx';
import content from'./ux-content.cjs';
import hub from './planning-hub.cjs';
import intent from './proposal-intent.cjs';
import readerUI from './reader-ui.cjs';
const l=content.directory;
export function DepartmentDirectory(){const params=new URLSearchParams(location.search),[q,setQ]=useState(params.get('q')||''),[filter,setFilter]=useState(l.filters.some(([k])=>k===params.get('scope'))?params.get('scope'):'all');const rows=content.rows.filter(r=>(filter==='all'||(filter==='missing'?!r.code:r.scope===filter))&&q.trim().toLowerCase().split(/\s+/).every(w=>[r.name,r.parent,r.code||'',r.title,r.goal,...r.projects.flatMap(p=>[p.id,p.title]),hub.departmentSearchText(r.code)].join(' ').toLowerCase().includes(w)));
 function change(nextQ,nextFilter){setQ(nextQ);setFilter(nextFilter);const u=new URL(location.href);nextQ.trim()?u.searchParams.set('q',nextQ):u.searchParams.delete('q');nextFilter==='all'?u.searchParams.delete('scope'):u.searchParams.set('scope',nextFilter);history.replaceState({},'',u);dispatchEvent(new Event('ts:content-filter'));}
 return <div className="page ux-directory"><Heading label={l.label} title={l.title} desc={readerUI.labels.directoryLead}/><div className="ux-directory-overview"><div className="ux-directory-counts">{l.counts.map(([label,n])=><span key={label}>{label}<strong>{n}</strong></span>)}</div><p>{l.scope}</p></div>
 <section className="ux-directory-controls" aria-label="처별 제안 검색"><form role="search" onSubmit={e=>e.preventDefault()}><label htmlFor="ux-department-query">{l.search}</label><div className="ux-search-field"><Search size={19}/><input id="ux-department-query" type="search" value={q} onChange={e=>change(e.target.value,filter)} placeholder={l.placeholder}/></div></form><div className="ux-filters" role="group" aria-label="소속·작성 상태">{l.filters.map(([key,label])=><button key={key} aria-pressed={filter===key} onClick={()=>change(q,key)}>{label}</button>)}</div><div className="ux-search-status"><p role="status">{rows.length}개 처 · 제안 연결 {rows.filter(r=>r.code).length}개 · 미작성 {rows.filter(r=>!r.code).length}개</p><button onClick={()=>change('','all')}>검색 초기화</button></div></section>
 <p className="ux-reading-tip">기관의 실제 업무와 최신 검토 상태를 확인한 뒤 과제 선택. 목적·근거·현행 한계·해결방법·도식·측정방법·요구사항·한글 문서는 통합 본문에서 연속 확인.</p>{rows.length?<div className="reader-directory-list">{rows.map(r=><article key={r.id} id={'directory-department-'+r.id} data-ux-department={r.id} className={'ux-department reader-directory-row '+(!r.code?'is-missing':'')}><header><small>{r.scope==='headquarters'?'본사':'자동차안전연구원'} · {r.parent}</small><h2>{r.name}</h2><span className={'ux-state '+(!r.code?'pending':'')}>{r.code?(r.reviewStatus||l.status):l.missing}</span>{r.code&&<small className="ux-review-date">검토 {r.reviewDate} · 한글 문서 {r.document.documents.length}종</small>}</header><div>{r.code?r.projects.map(p=>{const f=intent.byId[p.id];return <section key={p.id} className="reader-directory-project" data-directory-intent={p.id}><div><small>{p.id}</small><h3>{p.title}</h3><p><b>대상 편익</b> {f?.purpose}</p></div><Link className="ux-proposal-link" to={'index.html?dept='+r.code+'&project='+p.id+'#integrated-work-context'}>상세 본문 이어 읽기<ArrowRight size={16}/></Link></section>}):<section className="reader-directory-project"><div><p>{readerUI.labels.noPlan}</p><small>{r.goal}</small></div><Link to={'index.html?dept='+r.id+'#integrated-work-context'}>수요 확인 내용 보기<ArrowRight size={16}/></Link></section>}</div></article>)}</div>:<div className="ux-empty" role="status"><h2>검색 결과 없음</h2><p>{l.empty}</p><button onClick={()=>change('','all')}>전체 처 다시 보기</button></div>}
 <nav className="ux-related-links" aria-label="조직·설계 관련 자료">{l.related.map(([title,to])=><Link key={to} to={to}>{title}<ArrowRight size={16}/></Link>)}</nav></div>
}
