import React,{useState}from'react';
import{ArrowRight,ArrowUpRight,FileCheck2,GitBranch,ClipboardCheck,BookOpen,ChevronRight,Download}from'lucide-react';
import{Link,Out,Heading,Badge,depts,deptPath,navigate}from'./core.jsx';
import research from'./discovery.json';
const sources=ids=>research.sources.filter(s=>ids.includes(s.id));
function Refs({ids}){return <ul className="discovery-refs">{sources(ids).map(s=><li key={s.id}><Out url={s.url}>{s.title}</Out><small>{s.date} · {s.section}</small></li>)}</ul>}
function Block({title,children}){return <article className="discovery-block"><h3>{title}</h3><p>{children}</p></article>}
function Candidate({c}){const[step,setStep]=useState(0);return <div className="candidate-detail">
<div className="candidate-title"><div><span className="eyebrow">{c.id} · 업무 전환 가설</span><h2>{c.title}</h2><p>{c.benefit}</p></div><Badge>현업 검증 전</Badge></div>
<div className="transition-pair"><div><small>확인할 현행 흐름</small><p>{c.before}</p></div><ArrowRight aria-hidden="true"/><div><small>제안하는 전환</small><p>{c.after}</p></div></div>
<div className="candidate-flow" aria-label={c.id+' 제안 서비스 흐름'}>{c.steps.map((s,i)=><button key={i} aria-pressed={step===i} onClick={()=>setStep(i)}><span>0{i+1} / {s.who}</span><strong>{s.title}</strong><ChevronRight size={18}/></button>)}</div>
<div className="candidate-step" aria-live="polite"><span>0{step+1}</span><div><h3>{c.steps[step].title}</h3><p>{c.steps[step].detail}</p></div></div>
<div className="candidate-summary"><Block title="누가 · 어떤 상황에서">{c.actor+' · '+c.trigger}</Block><Block title="먼저 확인할 문제">{c.problem}</Block></div>
<details className="discovery-details" open><summary><GitBranch size={19}/> 기존 과업과 추가 작업</summary><div className="candidate-summary"><Block title="재사용 검토">{c.reuse}</Block><Block title="추가범위 후보">{c.delta}</Block></div><p className="source-note">직접 대조: 정성제안서 PDF 78–80쪽(SFR-006), 84쪽(SFR-007), 85–88쪽(SFR-008). 제안서 기재와 최종 계약·현재 구현 상태는 별도 확인.</p></details>
<details className="discovery-details"><summary><BookOpen size={19}/> 필요한 데이터 · CCK 구현방법</summary><div className="candidate-summary"><Block title="입력 자료·연결 조건">{c.data}</Block><Block title="CCK 적용 제안">{c.cck}</Block><Block title="비AI 비교안">{c.baseline}</Block><Block title="책임·정보 이동의 경계">{c.boundary}</Block></div></details>
<details className="discovery-details"><summary><ClipboardCheck size={19}/> 편익 검증 · 산출물 · 산정</summary><div className="candidate-summary"><Block title="측정 지표">{c.metric}</Block><Block title="대상과 분모">{c.denominator}</Block><Block title="반증할 다른 원인">{c.counter}</Block><Block title="공수·대가 판단">{c.cost}</Block></div><ul className="deliverable-list">{c.deliverables.map(x=><li key={x}>{x}</li>)}</ul><p className="note">수치 목표는 TS 기준선·위험 허용한계 확인 후 사전 합의. 선행기관 수치를 TS 개선율로 전용하지 않음.</p></details>
<div className="candidate-links"><div><h3>관련 부서의 기존 제안</h3><p>{c.mapping}</p><div>{c.codes.map(code=>{const d=depts.find(x=>x.code===code);return d&&<Link key={code} to={deptPath(d)}>{d.name}<ArrowUpRight size={15}/></Link>})}</div></div><div><h3>발굴에 참고한 선행근거</h3><Refs ids={c.refs}/><p className="micro">선행사례에서 TS 적용 가설을 도출한 기획 판단. 같은 추가기능이 이미 입증됐다는 의미와 구분.</p></div></div>
</div>}
function Cases(){const[id,setId]=useState('E01');const e=research.cases.find(x=>x.id===id);return <><div className="case-switch" aria-label="선행사례 선택">{research.cases.map(x=><button key={x.id} onClick={()=>setId(x.id)} aria-pressed={id===x.id}><span>{x.org}</span><strong>{x.label}</strong></button>)}</div><section className="case-detail" key={id}><div className="candidate-title"><div><span className="eyebrow">{e.org} / {e.id}</span><h2>{e.name}</h2><p>{e.at}</p></div><Badge>{e.stage}</Badge></div><div className="transition-pair"><div><small>기존 처리</small><p>{e.before}</p></div><ArrowRight/><div><small>변경한 처리</small><p>{e.after}</p></div></div><div className="candidate-summary"><Block title="공식 자료에서 확인">{e.facts}</Block><Block title="효과·적용범위의 한계">{e.limits}</Block></div><div className="case-question"><span>TS 현업에 물을 질문</span><h3>{e.question}</h3><p>{e.hypothesis}</p></div><Block title="CCK·로컬 LLM 조건으로 옮길 부분">{e.fit}</Block><Refs ids={e.refs}/></section><div className="discovery-callout"><b>5개 기관 사례의 선택 표본</b><p>교통·계획행정·서신·식품 규제의 업무 패턴 비교. 선진국 전체·공공 AX 전체의 대표 통계와 구분. 미지원 범위·연계 한계·기대효과를 운영성과와 함께 기록.</p></div></>}
function Validation(){return <div className="discovery-validation"><div><span className="eyebrow">COMMON DELIVERY PATTERN</span><h2>하나의 업무가 실제로 끝나는지 확인.</h2><p>아래는 제안 아키텍처. 기존 시스템의 공식 기록과 권한을 유지하는 공통 수행 구조.</p><ol className="candidate-architecture">{research.common.architecture.map(([a,b],i)=><li key={a}><span>0{i+1}</span><div><h3>{a}</h3><p>{b}</p></div></li>)}</ol><p className="note">{research.common.limits}</p></div><div><h2>현업 검증 순서</h2><div className="validation-list">{research.common.validation.map(([a,b])=><article key={a}><h3>{a}</h3><p>{b}</p></article>)}</div><Block title="현업 확인 요청">{research.common.interview}</Block><Block title="공수·대가 산정의 출발점">{research.common.cost}</Block></div><div className="internal-lead"><span className="eyebrow">INTERNAL EVIDENCE</span><h2>내부 자료의 작은 단서도 후속 확인.</h2><p>정성제안서 PDF 33쪽 참여인력 경력란의 온북(OS·GPMS) 개발·운영 및 ‘교안공(POC)’ 표기 직접 확인.</p><p><b>확인할 것</b> · 시험 업무·기간·성과·막힌 조건·재사용 권한. 현재 TS 운영·스마트폰 녹음 승인·CCK 현 보유기술의 증거로 확대하지 않음.</p></div></div>}
export function Discovery(){const params=new URLSearchParams(location.search),tab=params.get('tab')||'candidates';const c=research.candidates.find(x=>x.id===params.get('candidate'))||research.candidates[0];const select=(t,id=c.id)=>navigate('discovery.html?tab='+t+'&candidate='+id);return <div className="page discovery-page"><Heading label="FROM EVIDENCE TO WORK" title="사람이 다시 해야 했던 일에서, 다음 AX 발견." desc="선행사례의 업무 변화 → TS의 추가 작업 → 현업 자료로 검증할 후보."><Link to="downloads/TS_업무전환후보_검토.md" download className="button outline"><Download size={18}/>검토자료</Link></Heading><nav className="view-tabs discovery-tabs" aria-label="업무전환 검토 보기">{[['candidates','전환 후보 3건'],['cases','선행사례 5건'],['validation','공통 구조·검증']].map(([v,t])=><button key={v} onClick={()=>select(v)} aria-pressed={tab===v} className={tab===v?'active':''}>{t}</button>)}</nav>{tab==='cases'?<Cases/>:tab==='validation'?<Validation/>:<div className="discovery-workspace"><aside><div className="candidate-selector" aria-label="업무전환 후보 선택">{research.candidates.map(x=><button key={x.id} onClick={()=>select('candidates',x.id)} aria-pressed={c.id===x.id}><span>{x.id}</span><strong>{x.short}</strong><p>{x.benefit}</p><ArrowUpRight size={19}/></button>)}</div><div className="candidate-side-note"><FileCheck2 size={22}/><h3>아직 확정하지 않은 것</h3><p>TS 문제의 빈도·부담<br/>추가 계약범위<br/>주관부서·데이터 권한<br/>예산·정량 개선효과</p></div></aside><Candidate key={c.id} c={c}/></div>}<div className="discovery-foot"><p>조사 기준 {research.date} · {research.status}</p><Link to="solutions.html">처별 AX 서비스로 돌아가기 <ArrowRight size={17}/></Link></div></div>}
