import React,{useEffect,useMemo,useRef,useState}from'react';
import{ArrowUp,List,Maximize2,ExternalLink}from'lucide-react';
import{Link,href}from'./core.jsx';
import model from'./document-data.cjs';
import './document-reader.css';
import SourceFigure from './SourceFigure.jsx';
import {Proposal47,CommonFinding47,Catalogue47} from './Revision47.jsx';
import revision47 from './revision47.cjs';
import composition from './proposal-composition.cjs';
function Reference({link}){return /^[a-z][a-z0-9+.-]*:/i.test(link.to)?<a href={link.to} target="_blank" rel="noopener noreferrer">{link.label}<ExternalLink size={13}/></a>:<Link to={link.to}>{link.label}<ExternalLink size={13}/></Link>}
function DetailTables({tables=[]}){return <div className="proposal-tables">{tables.map((t,i)=><div className="proposal-table-wrap" key={i}><table><caption>{t.title}</caption><thead><tr>{t.headers.map((h,j)=><th scope="col" key={j}>{h}</th>)}</tr></thead><tbody>{t.rows.map((row,k)=><tr key={k}>{row.map((value,j)=><td data-label={t.headers[j]} key={j}>{value}</td>)}</tr>)}</tbody></table></div>)}</div>}
function Figure({section,onOpen}){const[failed,setFailed]=useState(false);return <figure className="reading-figure">{failed?<div className="reading-image-error"><p>도식을 불러오지 못했습니다.</p><a href={href(section.image)}>원본 도식 열기</a><button onClick={()=>setFailed(false)}>다시 불러오기</button></div>:<button type="button" onClick={e=>onOpen(section,e.currentTarget)} aria-label={(section.alt||section.title)+' 확대'}><img src={href(section.image)} alt={section.alt||section.title} loading="lazy" onError={()=>setFailed(true)}/><span><Maximize2 size={15}/>도식 확대</span></button>}<figcaption>{section.alt||section.title}</figcaption></figure>}
export function DocumentReader({route}){
 const doc=useMemo(()=>model.getDocument(route),[route]),originalTarget=model.targetFromRoute(route,doc),historyView=new URL(route,'https://local/').searchParams.get('history')==='20260924',requested=/^처별\//.test(route)&&!historyView?composition.currentTarget(originalTarget):originalTarget,grouped=doc.chapters.length>0,legacyOutlineItems=grouped?doc.chapters:doc.sections,intro=route.startsWith('about.html');
 const isCatalogue=/^(solutions|inspection|17_조직별_AX_전환제안)\.html/.test(route);
 const code=/^처별\/([A-Z]{2})_/.exec(route)?.[1],revised=revision47.get(code),legacyRef=useRef(),outlineItems=revised?revision47.chapters.map(([id,title])=>({id:'r47-'+id,title})):isCatalogue?Object.keys(revision47.data.departments).map(c=>({id:'r47-catalog-'+c,title:revision47.get(c).name})):legacyOutlineItems;
 useEffect(()=>{if(revised&&requested&&!requested.startsWith('r47-')&&legacyRef.current)legacyRef.current.open=true},[route,requested]);
 const[active,setActive]=useState(requested||doc.sections[0]?.id),[outline,setOutline]=useState(()=>!revised&&!isCatalogue&&matchMedia('(min-width:1440px)').matches),[image,setImage]=useState(null);
 const root=useRef(),dialog=useRef(),imageTrigger=useRef();
 useEffect(()=>{if(revised&&!historyView&&originalTarget&&requested!==originalTarget){const u=new URL(location.href);u.hash='section-'+requested;for(const key of ['slide','metric','contract','store'])u.searchParams.delete(key);history.replaceState({},'',u);dispatchEvent(new PopStateEvent('popstate'));}if(revised&&!historyView&&requested?.startsWith('r47-')&&legacyRef.current)legacyRef.current.open=false},[route,requested,originalTarget,historyView]);
 useEffect(()=>{const m=matchMedia('(min-width:1440px)');const update=()=>setOutline(!revised&&!isCatalogue&&m.matches);m.addEventListener('change',update);return()=>m.removeEventListener('change',update)},[]);
 useEffect(()=>{let frame=requestAnimationFrame(()=>{if(requested){const el=document.getElementById('section-'+requested);el?.scrollIntoView({block:'start'});el?.querySelector('h2,h3,h4')?.focus({preventScroll:true})}});return()=>cancelAnimationFrame(frame)},[route,requested]);
 useEffect(()=>{let queued=false,frame=null;const update=()=>{queued=false;frame=null;if(!root.current)return;const top=(document.querySelector('.ts-header')?.getBoundingClientRect().height||0)+70;const items=[...root.current.querySelectorAll(revised?'[data-revision-department] [data-section-id]':'[data-section-id]')];let current=items[0];for(const item of items){if(item.getBoundingClientRect().top<=top)current=item;else break}if(current)setActive(current.dataset.sectionId)};const scroll=()=>{if(!queued){queued=true;frame=requestAnimationFrame(update)}};addEventListener('scroll',scroll,{passive:true});update();return()=>{removeEventListener('scroll',scroll);if(frame!==null)cancelAnimationFrame(frame)}},[doc]);
 useEffect(()=>{const el=dialog.current;if(image&&!el.open)el.showModal();if(!image&&el.open)el.close()},[image]);
 function jump(e,id){if(e.ctrlKey||e.metaKey||e.shiftKey||e.altKey)return;e.preventDefault();const u=new URL(location.href);u.hash='section-'+id;u.searchParams.delete('slide');u.searchParams.delete('reading');history.pushState({},'',u);setActive(id);if(!matchMedia('(min-width:1440px)').matches)setOutline(false);requestAnimationFrame(()=>{const el=document.getElementById('section-'+id);el?.scrollIntoView({block:'start'});el?.querySelector('h2,h3,h4')?.focus({preventScroll:true})});}
 function closeImage(){setImage(null);imageTrigger.current?.focus({preventScroll:true})}
 function section(s,i,nested=false){const Title=nested?'h3':'h2',CardTitle=nested?'h4':'h3';return <section className={'document-section'+(nested?' chapter-section':'')+(s.image?' with-figure':'')+(/-method-/.test(s.id)?' measurement-fragment':'')} id={'section-'+s.id} data-section-id={s.id} key={s.id} aria-labelledby={'heading-'+s.id}>
 <header className="reading-section-heading">{!nested&&<span>{String(i+1).padStart(2,'0')}</span>}<div><Title id={'heading-'+s.id} tabIndex={-1}>{s.title===doc.title&&i===0?'개요·검토 범위':s.title}</Title><p>{s.message}</p></div></header>
 {s.additionalMessages?.length>0&&<div className="reading-joined-context">{s.additionalMessages.map((m,j)=><p key={j}>{m}</p>)}</div>}
 {s.paragraphs&&(s.media?.length?<><div className="reading-narrative"><p>{s.paragraphs[0]}</p></div>{s.media.filter(figure=>figure.placement!=='afterTables').map(figure=><SourceFigure figure={figure} key={figure.id}/>)}<div className="reading-narrative">{s.paragraphs.slice(1).map((p,j)=><p key={j}>{p}</p>)}</div></>:<div className="reading-narrative">{s.paragraphs.map((p,j)=><p key={j}>{p}</p>)}</div>)}
 {(s.image||s.diagram)&&<Figure section={s.diagram?{...s,image:'downloads/proposals/'+s.diagram.code+'_'+s.diagram.type+'.svg',alt:s.title+' / '+s.message}:s} onOpen={(value,trigger)=>{imageTrigger.current=trigger;setImage(value)}}/>}
 <div className={'reading-blocks'+(s.cards.length===1?' single':'')}>{s.cards.map((c,j)=><section className="reading-block" key={j} id={/^(DS[1-6]) · /.test(c.title)?'section-card-'+c.title.split(' · ')[0]:undefined}><CardTitle tabIndex={-1} id={/^(DS[1-6]) · /.test(c.title)?'heading-card-'+c.title.split(' · ')[0]:undefined}>{c.title.replace(/^0[1-4] · /,'')}</CardTitle><ul>{c.bullets.map((t,k)=><li key={k}>{t}</li>)}</ul></section>)}</div>
 {s.tables&&<DetailTables tables={s.tables}/>} {s.media?.filter(figure=>figure.placement==='afterTables').map(figure=><SourceFigure figure={figure} key={figure.id}/>)}<div className="reading-evidence"><p>{[s.status||'기존 사업기획 자료의 구조화 · 적용 조건·확인 범위는 원문 참조',...(s.additionalStatuses||[])].join(' / ')}</p>{s.links.length>0&&<nav aria-label={s.title+' 근거·상세자료'}>{s.links.map((l,j)=><Reference key={j} link={l}/>)}</nav>}</div></section>}
 return <article ref={root} className={'document-reader'+(grouped?' grouped-document':'')+(intro?' institution-document':'')} aria-label={doc.title+' 연속 문서'}>
 <header className="reading-header" id="document-start"><div><span className="reading-eyebrow">{intro?'기관 이해 → 책임 → 목표 → 조직 → 제안':'TS AX 사업기획 · 처별 제안과 근거'}</span><h1 tabIndex={-1}>{revised?revised.name+' · 통합 상세제안':doc.title}</h1><p>{revised?revised.detail.purpose:doc.lead||(grouped?'사업의 이유부터 업무 변화·구현·책임·효과까지, 큰 장의 순서대로 이어서 읽는 상세 제안.':'업무·근거·제안 내용을 아래로 이어서 확인')}</p></div></header>
 <div className="reading-layout">{!intro&&<aside className="reading-outline-area"><details className="reading-outline" open={outline} onToggle={e=>{if(e.currentTarget.open!==outline)setOutline(e.currentTarget.open)}}><summary><List size={17}/>본문 읽는 순서 <span>{outlineItems.length}개 {grouped?'장':'주제'}</span></summary><nav aria-label="본문 항목 목차">{outlineItems.map((s,i)=><a key={s.id} href={'#section-'+s.id} aria-current={(active===s.id||s.sections?.some(x=>x.id===active))?'location':undefined} onClick={e=>jump(e,s.id)}><span>{String(i+1).padStart(2,'0')}</span>{s.title===doc.title&&i===0?'개요·검토 범위':s.title}</a>)}</nav></details></aside>}
 <div className="reading-content">{isCatalogue&&<Catalogue47/>}{revised&&<Proposal47 code={code}/>}<details ref={legacyRef} className={revised||isCatalogue?'r47-legacy':'r47-unwrapped'} open={historyView||(!revised&&!isCatalogue)||(!!requested&&!requested.startsWith('r47-'))}><summary hidden={!revised&&!isCatalogue}>{revised?.verdict==='재설계'?'이전 가설(2026-09-24)':'이전 상세설계 참고(2026-09-24)'} · 기존 문서·도식·링크 보존</summary>{revised&&<p className="r47-legacy-note">아래 내용은 이전 가설의 설계 이력. 장·절의 구성은 위 최신 본문에 통합했으며, 과거 컨셉·공수·지표는 현재 확정 명세로 승계하지 않음. 근거 없는 목표 수치는 표시 철회. <Link to={route.split(/[?#]/)[0]+'?history=20260924#section-detail-sixw'}>2026-09-24 원문 위치로 이동</Link></p>}{grouped?doc.chapters.map((c,i)=><section className="reading-chapter" id={'section-'+c.id} key={c.id}><header><span>{String(i+1).padStart(2,'0')}</span><div><h2 id={'heading-'+c.id} tabIndex={-1}>{c.title}</h2><p>{c.intro}</p></div></header>{c.sections.map((s,j)=>section(s,j,true))}</section>):doc.sections.map((s,i)=>section(s,i))}
 {intro&&<CommonFinding47/>}
 </details><a className="reading-back-top" href="#document-start" onClick={e=>{e.preventDefault();document.getElementById('document-start')?.scrollIntoView({block:'start'});root.current?.querySelector('h1')?.focus({preventScroll:true})}}><ArrowUp size={16}/>문서 처음으로</a></div></div>
 <dialog ref={dialog} className="reading-image-dialog" aria-label="도식 확대 보기" onCancel={e=>{e.preventDefault();closeImage()}} onClick={e=>{if(e.target===dialog.current)closeImage()}}><div className="reading-dialog-header"><strong>{image?.alt||image?.title}</strong><button onClick={closeImage}>닫기 · Esc</button></div>{image&&<><img src={href(image.image)} alt={image.alt||image.title}/><a href={href(image.image)} target="_blank" rel="noopener noreferrer">원본 도식 열기</a></>}</dialog></article>
}
