import React,{useEffect,useRef,useState}from'react';
import{ChevronRight,PanelLeft,ArrowLeft}from'lucide-react';
import{Link,navigate}from'./core.jsx';
import'./document-nav.css';
import ux from'./ux-navigation.cjs';
import readerUI from './reader-ui.cjs';
import documents from './document-data.cjs';
export const documentTree=ux.sections;
export function DocumentNav({route}){const active=ux.sectionFor(route),context=ux.contextLinks(route),[generated,setGenerated]=useState([]),[mobile,setMobile]=useState(false),toggle=useRef(),panel=useRef();
 useEffect(()=>{
  setMobile(false);let frame,focusFrame;
  const collect=()=>{const headings=[...document.querySelectorAll('#main h2')].filter(e=>!e.closest('dialog')&&!e.closest('details:not([open])')&&!e.closest('.mandate-page'));const items=headings.slice(0,80).map((e,i)=>{const target=e.closest('.native-department-row[id],section,article')||e;if(!target.id||target.id.startsWith('reader-section-')){const key=e.textContent.trim()+'|'+target.textContent.slice(0,200);let hash=2166136261;for(const ch of key)hash=Math.imul(hash^ch.codePointAt(0),16777619);target.id='reader-section-'+(hash>>>0).toString(16);}return{id:target.id,title:e.textContent.trim(),to:route.split(/[?#]/)[0]+location.search+'#'+target.id}}).filter((e,i,a)=>a.findIndex(x=>x.id===e.id)===i);setGenerated(items)};
  collect();focusFrame=requestAnimationFrame(()=>{let id;try{id=decodeURIComponent(location.hash.slice(1))}catch{return}const target=document.getElementById(id);if(target){target.setAttribute('tabindex','-1');target.scrollIntoView({block:'start'});(target.querySelector('h2[tabindex]')||target).focus({preventScroll:true})}});
  const observer=new MutationObserver(()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(collect)}),main=document.getElementById('main');if(main)observer.observe(main,{childList:true,subtree:true});const filter=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(collect)};addEventListener('ts:content-filter',filter);return()=>{removeEventListener('ts:content-filter',filter);observer.disconnect();cancelAnimationFrame(frame);cancelAnimationFrame(focusFrame)};
 },[route]);
 function closeAfterLink(e){if(e.ctrlKey||e.metaKey||e.shiftKey||e.altKey)return;setMobile(false);const target=e.currentTarget;if(target.pathname===location.pathname&&target.hash){e.preventDefault();navigate(route.split(/[?#]/)[0]+location.search+target.hash);}}
 const mapping=route.startsWith('legal/mapping.html'),local=mapping?{d:{name:'法령·현행 업무'.replace('法','법')},links:[['mandate-start','법령·업무·솔루션 연결'],...((new URL(route,'https://local/').searchParams.get('mode')!=='law'||new URL(route,'https://local/').searchParams.has('project'))?[['mandate-current','선택 과제·현행 처리']]:[]),['mandate-matrix','법령별 책임·처 매핑'],['mandate-coverage','추가 확인 범위']].map(([id,title])=>({id,title,to:route.split('#')[0]+'#'+id}))}:context;const path=route.split(/[?#]/)[0],plainDoc=(path==='legal.html'||path.startsWith('legal/')||['vision.html','organization.html','architecture.html','katri.html','ars.html','discovery.html','updates.html'].includes(path))&&!mapping,doc=plainDoc?documents.getDocument(route):null,items=doc?(doc.chapters.length?doc.chapters.flatMap(x=>[x,...x.sections.map(s=>({...s,depth:1}))]):doc.sections).map(x=>({id:x.id,title:x.title,depth:x.depth||0,to:route.split('#')[0]+'#section-'+x.id})):generated;const links=mapping?local.links:context?context.links:items;const routeUrl=new URL(route,'https://local/'),chosen=links.find(n=>n.id===context?.activeId)||links.find(n=>n.to===route)||links.find(n=>routeUrl.hash&&new URL(n.to,'https://local/').hash===routeUrl.hash)||links.find(n=>!new URL(n.to,'https://local/').hash&&new URL(n.to,'https://local/').pathname===routeUrl.pathname&&new URL(n.to,'https://local/').search===routeUrl.search);
 return <aside className={'document-nav '+(mobile?'mobile-open':'')} aria-label="문서 탐색" onKeyDown={e=>{if(e.key==='Escape'&&mobile){setMobile(false);toggle.current?.focus()}}}>
 <button ref={toggle} className="doc-mobile-toggle" aria-expanded={mobile} aria-controls="document-tree-panel" onClick={()=>{setMobile(!mobile);if(!mobile)requestAnimationFrame(()=>panel.current?.querySelector('a')?.focus())}}><PanelLeft size={18}/>문서 목차 {mobile?'닫기':'열기'}</button>
 <div className="doc-panel" id="document-tree-panel" ref={panel}><div className="doc-section-heading"><span>{context?.kind==='institution'?'기관 이해':context?.kind==='analysis'?'2027 후속사업기획':context?'처별 상세제안':'현재 메뉴'}</span><strong>{local?local.d.name:active.title}</strong></div>
 {context?<Link to={readerUI.at(route,'integrated-start')} className="ux-back-link" onClick={closeAfterLink}><ArrowLeft size={15}/>{readerUI.labels.back}</Link>:<p className="ux-nav-description">{active.description}</p>}
 <nav aria-label="문서 목차"><ul className="doc-tree">{links.map((n,i)=>{const exact=chosen?.id===n.id;return <li key={n.id} className={n.depth?"reader-outline-child":""}><Link to={n.to} onClick={closeAfterLink} aria-current={exact?'page':undefined}>{context?<span className="ux-nav-number">{String(i+1).padStart(2,'0')}</span>:<ChevronRight size={14}/>}<span>{n.title}</span></Link></li>})}</ul></nav>

 <p className="ux-sidebar-note">자료 제목·조직 검색은 상단의 자료 검색 이용</p></div></aside>
}
