import React,{useEffect} from 'react';
import {Link,Out,href} from './core.jsx';
import data from './drt-assurance.cjs';
import './drt-assurance.css';
import {ProposalIntent} from './ProposalIntent.jsx';
import {ImplementationDRTNotice} from './ImplementationReview.jsx';

export function DrtRelated(){return <aside className="drt-related"><strong>{data.relatedNotice.title}</strong><p>{data.relatedNotice.text}</p><Link to="drt-assurance.html">근거·솔루션·5종 그림·정량평가 상세 보기 →</Link></aside>}
function References({ids=[]}){return ids.length>0&&<p className="drt-refs">근거: {ids.map((id,i)=><React.Fragment key={id}>{i>0?' · ':''}<a href={'#drt-source-'+id}>{id} {data.sources[id].title}</a></React.Fragment>)}</p>}
function MetricCards(){return <div className="drt-metrics">{data.metrics.map(m=><article key={m.id} id={m.id}><span>{m.id} · 기준선·수치 목표 미확정</span><h4>{m.name}</h4><dl>{[['산식',m.formula],['원천 증빙',m.evidence],['측정방법',m.method],['검증할 기대효과',m.value]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></article>)}</div>}
function Block({block:b}){if(b.deferred)return <details className="drt-deferred"><summary>{b.title} · 미선정 후속안 · 현재 과업 제외</summary><Block block={{...b,deferred:false}}/></details>;return <section id={b.type==='visual'?'drt-visual-'+b.id:undefined} className={'drt-block drt-block-'+b.type}><h3>{b.title}</h3>{b.type==='note'&&<ul>{b.items.map(t=><li key={t}>{t}</li>)}</ul>}{b.type==='table'&&<div className="drt-table"><table><caption>{b.title}</caption><thead><tr>{b.headers.map(h=><th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{b.rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j} data-label={b.headers[j]}>{v}</td>)}</tr>)}</tbody></table></div>}{b.type==='visual'&&<figure><a href={href(b.src)} target="_blank" rel="noopener noreferrer" aria-label={b.title+' 원본 확대 · 새 탭'}><img src={href(b.src)} alt={b.alt} width={b.width} height={b.height} loading="lazy" decoding="async"/></a><figcaption>{b.caption} <a href={href(b.src)} target="_blank" rel="noopener noreferrer">원본 확대 ↗</a>{b.points?.length>0&&<ul>{b.points.map(t=><li key={t}>{t}</li>)}</ul>}</figcaption></figure>}{b.type==='metrics'&&<MetricCards/>}<References ids={b.refs}/></section>}
export function DrtAssurance({route,embedded=false}){useEffect(()=>{let id;try{id=decodeURIComponent(location.hash.slice(1))}catch{return}if(!id)return;const frame=requestAnimationFrame(()=>{const target=document.getElementById(id);if(!target)return;target.scrollIntoView({block:"start",behavior:"instant"});const heading=target.querySelector("h2,h3,h4");if(heading){heading.setAttribute("tabindex","-1");heading.focus({preventScroll:true})}});return()=>cancelAnimationFrame(frame)},[route]);const Title=embedded?'h3':'h1';return <article className="drt-proposal" data-proposal="B08-G"><header className="drt-hero"><p className="drt-eyebrow">B08 확장 · {data.date} · CCK 주관 AX+SI 기획</p><Title>{data.title}</Title><p className="drt-lead">{data.lead}</p><p className="drt-status">{data.status}</p><div className="drt-summary">{data.summaries.map(([title,text])=><div key={title}><strong>{title}</strong><span>{text}</span></div>)}</div><nav aria-label="DRT 상세제안 목차">{data.sections.map((s,i)=><a key={s.id} href={'#drt-'+s.id}>{String(i+1).padStart(2,'0')} {s.title}</a>)}</nav><a className="drt-download" href={href('downloads/drt-assurance.md')} download>전체 기획안 Markdown 다운로드 ↓</a><nav aria-label="DRT 도식 바로가기">{data.sections.flatMap(s=>s.blocks).filter(b=>b.type==='visual').map(b=><a key={b.id} href={'#drt-visual-'+b.id}>{b.title}</a>)}</nav></header><ProposalIntent projectId="MR-02"/><ImplementationDRTNotice/>{data.sections.map((s,i)=><section className="drt-chapter" id={'drt-'+s.id} key={s.id}><header><span>{String(i+1).padStart(2,'0')}</span><div><h2 tabIndex={-1}>{s.title}</h2><p>{s.intro}</p></div></header>{s.blocks.map((b,j)=><Block key={j} block={b}/>)}</section>)}<section className="drt-chapter" id="drt-sources"><header><div><h2>근거 원문과 확인 범위</h2><p>갱신일 {data.date}. 근거별 실제 확인일과 공식자료·기술문서·공급사 설명·사용자 현장 의견을 구분. 도입 설계와 예상 편익은 실증 전의 제안.</p></div></header><div className="drt-sources">{Object.entries(data.sources).map(([id,s])=><article id={'drt-source-'+id} key={id}><h3>{id} · {s.url?<Out url={s.url}>{s.title}</Out>:s.title}</h3><p className="drt-source-date">{s.published} · 확인 {s.checkedAt||'2026-09-29'}{s.recheckedAt?' · 재확인 '+s.recheckedAt:''} · {s.kind==='user'?'사용자 현장 의견':s.kind==='technical'?'공식 기술문서':id==='S07'||id==='S08'?'공급사 설명':'공식 원문'}</p><p><b>확인 사실:</b> {s.fact}</p><p><b>적용 한계:</b> {s.limit}</p>{s.pdf&&<Out url={s.pdf}>처분요구서 PDF · 5~7쪽 수치 확인</Out>}</article>)}</div></section><aside className="drt-related"><h2>기존 제안과 이어서 보기</h2><p>모빌리티연구처·정책지원처의 대표안은 유지. 본 항목은 B08 DRT의 전화 접수·배차·운영계획 전환안이며, 정산감사·환수·전국 예산배분은 미선정 후속안이며 현재 납품·대가·핵심 성과에서 제외.</p>{data.related.map(([label,to])=><p key={to}><Link to={to}>{label} →</Link></p>)}</aside></article>}
