import React,{useEffect} from 'react';
import {Link,Out,href} from './core.jsx';
import data from './drt-assurance.cjs';
import './drt-assurance.css';

export function DrtRelated(){return <aside className="drt-related"><strong>{data.relatedNotice.title}</strong><p>{data.relatedNotice.text}</p><Link to="drt-assurance.html">근거·솔루션·3종 그림·정량평가 상세 보기 →</Link></aside>}
function References({ids=[]}){return ids.length>0&&<p className="drt-refs">근거: {ids.map((id,i)=><React.Fragment key={id}>{i>0?' · ':''}<a href={'#drt-source-'+id}>{id} {data.sources[id].title}</a></React.Fragment>)}</p>}
function MetricCards(){return <div className="drt-metrics">{data.metrics.map(m=><article key={m.id} id={m.id}><span>{m.id} · 기준선·목표 미확정</span><h4>{m.name}</h4><dl>{[['산식',m.formula],['원천 증빙',m.evidence],['측정방법',m.method],['검증할 기대효과',m.value]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></article>)}</div>}
function Block({block:b}){return <section className={'drt-block drt-block-'+b.type}><h3>{b.title}</h3>{b.type==='note'&&<ul>{b.items.map(t=><li key={t}>{t}</li>)}</ul>}{b.type==='table'&&<div className="drt-table"><table><caption>{b.title}</caption><thead><tr>{b.headers.map(h=><th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{b.rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j} data-label={b.headers[j]}>{v}</td>)}</tr>)}</tbody></table></div>}{b.type==='visual'&&<figure><a href={href(b.src)} target="_blank" rel="noopener noreferrer" aria-label={b.title+' 원본 확대 · 새 탭'}><img src={href(b.src)} alt={b.alt} width="1672" height="941" loading="lazy"/></a><figcaption>{b.caption} <a href={href(b.src)} target="_blank" rel="noopener noreferrer">원본 확대 ↗</a></figcaption></figure>}{b.type==='metrics'&&<MetricCards/>}<References ids={b.refs}/></section>}
export function DrtAssurance({route}){useEffect(()=>{let id;try{id=decodeURIComponent(location.hash.slice(1))}catch{return}if(!id)return;const frame=requestAnimationFrame(()=>{const target=document.getElementById(id);if(!target)return;target.scrollIntoView({block:"start",behavior:"instant"});const heading=target.querySelector("h2,h3,h4");if(heading){heading.setAttribute("tabindex","-1");heading.focus({preventScroll:true})}});return()=>cancelAnimationFrame(frame)},[route]);return <article className="drt-proposal" data-proposal="B08-G"><header className="drt-hero"><p className="drt-eyebrow">B08 확장 · {data.date} · CCK 주관 AX+SI 기획</p><h1>{data.title}</h1><p className="drt-lead">{data.lead}</p><p className="drt-status">{data.status}</p><div className="drt-summary">{data.summaries.map(([title,text])=><div key={title}><strong>{title}</strong><span>{text}</span></div>)}</div><nav aria-label="DRT 상세제안 목차">{data.sections.map((s,i)=><a key={s.id} href={'#drt-'+s.id}>{String(i+1).padStart(2,'0')} {s.title}</a>)}</nav><a className="drt-download" href={href('downloads/drt-assurance.md')} download>전체 기획안 Markdown 다운로드 ↓</a></header>{data.sections.map((s,i)=><section className="drt-chapter" id={'drt-'+s.id} key={s.id}><header><span>{String(i+1).padStart(2,'0')}</span><div><h2 tabIndex={-1}>{s.title}</h2><p>{s.intro}</p></div></header>{s.blocks.map((b,j)=><Block key={j} block={b}/>)}</section>)}<section className="drt-chapter" id="drt-sources"><header><div><h2>근거 원문과 확인 범위</h2><p>조사일 {data.date}. 공식자료와 공급사 설명을 구분하며, 도입 설계와 예상 편익은 검증 전의 제안.</p></div></header><div className="drt-sources">{Object.entries(data.sources).map(([id,s])=><article id={'drt-source-'+id} key={id}><h3>{id} · <Out url={s.url}>{s.title}</Out></h3><p className="drt-source-date">{s.published} · 확인 {data.date}{id==='S07'||id==='S08'?' · 공급사 설명':' · 공식 원문'}</p><p><b>확인 사실:</b> {s.fact}</p><p><b>적용 한계:</b> {s.limit}</p>{s.pdf&&<Out url={s.pdf}>처분요구서 PDF · 5~7쪽 수치 확인</Out>}</article>)}</div></section><aside className="drt-related"><h2>기존 제안과 이어서 보기</h2><p>모빌리티연구처·정책지원처의 대표안은 유지. 본 항목은 B08 DRT의 정책집행·정산검증 확장안으로 별도 관리.</p>{data.related.map(([label,to])=><p key={to}><Link to={to}>{label} →</Link></p>)}</aside></article>}
