import React from 'react';
import {Link,Out} from './core.jsx';
import d from './implementation-review.cjs';
import {InterviewPlan} from './InterviewPlan.jsx';
import './implementation-review.css';
function Table({title,headers,rows}){return <div className="implementation-table" role="region" aria-label={title} tabIndex={0}><table><caption>{title}</caption><thead><tr>{headers.map(h=><th scope="col" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{row.map((v,j)=>j===0?<th scope="row" key={j}>{v}</th>:<td key={j}>{v}</td>)}</tr>)}</tbody></table></div>}
function Fields({rows}){return <dl className="analysis-fields">{rows.map(([label,text])=><div key={label}><dt>{label}</dt><dd>{text}</dd></div>)}</dl>}
const anchor=id=>'research-library.html?view=planning#implementation-'+id;
const projectLinks=ids=>ids.map((id,i)=><React.Fragment key={id}>{i>0?' · ':''}<a href={'#implementation-mapping-'+id}>{id} {d.mappings.find(r=>r.id===id).department}</a></React.Fragment>);
export function ImplementationDRTNotice(){return <aside className="implementation-department-note" data-implementation-drt-notice><h2>2026-10-03 재조사 · 현행 수동 배차와 고도화 목표</h2><p>공식 RFP의 현 시스템은 수동 배차. 자동배차·최적 경로·재배차·상담이력·부정수급 관리 등은 2026 입찰의 목표범위이며 구현 완료는 미확인. 2027 추가안은 전화 요청 이해·근거 검토·운영조건 변경 영향의 실제 차분으로 제한.</p><p>공고문과 RFP의 계약기간이 불일치하여 확정 일정 확인 대기. 콜센터·배차 API 사용권과 실제 적용 시점 확인 전 자동 실행 착수 보류.</p><Link to={anchor('drt')}>원 RFP와 2027년 중복·추가범위 대조 ↗</Link></aside>}
export function ImplementationDepartmentNote({code}){const rows=d.mappings.filter(r=>r.code===code);return rows.length?<aside className="implementation-department-note" data-implementation-department={code}><b>{d.date} · 구현 검토</b><p>{rows.map(r=>r.id+' '+d.statuses[r.status]).join(' / ')}</p><Link to={anchor('mapping-'+rows[0].id)}>최신 구현경계·선행조건 확인 ↗</Link><p><Link to={anchor('interview-'+code)}>이 처의 인터뷰 준비·확인 질문·회신 양식 ↗</Link></p><p className="analysis-limit">{d.documentNote}</p></aside>:null}
export function ImplementationReview(){const counts=Object.entries(d.statuses).map(([key,label])=>[label,d.mappings.filter(r=>r.status===key).length]);return <section id="implementation-review" className="implementation-review" data-implementation-review={d.date} tabIndex={-1}>
 <header><small>{d.date} · {d.version} · 2027년 편성 재검토</small><h3>최신 현황에서 실제 구현범위까지</h3><p>{d.status}</p></header>
 <Fields rows={[["이번 확인 범위",d.scope],["실제 현업 피드백",d.feedback.human],["독립 검토",d.feedback.independent]]}/>
 <div className="implementation-summary">{counts.map(([label,count])=><div key={label}><strong>{count}개</strong><span>{label}</span></div>)}</div><p className="analysis-limit">42개 항목의 검토 분류. 확정 사업 수가 아닌 검증 순서. 39개 처를 동시에 발주하는 전제 배제. M1/M2/M3 중 실제 자료가 확보되는 1~2개 참조업무에서 시작.</p>
 <p className="analysis-downloads">{d.downloads.map(([title,to])=><Link key={to} to={to} download>{title} ↓</Link>)}</p>
 <p className="implementation-jumps"><a href="#implementation-drt">DRT 현황·중복</a><a href="#implementation-candidates">5개 검증 후보</a><a href="#implementation-technology">CCK 기술·실행</a><a href="#implementation-mapping">39처·42항목</a><a href="#implementation-metrics">측정·대가</a><a href="#implementation-feedback">현업 확인</a></p>
 <h4>반론·보완 의견의 실제 반영</h4><Table title="독립 검토 의견과 설계 변경" headers={['관점','새로 확인한 내용','반영 판단']} rows={d.reviews}/>
 <section id="implementation-drt" tabIndex={-1}><h4>DRT · 수동 운영과 2026 고도화의 구분</h4><p>전화 접수·기사 배정·운영계획이 핵심. 자동배차·정산 기능의 부재를 가정하기 전에 현행 운영과 이번 발주의 납품목표를 각각 확인.</p><Table title="DRT 현황·기구축/발주·추가 AI 범위" headers={['구분','공식 근거·확인 상태','2027년 제안의 처리']} rows={d.drtDifference}/><p><Out url={d.sources.find(s=>s.id==='F02').url}>원 입찰공고·첨부 RFP 확인 ↗</Out>　<Link to="drt-assurance.html">기존 DRT 상세제안 ↗</Link></p></section>
 <section id="implementation-candidates" tabIndex={-1}><h4>입력·신규 개발·결과·실패까지 정의한 5개 후보</h4>{d.candidates.map(c=><section key={c.id} className="implementation-candidate" data-implementation-candidate={c.id}><header><small>{c.id} · {c.module} · {c.priority}</small><h5>{c.title}</h5></header><Fields rows={[["대표 검증 업무",projectLinks(c.binding.primary)],["다른 업무의 코어 재사용",projectLinks(c.binding.reuse)],["업무를 구분할 조건",c.binding.note],["왜·누구를 위한가",c.why],["필요 입력",c.input],["CCK 재사용 후보",c.reuse],["추가 개발·설정",c.newWork],["사용할 결과",c.output],["반드시 시험할 실패",c.test],["축소·중단 경계",c.stop]]}/><ol className="implementation-flow" aria-label={c.title+' 처리 흐름'}>{c.flow.map((step,i)=><li key={step}><span>{i+1}</span>{step}</li>)}</ol></section>)}</section>
 <section id="implementation-technology" tabIndex={-1}><h4>CCK 기반기술 · 설명자료에서 실행 가능한 증거로</h4><p>지정 R&D 경로에서 실행 가능한 제품 소스·설치본을 이번 범위에서 특정하지 못한 상태. 회사 전체 미보유를 뜻하지 않으며, 아래 재사용은 설치본 대조 전 후보.</p><Table title="제품별 확인 수준·재사용 조건" headers={['제품','읽은 근거','재사용할 경계 후보','개발팀 확인']} rows={d.products}/><h5>하나의 플랫폼에서 처리할 공통 실행계약</h5><Table title="실행 단계·데이터·권한·검증" headers={['단계','기술 역할','입출력 계약','검증·차단조건']} rows={d.execution}/><p className="analysis-limit">{d.constraints.join(' · ')}. 문서 생성, 승인, 시스템 반영, 공식 종결은 서로 다른 완료상태.</p></section>
 <section id="implementation-mapping" tabIndex={-1}><h4>39개 처·42개 기획의 최소 구현경계</h4><p>아래 분류는 기존 계획서 전체의 구현범위를 다시 읽은 결과. 최신 외부 현황은 일부 업무만 재열람했으며 전 처의 현업 수락·예산·배포 상태는 미확인.</p><Table title="기획항목별 구현범위·선행조건" headers={['기획·처별 한글','검토·모듈','최소 경계·우선 확인']} rows={d.mappings.map(r=>[<div id={'implementation-mapping-'+r.id} tabIndex={-1} data-implementation-mapping={r.id}><b>{r.id} · {r.department}</b><p>{r.title}</p><Link to={'planning-documents.html#documents-'+r.code}>기존 한글 3종 ↗</Link></div>,<>{d.statuses[r.status]}<br/>{r.module}<small>{r.externalRefresh}</small>{r.refs.map(id=><a key={id} href={"#implementation-source-"+id}>{id} 원문　</a>)}</>,r.scope])}/></section>
 <section id="implementation-research100" tabIndex={-1}><h4>100단계 조사자료 · 문제 가설의 선별 반영</h4><p>{d.research100.method}</p><p className="analysis-limit">{d.research100.limit}</p><Table title="기존 조사에서 가져올 내용과 보류할 주장" headers={['단계·주제','사용할 문제·기능 가설','현재 기획 연결','미검증·제외']} rows={d.research100.rows}/><p>{d.research100.verdict}</p></section>
 <section id="implementation-metrics" tabIndex={-1}><h4>기대효과 5개 범주 · 측정 방법과 해석 한계</h4><p className="analysis-limit">현재 기준선·목표값·표본 수·실측 효과 미확정. A 현행 / B 정형 개선 / C B+NOA를 동일 사건에서 비교. 검수·재작업을 포함하고 오류 증가 여부를 함께 판단.</p>{d.metrics.map(m=><section key={m.id} className="implementation-metric" data-implementation-metric={m.id}><h5>{m.id} · {m.name}</h5><Fields rows={[["산식·단위",m.formula],["수집 기록",m.data],["측정 방법",m.method],["해석 제한",m.boundary]]}/></section>)}<h5>대가·투입량의 공통과 차분</h5><Table title="산정할 작업과 현재 미확정 입력" headers={['구분','산정 경계']} rows={d.procurement}/><Table title="검증에서 RFP·제한 운영으로 넘어가는 관문" headers={['관문','확보할 증거','축소·보류 판단']} rows={d.gates}/></section>
 <section id="implementation-feedback" tabIndex={-1}><h4>처별 인터뷰 준비·현업 확인</h4><InterviewPlan/><details><summary>이전 공통 확인 질문 14개 · 2026-10-03 참조</summary><p>현재 발송·회신 없음. 담당자에게 요청할 질문과 증거를 준비한 상태. 빈 응답은 수락·자료 제공확약·승인을 의미하지 않음. 최신 처별 계획은 현업 공통·처별·전문 담당 보충으로 구분.</p><Table title="현업·CCK 개발팀의 14개 확인 질문" headers={['질문·확인대상','확인할 내용','받아야 할 증거']} rows={d.questions.map(q=>[q.id+' · '+q.owner,q.question,q.evidence])}/></details></section>
 <section id="implementation-sources" tabIndex={-1}><h4>이번 재조사의 공식 출처</h4>{d.sources.map(s=><section className="implementation-source" key={s.id} id={'implementation-source-'+s.id}><h5>{s.id} · <Out url={s.url}>{s.title}</Out></h5><small>게시 {s.published} · 확인 {s.checkedAt} · {s.locator}</small><Fields rows={[["확인한 사실",s.fact],["근거 사용 한계",s.limit]]}/>{s.artifact&&<details><summary>다운로드 원문·해시·변환 범위</summary>{s.artifact.url&&<Out url={s.artifact.url}>공식 첨부 원문 다운로드 ↗</Out>}<p>{s.artifact.name} · {s.artifact.bytes.toLocaleString()} bytes</p><code>{s.artifact.sha256}</code><p>{s.artifact.method}</p></details>}</section>)}</section>
 <p className="analysis-limit">{d.documentNote}</p><p><a href="#analysis-platform">이전 공통 설계·근거 검토 계속 보기 ↓</a></p>
 </section>}
