import React from 'react';
import {Link,Out} from './core.jsx';
import d from './interview-plan.cjs';
import './interview-plan.css';
function Table({title,headers,rows}){return <div className="interview-table" role="region" aria-label={title} tabIndex={0}><table><caption>{title}</caption><thead><tr>{headers.map(h=><th scope="col" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=>j===0?<th scope="row" key={j}>{v}</th>:<td key={j}>{v}</td>)}</tr>)}</tbody></table></div>}
function Question({q,decision}){return <article className="interview-question" data-interview-question={q.id}><header><b>{q.id}</b><span>{q.priority||q.purpose||'전문 보충'}</span></header><p>{q.question}</p><dl><div><dt>근거 후보</dt><dd>{q.evidence}</dd></div>{decision&&<div><dt>편성 연결</dt><dd>{decision}</dd></div>}</dl></article>}
export function InterviewPlan(){return <section id="implementation-interview-plan" className="interview-plan" data-interview-plan={d.version} tabIndex={-1}>
 <header><small>{d.date} · {d.version} · 2027년 ISP 수요조사 준비</small><h5>{d.title}</h5><p>{d.status}</p><p>{d.method}</p></header>
 <div className="interview-counts">{[['작성 처',d.counts.mapped],['기존 기획항목',d.counts.existingProjects],['추가 후보',d.counts.additionalCandidates],['미매핑 처',d.counts.discoveryDepartments]].map(([label,value])=><div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div>
 <p className="analysis-limit">{d.scope} 공통 12문항·처/주제별 165문항·전문 보충 20문항의 고유 질문 설계. 전체 문항을 한 면담에 일괄 적용하는 방식 아님.</p><p className="interview-boundary">{d.entryRule}</p>
 <p className="analysis-downloads">{d.downloads.map(([label,to])=><Link key={to} to={to} download>{label} ↓</Link>)}</p>
 <nav className="interview-jumps" aria-label="인터뷰 준비 본문"><a href="#interview-steps">준비 순서</a><a href="#interview-common">공통 질문</a><a href="#interview-departments">51처 찾기</a><a href="#interview-specialists">전문 보충</a><a href="#interview-records">사례·회신·RFP</a></nav>
 <section id="interview-steps" tabIndex={-1}><h6>준비 순서·완료 조건</h6><Table title="업무 확인부터 질문지·RFP 입력까지" headers={['단계','응답/검토 역할 후보','준비할 결과','범위·보류 조건']} rows={d.phases}/><details><summary>가정·기술 제약 확인</summary><ul>{d.assumptions.map(v=><li key={v}>{v}</li>)}</ul><ul>{d.constraints.map(v=><li key={v}>{v}</li>)}</ul></details></section>
 <section id="interview-common" tabIndex={-1}><h6>현업 공통 12문항</h6><p>업무·실사례·기존 대응부터 확인. 핵심 6문항과 실제 한 건을 먼저 복원하고, 후속 문항은 서면 또는 추가 확인으로 진행하는 준비안. 45~60분은 설계 가정이며 면담 일정·참여자 미합의.</p><div className="interview-questions">{d.common.map(q=><Question key={q.id} q={q} decision={q.decision}/>)}</div></section>
 <section id="interview-departments" tabIndex={-1}><h6>처별 찾기·질문 묶음</h6><p>기존 39처는 계획 가설을 검증하고, KATRI 미매핑 12처는 실제 분장부터 확인. 모빌리티연구처·자격교육처·철도안전처·철도승인처의 복수 주제는 분리 기록.</p>{[['headquarters','본사 38처'],['katri','자동차안전연구원 13처']].map(([scope,label])=><div key={scope}><h6>{label}</h6><ul className="interview-directory">{d.departments.filter(r=>r.scope===scope).map(r=><li key={r.id}><a href={'#'+r.anchor}>{r.name}<small>{r.projectIds.length?'계획 검증':'업무 발견'}</small></a></li>)}</ul></div>)}
 {d.departments.map(r=><section key={r.id} className="interview-department" data-interview-department={r.id}><details><summary><span>{r.name} <small>{r.id}</small></span><span>{r.mode} · {r.topics.length}개 주제</span></summary><div id={r.anchor} tabIndex={-1} className="interview-department-body"><h6 className="interview-body-title">{r.name} · 확인 질문</h6><p><b>조직 대조</b> {r.parent} · {r.sourceId} · 실제 분장/전결 확인 필요</p><p><b>응답 역할 후보</b> {r.roles.join(' · ')}</p><p className="analysis-downloads">{r.downloads.map(([label,to])=><Link key={to} to={to} download>{label} ↓</Link>)}{r.documentsRoute&&<Link to={r.documentsRoute}>기존 한글 3종 ↗</Link>}{r.proposalRoute&&<Link to={r.proposalRoute}>사업 정의·설계 ↗</Link>}</p>
 {r.topics.map(t=><section className="interview-topic" data-interview-topic={t.id} key={t.id}><h6>{t.id} · {t.discovery?'업무 발견':t.id==='QE-H01'?'추가 후보':'기존 가설 검증'}</h6><p>응답 역할 후보: {t.roles.join(' · ')}</p>{t.questions.map(q=><Question key={q.id} q={q}/>)}<p className="interview-boundary"><b>답변에 따른 기획 판단</b> {t.decision}</p></section>)}
 <details className="interview-source-list"><summary>이 처의 기존 근거·확인일 보기 ({r.sources.length}건)</summary><p>{d.sourceNote}</p>{r.sources.map(s=><p key={s.id+'-'+s.url}><Out url={s.url}>{s.id} · {s.title}</Out><small>게시/시행 {s.published||s.effective||'미표시'} · 확인 {s.checkedAt||s.accessed||s.date||'미확인'} · {s.scope||s.limit||s.verification_scope||s.note||'기존 원장의 확인범위 참조'}</small></p>)}</details></div></details></section>)}
 </section>
 <section id="interview-specialists" tabIndex={-1}><h6>공통 전문 담당 보충지 5종</h6><p>제품·서버·API·계약 확인을 모든 처의 현업에게 반복하지 않고 공통 담당자가 답변. 처별 회신은 아래 ID의 확인결과와 연결.</p>{d.specialists.map(s=><details key={s.id} className="interview-specialist" data-interview-specialist={s.id}><summary>{s.id} · {s.title}</summary><p>응답 역할 후보: {s.roles.join(' · ')}</p>{s.questions.map(q=><Question key={q.id} q={q}/>)}<p className="analysis-limit">{s.boundary}</p></details>)}<h6>처 수와 구분할 지역·센터·팀·외부 인계</h6><ul>{d.regionalTypes.map(r=><li key={r.id}>{r.name}: {r.note}</li>)}{d.supplementary.map(r=><li key={r.type}><b>{r.type}</b>: {r.names.join(' · ')}. {r.note}</li>)}</ul></section>
 <section id="interview-records" tabIndex={-1}><h6>실제 사건·회신 상태·후속 편성</h6><p>실제 제공 가능한 한 건을 먼저 분석. 네 유형을 전부 요구하거나 없는 사례를 합성해 실제 기록으로 표시하지 않음.</p><Table title="실제 사건카드에 기록할 항목" headers={['필드','복원 내용']} rows={d.caseFields}/><h6>상태 축의 분리</h6><dl className="interview-states">{Object.entries(d.states).map(([key,values],i)=><div key={key}><dt>{['요청·회신','근거 확인','자료 가용','기획 판단'][i]}</dt><dd>{values.join(' / ')}</dd></div>)}</dl><p className="interview-boundary">{d.privacy}</p><Table title="회신에서 요구사항·인수·대가 입력으로 연결" headers={['구분','질문ID','확보할 입력','후속 산출물']} rows={d.handoff}/><details><summary>P01~P07 기획기준 연결</summary><Table title="기획 원칙과 질문의 대응" headers={['원칙','적용']} rows={d.principles}/></details><p className="analysis-limit">공고 미매핑 기획 초안. 현업 수요·효과·표본·FP·MM·가격·데이터/연계 권한 미확정. 현재 공개 자료는 빈 질문지 준비안이며 실제 인터뷰 수행 결과 없음.</p></section>
 </section>}
