import React,{useEffect,useRef,useState} from 'react';
import {Menu,Search,ArrowUp,FileText} from 'lucide-react';
import {Link,ReadingLinkContext,navigate,legal,href} from './core.jsx';
import reading from './integrated-reading.cjs';
import hub from './planning-hub.cjs';
import survey from './survey-design.cjs';
import supplement from './proposal-links.cjs';
import {DocumentReader} from './DocumentReader.jsx';
import {Proposal47} from './Revision47.jsx';
import {Profile} from './ProposalLinks.jsx';
import {DrtAssurance} from './DrtAssurance.jsx';
import {IspReview} from './IspReview.jsx';
import {CostReview} from './CostReview.jsx';
import {SkillPms} from './SkillPms.jsx';
import {Topic,SurveyOpinion} from './SurveyDesign.jsx';
import {DepartmentDocuments} from './DepartmentDocuments.jsx';
import './integrated-reading.css';
import {IntentDefinitions} from './ProposalIntent.jsx';
import {MandateWorkContext} from './MandateWorkContext.jsx';
import {SiteHeader} from './SiteNavigation.jsx';
import readerUI from './reader-ui.cjs';
import intent from './proposal-intent.cjs';
const l=reading.labels;
export function IntegratedHeader({route,navigationEpoch}){return <SiteHeader compact route={route} navigationEpoch={navigationEpoch}/>;}
function Chapter({section,children}){return <section className="integrated-chapter" id={section.id} tabIndex={-1} data-integrated-section={section.id}><header><span>{String(reading.sections.indexOf(section)+1).padStart(2,'0')}</span><div><h2>{section.title}</h2><p>{section.intro}</p></div></header>{children}</section>}
export function IntegratedReader({route}){
 const current=reading.selection(new URL(route,'https://reader/').search),{department:r,project:p}=current,topic=survey.departments.find(d=>d.id===r.surveyId),project=hub.projects.find(x=>x.id===p?.id),profile=p? supplement.profileById[new URL(p.to,'https://reader/').searchParams.get('unit')]:null;
 const[pendingProject,setPendingProject]=useState(p?.id||''),[pending,setPending]=useState(r.key),[q,setQ]=useState(''),[menu,setMenu]=useState(false),[active,setActive]=useState(reading.sections[0].id),button=useRef(),root=useRef();const words=q.trim().toLowerCase().split(/\s+/).filter(Boolean),rows=reading.rows.filter(r=>words.every(w=>[r.name,r.parent,...r.projects.map(p=>p.title)].join(' ').toLowerCase().includes(w))),parents=[...new Set(rows.map(r=>r.parent))];
 const resolve=to=>reading.resolve(to,current);
 useEffect(()=>{setPending(r.key);setPendingProject(p?.id||'')},[r.key,p?.id]);
 const pendingRow=reading.rows.find(x=>x.key===pending);
 function choose(key,projectId){const next=reading.rows.find(r=>r.key===key);if(!next)return;const params=new URLSearchParams({dept:next.key});if(projectId)params.set('project',projectId);navigate('index.html?'+params+'#integrated-work-context');}
 useEffect(()=>{let frame,second;function reveal(){cancelAnimationFrame(frame);cancelAnimationFrame(second);frame=requestAnimationFrame(()=>{second=requestAnimationFrame(()=>{let id;try{id=decodeURIComponent(location.hash.slice(1))}catch{return}if(!id)return;const target=document.getElementById(id);if(!target)return;for(let el=target.parentElement;el;el=el.parentElement)if(el.tagName==='DETAILS')el.open=true;target.setAttribute('tabindex','-1');target.scrollIntoView({block:'start'});target.focus({preventScroll:true});setMenu(false)})})}reveal();addEventListener('hashchange',reveal);return()=>{cancelAnimationFrame(frame);cancelAnimationFrame(second);removeEventListener('hashchange',reveal)}},[route]);
 useEffect(()=>{let frame;function scroll(){cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{const top=(document.querySelector('.ts-header')?.getBoundingClientRect().height||70)+24;let id=reading.sections[0].id;for(const s of reading.sections){const el=document.getElementById(s.id);if(el&&el.getBoundingClientRect().top<=top)id=s.id;}setActive(id)})}addEventListener('scroll',scroll,{passive:true});scroll();return()=>{cancelAnimationFrame(frame);removeEventListener('scroll',scroll)}},[]);
 function jump(e,id){if(e.ctrlKey||e.metaKey||e.shiftKey||e.altKey)return;e.preventDefault();const u=new URL(location.href);u.hash=id;history.pushState({},'',u);dispatchEvent(new PopStateEvent('popstate'));setMenu(false);}
 return <ReadingLinkContext.Provider value={resolve}><article className="integrated-reader" ref={root} data-integrated-reader={reading.date}>
 <aside className="integrated-sidebar" onKeyDown={e=>{if(e.key==='Escape'){setMenu(false);button.current?.focus()}}}><button ref={button} className="integrated-menu-toggle" aria-expanded={menu} aria-controls="integrated-outline" onClick={()=>setMenu(!menu)}><Menu size={18}/>본문 목차 · {r.name}</button><nav id="integrated-outline" className={menu?'open':''} aria-label="통합 본문 목차"><strong>하나의 흐름으로 읽기</strong>{reading.sections.map((s,i)=><a key={s.id} href={'#'+s.id} aria-current={active===s.id?'location':undefined} onClick={e=>jump(e,s.id)}><span>{String(i+1).padStart(2,'0')}</span>{s.title}</a>)}<div className="integrated-current"><small>현재 선택 · 담당 업무·검토방향</small><b>{r.name}</b><p>{topic?.reading.goal||r.goal}</p><a href="#integrated-start" onClick={e=>jump(e,'integrated-start')}>담당 처 변경</a></div><a className="integrated-top" href="#integrated-start" onClick={e=>jump(e,'integrated-start')}><ArrowUp size={14}/>본문 처음으로</a></nav></aside>
 <div className="integrated-content"><header className="integrated-intro" id="integrated-start" tabIndex={-1}><small>2027년 후속사업기획 · 통합 읽기</small><h1>{l.title}</h1><p>{l.lead}</p><p className="integrated-status">{l.status}</p></header><form className="integrated-selector reader-selection" aria-label="처·과제 선택" onSubmit={e=>{e.preventDefault();choose(pending,pendingProject)}}><div><label htmlFor="integrated-department-search"><Search size={15}/>처·업무 찾기</label><input id="integrated-department-search" type="search" value={q} onChange={e=>setQ(e.target.value)} placeholder="예: 모빌리티, 철도, 자격"/></div><div><label htmlFor="integrated-department-select">{l.pick}</label><select id="integrated-department-select" value={pending} onChange={e=>{setPending(e.target.value);setPendingProject(reading.rows.find(x=>x.key===e.target.value)?.projects[0]?.id||'')}}>{!rows.some(x=>x.key===pending)&&<option value={pending}>{reading.rows.find(x=>x.key===pending)?.name} · 선택 대기</option>}{parents.map(parent=><optgroup key={parent} label={parent}>{rows.filter(x=>x.parent===parent).map(x=><option key={x.key} value={x.key}>{x.name}{x.code?'':' · 수요 탐색'}</option>)}</optgroup>)}</select></div><div><label htmlFor="integrated-project-select">검토 과제</label><select id="integrated-project-select" value={pendingProject} onChange={e=>setPendingProject(e.target.value)} disabled={!pendingRow?.projects.length}>{pendingRow?.projects.length?pendingRow.projects.map(x=><option key={x.id} value={x.id}>{x.title}</option>):<option value="">계획서 미작성 · 수요 탐색</option>}</select></div><button className="reader-apply" type="submit">{readerUI.labels.apply}</button><p role="status">{rows.length}개 조사 대상 조직 · 현재 {r.name} · {r.projects.length?r.projects.length+'개 과제':'계획서 미작성'}{pending!==r.key||pendingProject!==(p?.id||'')?' / '+readerUI.labels.pending:''}</p>{!rows.length&&<button type="button" onClick={()=>setQ('')}>검색 초기화</button>}</form>{(current.invalid||current.invalidProject)&&<p className="integrated-warning" role="status">{current.invalid?l.unknown:'이 처에 해당하지 않는 과제입니다. 해당 처의 첫 과제를 표시했습니다.'}</p>}<p className="reader-selection-summary"><b>{p?.title||r.name}</b><span>{p?intent.byId[p.id]?.purpose||readerUI.labels.full:readerUI.labels.noPlan}</span><a href="#integrated-work-context" onClick={e=>jump(e,'integrated-work-context')}>선택 과제 바로 읽기</a></p><IntentDefinitions/>
 <Chapter section={reading.sections[0]}><DocumentReader route="about.html" embedded/></Chapter>
 <Chapter section={reading.sections[1]}><section className="integrated-project-intro"><h3>현재 적용과 추가 제안의 경계</h3>{survey.intro.map(b=><section key={b.id}><h4>{b.title}</h4><p>{b.text}</p><small>{b.status} {b.note}</small></section>)}</section></Chapter>
 <Chapter section={reading.sections[2]}>{!p&&<div id="integrated-work-context" tabIndex={-1}/>}<header className="integrated-department-heading"><small>{r.parent} · 실제 분장·전결 확인 필요</small><h3>{r.name}</h3><p><b>담당 업무·검토방향</b> {topic?.reading.goal||r.goal}</p></header>
 {r.projects.length>1&&<nav className="integrated-project-picker" aria-label="이 처의 검토 과제">{r.projects.map(x=><button key={x.id} aria-pressed={p?.id===x.id} onClick={()=>choose(r.key,x.id)}>{topic?.topics.find(t=>t.id===x.id)?.reading.title||x.title}</button>)}</nav>}
 {p&&<MandateWorkContext projectId={p.id}/>}
 <div className="integrated-proposal" key={p?.id||r.key} data-integrated-project={p?.id||r.key}>{p?.id==='MR-02'?<DrtAssurance route={p.to} embedded/>:profile?<Profile p={profile} embedded/>:r.code&&!r.code.startsWith('EX')?<Proposal47 code={r.code} embedded/>:topic?<><p className="integrated-warning">{l.missing}</p>{topic.topics.map((t,i)=><Topic key={t.id} t={t} first={i===0} index={i} includeOpinion={false}/>)}</>:<p>{l.missing}</p>}</div>
 <section id="integrated-feasibility" tabIndex={-1}><h3>이 과제의 현재 구현·편성 조건</h3>{project?<dl className="integrated-fields">{[['현재 상태',project.classificationLabel+' · '+project.classificationDate+' / '+project.status],['초기 범위',project.scope],['필요한 입력',project.inputs],['공식 판단 경계',project.decisionBoundary],['착수 조건',project.entry],['완료·인수 기준',project.acceptance],['제외·보류 조건',project.boundary],['기준선·수치 목표·가격','현재 기준선·수치 목표·최종 수행가격 미확정. 앞의 측정방법으로 원기록 확보 후 확인.']].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{Array.isArray(v)?v.join(' / '):v}</dd></div>)}</dl>:<p>{l.missing}</p>}</section></Chapter>
 <Chapter section={reading.sections[3]}><SkillPms embedded/></Chapter>
 <Chapter section={reading.sections[4]}><IspReview embedded/><CostReview/></Chapter>
 <Chapter section={reading.sections[5]}><SurveyOpinion key={r.key+'-'+p?.id} departmentId={r.surveyId} projectId={current.topicId} onTopic={id=>{const params=new URLSearchParams({dept:r.key});if(p)params.set("project",p.id);params.set("topic",id);navigate("index.html?"+params+"#survey-topic-"+id+"-opinion")}}/><section id="integrated-documents" tabIndex={-1}><h3>{r.name} · 관련 한글 문서</h3>{r.code?<DepartmentDocuments code={r.code}/>:<p>{l.missing}</p>}</section><section className="integrated-references"><h3>출처와 보존 자료</h3><p>핵심 근거는 앞의 해당 설명 옆에 표시. 아래 자료는 공식 원문·전체 조사·이전 설계를 확인할 보조 경로.</p><ul>{legal.sources.filter(s=>['foundation'].includes(s.id)).map(s=><li key={s.id}><a href={s.url} target="_blank" rel="noopener noreferrer">{s.name}</a> · {s.effective}</li>)}</ul><details><summary>전체 자료실·기존 독립 문서 확인</summary><p>최신 선택 처의 본문과 문서는 위에서 이어 확인. 아래 경로는 전체 원장·뉴스·이전 판본 대조용.</p><a href={href('research-library.html')}>조사자료실</a><a href={href('planning-documents.html')}>전체 처별 한글 자료</a><a href={href('index.html?view=map')}>조직 연결지도</a><a href={href('index.html?view=overview')}>이전 기획 목록</a></details></section></Chapter>
 </div></article></ReadingLinkContext.Provider>
}
