import React,{useState}from'react';
import{ArrowRight,ArrowUpRight,FileCheck2,Files,Globe2}from'lucide-react';
import{Heading,Link,Out,Badge,navigate}from'./core.jsx';
import data from'./katri.json';import'./katri.css';
const icons=[FileCheck2,Files,Globe2];
export function Katri(){const[index]=useState(()=>Math.max(0,data.cards.findIndex(c=>c.id===new URLSearchParams(location.search).get("case")))),c=data.cards[index];return <div className="page katri-page">
<Heading label="KATRI · 자동차안전연구원" title={<>검토할 자료의 누락을 줄이고,<br/>전문가의 판단을 더 충실하게.</>} desc="자료 수집부터 문서 1차 검토·보완 재검토까지 연결하는 CCK 기반 AX 제안."><Link className="button outline" to="downloads/KATRI_문서1차검토_AX_검토.md" download>검토안 내려받기 <ArrowUpRight size={18}/></Link></Heading>
<section className="katri-intro"><div><Badge>공개 업무 확인 · 추가 적용 설계</Badge><h2>자료 전체를 읽는 준비부터<br/>근거를 확인하는 검토로.</h2><p>{data.message}</p></div><div className="katri-proof"><span>공식 안내에서 확인한 출발점</span><strong>기술검토의 서류 확인<br/>안전검사의 조건별 제출자료</strong><p>후속 제원통보 자료의 사전 준비를 통한 재방문 방지 안내.</p><Out url={data.sources[1].url}>KATRI 안전검사 안내</Out></div></section>
<div className="katri-context"><span>기획 원칙</span><p>{data.boundaries}</p></div>
<section aria-labelledby="katri-applications"><div className="section-top"><div><span className="eyebrow">업무별 적용</span><h2 id="katri-applications">공통 검토 방식, 서로 다른 업무 기준.</h2></div><span className="muted">세 영역의 상세 내용 탐색</span></div>
<div className="katri-tabs" aria-label="KATRI 적용 영역">{data.cards.map((x,i)=>{const I=icons[i];return <button key={x.id} onClick={()=>navigate("katri.html?case="+x.id)} aria-pressed={i===index} aria-controls="katri-case" className={i===index?'active':''}><I size={25}/><span>{x.id}<strong>{x.name}</strong></span><ArrowUpRight size={19}/></button>})}</div>
<article id="katri-case" className="katri-case" key={c.id}><div className="katri-case-title"><div><span className="mini-label">{c.org}</span><h2>{c.goal}</h2></div>{c.first&&<Badge>우선 실증 후보</Badge>}</div><p className="katri-fact"><b>확인한 업무</b>{c.fact}</p>
<div className="katri-columns"><div><span className="katri-number">01</span><h3>검토에 필요한 자료</h3><ul>{c.input.map(t=><li key={t}>{t}</li>)}</ul></div><div><span className="katri-number">02</span><h3>AI·검증도구의 1차 검토</h3><ul>{c.check.map(t=><li key={t}>{t}</li>)}</ul></div><div><span className="katri-number">03</span><h3>담당자 검토·인계</h3><p>{c.output}</p><h4>전문가의 책임</h4><p>{c.human}</p></div></div>
<div className="katri-detail-link"><Link className="button outline" to={"architecture.html?unit="+c.id}>이 업무의 상세 아키텍처 <ArrowRight size={17}/></Link><p>구성요소 · 연계 계약 · 데이터 · 배치·복구 · RFP 추적</p></div><div className="katri-delta"><div><h3>기존 기반 활용</h3><p>{c.reuse}</p></div><div><h3>추가 개발의 가치</h3><p>{c.delta}</p></div></div><div className="katri-ref">{c.refs.map(id=>{const s=data.sources.find(s=>s.id===id);return <Out key={id} url={s.url}>{s.title}</Out>})}</div></article></section>
<section className="katri-section"><div className="section-top"><div><span className="eyebrow">서비스 흐름</span><h2>한 번의 요약에서 끝나지 않는 검토.</h2></div></div><ol className="katri-flow">{data.flow.map(([t,p],i)=><li key={t}><span>{String(i+1).padStart(2,'0')}</span><h3>{t}</h3><p>{p}</p>{i<5&&<ArrowRight aria-hidden="true"/>}</li>)}</ol>
<div className="katri-architecture" aria-label="기능별 구성안">{data.architecture.map(([t,p,n])=><div key={t}><span>{t}</span><strong>{p}</strong><small>{n}</small></div>)}</div></section>
<section className="katri-example katri-section"><div className="section-top"><div><span className="eyebrow">담당자가 받는 검토 결과</span><h2>‘어디를 왜 확인할지’가 보이는 쟁점 목록.</h2></div><Badge>설명용 예시</Badge></div><p className="katri-example-note">{data.example.label}</p><h3>{data.example.case}</h3><div className="katri-review-list">{data.example.items.map(([f,v,s,n])=><article key={f}><div><h4>{f}</h4><span className="katri-state">{s}</span></div><p><span>대조 결과</span>{v}</p><p><span>다음 확인</span>{n}</p></article>)}</div><p className="katri-record"><b>쟁점별 기록 항목</b>{data.example.record}</p><p className="note">자료가 보이지 않는 상태와 실제 미제출의 구분. AI가 표시하지 않은 부분에도 필수 전문검토 적용.</p></section>
<section className="katri-section"><div className="section-top"><div><span className="eyebrow">효과 검증</span><h2>누락과 재작업의 변화로 판단.</h2></div><Badge>핵심 지표 4개</Badge></div><p>{data.why}</p><div className="katri-metrics">{data.metrics.map(([t,f,n],i)=><article key={t}><span>0{i+1}</span><h3>{t}</h3><strong>{f}</strong><p>{n}</p></article>)}</div><p className="note">{data.validation}</p></section>
<section className="katri-section"><div className="section-top"><div><span className="eyebrow">적용 순서</span><h2>자동차인증처 한 유형부터 검증.</h2></div></div><div className="katri-pilot">{data.pilot.map(([t,p])=><article key={t}><h3>{t}</h3><p>{p}</p></article>)}</div><details className="katri-detail"><summary>검토 경계와 현업 확인사항</summary><ul>{data.guardrails.map(t=><li key={t}>{t}</li>)}</ul><h3>현업 협의 질문</h3><ul>{data.questions.map(t=><li key={t}>{t}</li>)}</ul></details></section>
<section className="katri-section"><div className="section-top"><div><span className="eyebrow">공식 근거</span><h2>업무 확인과 적용 제안의 구분.</h2></div><span className="muted">조사일 {data.date}</span></div><div className="katri-sources">{data.sources.map(s=><details key={s.id}><summary>{s.id} · {s.title}</summary><p>{s.finding}</p><Out url={s.url}>공식 업무안내 원문</Out></details>)}</div><p className="micro">{data.status}</p><Link className="inline-link" to="solutions.html">조직별 AX 서비스로 <ArrowRight size={18}/></Link></section>
</div>}