import React from 'react';
import {Link,Out} from './core.jsx';
import connections from './law-department-connections.cjs';
import planning from './problem-planning.cjs';
import official from './official-duty-research.cjs';
import katri from './katri-solution-expansion.cjs';

export function DepartmentOwners({binding:b}){const refs=connections.ownerRefsByBinding[b.id]||[];return <div className="law-owner-links" data-owner-binding={b.id}>{refs.length?refs.map(o=><div key={o.key} data-owner-key={o.key}><Link to={connections.departmentTo(o.key,b.id)}>{o.name}</Link><span>{o.duty}</span><small>{o.status}</small></div>):<div className="law-owner-pending"><strong>{b.owner}</strong><span>{b.ownerRole}</span><small>담당 처 직접 연결 보류 · 실제 분장 추가 확인. 제안 주관처로 수행처를 대체하지 않은 상태.</small></div>}</div>}
export function DepartmentOwnerEvidence({bindingId}){const refs=connections.ownerRefsByBinding[bindingId]||[];return <div className="law-owner-evidence">{refs.map(o=><section key={o.key}><h5>{o.name} · {o.duty}</h5><p>{o.role} / {o.status}</p>{o.observations.length?<ul>{o.observations.map(x=><li key={x.id}>{x.text} <Out url={x.url}>직원검색 {x.refs.map(r=>r.page+'쪽 '+r.row+'행').join(' · ')}</Out></li>)}</ul>:<p>관련 문구의 직접 대조 추가 필요. 조직명만으로 이 업무의 권한 확정 불가.</p>}<small>공개 담당업무 확인 {official.date} · 법령상 위탁·내부 전결·사건 배정의 확정 근거와 별도.</small></section>)}</div>}
export function AdditionalLawDuty({duty:a}){return <article className="law-additional-duty" data-additional-duty={a.id}><h3>{a.task}</h3><dl className="work-fields">{[['법령·조문',a.law],['기관 수행·권한 관계',a.authority],['관련 처·담당업무',a.owner.name+' · '+a.owner.duty],['연결 범위',a.boundary]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><Link className="law-owner-direct" to={connections.departmentTo(a.key)}>{a.owner.name}의 현행 업무·제안 보기</Link><div className="law-source-list">{a.sourceIds.map(id=>{const s=connections.additionalSources.find(s=>s.id===id);return <p key={id}><Out url={s.url}>{s.title}</Out><small>{s.published} · 직접 확인 {s.checkedAt}</small><span>{s.claim}</span><small>{s.limit}</small></p>})}{a.owner.sourceRefs.map(s=><p key={s.url}><Out url={s.url}>{s.title}</Out><small>담당업무 대조 {s.checkedAt} · {s.scope}</small></p>)}</div><nav aria-label={a.task+' 관련 제안'}>{a.projectIds.map(id=>{const p=connections.proposalById[id];return <Link key={id} to={p.to}>{p.department} · {id} · {p.title}</Link>})}</nav></article>}

export function LawDepartmentContext({department:d,project:p,bindingId}){if(!d)return null;const candidate=p&&katri.byId[p.id],theme=p&&planning.themes.find(t=>t.id===p.themeId);return <section id="mandate-department-context" className="law-department-context" data-law-department={d.key} tabIndex={-1}>
 <header><span>선택한 담당 처 · 공식 업무와 기획 적용관계</span><h2 id="mandate-title">{d.name}</h2><p>{d.path}</p>{p?<p className="law-selected-proposal">관련 제안 · {p.id} · {p.title}</p>:<p>처의 현행 업무 표시 · 연결할 제안은 아래에서 재선택.</p>}</header>
 <ol className="law-department-chain" aria-label="담당 처에서 법령과 제안까지 연결"><li><span>업무 근거</span><strong>{d.duties.length?d.duties.map(b=>b.law.title).join(' / '):d.additional.length?'KATRI 공식 업무안내·관련 조문':'개별 법령·수행 관계 추가 확인'}</strong></li><li><span>담당 처</span><strong>{d.name}</strong></li><li><span>현행 수행업무</span><strong>공식 직원검색 담당업무</strong></li><li><span>해결할 목적</span><strong>{p?.purpose||'관련 제안 선택 후 목적 확인'}</strong></li><li><span>구현 방법</span><strong>{p?.how||'법령·업무와 일치하는 추가 범위 검토'}</strong></li></ol>
 <section className="law-department-duties"><h3>공식 검색에 기재된 담당업무</h3><p>TS 공식 직원검색 기재내용 · 확인 {official.date}. 내부 위임전결·전체 업무분장의 확정과 구분.</p>{d.records.map(r=><section key={r.code}><ul>{r.observations.map(o=><li key={o.id} data-duty-observation={o.id}>{o.text}{o.reviewNotes.map(n=><small key={n.unitId} className="law-duty-review" data-duty-review={o.id}><b>{n.scopeReview?'현재 업무 확정 유보':'수행주체·기간 확인'}</b> · {n.note}</small>)}</li>)}</ul><Out url={r.sourceUrl}>공식 담당업무 확인 · {r.path}</Out><small>직원명·전화번호 제외. 원문 오탈자를 포함한 업무 기재 사실과 이번 제안 해석의 구분.</small></section>)}{!d.records.length&&<p className="work-notice">직접 대조 가능한 공개 담당업무 추가 확인 필요.</p>}</section>
 <section className="law-department-basis"><h3>현행 업무와 관련 법령의 연결</h3>{d.duties.length?d.duties.map(b=>{const owner=b.ownerRefs.find(o=>o.key===d.key);return <article key={b.id} data-department-binding={b.id} data-selected-binding={bindingId===b.id||undefined}><h4>{owner.duty}</h4><p><b>관련 법정업무</b> {b.task}</p><p><b>법령</b> {b.law.law}</p><p><b>원 권한·의뢰 주체</b> {b.law.principal} / {b.law.mode}</p><p><b>처 연결 근거</b> {owner.role} / {owner.status}</p><p><b>권한 경계</b> {b.law.boundary}</p><Link to={'legal/mapping.html?mode=law&law='+b.lawId+'#mandate-binding-'+b.id}>이 업무의 법령·담당 처·제안 연결표 보기</Link></article>;}):!d.additional.length&&<p className="work-notice">이 처의 담당업무는 확인되었으나, 현재 27개 대표 법정업무에서 개별 수행 관계가 연결되지 않은 상태. 업무가 없거나 법적 근거가 없다는 의미가 아니며, 설립법·개별 지정·위탁문서·협약·사규와 내부 분장 추가 확인 대상.</p>}{d.additional.map(a=><AdditionalLawDuty key={a.id} duty={a}/>)}
 {d.related.length>0&&<div className="law-related-context"><h4>제안 검토에 참고하는 다른 수행 관계</h4><p>아래는 이 처를 실제 수행처로 확인한 관계와 별도. 정책·조사 맥락, 기존 시스템 접점 등 관계별 설명 유지.</p>{d.related.map(b=><p key={b.id}><Link to={'legal/mapping.html?mode=law&law='+b.lawId+'#mandate-binding-'+b.id}>{b.task}</Link> · {b.projects.filter(p=>p.departmentKey===d.key).map(p=>p.relation.type+' / '+p.relation.reason).join(' · ')}</p>)}</div>}</section>
 <section className="law-department-proposals"><h3>{p?'현행 업무에서 이어지는 문제·솔루션 제안':'이 처의 추가 설계 후보 · 개별 업무와 연결 검토'}</h3>{p&&<><p><b>목적</b> {p.purpose}</p><p><b>CCK 적용 방법</b> {p.how}</p>{theme&&<p><b>관련 문제</b> <Link to={'index.html?view=problems#problem-'+theme.id}>{theme.title}</Link></p>}<small>{candidate?'KATRI 추가 설계 후보 등록 · 처별 한글 계획서·대가산정·첨부문서 3종 미작성':'기존 계획서·추가 설계 제안 · 해당 문서의 작성·검증 상태에서 확인'}. 법적 권한과 발주범위 확정 전 검토안.</small></>}{!p&&<p>아래는 이 처의 전체 제안 목록. 방금 선택한 법정업무에 모두 직접 적용되는 의미와 구분. 개별 후보 선택 후 해당 업무와의 적용관계 확인.</p>}{d.proposals.map(x=><Link key={x.id} data-law-proposal={x.id} to={x.to}>{x.department} · {x.id} · {x.title} · 전체 설계 이어 읽기</Link>)}{p&&!candidate&&<Link to={p.documentsTo}>선택한 처의 한글 계획서·첨부문서 확인</Link>}</section>
 </section>}
