import React,{useEffect,useState} from 'react';
import {ArrowRight,ArrowUpRight} from 'lucide-react';
import {Link,legal,navigate} from './core.jsx';
import map from './law-mapping.cjs';
import data from './mandate-workflows.cjs';
import connections from './law-department-connections.cjs';
import {MandateWorkContext,LawBindingContext} from './MandateWorkContext.jsx';
import {DepartmentOwners,LawDepartmentContext,AdditionalLawDuty} from './LawDepartmentContext.jsx';
import './law-mapping.css';
export function MandateSummary({code}){const p=data.projects.find(p=>p.code===code);if(!p)return null;return <section className="mandate-summary"><div><span>법령 → 수행업무 → 목적 → 해결방법</span><h2>{p.intent.department}의 업무와 제안 연결</h2><p>{p.intent.purpose}</p><small>현행 업무·국내외 사례·추가범위·책임의 구분</small></div><Link to={'legal/mapping.html?dept='+code+'&project='+p.id}>업무·법령 연결 보기 <ArrowUpRight size={17}/></Link></section>}
export function LawMapping(){
 const query=new URLSearchParams(location.search),requestedDept=query.get('dept'),requestedProject=query.get('project'),mode=query.get('mode')==='law'?'law':query.get('mode')==='dept'||requestedDept||requestedProject?'dept':'law',selection=connections.selection(location.search),department=selection.department,selected=selection.project,selectedLaw=legal.rows.find(r=>r.id===query.get('law')),invalidLaw=!!query.get('law')&&!selectedLaw;
 const [search,setSearch]=useState(''),[group,setGroup]=useState('all'),[authority,setAuthority]=useState('all'),[pendingDept,setPendingDept]=useState(department?.key||'');
 useEffect(()=>{setPendingDept(department?.key||'')},[department?.key]);
 useEffect(()=>{setSearch('');setGroup('all');setAuthority('all')},[mode]);
 useEffect(()=>{const frame=requestAnimationFrame(()=>{const id=location.hash.slice(1);if(!['mandate-current','mandate-department-context'].includes(id))return;const target=document.getElementById(id);target?.scrollIntoView({block:'start'});target?.focus({preventScroll:true})});return()=>cancelAnimationFrame(frame)},[location.search,location.hash]);
 const words=search.trim().toLowerCase().split(/\s+/).filter(Boolean),rows=connections.matrix.filter(b=>(!selectedLaw||b.lawId===selectedLaw.id)&&(group==='all'||b.law.group===group)&&(authority==='all'||(authority==='local'?/시장|군수|구청장|시·도|시도/.test(b.law.principal):/국토교통부/.test(b.law.principal)))&&words.every(w=>[b.law.title,b.law.law,b.policy,b.law.principal,b.owner,b.task,...b.ownerRefs.map(o=>o.name),...b.projects.map(p=>p.title)].join(' ').toLowerCase().includes(w))),laws=legal.rows.filter(r=>rows.some(b=>b.lawId===r.id)),additional=connections.additionalDuties.filter(a=>!selectedLaw&&group==='all'&&authority!=='local'&&words.every(w=>[a.task,a.law,a.authority,a.owner.name].join(' ').toLowerCase().includes(w)));
 function chooseProject(p){const params=new URLSearchParams({dept:p.departmentKey,project:p.id});if(mode==='law'){params.set('mode','law');if(selectedLaw)params.set('law',selectedLaw.id)}navigate('legal/mapping.html?'+params+(data.forProject(p.id)?'#mandate-current':'#mandate-department-context'));}
 function reset(){setSearch('');setGroup('all');setAuthority('all');if(selectedLaw||invalidLaw)navigate('legal/mapping.html?mode=law')}
 const canReadWorkflow=!!selected&&!!data.forProject(selected.id);
 return <article className="mandate-page" data-mandate-workbench={connections.date}>
 <header className="mandate-heading" id="mandate-start" tabIndex={-1}><span>법령 → 현행 업무 → 담당 처 → 문제·솔루션</span><h1>법령·현행 업무와 담당 처의 연결</h1><p>어떤 법령에 따라 어떤 업무를 수행하며, 어느 처에서 담당하고, 어떤 개선 제안으로 이어지는지 한 흐름에서 확인.</p><div className="mandate-reading-context"><p><b>법령별 보기</b>에서 실제 수행처를 클릭하거나, <b>처별 보기</b>에서 현행 업무·관련 조문·제안을 연속 확인. 원 권한·기관 위탁·처의 담당업무·제안 주관의 구분.</p>{selected&&<Link to={selected.to}>같은 제안의 전체 설계와 문서 이어 읽기 <ArrowRight size={16}/></Link>}</div><div className="mandate-subnav">{department&&<a href="#mandate-department-context">선택한 처의 업무·근거·제안</a>}{canReadWorkflow&&<a href="#mandate-current">선택 과제의 현행 업무·사례</a>}<a href="#mandate-matrix">법령·담당 처 연결표</a><a href="#mandate-coverage">개별 근거 추가 확인 제안</a><Link to="downloads/law-department-connections.md" download>최신 연결 내용 내려받기</Link></div></header>
 <nav className="mandate-modes" aria-label="매핑 탐색 기준"><Link to={department?'legal/mapping.html?dept='+department.key+(selected?'&project='+selected.id:''):'legal/mapping.html?mode=dept'} aria-current={mode==='dept'?'page':undefined}>담당 처·과제로 찾기</Link><Link to="legal/mapping.html?mode=law" aria-current={mode==='law'?'page':undefined}>법령·수행업무로 찾기</Link></nav>
 {(selection.invalidDept||selection.invalidProject||invalidLaw)&&<p className="work-notice" role="status" data-invalid-selection>지정한 처·과제 또는 법정업무를 찾을 수 없어 요청한 연결을 표시하지 않은 상태. 유효한 처의 현행 업무 또는 전체 법령에서 재선택 가능. 무관한 기본 과제로 자동 대체하지 않은 처리.</p>}
 <form className="mandate-selector" onSubmit={e=>{e.preventDefault();const d=connections.forDepartment(pendingDept);if(d)chooseProject(d.proposals[0]);}}><label htmlFor="mandate-dept">검토할 담당 처</label><select id="mandate-dept" value={pendingDept} onChange={e=>setPendingDept(e.target.value)}><option value="">담당 처 선택</option>{connections.departments.map(d=><option key={d.key} value={d.key}>{d.name}</option>)}</select><button type="submit" disabled={!pendingDept}>선택한 처 보기</button><small>51처·54개 제안 탐색 · 기존 27개 대표 법정업무·36개 수행관계 및 추가 4개 업무안내. 전체 업무분장·권한 확정과 구분.</small></form>
 {department?<><LawDepartmentContext department={department} project={selected} bindingId={query.get('binding')}/>{department.proposals.length>1&&<nav className="work-project-picker" aria-label="이 처의 검토 과제">{department.proposals.map(p=><button key={p.id} aria-pressed={selected?.id===p.id} onClick={()=>chooseProject(p)}>{p.id} · {p.title}</button>)}</nav>}</>:mode==='dept'&&<p className="work-notice" role="status">담당 처 선택 후 현행 업무·관련 법령·개선 목적·설계의 연속 확인 가능.</p>}
 {mode==='law'&&<section className="mandate-matrix-section" id="mandate-matrix"><h2>법령·원 권한·현행 업무·담당 처·제안 연결표</h2><p>담당 처의 이름을 클릭하면 해당 처의 실제 업무와 근거·제안으로 이동. 제안 연결은 법적 수행권한을 새로 부여하는 관계와 구분.</p><div className="mandate-law-filters"><label>법령·업무·처 검색<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="예: 앱미터, 결함조사1처, 철도승인처"/></label><label htmlFor="mandate-law-group">법령 분야<select id="mandate-law-group" aria-label="법령 분야" value={group} onChange={e=>setGroup(e.target.value)}><option value="all">전체 분야</option>{legal.groups.map(g=><option key={g.id} value={g.id}>{g.title}</option>)}</select></label><label htmlFor="mandate-authority">원 권한·의뢰 주체<select id="mandate-authority" aria-label="원 권한·의뢰 주체" value={authority} onChange={e=>setAuthority(e.target.value)}><option value="all">전체 주체</option><option value="central">국토교통부 관련</option><option value="local">지자체 관련</option></select></label><span role="status">대표 {laws.length}개 법정업무 · {rows.length}개 수행관계 · 추가 업무안내 {additional.length}개</span><button type="button" onClick={reset}>검색 초기화</button></div>
 {rows.length?<div className="mandate-matrix"><table><caption>법령상 기관 역할과 공개 담당업무의 연결. 담당 처 링크와 제안 링크의 구분.</caption><thead><tr>{['법령·현행 업무','원 권한·수행방식','TS 담당 처·세부업무','관련 제안 · 기획 적용관계'].map(x=><th key={x} scope="col">{x}</th>)}</tr></thead><tbody>{rows.map(b=><tr key={b.id} data-matrix-binding={b.id}><th scope="row"><a href={'#mandate-binding-'+b.id}>{b.law.title}</a><small>{b.law.law}</small><span>{b.task}</span><small>{b.policy}</small></th><td data-label="원 권한·수행방식">{b.law.principal}<small>{b.law.mode}</small></td><td data-label="TS 담당 처·세부업무"><DepartmentOwners binding={b}/></td><td data-label="관련 제안 · 기획 적용관계">{b.projects.length?b.projects.map(p=><button key={p.id} className="mandate-project-link" onClick={()=>chooseProject(p)}>{p.department} · {p.id} · {p.title}<small>{p.relation.type}</small></button>):<span>해당 업무와 개별 제안의 직접 연결 추가 확인</span>}</td></tr>)}</tbody></table></div>:!additional.length&&<p className="mandate-empty" role="status">일치하는 법정업무 없음. 검색 초기화로 전체 목록 복원.</p>}
 {additional.length>0&&<section className="law-additional-list"><h3>추가 확인한 KATRI 업무·법령·담당 처</h3><p>기존 27개 대표업무 외의 공개 업무안내 4건. 자동차인증과 건설기계인증의 별도 업무·조문·예외 확인.</p>{additional.map(a=><AdditionalLawDuty key={a.id} duty={a}/>)}</section>}</section>}
 {canReadWorkflow&&<MandateWorkContext projectId={selected.id} contextId="mandate-current"/>}
 {mode==='dept'&&department&&<section id="mandate-matrix" className="mandate-related-laws"><h2>선택 제안과 법정업무의 적용관계</h2>{selected?.relations.length?selected.relations.map(rel=>{const b=connections.matrix.find(b=>b.id===rel.bindingId);return <section id={'mandate-binding-'+b.id} key={b.id}><h3>{b.task} · {rel.type}</h3><p>{rel.reason}</p><p>{b.law.law}</p><LawBindingContext binding={b} showWorkflow={false}/></section>}):<p className="work-notice">선택 제안의 개별 법령·수행 관계는 추가 확인 대상. 위에 확인한 현행 업무·기관 역할과 새로 제안한 해결방법의 구분.</p>}<Link to="legal/mapping.html?mode=law">전체 법령·담당 처 연결표 보기 <ArrowRight size={16}/></Link></section>}
 {mode==='law'&&<div className="mandate-law-list">{laws.map(r=><article key={r.id}><header><small>{r.id} · {r.mode}</small><h2>{r.title}</h2><p>{r.law}</p><span>제도 소관 · {data.policyForLaw(r)} / 원 권한·의뢰 주체 · {r.principal}</span></header>{rows.filter(b=>b.lawId===r.id).map(b=><section className="mandate-law-duty" id={'mandate-binding-'+b.id} key={b.id}><header><h3>{b.task}</h3><p>{b.ownerRole}</p></header><LawBindingContext binding={b}/></section>)}<footer>{r.boundary}</footer></article>)}</div>}
 <section id="mandate-coverage" className="mandate-coverage"><h2>개별 법령·수행 관계를 추가 확인할 제안</h2><p>아래 {connections.unlinked.length}개는 현재 대표 법정업무·추가 업무안내와 개별 적용관계가 연결되지 않은 제안. 해당 처의 업무가 없다는 판단과 구분. 개별 위탁·지정·협약·사규·내부 분장 확인 대상.</p><div className="mandate-unlinked">{connections.unlinked.map(p=><section key={p.id}><Link to={connections.departmentTo(p.departmentKey)}>{p.department} · 현행 업무·근거 확인</Link><p>{p.id} · {p.title}</p>{data.distinctions[p.id]&&<small>{data.distinctions[p.id]}</small>}<button className="mandate-project-link" onClick={()=>chooseProject(p)}>이 제안의 목적·방법·확인사항 보기</button></section>)}</div></section>
 <footer className="mandate-limits"><p>{connections.limits}</p><p>기존 법령 원장 {map.date}와 현행 처리방식 조사 {data.date}, 공식 담당업무·추가 업무안내 대조 {connections.date}의 구분. 기존 조문 전체의 최신 개정·효력 재검증 완료와 구분.</p><p>KATRI 추가 12처의 설계 후보 등록 완료. 해당 처별 한글 계획서·대가산정·첨부문서 3종 작성은 별도 진행 상태.</p><Link to="downloads/law-department-connections.json" download>최신 처·업무·법령·제안 연결 JSON</Link> · <Link to="downloads/mandate-workflows.md" download>기존 42과제 현행·사례 조사</Link> · <Link to="downloads/law-concept-mapping.md" download>이전 법령 매핑 보존 문서</Link></footer>
 </article>;
}
