import React,{useEffect,useState} from 'react';
import {ArrowRight,ArrowUpRight} from 'lucide-react';
import {Link,legal,navigate} from './core.jsx';
import map from './law-mapping.cjs';
import data from './mandate-workflows.cjs';
import {MandateWorkContext,LawBindingContext,CurrentWorkflow} from './MandateWorkContext.jsx';
import './law-mapping.css';
export function MandateSummary({code}){const p=data.projects.find(p=>p.code===code);if(!p)return null;return <section className="mandate-summary"><div><span>법령 → 수행업무 → 목적 → 해결방법</span><h2>{p.intent.department}의 업무와 제안 연결</h2><p>{p.intent.purpose}</p><small>현행 업무·국내외 사례·추가범위·책임의 구분</small></div><Link to={'legal/mapping.html?dept='+code+'&project='+p.id}>업무·법령 연결 보기 <ArrowUpRight size={17}/></Link></section>}
export function LawMapping(){
 const query=new URLSearchParams(location.search),mode=query.get('mode')==='law'?'law':'dept',requestedDept=query.get('dept'),requestedProject=query.get('project'),departmentProjects=data.projects.filter(p=>p.code===requestedDept),candidate=data.forProject(requestedProject),projectMatches=!!candidate&&(!requestedDept||candidate.code===requestedDept),selected=(projectMatches?candidate:null)||departmentProjects[0]||data.projects[0],invalid=!!requestedProject&&!projectMatches||!!requestedDept&&!departmentProjects.length,selectedLaw=legal.rows.find(r=>r.id===query.get('law')),invalidLaw=!!query.get('law')&&!selectedLaw;
 const [search,setSearch]=useState(''),[group,setGroup]=useState('all'),[authority,setAuthority]=useState('all'),[pendingDept,setPendingDept]=useState(selected.code);
 useEffect(()=>{setPendingDept(selected.code)},[selected.code]);useEffect(()=>{setSearch('');setGroup('all');setAuthority('all')},[mode]);
 useEffect(()=>{const frame=requestAnimationFrame(()=>{if(location.hash!=='#mandate-current')return;const target=document.getElementById('mandate-current');target?.scrollIntoView({block:'start'});target?.focus({preventScroll:true})});return()=>cancelAnimationFrame(frame)},[location.search]);
 const deptRows=[...new Map(data.projects.map(p=>[p.code,{code:p.code,name:p.intent.department}])).values()];
 const words=search.trim().toLowerCase().split(/\s+/).filter(Boolean),rows=data.matrix.filter(b=>(!selectedLaw||b.lawId===selectedLaw.id)&&(group==='all'||b.law.group===group)&&(authority==='all'||(authority==='local'?/시장|군수|구청장|시·도|시도/.test(b.law.principal):/국토교통부/.test(b.law.principal)))&&words.every(w=>[b.law.title,b.law.law,b.policy,b.law.principal,b.owner,b.task,...b.projects.map(p=>p.intent.title)].join(' ').toLowerCase().includes(w))),laws=legal.rows.filter(r=>rows.some(b=>b.lawId===r.id));
 function chooseProject(p){const params=new URLSearchParams({dept:p.code,project:p.id});if(mode==='law'){params.set('mode','law');if(selectedLaw)params.set('law',selectedLaw.id)}navigate('legal/mapping.html?'+params+'#mandate-current');}
 function reset(){setSearch('');setGroup('all');setAuthority('all');if(selectedLaw||invalidLaw)navigate('legal/mapping.html?mode=law')}
 return <article className="mandate-page" data-mandate-workbench={data.date}><header className="mandate-heading" id="mandate-start" tabIndex={-1}><span>법령·조직·현재 업무·국내외 사례</span><h1>{data.labels.heading}</h1><p>{data.labels.lead}</p><div className="mandate-reading-context"><p>중앙부처의 제도 소관, 장관·지자체의 원 권한, TS의 위탁·대행·지정·지원 역할을 분리. 법정업무의 존재와 신규 사업의 필요성을 별도로 검증하고, 처 이름 대신 <b>실제 업무와 과제의 의미</b>를 기준으로 연결.</p><Link to={'index.html?dept='+selected.code+'&project='+selected.id+'#integrated-work-context'}>같은 과제의 전체 설계와 한글 문서까지 이어 읽기 <ArrowRight size={16}/></Link></div><div className="mandate-subnav">{(mode==='dept'||requestedProject)&&<a href="#mandate-current">선택 과제의 현행 업무·사례</a>}<a href="#mandate-matrix">법령·업무 전체 연결표</a><a href="#mandate-coverage">연결 확인이 필요한 과제</a><Link to="downloads/mandate-workflows.md" download>조사·적용안 내려받기</Link></div></header>
 <nav className="mandate-modes" aria-label="매핑 탐색 기준"><Link to={'legal/mapping.html?dept='+selected.code+'&project='+selected.id} aria-current={mode==='dept'?'page':undefined}>담당 처·과제로 찾기</Link><Link to="legal/mapping.html?mode=law" aria-current={mode==='law'?'page':undefined}>법령·수행업무로 찾기</Link></nav>
 {(invalid||invalidLaw)&&<p className="work-notice" role="status">지정한 처·과제 또는 법정업무를 찾을 수 없어 기본 과제·전체 업무를 표시. 아래 선택·검색으로 다시 확인 가능.</p>}
 {mode==='dept'&&<><form className="mandate-selector" onSubmit={e=>{e.preventDefault();chooseProject(data.projects.find(p=>p.code===pendingDept))}}><label htmlFor="mandate-dept">검토할 담당 처</label><select id="mandate-dept" value={pendingDept} onChange={e=>setPendingDept(e.target.value)}>{deptRows.map(d=><option key={d.code} value={d.code}>{d.name}</option>)}</select><button type="submit">선택한 처 보기</button><small>{data.scope.departments}개 작성 조직·{data.scope.projects}개 기획과제. 내부 전결·예산권 확정과 구분.</small></form><section className="mandate-concept"><div><span>현재 검토 과제 · {selected.id}</span><h2 id="mandate-title">{selected.intent.department}</h2><p>{selected.intent.title}</p></div><Link to={'index.html?dept='+selected.code+'&project='+selected.id+'#integrated-work-context'}>전체 상세설계 이어 읽기 <ArrowUpRight size={17}/></Link></section>{data.projects.filter(p=>p.code===selected.code).length>1&&<nav className="work-project-picker" aria-label="이 처의 검토 과제">{data.projects.filter(p=>p.code===selected.code).map(p=><button key={p.id} aria-pressed={selected.id===p.id} onClick={()=>chooseProject(p)}>{p.intent.title}</button>)}</nav>}</>}
 {mode==='law'&&<section className="mandate-matrix-section" id="mandate-matrix"><h2>법령·원 권한·TS 담당·최신 과제 연결표</h2><p>{data.labels.lawScope}</p><div className="mandate-law-filters"><label>법령·업무·처 검색<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="예: 앱미터, 지자체, 철도승인처"/></label><label htmlFor="mandate-law-group">법령 분야<select id="mandate-law-group" aria-label="법령 분야" value={group} onChange={e=>setGroup(e.target.value)}><option value="all">전체 분야</option>{legal.groups.map(g=><option key={g.id} value={g.id}>{g.title}</option>)}</select></label><label htmlFor="mandate-authority">원 권한·의뢰 주체<select id="mandate-authority" aria-label="원 권한·의뢰 주체" value={authority} onChange={e=>setAuthority(e.target.value)}><option value="all">전체 주체</option><option value="central">국토교통부 관련</option><option value="local">지자체 관련</option></select></label><span role="status">{laws.length}개 법정업무 · {rows.length}개 하위 관계</span><button type="button" onClick={reset}>검색 초기화</button></div>
 {rows.length?<div className="mandate-matrix"><table><caption>소관 중앙부처와 실제 권한자·수행기관의 구분. 최신 제안 연결은 기획상 적용관계.</caption><thead><tr>{['법령·제도 소관','원 권한·수행방식','TS 수행업무·담당','최신 제안과의 연결'].map(x=><th key={x} scope="col">{x}</th>)}</tr></thead><tbody>{rows.map(b=><tr key={b.id}><th scope="row"><a href={'#mandate-binding-'+b.id}>{b.law.title}</a><small>{b.law.law}</small><small>{b.policy}</small></th><td data-label="원 권한·수행방식">{b.law.principal}<small>{b.law.mode}</small></td><td data-label="TS 수행업무·담당"><strong>{b.owner}</strong><span>{b.task}</span><small>{b.ownerStatus}</small></td><td data-label="최신 제안과의 연결">{b.projects.length?b.projects.map(p=><button key={p.id} className="mandate-project-link" onClick={()=>chooseProject(p)}>{p.intent.title}<small>{data.projectRelations.find(r=>r.projectId===p.id&&r.bindingId===b.id).type}</small></button>):<span>해당 업무와 최신 과제의 직접 연결 미확정</span>}</td></tr>)}</tbody></table></div>:<p className="mandate-empty" role="status">일치하는 법정업무 없음. 검색 초기화로 전체 목록 복원.</p>}</section>}
 {(mode==='dept'||requestedProject)&&<MandateWorkContext projectId={selected.id} contextId="mandate-current"/>}
 {mode==='dept'&&<section id="mandate-matrix" className="mandate-related-laws"><h2>관련 법정업무와 수행 관계</h2>{data.bindingsForProject(selected.id).length?data.bindingsForProject(selected.id).map(b=><section id={'mandate-binding-'+b.id} key={b.id}><h3>{b.task} · {b.projectRelation.type}</h3><p>{b.law.law}</p><LawBindingContext binding={b} showWorkflow={false}/></section>):<p className="work-notice">{data.labels.internal}</p>}<Link to="legal/mapping.html?mode=law">전체 27개 법정업무·36개 관계를 같은 연결표로 보기 <ArrowRight size={16}/></Link></section>}
 {mode==='law'&&<div className="mandate-law-list">{laws.map(r=><article key={r.id}><header><small>{r.id} · {r.mode}</small><h2>{r.title}</h2><p>{r.law}</p><span>제도 소관 · {data.policyForLaw(r)} / 원 권한·의뢰 주체 · {r.principal}</span></header>{rows.filter(b=>b.lawId===r.id).map(b=><section className="mandate-law-duty" id={'mandate-binding-'+b.id} key={b.id}><header><h3>{b.task}</h3><p>{b.ownerRole}</p></header><LawBindingContext binding={b}/></section>)}<footer>{r.boundary}</footer></article>)}</div>}
 <section id="mandate-coverage" className="mandate-coverage"><h2>개별 법령·수행 관계를 추가 확인할 과제</h2><p>{data.labels.coverage}</p><p>아래 {data.unlinked.length}개는 현재 27개 대표 법정업무와 기획상 관계가 아직 연결되지 않은 과제. 해당 업무가 없다는 판단이 아니며, 별도 업무의 근거·내부 분장·사규·지정·협약을 확인할 대상.</p><div className="mandate-unlinked">{data.unlinked.map(p=><section key={p.id}><strong>{p.intent.department}</strong><p>{p.intent.title}</p>{data.distinctions[p.id]&&<small>{data.distinctions[p.id]}</small>}<button className="mandate-project-link" onClick={()=>chooseProject(p)}>이 과제의 목적·방법·확인사항 보기</button></section>)}</div></section>
 <details className="mandate-additional-work"><summary>추가 확인한 국내 업무 · 자동차인증처 기술검토 · 현재 개별 계획서 미작성</summary><CurrentWorkflow work={data.works.find(w=>w.id==='W-KATRI')}/></details><footer className="mandate-limits"><p>{data.labels.sourceLimit}</p><p>{data.labels.metrics}</p><p>기존 법령 원장 {map.date}와 이번 공개 안내·선택 조문 확인 {data.date} 구분. 일부 선택본에 미래 시행 조항이 함께 포함되므로 조문별 효력 확인 필요. 51개 조사 조직 중 12개는 현재 개별 계획서 미작성.</p><Link to="downloads/mandate-workflows.json" download>관계·출처·절차 JSON</Link> · <Link to="downloads/law-concept-mapping.md" download>이전 법령 매핑 보존 문서</Link></footer></article>
}
