import React,{useState,useEffect} from 'react';
import {ArrowRight,ArrowUpRight,Scale,Building2,Workflow,Lightbulb} from 'lucide-react';
import {Link,Out,legal,navigate} from './core.jsx';
import map from './law-mapping.cjs';
import './law-mapping.css';
import proposals from './proposal-design.cjs';
const relation=(b,code)=>b.concepts.find(c=>c.code===code);
function Evidence({binding:b}){return <details className="mandate-evidence"><summary>담당 관계·법령 원문 확인</summary><p>{b.ownerStatus} · {map.date}</p>{b.sourceIds.length?<ul>{b.sourceIds.map(id=>{const s=map.sources[id];return <li key={id}><Out url={s.url}>{s.title}</Out><small>담당 표시: {s.department} · 열람 {s.checked} · {s.published}</small></li>})}</ul>:<p>기존 원장 연결. 해당 하위 업무의 직접 담당 근거는 추가 확인 대상.</p>}<ul>{b.law.refs.map(id=>{const s=legal.sources.find(x=>x.id===id);return <li key={id}><Out url={s.url}>{s.name}</Out><small>{s.effective} · 기존 법령 원장 판본</small></li>})}</ul><p>공식 업무안내 담당 표시와 내부 위임전결·독점 소관·최종 승인권의 구분.</p></details>}
function ProposalContext({code}){const c=proposals.context(code);if(!c)return null;const {d,p,sources}=c;const base=d.folder+'/01_사업정의.html';return <section className="mandate-proposal" aria-labelledby="mandate-proposal-title"><header><span>법정업무에서 상세 사업설계로</span><h2 id="mandate-proposal-title">{d.name} · 왜, 무엇을 바꾸는가</h2><p>{p.mission}</p></header><div className="mandate-proposal-blocks"><article><h3>공공적 필요성</h3><p>{p.why}</p></article><article><h3>현행 기반·비AI 비교안</h3><p>{p.baseline}</p><small>현재 기능의 부재를 전제로 하지 않고 실제 업무 사례로 잔여 한계 확인</small></article><article><h3>CCK 기반 AX의 추가 능력</h3><p>{p.increment}</p><small>기획·설계안. 실제 제품 적용·기관 승인·개선효과 검증 전</small></article></div><div className="mandate-proposal-proof"><h3>확인한 공식업무와 적용 한계</h3>{sources.map((s,i)=><article key={i}><Out url={s.url}>{s.title}</Out><p>{s.fact}</p><small>{s.limit} · {s.date} · 열람 {proposals.date}</small></article>)}</div><nav aria-label="상세기획과 다섯 도식 읽기">{[['sixw','육하원칙·필요성·현행 한계'],['concept','컨셉도·공공 편익'],['overall','전체 아키텍처'],['service','서비스 아키텍처'],['data','데이터 흐름도'],['privacy','개인정보 처리도']].map(([id,title])=><Link key={id} to={base+'#section-detail-'+id}>{title}<ArrowUpRight size={16}/></Link>)}</nav><small>같은 상세 문서의 본문 위치로 이동 · 페이지 분할 없이 연속 스크롤로 열람</small></section>}
export function MandateSummary({code}){const p=map.forDepartment(code);if(!p)return null;return <section className="mandate-summary"><div><span>컨셉 ↔ 업무 ↔ 법령</span><h2>{p.department.name}의 업무에서 출발한 제안</h2><p>{p.rationale}</p><small>{p.assignmentStatus}</small></div><Link to={map.mappingPath(code)}>담당 처·법령 매핑 보기 <ArrowUpRight size={17}/></Link></section>}
export function LawMapping(){const query=new URLSearchParams(location.search),mode=query.get('mode')==='law'?'law':'dept';const requested=query.get('dept'),p=map.forDepartment(requested)||map.profiles[0],selectedLaw=legal.rows.find(r=>r.id===query.get('law'));const [search,setSearch]=useState(''),[group,setGroup]=useState('all'),[pendingDept,setPendingDept]=useState(p.code);useEffect(()=>{setPendingDept(p.code)},[p.code]);useEffect(()=>{setSearch('');setGroup('all')},[mode]);
const rows=legal.rows.filter(r=>(!selectedLaw||r.id===selectedLaw.id)&&(group==='all'||r.group===group)&&[r.title,r.law,r.org,r.work,...map.forLaw(r.id).flatMap(b=>[b.owner,b.task,b.ownerRole])].join(' ').includes(search.trim()));
return <div className="mandate-page"><header className="mandate-heading"><span>법정업무 · 조직 · AX 컨셉</span><h1>TS의 법정업무에서 AX 사업까지</h1><div className="mandate-reading-context"><p>한국교통안전공단은 교통사고 예방과 교통체계 운영·관리를 전문적으로 지원하는 국토교통부 소관 공공기관입니다. 법령과 위탁·대행 등의 근거에 따라 검사·시험·조사·교육·정보서비스를 수행합니다.</p><p>이 화면은 그 책임을 사업제안과 연결하는 자료입니다. <b>어떤 법에 따른 업무인지, 어느 처가 무엇을 수행하는지, 그 업무에서 어떤 편익을 높이려는지</b> 순서로 읽을 수 있습니다. 담당 관계는 공개 업무안내에 근거하며, 내부 전결·예산권의 확정과는 구분합니다.</p><Link to="index.html">TS의 정의·2030 목표부터 순서대로 읽기 <ArrowRight size={16}/></Link></div><div className="mandate-subnav"><Link to="legal.html">법정업무 목록</Link><Link to="legal/mapping.html" aria-current="page">처·컨셉 매핑</Link><Link to="legal/sources.html">법령 판본·근거</Link><Link to="downloads/law-concept-mapping.md" download>매핑 문서 내려받기</Link></div></header>
<nav className="mandate-modes" aria-label="매핑 탐색 기준"><Link to={map.mappingPath(p.code)} aria-current={mode==='dept'?'page':undefined}>처·컨셉에서 찾기</Link><Link to="legal/mapping.html?mode=law" aria-current={mode==='law'?'page':undefined}>법령·업무에서 찾기</Link></nav>
{mode==='dept'?<><form className="mandate-selector" onSubmit={e=>{e.preventDefault();navigate(map.mappingPath(pendingDept))}}><label htmlFor="mandate-dept">주관 검토 처 선택</label><select id="mandate-dept" value={pendingDept} onChange={e=>setPendingDept(e.target.value)}>{map.profiles.map(x=><option key={x.code} value={x.code}>{x.department.name} · {x.department.title}</option>)}</select><button type="submit">선택한 처 보기</button><small>사이트에 기획된 {map.profiles.length}개 처의 대표 컨셉 기준</small></form>
<section className="mandate-concept" aria-labelledby="mandate-title"><div><span>기획상 주관 검토 처</span><h2 id="mandate-title">{p.department.name}</h2><p>{p.department.title}</p></div><Link to={map.conceptPath(p.code)}>육하원칙·상세기획·5종 도식 <ArrowUpRight size={18}/></Link></section>
<ol className="mandate-chain" aria-label="법령부터 담당 처까지 연결"><li><Scale size={22}/><span>01 · 법령·원 권한자</span><h3>{p.primary.law.law}</h3><p>{p.primary.law.mode}</p><small>{p.primary.law.principal}</small></li><li><Workflow size={22}/><span>02 · 실제 수행업무</span><h3>{p.primary.task}</h3><p>{p.nature}</p><small>{p.primary.concepts.find(c=>c.code===p.code)?.label}</small></li><li><Building2 size={22}/><span>03 · 담당 처·현장 역할</span><h3>{p.primary.owner}</h3><p>{p.primary.ownerRole}</p><small>{p.primary.ownerStatus}</small></li></ol>
<div className="mandate-reason"><Lightbulb size={23}/><div><h3>이 처에 제안하는 이유</h3><p>{p.rationale}</p><p><b>협업·책임 경계</b> · {p.collaboration}</p></div></div><Evidence binding={p.primary}/><ProposalContext code={p.code}/>
<div className="mandate-section-title"><h2>업무별 적용 관계</h2><span>같은 법령·같은 처라도 대표 컨셉의 직접 범위와 구분</span></div><div className="mandate-bindings">{p.bindings.map(b=>{const c=relation(b,p.code);return <article key={b.id} data-relation={c.relation}><header><span className={'mandate-badge '+c.relation}>{c.label}</span><small>{b.lawId} · {b.id}</small></header><h3>{b.task}</h3><p>{c.reason}</p><dl><dt>관련 법령</dt><dd>{b.law.law}</dd><dt>업무 담당 관계</dt><dd>{b.owner} · {b.ownerRole}</dd></dl>{b.note&&<p className="mandate-note">{b.note}</p>}<Link to={'legal/mapping.html?mode=law&law='+b.lawId}>같은 법령 업무의 다른 담당 관계 <ArrowRight size={15}/></Link></article>})}</div>
<details className="mandate-overview"><summary>13개 처의 컨셉·연결 업무 한눈에 보기</summary><div className="mandate-overview-grid">{map.profiles.map(x=><Link key={x.code} to={map.mappingPath(x.code)}><strong>{x.department.name}</strong><span>{x.department.title}</span><small>{x.primary.lawId} · {x.primary.task}</small><small>{relation(x.primary,x.code)?.label}</small></Link>)}</div></details></>:<><div className="mandate-law-filters"><label>법령·업무·처 검색<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="예: 자동차관리법, 실증사업처"/></label><label htmlFor="mandate-law-group">법령 분야<select aria-label="법령 분야" id="mandate-law-group" value={group} onChange={e=>setGroup(e.target.value)}><option value="all">전체 분야</option>{legal.groups.map(g=><option key={g.id} value={g.id}>{g.title}</option>)}</select></label><span role="status">{rows.length}개 법정업무 묶음</span>{selectedLaw&&<Link to="legal/mapping.html?mode=law">업무 지정 해제</Link>}</div><div className="mandate-law-list">{rows.map(r=><article key={r.id}><header><small>{r.id} · {r.mode}</small><h2>{r.title}</h2><p>{r.law}</p><span>원 권한·의뢰 주체 · {r.principal}</span></header>{map.forLaw(r.id).map(b=><section className="mandate-law-duty" key={b.id}><div><h3>{b.task}</h3><strong>{b.owner}</strong><p>{b.ownerRole}</p><small>{b.ownerStatus}</small></div><div><h4>연결 컨셉·적용 관계</h4>{b.concepts.length?b.concepts.map(c=><React.Fragment key={c.code}><Link to={map.mappingPath(c.code)} className="mandate-concept-link"><span className={'mandate-badge '+c.relation}>{c.label}</span><strong>{c.department.name} · {c.department.title}</strong><small>{c.reason}</small></Link><Link className="mandate-direct-detail" to={map.conceptPath(c.code)+'#section-detail-sixw'}>{c.department.name} 상세기획·5종 도식 <ArrowUpRight size={15}/></Link></React.Fragment>):<p className="mandate-pending">현재 13개 처의 대표 컨셉에 직접 연결되지 않은 업무. 업무 담당 부재를 의미하지 않음.</p>}{b.note&&<p className="mandate-note">{b.note}</p>}<Evidence binding={b}/></div></section>)}<footer>{r.boundary}<Link to={'legal/'+r.group+'.html?slide='+r.id}>기존 법정업무 상세 <ArrowUpRight size={15}/></Link></footer></article>)}</div>{!rows.length&&<div className="mandate-empty" role="status">일치하는 법정업무 없음. <button onClick={()=>{setSearch('');setGroup('all');if(selectedLaw)navigate('legal/mapping.html?mode=law')}}>검색 초기화</button></div>}</>}
<details className="mandate-joint"><summary>복수 처 협업 사례 · {map.jointProposal.title}</summary><p>{map.jointProposal.status} · <b>{map.jointProposal.owner}</b></p><ul>{map.jointProposal.links.map(l=><li key={l.code}><Link to={map.mappingPath(l.code)}>{map.forDepartment(l.code).department.name}</Link> · {l.role}</li>)}</ul><p>{map.jointProposal.boundary}</p></details>
<footer className="mandate-limits"><p>{map.scope}</p><p>{map.lawEvidence}</p><p>주관 검토 처 배정은 제안 설계. 실제 과업·예산·전결 확정과 구분. 중앙부처·지자체는 원 권한자로 별도 표시.</p></footer></div>}
