import React,{useState} from 'react';
import research from './antigravity-research.json';

// 원자료의 확정 주장·민원 인용·수치가 아니라 파일 대조 결과와 검증 질문만 표시.
export function LinkedResearch({choose}){
 const [view,setView]=useState('topics'),[query,setQuery]=useState('');
 const term=query.trim().toLowerCase();
 const topics=research.groups.map(g=>({...g,topics:g.topics.filter(t=>(t.id+' '+t.title+' '+g.title+' '+t.flags.join(' ')).toLowerCase().includes(term))})).filter(g=>g.topics.length);
 const sites=research.sites.filter(s=>(s.name+' '+s.originalName+' '+s.url+' '+s.kind+' '+s.note).toLowerCase().includes(term));
 const count=view==='topics'?topics.reduce((n,g)=>n+g.topics.length,0):sites.length;
 return <div className="wb-research" data-linked-research="snapshot">
  <p className="wb-note">{research.scope}</p>
  <dl className="wb-research-counts"><div><dt>조사 주제·입력 문서</dt><dd>{research.stats.topics}개 <small>원문 검증 전</small></dd></div><div><dt>연계 사이트 목록</dt><dd>{research.stats.directoryEntries}개 <small>신규 검증 서비스 0개</small></dd></div><div><dt>PDF 보관파일</dt><dd>{research.stats.pdfFiles}개 <small>고유 해시 {research.stats.pdfUniqueHashes}개</small></dd></div></dl>
  <div className="wb-research-views" aria-label="연계 조사자료 유형">{[['topics','조사 주제'],['sites','사이트 대조'],['pdf','PDF 보관현황']].map(([key,name])=><button key={key} className="wb-button" aria-pressed={view===key} onClick={()=>{setView(key);setQuery('')}}>{name}</button>)}</div>
  {view!=='pdf'&&<><label htmlFor="wb-research-search">{view==='topics'?'주제·그룹·검토조건 검색':'사이트명·주소 검색'}</label><input id="wb-research-search" type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder={view==='topics'?'예: DRT, 검수, 비전':'예: RIMS, 교육, 드론'}/><p className="wb-result-count" role="status">{count}개 {view==='topics'?'주제':'사이트'}{term?' · 검색 결과':''}</p><button className="wb-link-button" onClick={()=>setQuery('')}>검색 초기화</button></>}
  {view==='topics'&&<><p>100개 파일의 제목·해시 보존 및 10개 그룹 탐색. 본문의 실제 민원·법령·효과 수치는 근거 대조 대상. 사이트의 사업후보 54개와 별도 자료 단위</p>{topics.map(g=><details className="wb-disclosure" key={g.id} open={term?true:undefined}><summary>{g.id} · {g.title} <small>{g.topics.length}개</small></summary><ul className="wb-research-topics">{g.topics.map(t=><li key={t.id}><small>{t.id}</small><strong>{t.title}</strong>{t.flags.length>0&&<p>{t.flags.join(' / ')}</p>}</li>)}</ul></details>)}{!count&&<p className="wb-empty-note">일치하는 조사 주제 없음 · 검색어 변경 또는 초기화</p>}<h3>기존 제안에서 우선 대조할 내용</h3>{research.nextChecks.map(c=><article className="wb-source" key={c.project}><button className="wb-link-button" onClick={()=>choose(c.project)}>{c.title} · {c.project}</button><p>연계 주제 {c.steps.map(n=>'STEP-'+String(n).padStart(3,'0')).join(' / ')}</p><p>{c.action}</p><small>제안범위 검토 연결 · 담당·효과의 공식 확정과 구분</small></article>)}</>}
  {view==='sites'&&<><p>기존 공식 목록·저장된 페이지와 대조한 진입주소. 이번 새 접속·인증 후 기능·운영 책임의 재검증은 미수행. 대표포털·업무서비스·공통 인증·외부 기관·캠페인 구분</p>{sites.map(s=><article className="wb-source" key={s.id}><h3>{s.name}</h3><span className="wb-badge">{s.kind}</span><dl><div className="wb-field"><dt>목록 대응</dt><dd>{s.inCatalog?'기존 공식 목록에 대응':s.inExistingLinks?'기존 연계 링크에 존재 · 목록 편입 검토':'같은 인증 도메인의 기존 링크 존재 · root 주소 확인 전'}</dd></div><div className="wb-field"><dt>저장된 접근 상태</dt><dd>{({'public-html-collected':'공개 HTML 수집','html-shell':'첫 화면 본문·기능 확인 제한','network-error':'해당 주소 요청 실패'})[s.storedAccess]||s.storedAccess}</dd></div>{s.catalogueUrl&&s.catalogueUrl!==s.url&&<div className="wb-field"><dt>공식 목록의 등록 주소</dt><dd>{s.catalogueUrl}<br/>등록주소의 저장 이력: {({'public-html-collected':'공개 HTML 수집','html-shell':'첫 화면 본문·기능 확인 제한','network-error':'해당 주소 요청 실패'})[s.catalogueAccess]||s.catalogueAccess}</dd></div>}<div className="wb-field"><dt>정정·확인 사항</dt><dd>{s.note}</dd></div></dl><a href={s.url} target="_blank" rel="noopener noreferrer" className="wb-external">{s.url}</a>{s.sourceUrl&&<p><a href={s.sourceUrl} target="_blank" rel="noopener noreferrer">기존 공식 연계목록 출처</a></p>}</article>)}{!count&&<p className="wb-empty-note">일치하는 사이트 없음 · 검색어 변경 또는 초기화</p>}</>}
  {view==='pdf'&&<><p>파일 98개·색인 98행·PDF 헤더 98개 대조. 동일 해시 중복 3쌍. PDF 전체 내용·진위·한글 앱 호환성의 확인과 구분</p><div className="wb-table-wrap"><table><thead><tr><th>보관 분류</th><th>파일 수</th><th>자료 성격</th></tr></thead><tbody>{research.pdfCategories.map(r=><tr key={r.title}><td>{r.title}</td><td>{r.files}</td><td>{r.nature}</td></tr>)}</tbody></table></div><dl><div className="wb-field"><dt>원문 URL 복원</dt><dd>기존 다운로드의 동일 SHA-256 대응 {research.stats.pdfSourceRecoveredFiles}개. 나머지 파일의 게시물·첨부 URL 재대조 필요</dd></div><div className="wb-field"><dt>파일명 복원</dt><dd>깨진 한글 파일명 {research.stats.pdfReadableAliases}개에 별도 읽기용 이름 등록. 원본 파일명·내용 보존</dd></div><div className="wb-field"><dt>자료 구분</dt><dd>자체 기획 PDF {research.stats.pdfGeneratedPlans}개를 공식 간행물·첨부자료와 별도 분류</dd></div></dl></>}
  <details className="wb-disclosure"><summary>반영 범위와 추가 검증</summary><ul>{research.limits.map(t=><li key={t}>{t}</li>)}</ul><p>색인 법적근거 공란 {research.stats.indexLegalBlank}개. 본문 URL 기재 문서 {research.stats.topicBodiesWithLinks}개. URL 존재도 해당 주장의 원문 입증 완료를 의미하지 않음</p><p>비전·영상 기술이 언급된 기획문서 {research.stats.visionMentionTopics}개는 현재 기본범위와 차분 검토. 문서별 표기 여부이며 과제 확정·기술 도입 건수와 구분</p></details>
  <p className="wb-note">자료 고정 시각 {research.snapshotAt.replace('T',' ')} · 자동 실시간 동기화 미설정</p>
 </div>;
}
