import React from 'react';
import {Link,Out} from './core.jsx';
import data from './mandate-workflows.cjs';
import {legal} from './core.jsx';
import './mandate-workflows.css';
import map from './law-mapping.cjs';
const text=(value)=>Array.isArray(value)?value.join(' / '):value;
export function WorkflowSources({ids}){return <div className="work-sources">{ids.map(id=>{const s=data.sourceById[id];return <section key={id}><Out url={s.url}>{s.title}</Out><small>{s.published} · 직접 확인 {s.checked}</small><p><b>확인 범위</b> {s.fact}</p><p><b>한계</b> {s.limit}</p></section>})}</div>}
export function CurrentWorkflow({work:w,compact=false}){return <section className="work-current" data-current-work={w.id}><header><h4>{w.title} · 현재의 처리방식</h4><span>{w.status}</span></header><dl className="work-fields">{[['현재 수행조직·확인 상태',w.owner],['수행·결정 역할',w.authority],['대상·참여자',w.actors],['현재 입력자료',w.inputs],['업무 근거',w.basis]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><div className="work-step-table"><table><caption>공식 안내에서 확인한 단계 · 내부 미공개 절차를 임의로 채우지 않은 범위</caption><thead><tr>{['단계','누가 무엇을 처리하는가','남는 결과'].map(t=><th key={t} scope="col">{t}</th>)}</tr></thead><tbody>{w.steps.map(([name,task,result],i)=><tr key={i}><th scope="row">{String(i+1).padStart(2,'0')} {name}</th><td data-label="처리">{task}</td><td data-label="결과">{result}</td></tr>)}</tbody></table></div><p><b>보완·예외</b> {w.exception}</p><p><b>재사용할 기존 기능</b> {w.existing}</p>{!compact&&<><p className="work-question"><b>현업에서 확인할 병목 가설</b> {w.question}</p><p><b>추가 적용 설계</b> {w.application}</p></>}<WorkflowSources ids={w.sourceIds}/></section>}
function OwnerSources({binding:b}){const fresh=data.ownerSourceIdsByBinding[b.id]||[];return <div className="work-owner-sources">{b.sourceIds.map(id=>{const s=map.sources[id];return <p key={id}><Out url={s.url}>{s.title}</Out><small>담당 {s.department} · 기존 확인 {s.checked} · {s.published} / 공개 담당 표시의 근거. 내부 전결 확정·이번 신규 검증과 구분</small></p>})}{fresh.map(id=>{const s=data.sourceById[id];return <p key={id}><Out url={s.url}>{s.title}</Out><small>이번 공식 안내 확인 {s.checked} · {s.fact} / 확인 범위의 담당 표시. 지역·현장 전체 분장·내부 전결 확정과 구분.</small></p>})}{!b.sourceIds.length&&!fresh.length&&<p className="work-owner-pending">이 법정업무의 담당을 직접 확인하는 공식 URL은 추가 확보 대상. 기존 조직·법령 원장 표기를 현재 업무분장·내부 전결 확정으로 사용하지 않음.</p>}</div>}
function InternationalCases({projectId}){const cases=data.casesForProject(projectId);return <section className="work-cases"><h4>국내 기반과 비교한 해외 운영방식의 적용</h4><p>해외 사례의 기술·운영을 확인하고 국내 과제에 가져올 원리와 필요한 조건을 분리한 적용안. 기관 전체를 일대일 대응하거나 해외 성과를 국내 효과로 승계하지 않음.</p>{cases.length?cases.map(c=><article key={c.id} data-international-case={c.id}><header><span>{c.country} · {c.kind}</span><h5>{c.title}</h5></header>{data.caseApplicability[c.id]?.[projectId]&&<p className="work-notice" data-case-applicability>{data.caseApplicability[c.id][projectId]}</p>}<dl className="work-fields">{[['확인한 운영',c.operation],['CCK로 추가할 업무 능력 · 설계',c.transfer],['국내 적용 선행조건',c.condition],['비교의 한계',c.limit]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><WorkflowSources ids={c.sourceIds}/></article>):<p className="work-notice">{data.labels.caseMissing}</p>}</section>}
export function LawBindingContext({binding:b,showWorkflow=true}){const projects=data.projectsForBinding(b.id),works=data.works.filter(w=>w.bindingIds?.includes(b.id));return <section className="work-binding-context" data-law-binding={b.id}><dl className="work-fields">{[['제도 소관 중앙부처',data.policyForLaw(b.law)],['원 권한·지정·의뢰 주체',b.law.principal],['수행 방식',b.law.mode],['TS 담당·역할',b.owner+' · '+b.ownerRole],['담당 확인 상태',b.ownerStatus]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>{projects.length?<div className="work-binding-proposals">{projects.map(p=>{const rel=data.projectRelations.find(r=>r.projectId===p.id&&r.bindingId===b.id);return <section key={p.id}><strong>{p.intent.department} · {p.intent.title}</strong><span className="work-state">{rel.type} · 기획상 적용관계</span><p>{rel.reason}</p><p><b>목적</b> {p.intent.purpose}</p><p><b>구현 수단</b> {p.intent.means.noa}</p><Link to={'index.html?dept='+p.code+'&project='+p.id+'#integrated-work-context'}>현행 업무·해외 사례·전체 설계 이어 읽기</Link></section>})}</div>:<p className="work-notice">현재 42개 과제와 업무 의미가 일치하는 직접 연결은 없음. 같은 처의 과제가 있다는 이유로 다른 업무의 법령을 연결하지 않음.</p>}{showWorkflow&&works.map(w=><CurrentWorkflow key={w.id} work={w} compact/>)}<details className="work-law-evidence"><summary>이 업무의 법령 판본·담당 근거</summary>{b.law.refs.map(id=>{const s=legal.sources.find(s=>s.id===id);return <p key={id}><Out url={s.url}>{s.name}</Out><small>{s.effective} · 기존 법령 원장 인용. 개별 조문의 시행일·현재 추가개정은 적용 전 확인.</small></p>})}<OwnerSources binding={b}/></details></section>}
export function MandateWorkContext({projectId,contextId='integrated-work-context'}){
 const p=data.forProject(projectId);if(!p)return null;const v=p.intent,bindings=data.bindingsForProject(p.id),primary=data.primaryBinding(p),works=data.workForProject(p.id),w=works[0];
 const chain=[['01 · 업무 근거',primary?.law.law||w?.basis||'개별 수행근거 추가 확보',primary?.projectRelation.type||'공식 안내·원자료와 연결 확인'],['02 · 책임·결정',primary?.law.principal||w?.authority||'내부 분장·대외 권한 확인 필요',primary?.law.mode||'기관 소관과 행위별 권한 구분'],['03 · 수행 조직',v.department,w?.status||'현재 업무의 세부 처리 기록 확인 필요'],['04 · 목적·변화',v.purpose,v.changes.join(' / ')],['05 · 구현 수단','NOA · 기존 시스템 · 담당자',v.means.noa]];
 return <section className="mandate-work-context" id={contextId} data-work-project={p.id} tabIndex={-1}><header className="work-context-heading"><small>법령·업무·사례 연결 · 조사 {data.date}</small><h3>{v.department} · 왜 이 솔루션인가</h3><p>법적 책임과 현행 처리방식을 먼저 확인하고, 달성할 목적·업무 변화·CCK 구현방법을 연결한 {v.reviewStatus} 제안.</p></header><ol className="work-chain" aria-label="법령에서 솔루션까지 연결">{chain.map(([label,title,note])=><li key={label}><span>{label}</span><strong>{title}</strong><p>{note}</p></li>)}</ol>
 {bindings.length>0?<section className="work-law-relations"><h4>법령·주체·수행업무와 이 과제의 관계</h4>{bindings.map(b=><section key={b.id}><h5>{b.task} <span>{b.projectRelation.type}</span></h5><p>{b.projectRelation.reason}</p><dl className="work-fields">{[['법령·조문',b.law.law],['제도 소관',data.policyForLaw(b.law)],['원 권한·의뢰 주체',b.law.principal],['TS 수행·담당 상태',b.owner+' · '+b.ownerStatus]].map(([k,t])=><div key={k}><dt>{k}</dt><dd>{t}</dd></div>)}</dl><p><b>책임 경계</b> {b.law.boundary}</p><details><summary>법령 원문·적용 판본·담당 근거</summary>{b.law.refs.map(id=>{const s=legal.sources.find(s=>s.id===id);return <p key={id}><Out url={s.url}>{s.name}</Out> · {s.effective}<small>기존 원장 인용. 새 조사와 판본·조문별 효력 확인을 구분.</small></p>})}<OwnerSources binding={b}/></details></section>)}</section>:<p className="work-notice" data-work-unmapped>{data.labels.internal}</p>}
 {data.distinctions[p.id]&&<p className="work-notice" data-distinct-work="FPIS">{data.distinctions[p.id]}</p>}
 {works.length?works.map(w=><CurrentWorkflow key={w.id} work={w}/>):<section className="work-current work-unverified"><h4>현재 처리방식 · 원기록 확인 필요</h4><p>{data.labels.unknown}</p><p><b>현행 한계의 검증 가설</b> {v.gap}</p><p><b>확인할 실제 흐름</b> {data.labels.workflowMissing}</p><p><b>확보할 자료 · 설계안</b> {text(v.inputs)}</p><p><b>누가 확인할 것인가</b> {v.department}의 실제 담당자·검토자·승인자 및 기존 시스템 운영자. 내부 역할·연계권한·완료 상태 현장 확인.</p><details><summary>이전 조사 근거 · 이번 원문 재검증과 구분</summary>{v.evidence?.map((s,i)=><section key={s.id||i}>{s.url?<Out url={s.url}>{s.title}</Out>:<strong>{s.title}</strong>}<small>{s.published} · 기존 확인 {s.accessed||s.checked||'원문 확인일 참조'}</small><p>{s.verification_scope||'기존 기획 원장 인용. 이 화면 작업에서 전체 원문·현재 업무 흐름을 재검증한 것으로 표시하지 않음.'}</p></section>)}</details></section>}
 <section className="work-solution"><h4>문제에서 CCK 적용범위로 전환</h4><dl className="work-fields">{[['해결할 목적',v.purpose],['현재 확인해야 할 한계',v.gap],['새로 바꿀 업무 방식',v.change.steps.join(' → ')],['NOA · 이해·계획·실행·검증',v.means.noa],['aRDa · 원문·판본·권한 기반',v.means.knowledge],['기존 시스템·검증된 규칙',v.means.rules],['사람·공식 판단',v.means.human],['추가 개발·기관 적용',v.newWork],['초기 적용 범위',v.scope],['업무가 끝났다고 볼 상태',v.completion]].map(([k,t])=><div key={k}><dt>{k}</dt><dd>{text(t)}</dd></div>)}</dl><p className="work-notice">CCK 실제 설치본의 기능·사용권·연계·성능을 검증해 재사용 공수와 신규 개발을 구분. 해외 ML·전문시험·경로최적화 엔진을 CCK 보유 기능으로 간주하지 않음.</p></section>
 <InternationalCases projectId={p.id}/><section className="work-measurement"><h4>적용효과를 어떻게 확인할 것인가</h4><p>{data.labels.metrics}</p>{v.goals.map(g=><section key={g.id}><h5>{g.metric.name}</h5><p><b>측정</b> {g.metric.formula}</p><p><b>원기록</b> {g.metric.records||'해당 측정식의 관측대상·분모·기간·원기록은 현업 확인 후 확정'}</p><small>{g.metric.note}</small></section>)}<p>현행·일반 검색/고정 규칙·CCK 적용을 같은 사건·자료·완료조건으로 비교. 담당자 독립 검토와 예외사례를 포함하고 기업 대기·기관 처리·외부 회신 시간을 분리.</p></section></section>
}
