const isp=require('./isp-review.cjs'),cost=require('./cost-review.cjs'),implementation=require('./implementation-review.cjs'),pms=require('./skill-pms.cjs'),manifest=require('./department-documents.json'),coverage=require('./department-coverage.cjs');
const route='research-library.html?view=planning';
const projects=isp.mappings.map(m=>{
 const i=implementation.mappings.find(r=>r.id===m.id),p=pms.portfolio.find(r=>r.id===m.id),d=manifest.departments.find(r=>r.code===m.code),b=cost.bundles.find(r=>r.id===m.bundle);
 return {id:m.id,code:m.code,department:m.department,title:m.title,bundle:m.bundle,bundleTitle:b.title,classification:i.status,classificationLabel:implementation.statuses[i.status],classificationDate:implementation.date,status:m.status,selected:m.selected,scope:i.scope,entry:b.entry,acceptance:b.acceptance,boundary:b.boundary,proposalRoute:p.proposalRoute,designLinks:p.designLinks,documentsRoute:p.documentsRoute,documents:d.documents,sharedDocuments:p.sharedDocuments,ispRoute:route+'#isp-dept-'+m.code,implementationRoute:route+'#implementation-mapping-'+m.id,costRoute:route+'#cost-audit-'+m.code,rfpRoute:route+'#cost-rfp',controls:m.controls,rfpCandidates:m.rfpCandidates,baseline:i.baseline,target:i.target,cost:i.cost};
});
const bundles=cost.bundles.map(b=>({...b,to:route+'#cost-bundle-'+b.id,count:projects.filter(p=>p.bundle===b.id).length}));
const readiness=isp.readiness.map(([title,evidence,state,owner])=>({title,evidence,state,owner}));
module.exports={date:isp.date,year:isp.year,title:'2027년 TS 후속사업기획',label:'CCK 기반 AX·SI 확장 검토',lead:'기관의 임무와 실제 문제에서 출발하여, 필요한 업무를 묶고 설계·대가·RFP·계획서로 연결하는 기획 안내.',status:'ISP 준비·1차 검토 / 사업 선정·발주·금액 미확정',counts:{departments:isp.departments.length,projects:projects.length,documents:manifest.departments.flatMap(d=>d.documents).length,controls:isp.controls.length},notice:'작성된 39처·42항목은 조사 후보. 공식 조직 대조 51처와 다른 범위이며, 확정 업무계획·TS 승인·실제 운영 서비스 아님.',journey:[['01','ISP부터 시작','임무·재원·현황·문제·대안 확인',route+'#isp-start'],['02','업무 묶음 편성','공통 코어·선택 업무·실행조건 검토',route+'#cost-bundles'],['03','처별 제안 검토','근거·HOW·설계·효과 측정 확인','solutions.html'],['04','설계·대가·문서','요구사항·RFP·한글 판본 연결','planning-documents.html']],projects,bundles,classificationOptions:[['all','검토 분류 전체'],...Object.entries(implementation.statuses)],readiness,metrics:isp.metrics,missing:coverage.rows.filter(r=>!r.code).map(r=>({id:r.id,name:r.name,parent:r.parent,to:'skill-pms.html?view=coverage#'+r.anchor})),sources:isp.sources,review:{questions:['왜 해야 하는가: 임무·근거·현행 대응 이후 남은 문제 확인','어떻게 구현하는가: 기존 제품·자료·연계·서버·권한의 실제 차분 확인','어느 범위를 발주하는가: 공통 기능과 선택 업무·인수조건 구분','얼마가 적정한가: 기능량·작업량·단가·운영비·측정 편익 대조'],panels:[{id:'isp',title:'ISP 준비·환경·현황 검토',date:isp.date,summary:'공식 5단계 · 업무 사례·대안 비교 · 보안·개인정보·AI 윤리 22통제 · 39처 연결',status:isp.status},{id:'cost',title:'묶음형 RFP·실행조건·대가 검토',date:cost.date,summary:'B00 공통 + B01~B04 · 39처 기존 산정 대조 · 가격·계약·RFP·비목·인수조건',status:cost.status},{id:'implementation',title:'실현가능성·제품·자료 확인',date:implementation.date,summary:'42항목의 최소 구현 범위 · 실제 제품/연계 제약 · 현업 질문서 · 5개 측정명세',status:implementation.status},{id:'history',title:'이전 검토·문제정의·참고 근거',date:require('./analysis-review.cjs').updatedAt,summary:'이전 13처 편성·공통 기술·근거 정정·신규 문제 탐색·편성 기준·출처 6장',status:'참고 이력 · 최신 ISP·묶음 편성과 함께 비교'}]}};
