import React,{useEffect,useState} from 'react';
import {Link,navigate} from './core.jsx';
import plan from './problem-planning.cjs';
import './problem-planning.css';
export function PlanningModeSwitch({route,problem=false}){
 const u=new URL(route,'https://reader/'),q=new URLSearchParams(u.search);q.set('view','problems');
 const problemTo='index.html?'+q+(u.searchParams.get('project')&&plan.byProject[u.searchParams.get('project')]?'#problem-'+plan.byProject[u.searchParams.get('project')]:'');
 const detailQ=new URLSearchParams(u.search);detailQ.delete('view');
 const detailTo=detailQ.has('dept')?'index.html?'+detailQ+'#integrated-start':'solutions.html';
 return <nav className="planning-mode-switch" aria-label="사업기획 읽기 방식" data-planning-mode={problem?'problems':'departments'}><Link to={problemTo} aria-current={problem?'page':undefined}>문제별 통합기획</Link><Link to={detailTo} aria-current={!problem?'page':undefined}>처별 상세기획</Link><span>문제·필요성부터 보기 → 관련 처의 설계 확인</span></nav>;
}
function SourceLinks({ids}){return <ul className="problem-source-links">{ids.map(id=>{const s=plan.sources.find(s=>s.id===id);return <li key={id}><a href={s.url} target="_blank" rel="noopener noreferrer">{s.title}<span className="sr-only"> · 새 창</span></a><small>확인 {s.checkedAt} · {s.limit}</small></li>})}</ul>;}
function Goals({data}){return <dl className="problem-goals">{[['목적',data.purpose],['목표·검증',data.goal],['수단',data.means]].map(([title,text])=><div key={title}><dt>{title}</dt><dd>{text}</dd></div>)}</dl>;}
function Theme({theme:t}){
 const pilot=t.projects.find(p=>p.id===t.pilot.id);
 return <section className="problem-theme" id={'problem-'+t.id} tabIndex={-1} data-problem-theme={t.id}>
  <header><span>{t.number}</span><div><h2>{t.title}</h2><p>{t.question}</p></div></header>
  <div className="problem-definition"><h3>무엇이 문제인가</h3><p>{t.problem}</p><p><strong>대상</strong> {t.people}</p></div>
  <div className="problem-why"><h3>왜 필요한가</h3><ul>{t.necessity.map(text=><li key={text}>{text}</li>)}</ul></div>
  <div className="problem-evidence"><h3>현행 업무와 확인할 병목</h3><p><strong className="problem-fact-label">공개 확인</strong> {t.fact}</p><SourceLinks ids={t.sourceIds}/><p><strong>대표 사례의 업무 흐름 개요 · 실제 처리순서 확인 전</strong> {t.current}</p><p className="problem-hypothesis"><strong>현업에서 검증할 가설</strong> {t.hypothesis}</p></div>
  <h3>어떤 결과를, 무엇으로 달성할 것인가</h3><Goals data={t}/>
  <div className="problem-cases"><h3>구체적인 개선 흐름</h3>{t.cases.map(([title,text])=><div key={title}><h4>{title}</h4><p>{text}</p></div>)}<p className="problem-boundary"><strong>수행 범위</strong> {t.boundary}</p></div>
  <section className="problem-pilot"><h3>2027년 첫 적용 검토 사례</h3><h4>{t.pilot.title}</h4><dl>{[['초기 범위',t.pilot.scope],['선정 이유',t.pilot.why],['착수 전 확인',t.pilot.conditions]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><Link to={pilot.to} className="problem-detail-link">{pilot.department} · 해당 상세설계 확인 →</Link></section>
  <section className="problem-measurement"><h3>개선효과의 측정방법</h3><p>수치 기준선·목표 미확정. 동일 사례·난도·조건에서 현행 / 규칙·SI 개선 / AI 결합 비교. 현업 책임자와 독립 검토자의 판정·측정기간·수락 기준은 적용 전 확정</p><div className="problem-table-wrap"><table><caption>{t.short} · 효과지표와 원기록</caption><thead><tr><th scope="col">지표</th><th scope="col">측정 단위·산식</th><th scope="col">필요한 원기록</th><th scope="col">해석 기준</th></tr></thead><tbody>{t.metrics.map(([name,formula,record,note])=><tr key={name}><th scope="row">{name}</th><td>{formula}</td><td>{record}</td><td>{note}</td></tr>)}</tbody></table></div></section>
  <section className="problem-related"><h3>이 문제와 연결되는 처·기존 설계</h3><p>{t.departments.join(' · ')}</p><details><summary>관련 제안 {t.projects.length}건의 역할·근거·상세설계 확인</summary><ul>{t.projects.map(p=><li key={p.id} data-problem-project={p.id}><div><Link to={p.to}>{p.department} · {p.title}</Link><small>{p.status}</small><p>{p.purpose}</p><p><strong>추가 처리</strong> {p.how}</p></div><div className="problem-project-evidence">{p.sourceRefs.slice(0,2).map((s,i)=><a key={s.id||i} href={s.url} target="_blank" rel="noopener noreferrer">{s.title||s.name}<span className="sr-only"> · 새 창</span></a>)}</div></li>)}</ul></details></section>
 </section>;
}
export function ProblemPlanning({route}){
 const[active,setActive]=useState('problem-overview');
 useEffect(()=>{const scroll=()=>{const line=(document.querySelector('.ts-header')?.getBoundingClientRect().height||100)+36,ids=['problem-overview',...plan.themes.map(t=>'problem-'+t.id),'problem-platform','problem-sequence'],before=ids.map(id=>({id,top:document.getElementById(id)?.getBoundingClientRect().top})).filter(x=>x.top!==undefined&&x.top<=line);setActive(before.at(-1)?.id||'problem-overview')};addEventListener('scroll',scroll,{passive:true});scroll();return()=>removeEventListener('scroll',scroll)},[]);
 useEffect(()=>{const id=location.hash.slice(1);if(!id)return;let second;const raf=requestAnimationFrame(()=>{second=requestAnimationFrame(()=>{const target=document.getElementById(id);if(target){target.scrollIntoView({block:'start'});target.focus({preventScroll:true})}})});return()=>{cancelAnimationFrame(raf);cancelAnimationFrame(second)}},[route]);
 function jump(e,id){if(e.ctrlKey||e.metaKey||e.shiftKey||e.altKey)return;e.preventDefault();const u=new URL(location.href);u.hash=id;navigate('index.html'+u.search+u.hash)}
 const outline=[['problem-overview','통합기획의 목적'],...plan.themes.map(t=>['problem-'+t.id,t.number+' '+t.short]),['problem-platform','CCK·기존 플랫폼 연결'],['problem-sequence','2027년 추진 순서']];
 return <article className="problem-planning" data-problem-planning={plan.date}><aside className="problem-outline"><strong>문제별 통합기획</strong><nav aria-label="문제별 본문 목차">{outline.map(([id,title])=><a href={'#'+id} key={id} onClick={e=>jump(e,id)} aria-current={active===id?'location':undefined}>{title}</a>)}</nav><Link to="solutions.html">전체 처의 상세기획 찾기 →</Link></aside><div className="problem-content">
  <PlanningModeSwitch route={route} problem/>
  <header className="problem-intro" id="problem-overview" tabIndex={-1}><small>{plan.intro.subtitle}</small><h1>{plan.intro.title}</h1><p className="problem-lead">{plan.intro.description}</p><p>{plan.intro.rationale}</p><Goals data={plan.intro}/><p className="problem-status">{plan.intro.status}</p></header>
  <section className="problem-overview"><h2>사업의 꼭지 · 네 가지 공공목적과 공통 기반</h2><div className="problem-table-wrap"><table><caption>문제 → 필요성 → 개선 방향의 연결</caption><thead><tr><th scope="col">문제의 중심</th><th scope="col">확보할 결과</th><th scope="col">첫 검토 대상</th></tr></thead><tbody>{plan.themes.map(t=><tr key={t.id}><th scope="row"><a href={'#problem-'+t.id} onClick={e=>jump(e,'problem-'+t.id)}>{t.number} {t.short}</a></th><td>{t.purpose}</td><td>{t.pilot.title}</td></tr>)}</tbody></table></div><p>{plan.intro.evidence}</p><p className="problem-mapping-note">{plan.intro.mapped}</p></section>
  {plan.themes.map(t=><Theme key={t.id} theme={t}/>)}
  <section className="problem-common" id="problem-platform" tabIndex={-1}><h2>하나의 기구축 AI 플랫폼에서 확장</h2><p>앞의 문제별 업무 스킬을 공통 실행·지식·검증 기반에 연결. 처마다 독립 AI 플랫폼을 다시 만드는 편성 대신 같은 기반에서 자료·업무조건·권한·전문 도구·인수 기준을 구분하는 구성</p><ol className="problem-platform-flow">{['요청·변경 접수','기준·증빙 연결','NOA 검토·실행안','담당자 판단','기존 시스템 처리','이용·조치·성과 확인'].map(t=><li key={t}>{t}</li>)}</ol><div className="problem-table-wrap"><table><caption>CCK 제품과 기존 시스템의 역할 · 기술 적용안</caption><thead><tr><th scope="col">구성</th><th scope="col">맡길 처리</th><th scope="col">적용 조건</th></tr></thead><tbody>{plan.platform.map(([name,role,boundary])=><tr key={name}><th scope="row">{name}</th><td>{role}</td><td>{boundary}</td></tr>)}</tbody></table></div><p>제품 설명과 TS 설치본의 실제 구현·성능은 별도 확인. 로컬 LLM·기존 서버를 적용 전제로 검토하되 가용량·보안·사용권·연계의 추가 작업량 확인 필요. 개인정보는 업무별 최소 항목·처리 근거·보유기간·접근범위 정의 후 이용</p><Link to="skill-pms.html#pms-direction">기존 AI 플랫폼 확장형 PMS 상세 확인 →</Link></section>
  <section className="problem-common" id="problem-sequence" tabIndex={-1}><h2>2027년 편성·검증 순서</h2><ol className="problem-phase-list">{plan.phases.map(([title,work,result])=><li key={title}><h3>{title}</h3><p>{work}</p><p>{result}</p></li>)}</ol><p>우선순위는 실제 국민·기업 부담, 문제의 반복성·중대도, 자료·권한·연계 준비도, 기존 기능과의 차이, 운영·검증 비용으로 결정. 축별 첫 사례는 비교 가능한 후보이며 적용대상·일정·사업비는 현업 확인 후 확정</p><div className="problem-final-links"><Link to="research-library.html?view=survey">처별 병목·추가 의견 확인</Link><Link to="research-library.html?view=planning#isp-start">ISP·실현가능성·편성 상세</Link><Link to="planning-documents.html">처별 한글 계획서</Link><Link to="index.html#official-duty-catalog">공식 담당업무 근거 확인</Link><Link to="downloads/problem-planning-20261008.md" download>문제별 통합기획 본문 내려받기</Link></div></section>
 </div></article>;
}
