import {AnalysisRefinement} from './AnalysisReview.jsx';
import React,{useEffect,useState}from'react';
import {Link,Out,Heading}from'./core.jsx';
import data from'./proposal-links.cjs';
import org from'./org-map-data.cjs';
import law from'./law-mapping.cjs';
import './proposal-links.css';
import {DrtRelated} from './DrtAssurance.jsx';
import {DepartmentDocuments} from './DepartmentDocuments.jsx';
export function SupplementLinks({binding}){const r=data.forLaw(binding);if(!r)return null;return <div className="supplement-links" data-binding={binding}><strong>{r.type}</strong><p>{r.note}</p>{r.profiles.map(id=>{const p=data.profileById[id];return <p key={id}><Link to={data.path(id)}>{p.name} · {p.title} ↗</Link><br/><small>{p.status}</small></p>})}</div>}
export function AssociationProposalLinks({id}){const r=data.forAssociation(id);if(!r)return null;return <div className="supplement-links" data-association={id}><h4>담당 조직·법정업무·상세제안 연결</h4><p><strong>{r.type}</strong> · {r.note}</p><div className="supplement-nav">{r.profiles.map(id=><Link key={id} to={data.path(id)}>{r.type} · {data.profileById[id].name} / {data.profileById[id].title}</Link>)}{r.orgs.map(id=><React.Fragment key={id}><Link to={'index.html?node='+id}>{org.nodes[id].name} · 조직지도</Link>{org.departmentByCode[id]&&<Link to={org.departmentByCode[id].folder+'/01_사업정의.html'}>{r.type} · {org.departmentByCode[id].title}</Link>}{id==='KATRI'&&<Link to='katri.html'>관련 문서기술 · KATRI 기존 적용안</Link>}</React.Fragment>)}{r.laws.map(id=><Link key={id} to={'legal/mapping.html?mode=law&law='+law.bindings.find(b=>b.id===id).lawId}>{law.bindings.find(b=>b.id===id).task} · 법령관계</Link>)}</div></div>}
function List({items}){return <ul>{items.map((v,i)=><li key={i}>{v}</li>)}</ul>}
function Table({title,heads,rows}){return <div className="supplement-table" tabIndex={0} role="region" aria-label={title}><table><caption>{title}</caption><thead><tr>{heads.map(h=><th scope="col" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table></div>}
export function Profile({p,embedded=false}){const bindings=data.legalLinks.filter(l=>l.profiles.includes(p.id));return <article className="supplement-profile" id={'proposal-'+p.id} data-profile={p.id} tabIndex={-1}>
 <header><span>{p.group} · {p.relation}</span><h2>{p.name}</h2><h3>{p.title}</h3><p className={p.pending?'supplement-status pending':'supplement-status'}>{p.status}</p><p>{p.ownerStatus}</p></header>
 {!embedded&&<DepartmentDocuments profileId={p.id}/>}
 <h3 id={'proposal-'+p.id+'-why'} tabIndex={-1}>왜 필요한가 · 무엇을 개선할 것인가</h3><dl><dt>현재 수행업무·기구축 기반</dt><dd>{p.known}</dd><dt>목적·공공 편익</dt><dd>{p.goal}</dd><dt>검증할 현행 한계</dt><dd>{p.gap}</dd><dt>누가·어디서</dt><dd>{p.pending?'담당 조직·과업 범위 확인 후 실제 자료관리자·검토자·승인자를 지정할 대상. 현재 배정된 것으로 간주하지 않음.':p.name+'의 해당 업무 담당자·검토자와 신청·협력 주체. 기존 업무시스템과 허용된 자료공간에서 적용하는 제안.'}</dd><dt>언제</dt><dd>{data.common.when}</dd></dl>
 <p className="supplement-note">{data.common.why}</p>
 <h3 id={'proposal-'+p.id+'-evidence'} tabIndex={-1}>공식 근거 · 확인 범위</h3><div className="supplement-sources">{p.sourceIds.map(id=>{const s=data.sources[id];return <section key={id}><Out url={s.url}>{s.title}</Out><p>{s.fact}</p><small>게시 {s.published} · 열람 {s.checkedAt}<br/>{s.limit}</small></section>})}</div>
 <AnalysisRefinement id={p.id}/><h3 id={'proposal-'+p.id+'-how'} tabIndex={-1}>어떻게 해결할 것인가 · AI와 기존 시스템의 역할</h3><dl><dt>입력자료</dt><dd><List items={p.inputs}/></dd><dt>NOA·aRDa 추가 처리</dt><dd>{p.llm}</dd><dt>일반 SI·규칙·기존 시스템</dt><dd>{p.rules}</dd><dt>사람·공식 권한</dt><dd>{p.human}</dd></dl>
 <h3 id={'proposal-'+p.id+'-flow'} tabIndex={-1}>업무 흐름 · 사건별 검토에서 완료 확인까지</h3><ol className="supplement-flow">{p.flow.map((v,i)=><li key={v}><b>{String(i+1).padStart(2,'0')}</b><span>{v}</span></li>)}</ol>
 <p>산출물: 해당 사건의 적용조건·원문근거, 미확인 질문, 담당자 검토안, 보완·처리결과 대조 기록. 문서 생성 완료와 공식 업무 완료의 상태 구분.</p>
 <h3 id={'proposal-'+p.id+'-architecture'} tabIndex={-1}>구현 구조 · 업무별 입력과 공통 기반의 결합</h3><p>{data.common.technology}</p><Table title={p.name+' 적용 구성요소'} heads={['계층','구성','역할·연계 경계']} rows={data.common.architecture}/>
 <h3 id={'proposal-'+p.id+'-privacy'} tabIndex={-1}>데이터·개인정보 처리</h3><ol className="supplement-dataflow">{data.common.dataflow.map(v=><li key={v}>{v}</li>)}</ol><p>{data.common.privacy}</p><p className="supplement-note">{p.human}</p>
 <h3 id={'proposal-'+p.id+'-metrics'} tabIndex={-1}>정량효과 · 측정할 3개 지표</h3><Table title={p.title+' · 실측 전 측정안'} heads={['지표','산식·관측단위','기준선·목표']} rows={p.metrics.map(m=>[m.name,m.formula,'기준선 미확보 · 목표 미설정'])}/><p>{data.common.measurement}</p>
 <h3 id={'proposal-'+p.id+'-requirements'} tabIndex={-1}>요구사항·실증·편성 조건</h3><Table title={p.name+' 추가과업 수락기준안'} heads={['ID','요구','검증조건']} rows={data.common.requirements}/><p><strong>중단·축소:</strong> {p.stop||data.common.stop}</p><p>{data.common.cost}</p>
 <nav className="supplement-nav" aria-label={p.name+' 관련자료'}>{p.org&&<Link to={'index.html?node='+p.org}>조직지도에서 보기</Link>}{bindings.map(b=><Link key={b.binding} to={'legal/mapping.html?mode=law&law='+law.bindings.find(x=>x.id===b.binding).lawId}>{law.bindings.find(x=>x.id===b.binding).task} · 법정업무 관계</Link>)}{data.associationLinks.filter(r=>r.profiles.includes(p.id)).map(r=><Link key={r.proposal} to={'associations.html#proposal-'+r.proposal}>협회 후보 {r.proposal} · {r.type}</Link>)}<a href={embedded?'#integrated-department':'#supplement-top'}>{embedded?'처별 제안 처음으로 ↑':'목차로 ↑'}</a></nav>
 </article>}
export function ProposalLinks(){useEffect(()=>{let next;const first=requestAnimationFrame(()=>{next=requestAnimationFrame(()=>{if(!location.hash)return;let id=location.hash.slice(1);try{id=decodeURIComponent(id)}catch{return}const target=document.getElementById(id);target?.focus({preventScroll:true});target?.scrollIntoView({block:'start',behavior:'instant'})})});return()=>{cancelAnimationFrame(first);if(next)cancelAnimationFrame(next)}},[]);const requested=new URLSearchParams(location.search).get('unit'),selected=data.profileById[requested];const[q,setQ]=useState(''),[group,setGroup]=useState('all');const groups=[...new Set(data.profiles.map(p=>p.group))];const rows=data.profiles.filter(p=>(!selected||p.id===selected.id)&&(group==='all'||p.group===group)&&[p.name,p.title,p.known,p.goal].join(' ').includes(q.trim()));
 return <div className="page supplement-page" id="supplement-top"><Heading label={'상세제안 연결 보완 · '+data.date} title={selected?selected.name+' · 상세제안':'조직·법정업무·협회에서 상세제안으로'} desc={selected?selected.goal:'기존 미연결 조직의 근거와 업무별 검토안을 한 문서에서 확인. 확정 사업과 현장 검증 전 기획의 구분.'}/>
 {selected?<div className="supplement-summary"><p><strong>{selected.title}</strong></p><p>{selected.status}</p><p>{selected.ownerStatus}</p></div>:<div className="supplement-summary"><p><strong>보완 범위</strong> · 기존 미연결 32개 조직 항목의 검토경로 + 철도 자격·형식승인 별도 업무 + KATRI 2개 업무 + 운송플랫폼 선행 조사</p><p>32개는 25개 처·3개 실·4개 현장 묶음. 기존 13개 처 대표제안 유지. {data.profiles.length}개 카드는 독립 신규사업 수가 아닌 업무별 검토단위.</p><p>공식 업무접점과 기존 기능은 근거로 확인. 실제 미해결 문제·구매수요·효과는 검증 전. AI미래전략실의 배정 및 운송플랫폼 과업 편성은 확인 대기.</p><div className="supplement-nav"><Link to="index.html?view=map">조직 연결지도</Link><Link to="legal/mapping.html?mode=law">법정업무 매핑</Link><Link to="associations.html">협회·민원 조사</Link><Link to="planning-documents.html">처별 한글 계획서·대가산정·도식집</Link><Link to="downloads/proposal-links.md" download>상세 검토문서 다운로드</Link></div></div>}
 {(!selected||selected.org==='MR')&&<DrtRelated/>}
 {requested&&!selected&&<p role="status">지정한 검토안이 없어 전체 목록 표시.</p>}
 {selected?<p className="supplement-note">{selected.name} 지정 보기 · <Link to="proposal-links.html">전체 상세검토안 연속으로 보기</Link></p>:<div className="supplement-filter"><label>조직·업무 검색<input value={q} onChange={e=>setQ(e.target.value)} placeholder="예: 기술승인, 철도, 예산"/></label><label>업무 계통<select value={group} onChange={e=>setGroup(e.target.value)}><option value="all">전체</option>{groups.map(g=><option key={g}>{g}</option>)}</select></label><button onClick={()=>{setQ('');setGroup('all')}}>검색 초기화</button><p role="status">{rows.length}개 검토안</p></div>}
 <nav className="supplement-index" aria-label="상세검토안 본문 목차">{rows.map(p=><a key={p.id} href={'#proposal-'+p.id}><strong>{p.name}</strong><span>{p.title}</span>{p.pending&&<small>배정·편성 확인 필요</small>}</a>)}</nav>
 {rows.map(p=><Profile key={p.id} p={p}/>)}{!rows.length&&<p role="status">검색 결과 없음. 조직명 일부 또는 업무 계통으로 다시 검색.</p>}
 </div>}
