import React,{useEffect,useState,useRef} from 'react';
import {href,Out,Link} from './core.jsx';
import design from './proposal-e2e-diagrams.cjs';
import manifest from './proposal-diagram-assets.json';
import business from './proposal-business-language.cjs';
import './proposal-diagrams.css';
function SpecTable({title,heads,rows}){return <div className="diagram-spec-table" role="region" aria-label={title} tabIndex={0}><table><caption>{title}</caption><thead><tr>{heads.map(h=><th scope="col" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j} data-label={heads[j]}>{v}</td>)}</tr>)}</tbody></table></div>}
function description(p,type){const b=business.byId[p.id];return type==='overall'?`${p.department} ${p.shortTitle}. 기존 TS AI 플랫폼에 NOA의 업무 검토, aRDa의 자료 연결, Grantee의 자료 비교와 기존 전문도구를 연계. ${p.authority}가 결정하고 처리 결과 확인.`:type==='service'?`${business.steps(p).join(' → ')}. ${b.when}. ${b.action}.`:type==='data'?`${p.source}의 자료를 같은 업무로 연결하고 담당자 검토와 처리 결과 확인. ${p.privacy}.`:`${p.precondition}을 준비하고 기존 업무망·서버에 NOA/aRDa/Grantee 연계 검토. 자료 제공·운영·비용 조건은 담당자 협의 대상.`;}
function DiagramImage({p,a,type}){const [failed,setFailed]=useState(false),[retry,setRetry]=useState(0),zoom=useRef(null);useEffect(()=>{setFailed(false);setRetry(0)},[a.path]);const repeat=()=>{setFailed(false);setRetry(n=>n+1);requestAnimationFrame(()=>zoom.current?.focus())};return <><a ref={zoom} className="proposal-diagram-image" href={href(a.path)} target="_blank" rel="noopener noreferrer" aria-label={p.shortTitle+' '+design.labels[type]+' 원본 확대 · 새 탭'}><img key={retry} src={href(a.path)+(retry?'?retry='+retry:'')} alt={description(p,type)} loading="lazy" decoding="async" width={a.width} height={a.height} onError={()=>setFailed(true)} onLoad={()=>setFailed(false)} style={failed?{display:'none'}:undefined}/></a>{failed&&<div className="diagram-image-error" role="alert"><p>이미지를 불러오지 못했습니다. 아래 설계 명세를 계속 읽거나 원본을 확인할 수 있습니다.</p><button type="button" onClick={repeat}>이미지 다시 불러오기</button><a href={href(a.path)} target="_blank" rel="noopener noreferrer">원본 이미지 확인 ↗</a></div>}<figcaption><span>{p.id} · {design.labels[type]} · 이미지 모델 제작{a.businessDate?' · 업무 설명 개정본 v'+a.revision:(a.revision?' · 한글 표기 교정본 v'+a.revision:'')}</span><a href={href(a.path)} target="_blank" rel="noopener noreferrer">원본 확대 · 새 탭 ↗</a></figcaption></>}
export function ProposalDiagram({projectId,type}){const p=design.byId[projectId];if(!p)return null;const a=manifest.assets.find(a=>a.id===projectId&&a.type===type),id='diagram-'+projectId+'-'+type;return <section className="proposal-diagram-section" id={id} data-proposal-diagram={type} data-diagram-project={projectId}><h4 tabIndex={-1} id={'heading-'+id}>{design.labels[type]}</h4><figure>{a?<DiagramImage p={p} a={a} type={type}/>:<figcaption>도식 생성·검수 중. 아래 정확한 설계 명세 참조.</figcaption>}</figure>
 {type==='overall'&&<><p><b>연결 원칙</b> 기존 플랫폼에서 요청 접수 → aRDa로 관련 자료 연결 → NOA로 검토할 일 구성 → Grantee로 자료 일치 여부 비교 → 전문도구로 계산·조회 → 담당자 결정 → 기존 업무 절차로 처리 → 실제 처리 결과 확인 → 추가 안내와 후속 검토.</p><SpecTable title={p.id+' 구성요소의 업무 책임'} heads={['구성','이 과제에서 맡는 처리','결과·책임 경계']} rows={[
 ['기존 TS AI 플랫폼','기존 로그인·자료·모델·서비스 기반의 활용','현재 설치·계약 범위와 추가 적용할 업무 확인'],['NOA',business.capability(p),'관련 자료와 확인할 질문·다음 업무의 제안. 최종 판단은 담당자'],['aRDa · 적용 검토',p.source+'의 원문·작성시점·적용판본 연결','자료 이용범위와 제공 담당자 확인'],['Grantee · 적용 검토','업무기준·제출자료·실제 처리기록의 일치 여부 확인','업무별 비교 항목·규칙을 구성하고 실제 사례로 정확성 확인'],['기존 규칙·전문도구',p.tool,'수치 계산·정형 규칙은 해당 전문도구의 결과 사용'],['담당자·기존 업무 절차',p.authority+' 검토·결정 후 해당 기관·시스템에 전달','접수·등록·실제 시행을 각각 확인하고 같은 요청의 중복 처리 방지']
 ]}/></>}
 {type==='service'&&<ServiceExplanation p={p}/>}
 {type==='data'&&<SpecTable title={p.id+' 데이터·처리·개인정보 명세'} heads={['구간','입력·처리','보존·확인']} rows={[
 ['원자료',p.inputs.join(' / '),'허용 조회·파일 반입·처리근거 확인'],['연결키',p.key,'원문 위치·시점·판본·공식 참조를 함께 유지'],['검토 파생물',p.output,'AI 추출·담당자 수정·공식 확정을 구별'],['보호 경계',p.privacy,'원식별정보를 NOA 문맥에 불필요하게 복제하지 않는 제안'],['후속 집계','공식 결과 참조·미완료/결측 분리·비식별 집계','개별 지표의 분모·기간·노출량·비교조건 적용'],['정정·삭제',p.data.retention,'검색·파생본·내보내기·백업의 권한/보존 전파 확인']
 ]}/>}
 {type==='environment'&&<><p><b>업무 선행조건</b> {p.precondition}</p><SpecTable title={p.id+' 요구환경·확인 항목'} heads={['환경','요구·검증할 조건']} rows={p.environment.groups}/><dl className="diagram-facts"><div><dt>연계가 어려운 경우</dt><dd>기존 담당자의 업무 방식으로 처리하고, 연계 복구 후 같은 요청의 처리 결과 확인.</dd></div><div><dt>과제 고유 경계</dt><dd>{p.boundary}</dd></div>{p.id==='MR-02'&&<div><dt>선택 모듈</dt><dd>전화망·STT·지도·문자·기사앱은 실제 사용권·현장 성능·서버 동시성·통신/SW요금 확인 후 적용. 초기 입력은 상담원 기록·허용 전사 텍스트.</dd></div>}{p.id==='EX11-01'&&<div><dt>ERP 쓰기 조건</dt><dd>초기 범위는 ERP 읽기·검토안 작성·기존 절차 인계. 전표 등록은 현재 초기 범위에서 제외한 별도 후속 범위. 실제 연계·쓰기권한·멱등·결과 조회 시험 후 확장 여부 검토. 지급·마감·취소 자동실행 제외.</dd></div>}</dl></>}
 </section>}
function ServiceExplanation({p}){const b=business.byId[p.id];return <div data-business-service={p.id}><ol className="diagram-service-steps">{business.steps(p).map((s,i)=><li key={s}><b>{i+1}</b>{s}</li>)}</ol><section className="diagram-business-cases"><h5>상황별 처리와 안내</h5><dl className="diagram-facts">{(b.situations||[[b.when,b.action],['자료나 담당기관의 답변이 필요한 경우',`${b.queryLabel}. 필요한 자료·답변과 확인할 담당자를 명시하고, 확인되지 않은 사항을 확정된 결과와 구분.`],['처리 이후 확인할 내용',p.completion]]).map(([title,text])=><div key={title}><dt>{title}</dt><dd>{text}</dd></div>)}</dl></section>{b.roles&&<SpecTable title="DRT 업무와 제품별 역할" heads={['담당·제품','서비스에서 수행할 일']} rows={b.roles}/>}<p className="diagram-business-result"><b>이 서비스로 이루려는 결과</b> {b.result||p.completion}</p></div>}
export function ProposalDiagramSuite({projectId}){useEffect(()=>{let first,second;const reveal=()=>{cancelAnimationFrame(first);cancelAnimationFrame(second);let id;try{id=decodeURIComponent(location.hash.slice(1))}catch{return}if(!id.startsWith('diagram-'+projectId+'-'))return;first=requestAnimationFrame(()=>{const target=document.getElementById(id);if(!target)return;for(let el=target.parentElement;el;el=el.parentElement)if(el.tagName==='DETAILS')el.open=true;second=requestAnimationFrame(()=>{target.scrollIntoView({block:'start'});target.querySelector('h4')?.focus({preventScroll:true})})})};reveal();addEventListener('hashchange',reveal);addEventListener('popstate',reveal);return()=>{cancelAnimationFrame(first);cancelAnimationFrame(second);removeEventListener('hashchange',reveal);removeEventListener('popstate',reveal)}},[projectId]);const p=design.byId[projectId];if(!p)return null;return <section className="proposal-diagram-suite" data-diagram-suite={p.id} aria-label={p.shortTitle+' 상세 도식·End-To-End 연계'}><header><h3>서비스와 제품별 업무 역할</h3><p>{design.common.status}</p></header><nav aria-label="4종 상세 도식 바로가기">{design.types.map(type=><a key={type} href={'#diagram-'+p.id+'-'+type}>{design.labels[type]}</a>)}</nav><SpecTable title={p.id+' End-To-End · CCK 제품과 기존 플랫폼의 연결'} heads={['업무 단계','적용 위치·제품','처리 내용·다음 안내']} rows={business.flow(p)}/>{design.types.map(type=><ProposalDiagram key={type} projectId={p.id} type={type}/>)}<details className="diagram-product-evidence"><summary>개발·운영 조건과 CCK 제품 근거</summary><SpecTable title={p.id+' 개발·연계 상세'} heads={['단계','제품·연계','기술 조건']} rows={p.e2e}/><SpecTable title="CCK 공통제품·확장 책임" heads={['제품·기반','위치·역할','구현 확인 조건']} rows={design.products}/>{design.productSources.map(s=><p key={s.id}><b>{s.id} · {s.url?<Out url={s.url}>{s.title}</Out>:s.title}</b><br/>{s.locator} · {s.level} · {s.date} · 확인 {s.checked}<br/>{s.limit}</p>)}</details><p className="diagram-downloads"><Link download to="downloads/proposal-diagrams/design.md">전체 도식 설계·텍스트 명세 MD ↓</Link><Link download to="downloads/proposal-diagrams/design.json">과제별 노드·흐름·요구환경 JSON ↓</Link></p></section>}
