import React from 'react';
import {href,Out} from './core.jsx';
import engineering from './proposal-engineering.cjs';
import './proposal-engineering.css';
function Table({title,heads,rows}){return <table className="engineering-table"><caption>{title}</caption><thead><tr>{heads.map(h=><th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{row.map((v,j)=><td key={j} data-label={heads[j]}>{v}</td>)}</tr>)}</tbody></table>}
function Fields({rows}){return <dl className="engineering-fields">{rows.map(([k,v])=><div key={k}><dt>{k}</dt><dd>{Array.isArray(v)?<ul>{v.map((x,i)=><li key={i}>{x}</li>)}</ul>:v}</dd></div>)}</dl>}
export function ProposalEngineering({projectId}){const p=engineering.byId[projectId];if(!p)return null;const id='engineering-'+p.id;return <section className="proposal-engineering" id={id} tabIndex={-1} data-engineering-project={p.id} aria-labelledby={id+'-title'}>
 <header><h3 id={id+'-title'}>개발범위 · 검증 · 대가 설계</h3><p><b>{p.id} · {p.reviewStatus}</b> · {p.selection}</p><p>{p.status}</p></header>
 <section id={id+'-scope'}><h4>1. 우선 적용할 업무와 구현방법</h4><Fields rows={[
 ['확인할 현재 한계',p.gap],['우선 적용범위',p.scope],['업무 연결 단위',p.key],['담당자에게 제공할 결과',p.prepared],['담당자·업무 완료',p.authority+' / '+p.completion],['추가 개발 차분',p.newWork],['적용 경계',p.boundary]
 ]}/><Table title={p.id+' 업무별 CCK 구현 역할'} heads={['적용 위치','구현할 처리']} rows={p.productPlan}/><p className="engineering-note">공식 업무 근거는 담당영역·절차의 근거. 현재 병목의 규모와 AI 필요성·제품 성능은 실제 사례 및 비교시험으로 별도 확인. 아래 요구사항은 현업 확인 후 선택·조정할 후보.</p></section>
 <section id={id+'-requirements'}><h4>2. 요구사항 · 산출물 · 인수시험</h4><div className="engineering-requirements">{p.requirements.map(r=><article key={r.id} data-engineering-requirement={r.id}><h5>{r.title} <small>{r.id}</small></h5><Fields rows={[
 ['입력',r.input],['개발·처리',r.work],['산출물',r.output],['책임',r.owner],['인수·시험',r.acceptance],['추적',r.testId+' / 대가 '+r.costId]
 ]}/></article>)}</div><p className="engineering-note">요구 ID는 기획용 관리번호. 공식 RFP 번호·기능점수·인월과 다른 단위. 공통 접근권한·실행통제·부하·복구·변경 요구는 공통 개발에서 한 번 관리.</p></section>
 <section id={id+'-interfaces'}><h4>3. 서비스 연계 · 데이터 · 예외 처리</h4><Fields rows={[
 ['입력 자료',p.inputs],['보호할 정보',p.privacy],['데이터 책임','원문·기준 판본은 지정 원천, 공식 판단·거래는 담당기관·기존 시스템, AI 검토안·수정 이유는 추가 업무기록으로 구별. 원천 갱신 시 이전 검토안의 유효성 재확인'],['보존·정정','처리근거·필요 필드·보존기간·삭제 범위는 자료 담당자 확정. 원문·추출·검색·요약·내보내기·로그·백업을 함께 검토']
 ]}/>{p.interfaces.map(x=><article className="engineering-contract" key={x.id}><h5>{x.title} <small>{x.id} · {x.stage}</small></h5><Fields rows={[
 ['연결',x.direction],['초기 방식',x.mode],['요청할 항목',x.request],['반환할 항목',x.response],['예외 처리',x.failure],['연계 시험',x.acceptance],['요구·시험',x.requirementIds.join(' / ')+' → '+x.testIds.join(' / ')]
 ]}/>{x.optionalWrite&&<p className="engineering-note"><b>후속 쓰기 조건 · 초기 범위 제외</b> {x.optionalWrite.condition} · {x.optionalWrite.fields.join(' / ')}</p>}</article>)}<Table title={p.id+' 업무 고유 반례·시험안'} heads={['상황','기대 처리']} rows={p.special.map(x=>[(x.stage?x.stage+' / ':'')+x.case,x.expected])}/><details><summary>공통 보안·AI 윤리·운영 요구</summary><Table title="공통 기반 1회 검증" heads={['공통 요구','개발·운영 조건','시험·인수']} rows={engineering.commonRequirements.map(r=>[r.id+' · '+r.title,r.work,r.acceptance+' / '+r.testId])}/><p>{engineering.legalRule}</p><p>{engineering.environmentRule}</p><p>독립 법률·영향평가·감리·기관 보안 심의 완료를 의미하지 않는 설계안. 적용 판단과 결과는 정식 수행 단계에서 별도 확보.</p></details></section>
 <section id={id+'-measurement'}><h4>4. 기대효과 · 수집기록 · 비교방법</h4><p>현재 기준선·목표값 미확정. 지표별 원자료·분모·관측기간·오류 중요도를 합의한 뒤 목표 설정. 아래 기록은 확보·측정 완료 자료가 아닌 수집·평가 계획.</p><div className="engineering-measures">{p.measurement.map(m=><article key={m.id} data-engineering-metric={m.id}><h5>{m.title}</h5><Fields rows={[
 ['측정식',m.formula],['수집할 기록',m.records],['자료 상태',m.recordsStatus],['측정·비교',m.comparison],['해석 조건',m.condition],['책임·판정',m.owner+' / '+m.decision]
 ]}/></article>)}</div></section>
 <section id={id+'-delivery'}><h4>5. 2027년 수행단계 · 인수조건</h4><p>{engineering.scheduleRule}</p><Table title={p.id+' 단계별 산출물·진입 판단'} heads={['단계·업무','산출물','다음 단계 조건·중단 기준']} rows={p.stages.map(s=>[s.title+' / '+s.work,s.outputs.join(' / '),s.exit+' / '+s.stop+' / 책임: '+s.owner])}/></section>
 <section id={id+'-cost'}><h4>6. 처별 추가 공수 · 대가산정 근거</h4><p>{engineering.costRule}</p><Table title={p.id+' 증분 WBS·산정 입력'} heads={['비목·작업','수량을 정할 근거','연결·중복 제외']} rows={p.workPackages.map(w=>[w.id+' · '+w.item,w.quantityBasis,w.rule+' / '+w.requirementIds.join(' · ')])}/><p className="engineering-note">수량·단가·금액·인월 미산정. 신규 하드웨어 구매 제외는 사용자 조건이며, 제품 사용권·운영비·통신비가 0원이라는 의미가 아님. 기존 비용 참고표를 현 개발범위의 견적으로 합산하지 않는 기준.</p><Table title="수행 역할·투입량 결정 조건" heads={['역할','담당 산출물','작업량 근거']} rows={engineering.staff}/><details><summary>공통 개발 1회 · 조건부 비용 · 산정방법</summary><Table title="공통 코어 1회 · 처마다 중복 산정 제외" heads={['비목','확인할 입력','산정 경계']} rows={engineering.commonCosts.map(w=>[w.id+' · '+w.item,w.evidence,w.rule])}/><Table title="제품·운영·별도 검토의 조건부 비용" heads={['비목','확인할 입력','산정 경계']} rows={engineering.conditionalCosts.filter(w=>w.id!=='CHANNEL-01'||p.id==='MR-02').map(w=>[w.id+' · '+w.item,w.evidence,w.rule])}/><ul>{engineering.pricing.map((r,i)=><li key={i}>{Array.isArray(r)?r.join(' · '):JSON.stringify(r)}</li>)}</ul></details></section>
 <section id={id+'-evidence'}><h4>7. 적용 근거 · 제품 확인범위</h4><ul className="engineering-source-list">{p.evidence.slice(0,3).map((s,i)=><li key={s.id||i}><b>{s.id} · {s.url?<Out url={s.url}>{s.title}</Out>:s.title}</b><p>{s.fact||s.value}</p><small>{s.published||'게시일 미표시'} · 확인 {s.checkedAt||s.accessed||'기존 원장 참조'} · {s.limit||p.boundary}</small></li>)}</ul><details><summary>제품 근거·구현 확인표와 공공 RFP 적용 사례</summary><Table title="공급사 설명과 TS 재사용 검증의 구분" heads={['제품·확인 수준','추가 적용','검증 조건']} rows={engineering.productChecks.map(r=>[r[0]+' · '+r[2],r[3],r[4]])}/>{engineering.precedents.map(s=><article className="engineering-source" key={s.id}><h5>{s.url?<Out url={s.url}>{s.title}</Out>:s.title}</h5><p>{s.date} · {s.locator} · {s.verified}</p><p><b>재사용할 설계</b> {s.lesson}</p><p><b>적용 한계</b> {s.limit}</p></article>)}{engineering.guides.map(s=><article className="engineering-source" key={s.id}><h5><Out url={s.url}>{s.title}</Out></h5><p>{s.date} · {s.locator} · {s.fact}</p><p>{s.limit}</p></article>)}</details></section>
 <p className="engineering-downloads"><a download href={href(p.downloads.md)}>이 과제 개발·검증·대가 설계 MD 다운로드</a><a download href={href(p.downloads.json)}>이 과제 요구사항·연계·시험 JSON 다운로드</a></p>
 </section>}
