import React,{useEffect,useState,useRef} from 'react';
import {href,Out,Link} from './core.jsx';
import design from './proposal-e2e-diagrams.cjs';
import manifest from './proposal-diagram-assets.json';
import './proposal-diagrams.css';
function SpecTable({title,heads,rows}){return <div className="diagram-spec-table" role="region" aria-label={title} tabIndex={0}><table><caption>{title}</caption><thead><tr>{heads.map(h=><th scope="col" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j} data-label={heads[j]}>{v}</td>)}</tr>)}</tbody></table></div>}
function description(p,type){return type==='overall'?`${p.department} ${p.shortTitle}. 기존 TS AI 플랫폼 안에서 NOA가 ${p.ai}을 계획하고 aRDa 근거와 Grantee 대사 후보·${p.tool}를 연결. ${p.authority} 확정 이후 공식 결과를 재조회하는 구성.`:type==='service'?`${p.steps.join(' → ')}. ${p.exception}. 담당자 확정과 공식 결과 확인을 구분하는 업무 흐름.`:type==='data'?`${p.source}에서 ${p.key}로 원문·판본·근거를 연결하고 검토안·확정기록·공식 결과를 대사. ${p.privacy}.`:`${p.precondition} 확보를 선행조건으로 기존 업무망·로컬 서버·NOA/aRDa/Grantee 후보를 배치. 실제 사양·사용권·API·복구목표는 확인 대상.`;}
function DiagramImage({p,a,type}){const [failed,setFailed]=useState(false),[retry,setRetry]=useState(0),zoom=useRef(null);useEffect(()=>{setFailed(false);setRetry(0)},[a.path]);const repeat=()=>{setFailed(false);setRetry(n=>n+1);requestAnimationFrame(()=>zoom.current?.focus())};return <><a ref={zoom} className="proposal-diagram-image" href={href(a.path)} target="_blank" rel="noopener noreferrer" aria-label={p.shortTitle+' '+design.labels[type]+' 원본 확대 · 새 탭'}><img key={retry} src={href(a.path)+(retry?'?retry='+retry:'')} alt={description(p,type)} loading="lazy" decoding="async" width={a.width} height={a.height} onError={()=>setFailed(true)} onLoad={()=>setFailed(false)} style={failed?{display:'none'}:undefined}/></a>{failed&&<div className="diagram-image-error" role="alert"><p>이미지를 불러오지 못했습니다. 아래 설계 명세를 계속 읽거나 원본을 확인할 수 있습니다.</p><button type="button" onClick={repeat}>이미지 다시 불러오기</button><a href={href(a.path)} target="_blank" rel="noopener noreferrer">원본 이미지 확인 ↗</a></div>}<figcaption><span>{p.id} · {design.labels[type]} · 이미지 모델 제작</span><a href={href(a.path)} target="_blank" rel="noopener noreferrer">원본 확대 · 새 탭 ↗</a></figcaption></>}
export function ProposalDiagram({projectId,type}){const p=design.byId[projectId];if(!p)return null;const a=manifest.assets.find(a=>a.id===projectId&&a.type===type),id='diagram-'+projectId+'-'+type;return <section className="proposal-diagram-section" id={id} data-proposal-diagram={type} data-diagram-project={projectId}><h4 tabIndex={-1} id={'heading-'+id}>{design.labels[type]}</h4><figure>{a?<DiagramImage p={p} a={a} type={type}/>:<figcaption>도식 생성·검수 중. 아래 정확한 설계 명세 참조.</figcaption>}</figure>
 {type==='overall'&&<><p><b>연결 원칙</b> 기존 플랫폼 진입 → aRDa 근거 → NOA 계획 → Grantee 증거 대사 → 전문도구 계산·조회 → 담당자 확정 → 기존 절차 인계 → 공식 결과 대사 → 근거·계획 갱신.</p><SpecTable title={p.id+' 구성요소의 업무 책임'} heads={['구성','이 과제에서 맡는 처리','결과·책임 경계']} rows={[
 ['기존 TS AI 플랫폼','기존 로그인·자료·모델·서비스 기반 재사용 검토','설치본·인수·계약 범위 대조'],['NOA',p.ai,'근거·미확인·확인질문·Task 제안. 공식 판단은 담당자'],['aRDa 후보',p.source+'의 판본·원문 위치·ACL','원문 저장소 대체/연계 여부·사용권 확인'],['Grantee 후보','업무기준–제출증거–공식기록 대사·근거 보고','업무별 스킬·필드·규칙·정답셋 추가. TS 적용 전 검증'],['규칙·전문도구',p.tool,'수치·정형 규칙은 검증된 도구. LLM 자유계산 제외'],['공식 결정·원천',p.authority+' 검토·확정 후 허용 인계','실제 반영·수신·시행 증거 재조회. 응답 유실 시 중복 실행 차단']
 ]}/></>}
 {type==='service'&&<><ol className="diagram-service-steps">{p.steps.map((s,i)=><li key={s}><b>{i+1}</b>{s}</li>)}</ol><dl className="diagram-facts"><div><dt>보완·재계획</dt><dd>{p.exception}</dd></div><div><dt>확인 불가·권한 미확보</dt><dd>추정으로 완료 처리하지 않고 보완·대기. 기존 수기 검토로 복귀 후 사건ID 대사.</dd></div><div><dt>공식 완료 증거</dt><dd>{p.completion}</dd></div></dl></>}
 {type==='data'&&<SpecTable title={p.id+' 데이터·처리·개인정보 명세'} heads={['구간','입력·처리','보존·확인']} rows={[
 ['원자료',p.inputs.join(' / '),'허용 조회·파일 반입·처리근거 확인'],['연결키',p.key,'원문 위치·시점·판본·공식 참조를 함께 유지'],['검토 파생물',p.output,'AI 추출·담당자 수정·공식 확정을 구별'],['보호 경계',p.privacy,'원식별정보를 NOA 문맥에 불필요하게 복제하지 않는 제안'],['후속 집계','공식 결과 참조·미완료/결측 분리·비식별 집계','개별 지표의 분모·기간·노출량·비교조건 적용'],['정정·삭제',p.data.retention,'검색·파생본·내보내기·백업의 권한/보존 전파 확인']
 ]}/>}
 {type==='environment'&&<><p><b>업무 선행조건</b> {p.precondition}</p><SpecTable title={p.id+' 요구환경·확인 항목'} heads={['환경','요구·검증할 조건']} rows={p.environment.groups}/><dl className="diagram-facts"><div><dt>장애·권한 미확보 시</dt><dd>{p.environment.fallback}</dd></div><div><dt>과제 고유 경계</dt><dd>{p.boundary}</dd></div>{p.id==='MR-02'&&<div><dt>선택 모듈</dt><dd>전화망·STT·지도·문자·기사앱은 실제 사용권·현장 성능·서버 동시성·통신/SW요금 확인 후 적용. 초기 입력은 상담원 기록·허용 전사 텍스트.</dd></div>}{p.id==='EX11-01'&&<div><dt>ERP 쓰기 조건</dt><dd>승인 초안 인계가 기본. 실제 연계·쓰기권한·멱등·결과 조회 확인 시 제한 등록 검토. 지급·마감·취소 자동실행 제외.</dd></div>}</dl></>}
 </section>}
export function ProposalDiagramSuite({projectId}){useEffect(()=>{let first,second;const reveal=()=>{cancelAnimationFrame(first);cancelAnimationFrame(second);let id;try{id=decodeURIComponent(location.hash.slice(1))}catch{return}if(!id.startsWith('diagram-'+projectId+'-'))return;first=requestAnimationFrame(()=>{const target=document.getElementById(id);if(!target)return;for(let el=target.parentElement;el;el=el.parentElement)if(el.tagName==='DETAILS')el.open=true;second=requestAnimationFrame(()=>{target.scrollIntoView({block:'start'});target.querySelector('h4')?.focus({preventScroll:true})})})};reveal();addEventListener('hashchange',reveal);addEventListener('popstate',reveal);return()=>{cancelAnimationFrame(first);cancelAnimationFrame(second);removeEventListener('hashchange',reveal);removeEventListener('popstate',reveal)}},[projectId]);const p=design.byId[projectId];if(!p)return null;return <section className="proposal-diagram-suite" data-diagram-suite={p.id} aria-label={p.shortTitle+' 상세 도식·End-To-End 연계'}><header><h3>기존 AI 플랫폼에서 업무 완료까지의 구현 설계</h3><p>{design.common.status}</p></header><nav aria-label="4종 상세 도식 바로가기">{design.types.map(type=><a key={type} href={'#diagram-'+p.id+'-'+type}>{design.labels[type]}</a>)}</nav><SpecTable title={p.id+' End-To-End · CCK 제품과 기존 플랫폼의 연결'} heads={['업무 단계','적용 위치·제품','처리·다음 단계의 확인조건']} rows={p.e2e}/>{design.types.map(type=><ProposalDiagram key={type} projectId={p.id} type={type}/>)}<details className="diagram-product-evidence"><summary>CCK 제품별 재사용 범위·근거와 확인 상태</summary><SpecTable title="CCK 공통제품·확장 책임" heads={['제품·기반','위치·역할','구현 확인 조건']} rows={design.products}/>{design.productSources.filter(s=>['CCK-NOA','CCK-GRANTEE'].includes(s.id)).map(s=><p key={s.id}><b>{s.id} · {s.url?<Out url={s.url}>{s.title}</Out>:s.title}</b><br/>{s.locator} · {s.level} · {s.date} · 확인 {s.checked}<br/>{s.limit}</p>)}</details><p className="diagram-downloads"><Link download to="downloads/proposal-diagrams/design.md">전체 도식 설계·텍스트 명세 MD ↓</Link><Link download to="downloads/proposal-diagrams/design.json">과제별 노드·흐름·요구환경 JSON ↓</Link></p></section>}
