const data=require('./solutions-47.json'),detail=require('./solution-detail-47.json'),departments=require('./data.json').departments;
const analysis=require('./analysis-review.cjs');
const amendments={
MR:{0:'2023-11-29 TS 보도자료는 당시 약 18만 대의 앱미터 이용과 전문검정기관 지정을 설명. 현재 보급 규모와 구분.',1:'확보된 검정기준 첨부파일은 업데이트 계획 제출과 새로운 요금산정 기능의 수리검정을 구분. 현행 고시 판본·세부 경계의 추가 확인 필요.'},
SA:{2:'정본이 인용한 법령에는 사고 기준에 따른 점검과 관리규정의 주기적 확인·평가가 별도로 존재. 조치 후 관측 방식과 실제 운영기록은 현장 확인 대상.'},
QE:{0:'47번 정본의 공개 원자료 집계: 2025년 운수종사자 831,663명 중 65세 이상 221,743명(26.7%). 이번 사이트 작업에서 원자료 재집계는 미수행.',2:'정본 집계의 상주 개인택시 양수교육 신청 17,609명·입교 5,284명(2025). 미입교 원인을 수용능력 하나로 확정하지 않고 중복 신청·취소·기간 차이 등 확인 필요.'},
CL:{0:'화물자동차 운수사업법 제70조는 안전운임 미달 지급 과태료와 부과 주체를 규정. CL-E10만으로 신고센터의 세부 위탁업무 전체를 확정할 수 없어 시행령·업무규정 추가 대조 필요.'},
RI:{0:'47번 정본 분석자의 공개 게시판 집계: 승인→최초 유효기간 시작일 중앙값 169일(n=51), 관측기간을 채운 1~7차 승인 79건 중 180일 내 고지상 개시 25건(31.6%). 실제 개시·행정 처리기간과 구분.',2:'정본의 이용자 고지 52건 중 29건은 조건이 본문에 열거되지 않거나 이미지 형태. 조건 자체가 없다는 의미가 아니며 원 확인서 대조 필요.'},
IP:{1:'2026년 상반기 선별 점검 201곳 중 23곳 적발로 보도됨. 단일 점검 표본을 전체 검사소 위반율 또는 반복 적발률로 확대하지 않음.',2:'정본 적용례에 따르면 화재 우려 결함 관련 검사기준은 2026-01-01 이후 시정계획 통지·공고 차량부터 적용. 대상·경과기간·판본의 사건별 확인 필요.'},
SI:{0:'2026-10-01 공개 CSV 재집계: 부적합 746행 중 재검일 기재 598행·공란 148행. 날짜 기재 비율 80.2%·공란 비율 19.8%. 실제 재검 합격률·미재검률·기관 성과로 해석하지 않음.',1:'부적합 사유의 자유기술 표준화 필요성을 검토. “115종·판독 곤란” 수치는 고유값 산정·정규화 기준과 원자료 위치 재확인 전 확정 인용 보류.',2:'정본이 연결한 시행규칙은 부적합 기기 사용금지와 시·도 보고의 근거. 그 조항만으로 종결 기록의 미보유·비공개를 입증하지 않으며 별도 대장 확인 필요.'},
PK:{0:'2026년 7월 말 기준, 재검사 없이 남은 656기 중 운행중지명령 확인 152기(23.2%)라는 보도 인용. 나머지 장치의 실제 운행·명령 상태는 미확인.',2:'2026년 7월 기준 전국 36,234기 중 20년 이상 장치가 43.7%라는 보도 인용. 노후도만으로 개별 장치 위험 확정 불가.'},
AD:{0:'확보한 기준은 일부 진단 불가 시 대체 확인방법을 안내. 이것만으로 진단불가 통계가 존재하지 않는다고 결론낼 수 없어 시도·결측·공표항목의 확인 필요.'},
RD:{0:'정본의 연구자료와 검사기준을 연결해 연구성과의 현장 적용 범위를 검토. 차로이탈경고장치 등의 진단불가 예외를 전체 ADAS 검사방법으로 일반화하지 않음.',1:'사용후 배터리 조항의 시행 예정 주장 검증 보류. RD-E28 연결 URL은 2025-08-14 시행판으로 확인되어 주장한 2027년 시행판과 불일치. 올바른 개정 원문 확보 전 현행 법적 의무로 사용하지 않음.'}
};
const held=new Set(['MR:1','SA:2','CL:0','SI:1','SI:2','AD:0','RD:1']);
function evidence(id){const s=data.evidence.find(x=>x.id===id);if(!s)return null;let e={...s,verification_scope:'제공된 47번 원장 판정 · 이번 사이트 작업의 전체 원문 재검증 아님'};if(id==='SI-E01')e={...e,value:'2026-10-01 보존 공개 CSV 재집계: 746행 중 재검일 기재 598행(80.2%)·공란 148행(19.8%). 날짜 기재 비율이며 실제 재검 합격률·미재검률·기관 종결 성과와 구분. 과거 검사유형·기기명·소요일·사유별 수치는 이번 재집계하지 않음.',accessed:analysis.date,locator:'20230720 판본의 재검일 칸 기재·공란 집계',note:'원 정본의 과거 집계·해석은 역사 자료로 보존. 현재 확인은 보존 CSV 행수와 날짜 기재 여부에 한정. SHA-256 '+analysis.audit.csv.sha256,verification_scope:'2026-10-01 보존 CSV 직접 재집계. 원 정의서·내부 상태·공식 최신본 대조 미수행.'};
if(id==='SI-E02')e={...e,value:'본부·업체구분·사유의 과거 교차집계는 이번 미재계산으로 확인 보류. 날짜 공란을 실제 미재검으로 변환하거나 본부별 기관 성과를 비교할 수 없음. 정의서·추적기간·원 대장 대조 필요.',grade:'UNKNOWN',note:'원 정본 값은 보존. 현재 재집계 범위는 전체 행수·재검일 기재/공란이며 본부별 비율·사유 교차표는 포함하지 않음.',verification_scope:'2026-10-01 해석 정정·교차집계 검증 보류.'};
if(id==='IP-E18')e={...e,source_level:'2차',note:[e.note,'표시 검토: 언론의 정부 발표 인용으로 2차 분류'].filter(Boolean).join(' / ')};if(id==='RD-E28')e={...e,grade:'UNKNOWN',value:'주장과 연결 법령 판본 불일치로 확인 보류',note:'2025-08-14 시행판 링크와 2027년 시행 주장의 불일치. 정확한 개정 원문 확보 전 법적 근거 사용 보류.'};return e;}
function get(code){const d=data.departments[code];if(!d)return null;return {...d,code,name:departments.find(x=>x.code===code)?.name,folder:departments.find(x=>x.code===code)?.folder,currentReview:analysis.departments[code],oneLine:analysis.departments[code].how,excluded:analysis.departments[code].exclude+' '+d.excluded,baseline:code==='SI'?'공개 CSV 재집계: 746행 중 재검일 기재 598행·공란 148행(2022년 자료). 기재율 80.2%이며 재검 합격·종결 성과가 아님. 원 대장·추적기간·종결유형 대사 후 기준선 확정. 18일은 이번 미재집계 과거 기술통계로 성과 인용 보류.':code==='RI'?'공개 승인→유효기간 시작의 과거 날짜 집계는 배경 자료. 원 확인서·실제 준비 및 개시 시각·대기 사유를 확보한 후 처리시간 기준선 확정. 원 게시판 재집계는 이번 미수행.':d.baseline,detail:{...detail.profiles[code],purpose:analysis.departments[code].purpose,why:[analysis.departments[code].why,...detail.profiles[code].why],boundary:analysis.departments[code].exclude+' '+(code==='SI'?'공개 파일의 날짜 기재 집계와 원천 기기의 실제 상태 구분. 18일과 사유 고유값은 이번 재집계하지 않음.':detail.profiles[code].boundary),pilot:analysis.departments[code].status.includes('보류')?'독립 편성 보류. '+analysis.departments[code].records+' 확보와 현업 수요 확인 후 기존 제한 실증안을 재검토.':detail.profiles[code].pilot},facts:d.facts.map((f,i)=>({...f,text:amendments[code]?.[i]||f.text,role:code==='QE'?'업무·수요 배경 · 소견 이해 문제의 직접 증거 아님':code==='SI'?'공개 파일·제도 근거 · 실제 조치 여부는 원 대장 확인':code==='RI'?'공개 고지·제도 근거 · 실제 처리시간은 별도 확인':'공개 업무·현황 · 잔여 문제는 현장 확인',review:held.has(code+':'+i)?'추가 확인 필요':'정본 인용 · 적용 범위 확인',grades:f.ids.map(evidence).filter(Boolean).map(s=>s.grade),sources:f.ids.map(evidence).filter(Boolean)}))};}
const chapters=require('./proposal-composition.cjs').chapters.map(c=>[c.id,c.title]);
const common={title:'판정 이후 실제 조치와 결과까지 연결하는 사업기획',text:'47번 정본의 공통 검토 주제는 공식 판정 이후 조치·확인·종결·후속 관측의 연결. 법령에 절차가 있다는 사실과 실제 기록이 단절됐다는 사실은 구분하며, 각 처의 공개 근거와 사건 대장으로 추가 적용범위를 확인하는 설계.',limit:'제공된 공개 근거 원장의 재구성과 상세 설계안. 529개 원문을 이번 작업에서 모두 재열람·검증했다는 의미가 아니며, 재설계 방향은 확정 전 제안.'};
module.exports={data,detail,get,evidence,chapters,common};
