import React,{useState} from 'react';
import {ExternalLink} from 'lucide-react';
import data from './alio-rfp-learning.json';

export function RfpLearning(){
 const [view,setView]=useState('structure');
 const s=data.scope;
 function showSample(id){const node=document.getElementById('rfp-'+id);if(node){node.open=true;node.scrollIntoView({block:'start'});node.querySelector('summary')?.focus();}}
 return <div className="wb-rfp">
  <p className="wb-detail-summary">실제 TS 발주 요구에서 확인한 공통 작성구조와 사업별 차이. 후속 제안의 범위·증빙·인수기준을 구체화하기 위한 참고 기준</p>
  <p className="wb-note">{data.date} 확인 · 최근 {s.inspectedPages}쪽 {s.inspectedRows}행에서 {s.sampleCount}건 선정 · 표본 공고·RFP 첨부 {s.attachmentCount}개와 DRT 선행사업·버전 대조용 HWP {s.supplementaryAttachmentCount}개 확보. 공고의 요구와 실제 계약·구현·검수 결과는 별도 확인</p>
  <div className="wb-mandate-tabs" role="group" aria-label="RFP 자료 보기">{[['structure','기본 작성구조'],['samples','공고 5건 비교'],['draft','요구사항 작성 예시']].map(([id,title])=><button type="button" key={id} className="wb-button" aria-pressed={view===id} onClick={()=>setView(id)}>{title}</button>)}</div>
  {view==='structure'&&<><h3>발주기관의 RFP 작성 흐름</h3><ol className="wb-rfp-outline">{data.outline.map((o,i)=><li key={o.id}><small>{String(i+1).padStart(2,'0')}</small><div><h4>{o.title}</h4><p>{o.question}</p><ul>{o.items.map(t=><li key={t}>{t}</li>)}</ul><p><b>작성 산출물</b> · {o.output}</p><small>대조 위치 · {o.proof}</small></div></li>)}</ol><h3>후속 기획에 먼저 반영할 사항</h3><ul>{data.nextActions.map(t=><li key={t}>{t}</li>)}</ul><p className="wb-note">5건의 기술90·가격10 관찰을 모든 공공사업의 고정 평가규칙으로 일반화하지 않음. 금액·기간·배점·제출·공동수급 조건은 해당 공고의 최종본으로 확인</p></>}
  {view==='samples'&&<><h3>사업 성격별 요구사항 대조</h3><div className="wb-table-wrap"><table><thead><tr><th>공고·유형</th><th>요구사항 수·산출근거</th><th>추가 기획의 경계</th></tr></thead><tbody>{data.samples.map(x=><tr key={x.id}><td><button type="button" className="wb-link-button" onClick={()=>showSample(x.id)}>{x.title}</button><small>{x.published} · {x.kind}</small></td><td><b>{x.count}건</b><small>{x.countMethod}</small><small>{x.locator}</small></td><td>{x.application}</td></tr>)}</tbody></table></div>{data.samples.map(x=><details className="wb-disclosure wb-rfp-sample" key={x.id} id={'rfp-'+x.id}><summary>{x.title} · {x.kind}</summary><p>{x.scope}</p><dl><div className="wb-field"><dt>공고·수행조직</dt><dd>{x.published} · {x.dept}</dd></div><div className="wb-field"><dt>자료 성격</dt><dd>{x.meaning}</dd></div><div className="wb-field"><dt>요구 유형별 수</dt><dd>{Object.entries(x.categories).map(([k,v])=>`${k} ${v}`).join(' / ')}<br/>{x.countMethod} · {x.locator}</dd></div></dl><ul>{x.findings.map(([title,body,position])=><li key={title}><b>{title}</b> · {body}<small className="wb-rfp-locator">원문 위치 · {position}</small></li>)}</ul>{x.conflicts.length>0&&<div className="wb-alert"><b>원문 대조에서 남은 확인사항</b><ul>{x.conflicts.map(t=><li key={t}>{t}</li>)}</ul></div>}<p><b>후속 제안에 적용</b> · {x.application}</p><p className="wb-note">{x.boundary}</p><div className="wb-actions"><a className="wb-button" href={x.url} target="_blank" rel="noopener noreferrer">ALIO 공고 <ExternalLink size={15}/></a>{x.files.map(f=><a className="wb-button" href={f.url} key={f.kind} target="_blank" rel="noopener noreferrer">공식 {f.kind} 첨부 <ExternalLink size={15}/></a>)}{x.supplementarySources?.map(s=><a className="wb-button" href={s.url} key={s.id} target="_blank" rel="noopener noreferrer">{s.title} <ExternalLink size={15}/></a>)}</div><small>공식 첨부 주소 변경 시 ALIO 상세공고에서 해당 첨부 재확인. 보관 원본은 파일별 SHA-256 대조 완료</small></details>)}</>}
  {view==='draft'&&<><h3>개별 요구사항에 필요한 항목</h3><dl>{data.requirementFields.map(([k,v])=><div className="wb-field" key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><h3>{data.example.title}</h3><p className="wb-note">{data.example.status}</p><dl>{[['관리번호',data.example.id],['목적',data.example.purpose],['기존 발주범위 대조',data.example.reuse],['입력·사전조건',data.example.input],['처리·담당자·결과',data.example.process],['예외 처리',data.example.exception],['개인정보',data.example.privacy],['인수·효과 측정',data.example.acceptance],['산출물',data.example.outputs]].map(([k,v])=><div className="wb-field" key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></>}
  <details className="wb-disclosure"><summary>조사 범위·추출 방법·확인 한계</summary><p>{s.limit}</p><p>목록 표시 총 {s.totalRows.toLocaleString()}행·{s.totalPages}쪽 / 이번 열람 기간 {s.fromDate}~{s.toDate}</p><ul>{data.limitations.map(t=><li key={t}>{t}</li>)}</ul></details>
 </div>;
}
