import React,{useEffect,useRef,useState} from 'react';
import {Search,Menu,X,ChevronDown,ChevronRight,Home,ArrowUpRight,Network,BookOpen,FileText} from 'lucide-react';
import {Link,href,navigate} from './core.jsx';
import nav from './navigation.cjs';
import readingNav from './ux-navigation.cjs';
const {records,locate,trailFor,firstRoute}=nav;
const {sections}=readingNav;
function Tree({nodes,close}){return <ul>{nodes.map(n=><li key={n.id}>{n.children?<details><summary>{n.title}</summary><Tree nodes={n.children} close={close}/></details>:<Link to={n.to} onClick={close}>{n.title}<ChevronRight size={13}/></Link>}</li>)}</ul>}
export function SiteHeader({route,navigationEpoch}){
 const [opened,setOpened]=useState(null),[mode,setMode]=useState(null),[query,setQuery]=useState(''),[searchFilter,setSearchFilter]=useState('all');const root=useRef(),dialog=useRef(),trigger=useRef(),searchInput=useRef(),buttons=useRef({});
 const active=readingNav.sectionFor(route),section=sections.find(s=>s.id===opened);
 const words=query.trim().toLowerCase().split(/\s+/).filter(Boolean),matches=words.length?readingNav.searchRecords.filter(r=>(searchFilter==='all'||r.type===searchFilter)&&words.every(w=>[r.title,...r.breadcrumb,readingNav.sectionFor(r.route).title,r.organization||'',...(r.keywords||[])].join(' ').toLowerCase().includes(w))):[];
 useEffect(()=>{setOpened(null);setMode(null);setQuery('');setSearchFilter('all')},[route,navigationEpoch]);
 useEffect(()=>{if(!opened)return;const outside=e=>{if(!root.current?.contains(e.target))setOpened(null)};document.addEventListener('pointerdown',outside);return()=>document.removeEventListener('pointerdown',outside)},[opened]);
 useEffect(()=>{const el=dialog.current;if(mode){if(!el.open)el.showModal();if(mode==='search')requestAnimationFrame(()=>searchInput.current?.focus());const prev=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=prev}}else if(el.open)el.close()},[mode]);
 const close=()=>{setMode(null);setQuery('')};
 function openDialog(next,e){trigger.current=e.currentTarget;setOpened(null);setMode(next)}
 function dismiss(){close();requestAnimationFrame(()=>trigger.current?.focus())}
 const title=mode==='search'?'자료 통합검색':'전체메뉴';
 return <><header className="header ts-header" ref={root} onKeyDown={e=>{if(e.key==='Escape'&&opened){e.stopPropagation();setOpened(null);buttons.current[opened]?.focus()}}} onBlur={e=>{if(e.relatedTarget&&!e.currentTarget.contains(e.relatedTarget))setOpened(null)}}>
  <div className="ts-utility"><span>CCK 제안·검토자료 <i/> 공식 누리집과 구분</span><div><a href="https://main.kotsa.or.kr/main.do" target="_blank" rel="noopener noreferrer">TS 공식 누리집 <ArrowUpRight size={12}/><span className="sr-only">새 창</span></a><Link to="planning-documents.html">한글 자료</Link><button onClick={e=>openDialog('all',e)}>사이트맵</button></div></div>
  <div className="ts-masthead"><Link to="index.html" className="ts-brand" aria-label="TS AX 홈"><span className="ts-brand-mark"><b>T</b><b>S</b></span><span><strong>AX 사업기획</strong><small>한국교통안전공단 제안 자료</small></span></Link>
   <nav className="ts-topnav" aria-label="주 메뉴">{sections.map(s=><button key={s.id} ref={el=>buttons.current[s.id]=el} aria-expanded={opened===s.id} aria-controls="ts-megamenu" aria-current={active?.id===s.id?'true':undefined} onClick={()=>setOpened(opened===s.id?null:s.id)} onKeyDown={e=>{if(e.key==='ArrowDown'){e.preventDefault();setOpened(s.id);requestAnimationFrame(()=>document.querySelector('#ts-megamenu a')?.focus())}}}>{s.title}<ChevronDown size={13}/></button>)}</nav>
   <div className="ts-header-tools"><button className="ts-search-trigger" onClick={e=>openDialog('search',e)} aria-label="자료 통합검색 열기"><span>자료 검색</span><Search size={21}/></button><button onClick={e=>openDialog('all',e)} aria-label="전체메뉴 열기"><Menu size={27}/></button></div>
  </div>
  {section&&<div id="ts-megamenu" className="ts-menu-panel" role="region" aria-label={section.title+' 세부 메뉴'}><div className="ts-menu-intro"><span>TS AX</span><h2>{section.title}</h2><p>{section.description}</p><button onClick={e=>openDialog('all',e)}>전체메뉴 보기 <ChevronRight size={15}/></button></div><div className="ts-menu-columns">{section.children.map(n=><section key={n.id}><h3><Link to={firstRoute(n)}>{n.title}<ChevronRight size={14}/></Link></h3>{n.children&&<ul>{n.children.slice(0,4).map(c=><li key={c.id}><Link to={firstRoute(c)}>{c.title}</Link></li>)}</ul>}{n.children?.length>4&&<Link className="ts-more-items" to={firstRoute(n)}>상세 자료·목차 보기</Link>}</section>)}</div><button className="ts-panel-close" aria-label="세부 메뉴 닫기" onClick={()=>{setOpened(null);buttons.current[opened]?.focus()}}><X size={19}/></button></div>}
 </header>
 <dialog ref={dialog} className="ts-dialog" aria-label={title} onCancel={e=>{e.preventDefault();dismiss()}} onClick={e=>{if(e.target===dialog.current)dismiss()}}><div className="ts-dialog-inner"><header><div><span>TS AX 사업기획</span><h2>{title}</h2></div><button onClick={dismiss} aria-label={title+' 닫기'}><X size={24}/></button></header>
 {mode==='search'?<div className="ts-search-content"><form onSubmit={e=>{e.preventDefault();if(matches.length===1)document.querySelector('.ts-search-results a')?.click()}}><label htmlFor="ts-global-query">자료 제목·조직·메뉴 검색</label><div><input id="ts-global-query" ref={searchInput} value={query} onChange={e=>setQuery(e.target.value)} placeholder="예: 모빌리티연구처, 아키텍처, 측정명세"/><Search size={21}/></div></form><div className="ux-search-types" role="group" aria-label="검색 자료 유형">{[['all','전체'],['department','처별 제안'],['document','한글 문서'],['planning','2027 기획 검토'],['detail','상세자료']].map(([id,label])=><button key={id} aria-pressed={searchFilter===id} onClick={()=>setSearchFilter(id)}>{label}</button>)}</div>{words.length?<><p role="status">{matches.length}개 자료</p>{matches.length?<ul className="ts-search-results">{matches.map(r=><li key={r.id}><Link to={r.route} download={r.downloadName} onClick={close}><strong><span className="ux-search-type">{r.type==='department'?'처별 제안':r.type==='document'?'한글 문서':r.type==='planning'?'2027 기획 검토':'상세자료'}</span>{r.title}</strong><small>{[readingNav.sectionFor(r.route).title,...r.breadcrumb.slice(1)].join(' › ')}</small>{r.type==='planning'&&(r.keywords||[]).some(k=>/^[A-Z][A-Z0-9]*-?\d+$/i.test(k)&&words.includes(k.toLowerCase()))&&<small>일치한 코드: {(r.keywords||[]).filter(k=>/^[A-Z][A-Z0-9]*-?\d+$/i.test(k)&&words.includes(k.toLowerCase())).join(' · ')}</small>}<ChevronRight size={16}/></Link></li>)}</ul>:<div className="ts-search-empty">일치하는 자료 없음. 처 이름이나 짧은 검색어로 재검색.</div>}</>:<div className="ts-search-suggestions"><p>자주 찾는 자료</p>{[['2027년 ISP·사업기획 검토','research-library.html?view=planning#isp-start'],['처별 제안 찾기','solutions.html'],['한글 계획서·첨부문서','planning-documents.html'],['조사자료·공식 출처','research-library.html']].map(([t,p])=><Link key={p} to={p} onClick={close}>{t}<ChevronRight size={15}/></Link>)}</div>}</div>:<nav className="ts-sitemap" aria-label="전체메뉴">{sections.map(s=><section key={s.id}><h3>{s.title}</h3><p>{s.description}</p><Tree nodes={s.children} close={close}/></section>)}</nav>}
 </div></dialog></>;
}
export function SiteLocation({route}){const trail=readingNav.trailFor(route);return <div className="ts-location"><nav aria-label="현재 메뉴 위치"><Link to="index.html" aria-label="처음으로"><Home size={16}/></Link>{trail.map((n,i)=><React.Fragment key={n.id}><ChevronRight size={13}/>{i===trail.length-1?<span aria-current="page">{n.title}</span>:<Link to={firstRoute(n)}>{n.title}</Link>}</React.Fragment>)}</nav><Link to="index.html?view=map" className="ts-map-shortcut"><Network size={15}/>조직 지도</Link></div>}
export function SiteQuickLinks(){return <nav className="ts-quick-links" aria-label="자주 찾는 메뉴"><b>자주 찾는 메뉴</b>{[[Home,'공단 이해','about.html'],[Network,'조직 연결지도','index.html?view=map'],[BookOpen,'처별 AX 제안','solutions.html'],[ArrowUpRight,'공식 홈페이지','websites.html'],[FileText,'법정·수탁업무','legal.html']].map(([Icon,title,to])=><Link key={to} to={to}><Icon size={21}/><span>{title}</span></Link>)}</nav>}
