import React,{useEffect,useState}from'react';
import{Heading,Link,Out,href}from'./core.jsx';
import design from'./skill-pms.cjs';
import'./skill-pms.css';
const l=design.labels;
function Refs({ids}){return ids?.length?<p className="pms-refs">{l.references}: {ids.map(id=><a key={id} href={'#pms-source-'+id}>{id} · {design.sources[id].title}</a>)}</p>:null}
function Table({headers,rows,caption}){return <div className="pms-table" role="region" aria-label={caption} tabIndex={0}><table><caption>{caption}</caption><thead><tr>{headers.map(h=><th scope="col" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=>j===0?<th scope="row" key={j}>{v}</th>:<td key={j}>{v}</td>)}</tr>)}</tbody></table></div>}
function Portfolio(){const[q,setQ]=useState(''),rows=design.portfolio.filter(p=>[p.code,p.id,p.department,p.title].join(' ').toLowerCase().includes(q.trim().toLowerCase()));return <>
 <form className="pms-search" role="search" onSubmit={e=>e.preventDefault()}><label htmlFor="pms-project-search">{l.portfolioSearch}</label><input id="pms-project-search" type="search" value={q} onChange={e=>setQ(e.target.value)} placeholder={l.searchPlaceholder}/><button type="button" onClick={()=>setQ('')}>{l.reset}</button><p role="status">{rows.length} / {design.counts.projects} · {l.countNote}</p></form>
 {rows.length?<div className="pms-table" role="region" aria-label={l.portfolioCaption} tabIndex={0}><table><caption>{l.portfolioCaption}</caption><thead><tr>{l.portfolioHeaders.map(h=><th scope="col" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(p=><tr key={p.id} data-pms-project={p.id}><th scope="row"><span>{p.id}</span><br/>{p.department}</th><td>{p.title}<br/><Link to={p.proposalRoute}>{l.proposalLink} ↗</Link></td><td>{p.documentVersions}<br/><Link to={p.documentsRoute}>{l.documentsLink} ↗</Link></td></tr>)}</tbody></table></div>:<p className="pms-empty" role="status">{l.empty}</p>}
 </>}
function Block({b,section}){let content;
 if(b.type==='note')content=<div className="pms-note">{b.title&&<h3>{b.title}</h3>}<ul>{b.items.map(t=><li key={t}>{t}</li>)}</ul></div>;
 else if(b.type==='table')content=<Table {...b} caption={b.caption||section.title+' · '+b.headers.join(' / ')}/>;
 else if(b.type==='links')content=<p className="pms-links">{b.items.map(item=><Link to={item.to} key={item.to}>{item.title} ↗</Link>)}</p>;
 else if(b.type==='architecture')content=<><figure className="pms-architecture"><img src={href('assets/skill-pms/architecture.svg')} alt={l.diagramAlt} width="1440" height="1140"/><figcaption>{l.diagramCaption}</figcaption></figure><Table caption={section.title} headers={l.layerHeaders} rows={design.layers.map(n=>[n.id+' · '+n.name,n.status,n.items.join(' / '),n.detail])}/></>;
 else if(b.type==='skills')content=<><h3>{l.skillsTitle}</h3><div className="pms-skill-grid">{design.skills.map(s=><article key={s.id} id={'pms-skill-'+s.id} tabIndex={-1}><div className="pms-kicker">{s.id}</div><h3>{s.name}</h3><dl>{[['input',s.input],['how',s.how],['tools',s.tools.join(' · ')],['output',s.output],['gate',s.gate]].map(([key,text])=><div key={key}><dt>{l[key]}</dt><dd>{text}</dd></div>)}</dl></article>)}</div></>;
 else if(b.type==='contract')content=<div className="pms-contract"><h3>{l.contract}</h3><pre tabIndex={0}><code>{JSON.stringify(design.contract,null,2)}</code></pre></div>;
 else if(b.type==='flow')content=<ol className="pms-flow" aria-label={l.flowLabel}>{design.flow.map(f=><li key={f[0]}><span className="pms-kicker">{f[0]}</span><h3>{f[1]}</h3><p>{f[2]}</p><code>{f[3]}</code></li>)}</ol>;
 else if(b.type==='portfolio')content=<Portfolio/>;
 else if(b.type==='metrics')content=<div className="pms-metrics">{design.metrics.map(m=><article key={m.id} id={'pms-metric-'+m.id} tabIndex={-1}><h3>{m.id} · {m.name}</h3><dl>{[['formula',m.formula],['method',m.method],['quality',m.quality]].map(([key,text])=><div key={key}><dt>{l[key]}</dt><dd>{text}</dd></div>)}</dl><p>{l.metricsBaseline}</p></article>)}</div>;
 else if(b.type==='sources')content=<div className="pms-source-list">{Object.entries(design.sources).map(([id,s])=><article key={id} id={'pms-source-'+id} tabIndex={-1}><h3>{id} · {s.title}</h3><p>{l.sourceDate}: {s.published} / {s.checkedAt}</p><p>{s.location}</p><dl><div><dt>{l.sourceFact}</dt><dd>{s.fact}</dd></div><div><dt>{l.sourceLimit}</dt><dd>{s.limit}</dd></div></dl>{s.url?<Out url={s.url}>{s.title}</Out>:s.to?<Link to={s.to}>{s.title} ↗</Link>:<small>{l.internalSource}</small>}</article>)}</div>;
 return <div className={'pms-block pms-block-'+b.type}>{content}<Refs ids={b.refs}/></div>
}
export function SkillPms(){useEffect(()=>{let next;const first=requestAnimationFrame(()=>{next=requestAnimationFrame(()=>{if(!location.hash)return;let id=location.hash.slice(1);try{id=decodeURIComponent(id)}catch{}const target=document.getElementById(id);target?.focus({preventScroll:true});target?.scrollIntoView({block:'start'})})});return()=>{cancelAnimationFrame(first);if(next)cancelAnimationFrame(next)}},[]);
 return <div className="page skill-pms-page"><Heading label={design.id+' · '+design.version+' · '+design.date} title={design.title} desc={design.lead}/><div className="pms-intro"><p><strong>{design.status}</strong></p><p>{design.constraints}</p><p>{design.counts.departments} {l.countDepartments} · {design.counts.projects} {l.countProjects} · {design.counts.files} {l.countFiles}</p><small>{l.countNote}</small><p className="pms-links">{design.downloads.map(d=><Link key={d.to} to={d.to} download>{d.title} ↓</Link>)}</p></div><nav className="pms-toc" aria-label={l.toc}>{design.sections.map(s=><a key={s.id} href={'#pms-'+s.id}>{s.title}</a>)}</nav>{design.sections.map(s=><section className="pms-section" id={'pms-'+s.id} tabIndex={-1} key={s.id}><header><h2>{s.title}</h2><p>{s.intro}</p></header>{s.blocks.map((b,i)=><Block key={i} b={b} section={s}/>)}</section>)}</div>
}
