import React,{useEffect,useState}from'react';
import{Heading,Link,Out,href}from'./core.jsx';
import design from'./skill-pms.cjs';
import{DepartmentCoverage}from'./DepartmentCoverage.jsx';
import ux from'./ux-content.cjs';
import'./skill-pms.css';
import {TsAiPmsPlan} from './TsAiPmsPlan.jsx';
const l=design.labels;
function Refs({ids}){return ids?.length?<p className="pms-refs">{l.references}: {ids.map(id=><Link key={id} to={'skill-pms.html#pms-source-'+id}>{id} · {design.sources[id].title}</Link>)}</p>:null}
function Table({headers,rows,caption}){return <div className="pms-table" role="region" aria-label={caption} tabIndex={0}><table><caption>{caption}</caption><thead><tr>{headers.map(h=><th scope="col" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=>j===0?<th scope="row" key={j}>{v}</th>:<td key={j}>{v}</td>)}</tr>)}</tbody></table></div>}
function Portfolio(){const[q,setQ]=useState(new URLSearchParams(location.search).get('q')||'');const update=value=>{setQ(value);const u=new URL(location.href);value.trim()?u.searchParams.set('q',value):u.searchParams.delete('q');history.replaceState({},'',u)};const rows=design.documentGroups.map(d=>({...d,projects:d.projects.filter(p=>[p.code,p.id,p.department,p.title].join(' ').toLowerCase().includes(q.trim().toLowerCase()))})).filter(d=>d.projects.length),projects=rows.reduce((n,d)=>n+d.projects.length,0),files=new Set(rows.flatMap(d=>d.documents.map(f=>f.path))).size;return <>
 <form className="pms-search" role="search" onSubmit={e=>e.preventDefault()}><label htmlFor="pms-project-search">{l.portfolioSearch}</label><input id="pms-project-search" type="search" value={q} onChange={e=>update(e.target.value)} placeholder={l.searchPlaceholder}/><button type="button" onClick={()=>update('')}>{l.reset}</button><p role="status">{rows.length} {l.countDepartments} · {projects} {l.countProjects} · {files} {l.uniqueFiles}</p></form>
 <p className="pms-map-note">{l.mappingGuide}</p>
 {rows.length?<><nav className="pms-department-index" aria-label={l.departmentIndex}>{rows.map(d=><a key={d.code} href={'#'+d.anchor}>{d.code} · {d.name}</a>)}</nav><div className="pms-document-groups">{rows.map(d=><article key={d.code} id={d.anchor} tabIndex={-1} data-pms-department={d.code} className="pms-department-card">
  <header><span className="pms-kicker">{d.code}</span><h3>{d.name}</h3><p>{d.sharedDocuments?l.sharedDocuments:l.singleDocuments}</p></header>
  <div className="pms-file-grid">{d.documents.map(f=><div key={f.kind} className={'pms-file pms-file-'+f.kind}><span className="pms-file-version">{f.kind==='plan'?l.latestPlan:l.referenceFile} · {f.version}</span><h4>{f.label}</h4><p>{f.status}</p><Link to={f.path} download={f.downloadName} data-pms-document={f.kind}>{l.documentActions[f.kind]} ↓</Link><small>HWPX · {(f.bytes/1024/1024).toFixed(1)} MB · {f.date} · {l.embeddedImages} {f.embeddedImages}</small></div>)}</div>
  <p className="pms-version-note">{l.versionNote} <Link to={'planning-documents.html#documents-'+d.code}>{l.documentMetadata} ↗</Link></p>
  <div className="pms-projects">{d.projects.map(p=><section key={p.id} id={p.anchor} tabIndex={-1} data-pms-project={p.id} className="pms-project-card"><header><span>{p.id}</span><h4>{p.title}</h4></header><p>{p.designScope}</p><nav className="pms-design-links" aria-label={p.id+' '+l.designLinks}>{p.designLinks.map(a=><Link key={a.to} to={a.to} data-pms-design>{a.label} ↗</Link>)}</nav><div className="pms-project-footer"><Link to={p.proposalRoute}>{l.fullProposal} ↗</Link><a href={'#'+p.anchor}>{l.projectPermalink}</a><a href="#pms-portfolio">{l.backToSearch} ↑</a></div></section>)}</div>
 </article>)}</div></>:<p className="pms-empty" role="status">{l.empty}</p>}
 </>}
function Block({b,section}){let content;
 if(b.type==='note')content=<div className="pms-note">{b.title&&<h3>{b.title}</h3>}<ul>{b.items.map(t=><li key={t}>{t}</li>)}</ul></div>;
 else if(b.type==='table')content=<Table {...b} caption={b.caption||section.title+' · '+b.headers.join(' / ')}/>;
 else if(b.type==='links')content=<p className="pms-links">{b.items.map(item=><Link to={item.to} key={item.to}>{item.title} ↗</Link>)}</p>;
 else if(b.type==='architecture')content=<><figure className="pms-architecture"><img src={href('assets/skill-pms/architecture.svg')} alt={l.diagramAlt} width="1440" height="1140"/><figcaption>{l.diagramCaption}</figcaption></figure><Table caption={section.title} headers={l.layerHeaders} rows={design.layers.map(n=>[n.id+' · '+n.name,n.status,n.items.join(' / '),n.detail])}/></>;
 else if(b.type==='skills')content=<><h3>{l.skillsTitle}</h3><div className="pms-skill-grid">{design.skills.map(s=><article key={s.id} id={'pms-skill-'+s.id} tabIndex={-1}><div className="pms-kicker">{s.id}</div><h3>{s.name}</h3><dl>{[['input',s.input],['how',s.how],['tools',s.tools.join(' · ')],['output',s.output],['gate',s.gate]].map(([key,text])=><div key={key}><dt>{l[key]}</dt><dd>{text}</dd></div>)}</dl></article>)}</div></>;
 else if(b.type==='contract')content=<div className="pms-contract"><h3>{l.contract}</h3><pre tabIndex={0}><code>{JSON.stringify(design.contract,null,2)}</code></pre></div>;
 else if(b.type==='flow')content=<ol className="pms-flow" aria-label={l.flowLabel}>{design.flow.map(f=><li key={f[0]}><span className="pms-kicker">{f[0]}</span><h3>{f[1]}</h3><p>{f[2]}</p><code>{f[3]}</code></li>)}</ol>;
 else if(b.type==='coverage')content=<DepartmentCoverage/>;
 else if(b.type==='portfolio')content=<Portfolio/>;
 else if(b.type==='metrics')content=<div className="pms-metrics">{design.metrics.map(m=><article key={m.id} id={'pms-metric-'+m.id} tabIndex={-1}><h3>{m.id} · {m.name}</h3><dl>{[['formula',m.formula],['method',m.method],['quality',m.quality]].map(([key,text])=><div key={key}><dt>{l[key]}</dt><dd>{text}</dd></div>)}</dl><p>{l.metricsBaseline}</p></article>)}</div>;
 else if(b.type==='sources')content=<div className="pms-source-list">{Object.entries(design.sources).map(([id,s])=><article key={id} id={'pms-source-'+id} tabIndex={-1}><h3>{id} · {s.title}</h3><p>{l.sourceDate}: {s.published} / {s.checkedAt}</p><p>{s.location}</p><dl><div><dt>{l.sourceFact}</dt><dd>{s.fact}</dd></div><div><dt>{l.sourceLimit}</dt><dd>{s.limit}</dd></div></dl>{s.url?<Out url={s.url}>{s.title}</Out>:s.to?<Link to={s.to}>{s.title} ↗</Link>:<small>{l.internalSource}</small>}</article>)}</div>;
 return <div className={'pms-block pms-block-'+b.type}>{content}<Refs ids={b.refs}/></div>
}
export function SkillPms({embedded=false}){let hash=location.hash;try{hash=decodeURIComponent(hash)}catch{}const requested=new URLSearchParams(location.search).get('view'),view=embedded?'common':requested==='coverage'||/^#(?:pms-department-review|pms-review-|coverage-source-)/.test(hash)?'coverage':requested==='departments'||/^#(?:pms-portfolio|pms-department-|pms-project-)/.test(hash)?'departments':'common',u=ux.pms;
 const sections=view==='departments'?design.sections.filter(s=>s.id==='portfolio'):design.sections.filter(s=>s.id!=='portfolio');
 useEffect(()=>{let next;const first=requestAnimationFrame(()=>{next=requestAnimationFrame(()=>{if(!location.hash)return;let id=location.hash.slice(1);try{id=decodeURIComponent(id)}catch{}const target=document.getElementById(id);target?.focus({preventScroll:true});target?.scrollIntoView({block:'start'})})});return()=>{cancelAnimationFrame(first);if(next)cancelAnimationFrame(next)}},[]);
 return <div className="page skill-pms-page" data-pms-view={view}><Heading label={design.id+' · '+design.version+' · '+design.date} title={view==='common'?design.title:view==='departments'?u.portfolio:u.coverage} desc={view==='common'?u.commonGuide:view==='departments'?u.portfolioGuide:u.coverageGuide}/>
 {!embedded&&view==='common'&&<TsAiPmsPlan/>}
 <nav className="ux-pms-views" aria-label="플랫폼 설계·처별 자료 보기">{u.nav.map(([key,title,to])=><Link key={key} to={to} aria-current={view===key?'page':undefined}>{title}</Link>)}</nav>
 <div className="pms-intro"><p><strong>{design.status}</strong></p><p>{design.constraints}</p><p>{design.counts.departments} {l.countDepartments} · {design.counts.projects} {l.countProjects} · {design.counts.files} {l.countFiles}</p><small>{l.countNote}</small><p className="pms-links"><Link to="solutions.html">처별 제안 찾기 ↗</Link><Link to="planning-documents.html">한글 자료실 ↗</Link>{design.downloads.map(d=><Link key={d.to} to={d.to} download>{d.title} ↓</Link>)}</p></div>
 {view==='coverage'?<DepartmentCoverage/>:<><nav className="pms-toc" aria-label={l.toc}>{sections.map(s=><a key={s.id} href={'#pms-'+s.id}>{s.title}</a>)}</nav>{sections.map(s=><section className="pms-section" id={'pms-'+s.id} tabIndex={-1} key={s.id}><header><h2>{s.title}</h2><p>{s.intro}</p></header>{s.blocks.filter(b=>b.type!=='coverage').map((b,i)=><Block key={i} b={b} section={s}/>)}</section>)}</>}
 </div>
}
