import React,{useEffect,useRef,useState} from 'react';
import {Link,Out} from './core.jsx';
import d from './survey-design.cjs';
import './survey-design.css';
const p=d.presentation;
const selectedFromHash=()=>d.departments.find(r=>location.hash==='#'+r.anchor||r.topics.some(t=>location.hash.startsWith('#survey-topic-'+t.id+'-')))?.id||'';
function Paras({text}){return String(text||'확인 필요').split('\n').filter(Boolean).map((line,i)=><p key={i}>{line}</p>)}
function Fields({fields,topic}){const b=topic?.briefing;return <div className="survey-fields">{fields.map((f,i)=>{
 const hint=b&&({SCOPE_MATCH:'위에서 설명한 업무가 실제 담당범위와 맞는지 확인.',CURRENT_STATE:'같은 업무의 실제 기록으로 발생·해결·미관찰 구분.',BOTTLENECK_VALIDITY:b.probes[0]?.question,ACTUAL_CASE:'입력 → 실제 처리 → 보완/변경 → 공식 결과를 가명으로 작성.',EXISTING_RESPONSE:b.probes[1]?.question,AI_ADDED_VALUE:'기술 설명의 NOA 처리와 기존 도구 처리를 비교하여, 기존 기능으로 충분한 부분도 표시.',FEASIBILITY_CONDITIONS:b.probes[2]?.question,EFFECT_AND_MEASUREMENT:'앞의 효과 측정에서 제시한 지표·기록·비교조건이 현업에 맞는지 확인.',DISCOVERY_SCOPE:b.probes[0]?.question,DISCOVERY_CURRENT:b.probes[1]?.question,DISCOVERY_PROBLEM:b.probes[2]?.question}[f.id]);
 const ordinal=topic&&!topic.discovery?d.topicFields.findIndex(x=>x.id===f.id)+1:i+1,Heading=topic&&!topic.discovery?'h6':'h5';
 return <article key={f.id} data-survey-field={f.id}><Heading><span>{String(ordinal).padStart(2,'0')}</span>{f.title}</Heading><p className="survey-question">{f.question}</p>
 {hint&&<p className="survey-context-hint">{hint}</p>}
 {f.options.length>0&&<p className="survey-options"><b>응답 범주</b> {f.options.map(o=>o.label).join(' / ')}</p>}
 <p className="survey-field-help">{f.help}</p>
 {f.displayIf&&<p className="survey-branch">{f.id==='ACTUAL_CASE'?'현재 또는 조건부 발생을 확인한 경우 작성':'AI 추가 적용을 선택한 경우 작성'}</p>}
 </article>})}</div>}
function Sources({sources}){return <section className="survey-sources"><p className="survey-source-notice">출처는 해당 업무·절차·사례를 뒷받침하는 범위에서 사용. 현재 병목의 발생률·AI 효과·기관 구매수요를 입증한 것으로 확대하지 않음.</p>{sources.map(s=><article key={s.id+'-'+s.url} data-evidence-source={s.id}><h5>{s.url?<Out url={s.url}>{s.title}</Out>:s.title}</h5><p><b>확인 내용</b> {s.claim||s.fact||s.value||s.finding||s.locator||'해당 설명의 근거 위치 확인 필요'}</p><p className="survey-source-location"><b>원문 위치</b> {s.location||s.locator||s.section||'기존 조사 기록 참조'} · <b>게시·시행</b> {s.published||s.effective||'미표시'} · <b>조사 기록</b> {s.checkedAt||s.accessed||s.date||'미확인'}</p><p className="survey-source-limit"><b>적용 한계</b> {s.verification||s.limit||s.verification_scope||s.note||s.scope||'기존 자료의 확인 범위. 계약 원문·실제 배포본 직접 검증과 구분.'}</p></article>)}</section>}
export function Topic({t,first,index,includeOpinion=true}){const b=t.briefing,c=t.reading,id='survey-topic-'+t.id;return <article className="survey-topic" data-survey-topic={t.id}><header><small>검토과제 {String(index+1).padStart(2,'0')} · {t.status}</small><h3>{c.title}</h3><p className="survey-topic-goal">{c.goal}</p><p className="survey-status">검토 상태: {b.provenance}</p></header>
 <nav className="survey-topic-nav" aria-label={c.title+' 본문 목차'}>{p.topicNavigation.map(([key,title])=><a href={'#'+id+'-'+key} key={key}>{title}</a>)}</nav>
 <section id={id+'-purpose'} className="survey-chapter survey-case" tabIndex={-1}><small className="survey-chapter-context">{c.title}</small><h4>1. 목적과 근거</h4><h5>검토할 목적</h5>{b.why.map((why,i)=><p key={i}>{why}</p>)}<h5>대상 업무의 범위</h5><dl className="survey-facts">{[['대상 업무',b.unit],['사용자·관계자',b.users],['시작 시점',b.trigger],['자료 연결 기준',b.key]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><p className="survey-formal-title"><b>상세 기획명</b> {t.id} · {t.title}</p><h5>확인한 업무·기존 대응</h5><Paras text={b.known}/><Sources sources={b.sources}/></section>
 <section id={id+'-process'} className="survey-chapter" tabIndex={-1}><small className="survey-chapter-context">{c.title}</small><h4>2. 현행과 문제</h4><div className="survey-distinction"><article><h5>현재 확인할 처리</h5><p>{b.unit}을 처리할 때 어떤 자료를 읽고, 어떤 기준·도구로 확인하며, 누가 보완·공식 결과를 결정하는지 실제 정상 사례로 복원.</p><p>공식 절차의 존재와 실제 운영상 불편의 존재는 별도. 아래 단계는 담당자의 실제 순서·자료·책임과 대조할 운영 설계.</p></article><article><h5>{t.discovery?'아직 배정하지 않은 병목':'검증할 병목 가설'}</h5><p>{t.gap||'현재 병목 가설 없음. 실제 분장·처리·기존 기능·문제 유무부터 확인.'}</p><p>{b.exception}</p></article></div>
 <h5>현업에 확인할 실제 자료</h5><ul className="survey-inputs">{b.inputs.map((x,i)=><li key={i}>{x}</li>)}</ul>
 <h5>이 처리에서 받아야 할 결과물</h5><ul>{b.outputs.map((x,i)=><li key={i}>{x}</li>)}</ul><p className="survey-help">AI 초안·자료 접수·공식 판단·후속 이행은 서로 다른 완료 상태. 결과물의 품질과 실제 업무 결과를 함께 검토.</p></section>
 <section id={id+'-technology'} className="survey-chapter" tabIndex={-1}><small className="survey-chapter-context">{c.title}</small><h4>3. 해결방법</h4><p>{t.discovery?'아래는 자료·업무를 확인하기 위한 순서. 새 솔루션 구현을 확정한 명세가 아님.':c.layout==='roles'?'아래는 세 가지 처리 영역의 자료·도구·전문가 역할. 시간순서나 의료 판단의 자동화 단계가 아님.':'아래는 제안된 처리흐름. 실제 설치본·API·자료권한과 대조한 뒤 구현범위 확정.'}</p>
 <ol className={'survey-core-flow'+(c.layout==='roles'?' survey-core-roles':'')} aria-label={c.layout==='roles'?'세 가지 처리 영역':'핵심 처리 흐름'}>{c.groups.map((g,i)=><li key={g.title}><a href={'#'+id+'-work-'+i}>{g.title}</a></li>)}</ol>
 {c.groups.map((g,groupIndex)=><section className="survey-work-group" data-work-group={groupIndex} id={id+'-work-'+groupIndex} tabIndex={-1} key={g.title}><h5 className="survey-work-heading">{c.layout==='roles'?'처리 영역':'핵심 흐름'} {groupIndex+1} · {g.title}</h5><ol className={'survey-process'+(c.layout==='roles'?' survey-process-roles':'')} data-technical-flow>{g.indices.map(i=>{const s=b.steps[i];return <li key={i} data-step-index={i}><h6>{c.layout!=='roles'&&<span>{String(i+1).padStart(2,'0')}</span>}{s.title}</h6><dl><div><dt>입력</dt><dd>{s.input}</dd></div><div><dt>처리·역할</dt><dd>{s.operation}</dd></div><div><dt>산출·다음 단계</dt><dd>{s.output}</dd></div></dl></li>})}</ol></section>)}
 <h5>제품·도구·담당자의 구체 역할</h5><dl className="survey-tech-roles">{b.tech.map(([name,role],i)=><div key={i}><dt>{name}</dt><dd>{role}</dd></div>)}</dl><div className="survey-scenario"><h5>{t.discovery?'실제 사례 확보 기준':'정상·변경·예외를 검증할 상황'}</h5><p>{b.scenario}</p></div><h5>공식 완료조건과 판단 경계</h5><p>{b.complete}</p><p className="survey-help">{b.boundary}</p></section>
 <section id={id+'-conditions'} className="survey-chapter" tabIndex={-1}><small className="survey-chapter-context">{c.title}</small><h4>4. 적용조건</h4><h5>시범범위·인수 검증</h5><p>{b.pilot}</p><h5>처별 추가 개발·확인 대상</h5><ul><li>자료 모델: 앞서 정의한 자료 연결 기준과 실제 필드의 일치 확인.</li><li>업무 스킬·규칙: 위 처리단계의 확인질문·필수조건·종료조건·예외를 현업과 확정. 기존 기능과 겹치는 납품분은 제외.</li><li>원천 연계: 실제 조회·등록·결과조회 경로, 사용권·권한·담당자 인계 확인. 쓰기 미허용 시 조회·검토안 범위로 제한.</li><li>평가자료: 정상·보완·변경·반대 사례와 전문가 참조결과 확보. 기준선·목표·기간·공수는 자료 확보 후 산정.</li></ul>
 <h5>개인정보·자료 처리</h5><Paras text={b.privacy}/><ol className="survey-data-path"><li>원천 자료·권한 확인</li><li>대체키·최소 문맥</li><li>로컬 분석·원문 연결</li><li>권한자 검토·정정</li><li>필요한 결과만 인계</li><li>보유·파기·로그 확인</li></ol><p className="survey-help">로컬 LLM 사용만으로 자료 이용이 허용되는 것은 아님. 제공근거·목적·필드·역할·보유기간을 먼저 확인. 설문에는 민감 원문 대신 가명 유형·집계 정의·확인 역할만 작성.</p>
 <h5>실패·보류 시 처리</h5><p>{b.exception}</p><p>자료 부족·상충은 미확인으로 유지. 도구 실패·응답 유실은 공식 원천을 대사한 뒤 재시도하며, 처리 불명 상태를 성공으로 표시하지 않는 설계.</p></section>
 <section id={id+'-effects'} className="survey-chapter survey-measures" tabIndex={-1}><small className="survey-chapter-context">{c.title}</small><h4>5. 효과 검증</h4>{b.metrics.length?<><p>기대하는 방향은 아래 지표의 개선. 현재 기준선·목표값·실측효과는 미확정이며 임의 개선율을 부여하지 않음.</p><div className="survey-metrics">{b.metrics.map((m,i)=><article key={i}><h5>{i+1}. {m.name}</h5><dl>{[['산식·분모',m.formula],['수집 기록',m.records],['비교·측정 방법',m.method],['해석·불리한 결과 확인',m.note]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></article>)}</div></>:<p>업무·문제 확인 전 지표 미설정. 실제 완료 결과·오류·반복 부담이 확인되면 분모·기록·비교조건부터 정의. 조사 미완료를 효과 0 또는 개선 필요 없음으로 기록하지 않음.</p>}</section>
 {includeOpinion&&<section id={id+'-opinion'} className="survey-chapter survey-writing" tabIndex={-1}><small className="survey-chapter-context">{c.title}</small><h4>6. 현업 의견</h4><p>{p.groupsNote} 아래는 질문 안내이며 이 페이지에서 선택·저장·제출하지 않음. 모든 문항 선택 작성.</p>
 {first&&<section className="survey-background"><h5>응답 역할·현재 플랫폼 사용</h5><Fields fields={d.profile}/></section>}
 <div className="survey-probes"><h5>이 주제의 핵심 확인 질문·필요 근거</h5>{b.probes.map((q,i)=><article key={i}><p><b>{i+1}. {q.question}</b></p><p>필요 근거: {q.evidence}</p></article>)}</div>
 {t.discovery?<Fields fields={d.discovery} topic={t}/>:p.questionGroups.map(g=><section className={'survey-question-group survey-question-group-'+g.id} key={g.id}><h5>{g.title}</h5><Fields fields={g.fields.map(id=>d.topicFields.find(f=>f.id===id))} topic={t}/></section>)}
 </section>}</article>}
export function SurveyDesign({standalone=false}){
 const [selected,setSelected]=useState(selectedFromHash),selectedRef=useRef(selected),current=d.departments.find(r=>r.id===selected);
 useEffect(()=>{if(!Object.hasOwn(history.state||{},'surveyDepartment'))history.replaceState({...history.state,surveyDepartment:selectedFromHash()},'',location.href);let first,second;function reveal(){const id=selectedFromHash()||(Object.hasOwn(history.state||{},'surveyDepartment')?history.state.surveyDepartment:selectedRef.current);selectedRef.current=id;setSelected(id);if(history.state?.surveyDepartment!==id)history.replaceState({...history.state,surveyDepartment:id},'',location.href);cancelAnimationFrame(first);cancelAnimationFrame(second);first=requestAnimationFrame(()=>{second=requestAnimationFrame(()=>{const target=document.getElementById(location.hash.slice(1));if(!target||!target.closest('#implementation-survey-design'))return;for(let el=target.parentElement;el;el=el.parentElement)if(el.tagName==='DETAILS')el.open=true;target.scrollIntoView({block:'start'});target.focus({preventScroll:true})})})}reveal();addEventListener('hashchange',reveal);addEventListener('popstate',reveal);return()=>{cancelAnimationFrame(first);cancelAnimationFrame(second);removeEventListener('hashchange',reveal);removeEventListener('popstate',reveal)}},[]);
 function choose(id){selectedRef.current=id;setSelected(id);location.hash=id?d.departments.find(r=>r.id===id).anchor:'survey-departments';history.replaceState({...history.state,surveyDepartment:id},'',location.href);}
 const parents=[...new Set(d.departments.map(r=>r.parent))],Title=standalone?'h1':'h5';
 return <section id="implementation-survey-design" className={'survey-design'+(standalone?' survey-standalone':'')} data-survey-version={d.version} tabIndex={-1}>
 <header><small>{d.date} · {d.version} · 2027년 후속사업 의견 수렴</small><Title>{p.title}</Title><p>{p.lead}</p><p className="survey-preview-note">{p.previewNote}</p></header>
 <nav className="survey-jumps" aria-label="설문 구성">{p.navigation.map(([id,title],index)=><a href={'#'+id} key={id}><span>0{index+1}</span>{title}</a>)}</nav>
 <section id="survey-intro" className="survey-stage" tabIndex={-1}><h2><span>01</span>현재 프로젝트와 CCK 기반 AX 확대</h2>{d.intro.map(b=><article className="survey-intro-block" data-survey-intro={b.id} key={b.id}><h3>{b.title}</h3><p>{b.text}</p><small>{b.status}</small><p className="survey-help">{b.note}</p></article>)}
 <h3>기구축 플랫폼을 중심으로 연결할 역할</h3><dl className="survey-products">{d.products.map(([name,role,status])=><div key={name}><dt>{name}</dt><dd>{role}<small>{status}</small></dd></div>)}</dl>
 <ol className="survey-data-path survey-common-flow"><li>업무 목표·대상·권한</li><li>aRDa 원문·판본</li><li>NOA 질문·과업계획</li><li>규칙·허용 도구</li><li>담당자 검토·공식 결과</li><li>결과 대사·재계획</li></ol>
 <h3>공통 재사용과 처별 추가 과업</h3><p>실제 설치본·사용권·API·권한 상속·품질을 확인한 기능만 재사용 공수로 반영. 처별로 업무자료·식별키·적용규칙·스킬·원천 연계·전문 검수·인수평가를 추가.</p><p>자료정비·업무 스킬·규칙·연계·검증·교육·운영 전환의 증분 WBS로 대가 검토. FP/MM·단가·기간·인원은 범위와 원천 연계 확인 전 미확정. 기존 서버·로컬 LLM·신규 인프라 투자 0원·비전 제외 조건.</p><p>현행 처리 A → 정형·운영 개선 B → NOA 추가안 C를 비교하여 AI의 추가가치를 확인. 기존 기능으로 충분하면 범위 축소·보류·제외.</p><Sources sources={d.introSources}/></section>
 <section id="survey-departments" className="survey-stage" tabIndex={-1}><h2><span>02</span>내 처의 상세 업무와 병목 검토</h2><p>{p.selectionNote}</p><div className="survey-picker"><label htmlFor="survey-department-select">담당 처</label><select id="survey-department-select" value={selected} onChange={e=>choose(e.target.value)} aria-describedby="survey-selection-status"><option value="">담당 처를 선택해 주세요</option>{parents.map(parent=><optgroup key={parent} label={parent}>{d.departments.filter(r=>r.parent===parent).map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</optgroup>)}</select><p id="survey-selection-status" role="status">{current?current.name+' · '+current.topics.length+'개 주제 · '+current.mode:'선택한 처 없음 · 서두와 별도 의견은 먼저 확인 가능'}</p></div>
 <details className="survey-directory-details"><summary>전체 51처 목록에서 찾기</summary><p>{p.scopeNote}</p><ul className="survey-directory">{d.departments.map(r=><li key={r.id}><a href={'#'+r.anchor}>{r.name}<small>{r.parent}</small></a></li>)}</ul></details>
 {!current&&<p className="survey-empty">처 선택 후 업무·목적·근거부터 처리방법·측정·의견까지 연속해서 읽는 구성. 페이지 분할이나 이전 문서 이동 없이 확인.</p>}
 {d.departments.map(r=><section className="survey-department" data-survey-department={r.id} key={r.id} hidden={selected!==r.id}><details open={selected===r.id}><summary>{r.name} <small>{r.mode} · {r.topics.length}개 주제</small></summary><div id={r.anchor} className="survey-department-body" tabIndex={-1}><h3 className="survey-body-title">{r.name} · 2027년 검토과제</h3><p className="survey-scope-note">{r.parent} · 현재 조사 주제의 범위. 실제 분장·전결 확인 필요.</p><div className="survey-department-goal"><h4>이번 검토의 목적</h4><p>{r.reading.goal}</p></div><div className="survey-department-overview" aria-label="검토과제 목록">{r.topics.map((t,i)=><a key={t.id} href={'#survey-topic-'+t.id+'-purpose'}><small>검토과제 {String(i+1).padStart(2,'0')}</small><b>{t.reading.title}</b><span>{t.reading.goal}</span></a>)}</div>{r.topics.map((t,i)=><Topic key={t.id} t={t} first={i===0} index={i}/>)}<p className="survey-next"><a href="#survey-additional">별도 문제·대국민서비스 의견으로 이동 ↓</a></p></div></details></section>)}</section>
 <section id="survey-additional" className="survey-stage" tabIndex={-1}><h2><span>03</span>추가 문제·현업 불편·대국민서비스 의견</h2><p>선택한 병목의 타당성이나 AI 적용 찬반과 무관하게 작성할 의견. 누락된 문제·다른 원인·AX 확대와 제외 범위도 검토.</p>{current&&<p className="survey-selected-context">현재 선택: {current.name} · 해당 처 양식에 아래 5문항 포함</p>}<Fields fields={d.general}/><p className="survey-help">{d.privacy}</p></section>
 <section id="survey-resources" className="survey-stage" tabIndex={-1}><h2><span>04</span>현재 내용의 최신 설문지</h2><p>{p.resourcesNote}</p>{current?<div className="survey-resource-current"><h3>{current.name} · {d.version}</h3><p className="survey-primary-downloads"><Link to={current.downloads[0][1]} download>상세 설명·설문지 {d.version} MD ↓</Link><Link to={current.downloads[2][1]} download>빈 회신 양식 CSV ↓</Link></p></div>:<p>담당 처 선택 후 이 위치에서 최신 상세 설명과 빈 회신 양식 다운로드.</p>}<p>{d.interpretation}</p><p>{d.handoff}</p><p className="survey-help">실제 회신은 자동 공개하지 않음. 조사도구 등록·발송·회신 수집 미실시. ResearchBay의 실제 가져오기 규격·보관·권한 설정은 별도 확인.</p></section>
 </section>;
}

// 통합 읽기 화면에서는 이미 읽은 설명을 반복하지 않고 현업 확인 문항만 연결.
export function SurveyOpinion({departmentId,projectId,onTopic}){const r=d.departments.find(r=>r.id===departmentId);if(!r)return <p>현재 연결된 처별 질문 없음. 담당 업무·자료·병목부터 확인할 대상.</p>;const t=r.topics.find(t=>t.id===projectId)||r.topics[0],b=t.briefing;return <section className="survey-design integrated-survey" id={r.anchor} tabIndex={-1} data-integrated-survey={r.id}>
 <header><h3>{r.name} · 현업 확인</h3><p>{t.reading.title} · {t.status}. {b.provenance}</p><p>앞의 설명을 바탕으로 병목의 정합성·타당성·별도 원인·추가 의견을 확인하는 질문. 실제 응답 저장·제출 기능과 구분.</p></header>
 {r.topics.length>1&&<nav className="integrated-project-picker" aria-label="이 처의 의견 주제">{r.topics.map(x=><button key={x.id} aria-pressed={t.id===x.id} onClick={()=>onTopic?.(x.id)}>{x.reading.title}{x.id==='QE-H01'?' · 추가 검토':''}</button>)}</nav>}<section id={'survey-topic-'+t.id+'-opinion'} tabIndex={-1}><h4>이 과제의 확인 질문</h4><div className="survey-probes">{b.probes.map((q,i)=><article key={i}><p><b>{i+1}. {q.question}</b></p><p>필요 근거: {q.evidence}</p></article>)}</div>
 <h4>응답 역할·현재 플랫폼 사용</h4><Fields fields={d.profile}/>{t.discovery?<Fields fields={d.discovery} topic={t}/>:p.questionGroups.map(g=><section className={'survey-question-group survey-question-group-'+g.id} key={g.id}><h5>{g.title}</h5><Fields fields={g.fields.map(id=>d.topicFields.find(f=>f.id===id))} topic={t}/></section>)}
 </section><section id="survey-additional" tabIndex={-1}><h4>별도 문제·현업 불편·대국민서비스 의견</h4><Fields fields={d.general}/><p>{d.privacy}</p></section>
 <section id="survey-resources" tabIndex={-1}><h4>최신 상세 설명·설문지</h4><p className="survey-primary-downloads"><Link to={r.downloads[0][1]} download>상세 설명·설문지 {d.version} MD ↓</Link><Link to={r.downloads[2][1]} download>빈 회신 양식 CSV ↓</Link></p><p>{d.handoff}</p><p>{d.interpretation}</p></section>
 </section>}
