import React from 'react';
import {Link,Out} from './core.jsx';
import d from './survey-design.cjs';
import './survey-design.css';
function Fields({fields}){return <div className="survey-fields">{fields.map(f=><article key={f.id} data-survey-field={f.id}><small>{f.id} · {f.type==='single_choice'?'단일선택':f.type==='multiple_choice'?'복수선택':'서술형'} · 선택 작성</small><h6>{f.title}</h6><p>{f.question}</p>{f.options.length>0&&<ul className="survey-options">{f.options.map(o=><li key={o.code}>{o.label}</li>)}</ul>}<p className="survey-help">{f.help}</p>{f.displayIf&&<p className="survey-help">{f.id==='ACTUAL_CASE'?'현재/조건부 발생을 확인한 경우 선택 작성':'AI 추가 적용을 선택한 경우에만 작성'}</p>}</article>)}</div>}
function Sources({sources}){return <details className="survey-sources"><summary>출처·확인 범위 ({sources.length}건)</summary><p>{d.sourceNote}</p>{sources.map(s=><p key={s.id+'-'+s.url}><b>{s.id} · </b>{s.url?<Out url={s.url}>{s.title}</Out>:s.title}<small>게시/시행 {s.published||s.effective||'미표시'} · 기존 확인 {s.checkedAt||s.accessed||s.date||'미확인'} · {s.limit||s.verification_scope||s.note||s.scope||'기존 원장 확인범위 참조'}</small></p>)}</details>}
export function SurveyDesign(){return <section id="implementation-survey-design" className="survey-design" data-survey-version={d.version} tabIndex={-1}>
 <header><small>{d.date} · {d.version} · 2027년 후속사업 의견 수렴</small><h5>{d.title}</h5><p>{d.status}</p><p>설명문을 읽은 뒤 본인 처의 병목과 제안 방법을 검토하고, 추가 의견을 작성하는 구성. 아래는 문항 미리보기와 빈 양식이며 실제 회신 수집 화면이 아님.</p></header>
 <ol className="survey-flow">{d.flow.map(s=><li key={s}>{s}</li>)}</ol>
 <p className="analysis-downloads">{d.downloads.map(([label,to])=><Link key={to} to={to} download>{label} ↓</Link>)}</p>
 <nav className="survey-jumps" aria-label="설문 구성"><a href="#survey-intro">서두 설명</a><a href="#survey-departments">내 처의 병목 검토</a><a href="#survey-response-model">의견 작성 방식</a><a href="#survey-additional">별도 의견</a></nav>
 <section id="survey-intro" tabIndex={-1}><h6>먼저 읽는 프로젝트·솔루션·AX 확대 설명</h6>{d.intro.map(b=><article className="survey-intro-block" data-survey-intro={b.id} key={b.id}><small>{b.status}</small><h6>{b.title}</h6><p>{b.text}</p><p className="survey-help">{b.note}{b.source&&' · '+b.source}</p></article>)}<dl className="survey-products">{d.products.map(([name,role,status])=><div key={name}><dt>{name}</dt><dd>{role}<small>{status}</small></dd></div>)}</dl><Sources sources={d.introSources}/></section>
 <section id="survey-departments" tabIndex={-1}><h6>처별 병목·제안 방법·검토 양식</h6><p>39처의 기존 42개 기획과 QE-H01 추가 후보 1개를 검토. KATRI 미매핑 12처는 병목 동의를 묻기 전 실제 업무·문제부터 확인. 조사 준비 범위 51처·55주제이며 확정 사업 수가 아님.</p><ul className="survey-directory">{d.departments.map(r=><li key={r.id}><a href={'#'+r.anchor}>{r.name}<small>{r.mode}</small></a></li>)}</ul>
 {d.departments.map(r=><section className="survey-department" data-survey-department={r.id} key={r.id}><details><summary>{r.name} <small>{r.mode} · {r.topics.length}개 주제</small></summary><div id={r.anchor} className="survey-department-body" tabIndex={-1}><h6 className="survey-body-title">{r.name} · 병목 검토·추가 의견</h6><p>{r.parent} · 실제 분장·전결 확인 필요. 응답 역할 후보: {r.roles.join(' · ')}</p><p><a href="#survey-intro">공통 서두·NOA/현재 프로젝트 설명 먼저 읽기 ↑</a></p><p className="analysis-downloads">{r.downloads.map(([label,to])=><Link key={to} to={to} download>{label} ↓</Link>)}{r.documentsRoute&&<Link to={r.documentsRoute}>기존 한글 계획서 ↗</Link>}<a href={'#implementation-interview-'+r.id}>이전 인터뷰 준비 v0.1 ↗</a></p>
 {r.topics.map(t=><article className="survey-topic" data-survey-topic={t.id} key={t.id}><small>{t.id} · {t.status}</small><h6>{t.title}</h6><dl>{[['목적·필요한 결과',t.purpose],['현재 조사된 병목 가설',t.gap||'현재 제시할 병목 가설 없음. 담당 업무와 문제 유무부터 확인.'],['CCK 기반 해결 방법',t.how||'현행 확인 후 대안 검토. 솔루션을 사전 배정하지 않음.'],['필요한 자료·조건',t.inputs.join(' · ')||'실제 입력·자료·권한 미확인'],['기존 대응·공식 판단 경계',t.boundary]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>
 {t.metrics.length>0&&<div className="survey-measures"><b>검토할 효과·측정 방법</b><ul>{t.metrics.map(m=><li key={m.name}><strong>{m.name}</strong><p>{m.formula}</p><small>{m.method||m.records||m.note}</small></li>)}</ul><p className="survey-help">기준선·목표값·CCK 적용효과는 실측 전 미확정. 편익과 중요 오류·과잉처리를 함께 확인.</p></div>}
 <div className="survey-writing"><b>{t.discovery?'업무·문제 발견 3문항':'이 병목에 대한 판단·의견 작성'}</b>{t.discovery?<Fields fields={d.discovery}/>:<><p>① 업무 정합성 ② 현재 발생 상태 ③ 설명·원인 타당성 ④ 이유·수정문 ⑤ 실제 근거·반대 사례 ⑥ 기존 대응·개선 방식 ⑦ 추가 AI 가치·실행조건 ⑧ 우려·측정·별도 대안·중요도.</p><p>선택지와 질문 전문은 아래 <a href="#survey-response-model">공통 의견 작성 방식</a> 및 이 처의 설문지/CSV에 수록. <b>담당 아님·자료 부족·이미 해결·AI 불필요도 작성 가능.</b></p></>}
 <details><summary>이 주제를 구체화할 기존 확인 질문 3개</summary><ul>{t.probeQuestions.map(q=><li key={q.id}>{q.id} · {q.question}</li>)}</ul></details></div><Sources sources={t.sources}/></article>)}
 <p className="survey-help">병목에 동의하지 않아도 현업 불편·대국민서비스·추가 문제·확대/제외 의견 작성 가능. <a href="#survey-additional">별도 의견 5문항 보기</a></p></div></details></section>)}
 </section>
 <section id="survey-response-model" tabIndex={-1}><h6>의견 작성 방식 · 정합성과 타당성의 분리</h6><p>응답 배경 3문항, 선택한 병목별 15문항, 추가 의견 5문항의 정의. 모든 문항을 한꺼번에 강제하지 않고 담당 범위와 응답에 따라 분기. 미매핑 처에는 업무 발견 3문항 적용.</p><Fields fields={d.profile}/><Fields fields={d.topicFields}/><h6>선택·분기·해석</h6><dl className="survey-products">{d.branchRules.map(([label,rule])=><div key={label}><dt>{label}</dt><dd>{rule}</dd></div>)}</dl><p>{d.interpretation}</p><p className="survey-help">NONE(근거 미확보), NO_NEED(추가 개선 불필요), UNKNOWN(판단자료 부족)은 해당 복수선택의 다른 항목과 동시 선택하지 않음. 숫자 척도의 평균·합계로 발주를 자동 결정하지 않음.</p></section>
 <section id="survey-additional" tabIndex={-1}><h6>별도 의견 · 현업 불편·대국민서비스·AX 확대</h6><Fields fields={d.general}/><p className="survey-help">{d.privacy}</p><p>{d.handoff}</p><p className="survey-help">{d.tool}</p></section>
 </section>}
