import React,{useState,useEffect,useRef}from'react';
import{ArrowRight,Search,ChevronDown,Network,FileText,ShieldCheck,Layers,FolderOpen}from'lucide-react';
import{Link,Out,navigate}from'./core.jsx';
import content from'./ux-content.cjs';
import hub from'./planning-hub.cjs';
import './planning-hub.css';
import './feedback-review.css';
const h=content.home;
export function UserHome({route,navigationEpoch}){
 const initial=hub.homeFilters(location.search);
 const[q,setQ]=useState(initial.q),[bundle,setBundle]=useState(initial.bundle),[status,setStatus]=useState(initial.status),[notice,setNotice]=useState('');
 const[expanded,setExpanded]=useState({});const input=useRef(null);
 const rows=hub.projects.filter(p=>(bundle==='all'||p.bundle===bundle)&&(status==='all'||p.classification===status)&&hub.matchesQuery(hub.projectSearchText(p),q));
 function writeFilters(text,b,s){const url=new URL(location.href);[['q',text.trim()],['bundle',b==='all'?'':b],['status',s==='all'?'':s]].forEach(([k,v])=>v?url.searchParams.set(k,v):url.searchParams.delete(k));return url;}
 function change(text=q,b=bundle,s=status){setQ(text);setBundle(b);setStatus(s);setNotice('');const url=writeFilters(text,b,s),target=hub.projects.find(p=>'#planning-project-'+p.id===url.hash);if(target&&((b!=='all'&&target.bundle!==b)||(s!=='all'&&target.classification!==s)||!hub.matchesQuery(hub.projectSearchText(target),text)))url.hash='planning-candidates';history.replaceState(history.state,'',url);if(document.activeElement?.closest('[data-planning-project]'))requestAnimationFrame(()=>input.current?.focus())}
 function all(open){setExpanded(Object.fromEntries(rows.map(p=>[p.id,open])))}
 useEffect(()=>{const filters=hub.homeFilters(location.search);let id=location.hash.slice(1);try{id=decodeURIComponent(id)}catch{id=''}const target=hub.projects.find(p=>id==='planning-project-'+p.id),adjusted=[];
  if(target){if(!hub.matchesQuery(hub.projectSearchText(target),filters.q)){filters.q='';adjusted.push('검색어')}if(filters.bundle!=='all'&&filters.bundle!==target.bundle){filters.bundle='all';adjusted.push('묶음')}if(filters.status!=='all'&&filters.status!==target.classification){filters.status='all';adjusted.push('이전 분류')}setExpanded(v=>({...v,[target.id]:true}));}
  setQ(filters.q);setBundle(filters.bundle);setStatus(filters.status);setNotice(adjusted.length?target.id+' 공유 링크를 표시하기 위해 충돌하는 '+adjusted.join('·')+' 필터 해제. 다른 조건 유지.':'');if(adjusted.length)history.replaceState(history.state,'',writeFilters(filters.q,filters.bundle,filters.status));
  let next;const frame=requestAnimationFrame(()=>{next=requestAnimationFrame(()=>{if(target){const el=document.getElementById(id);el?.scrollIntoView({block:'start'});el?.focus()}})});return()=>{cancelAnimationFrame(frame);if(next)cancelAnimationFrame(next)};
 },[route,navigationEpoch]);
 return <div className="ux-home planning-home" data-planning-home={hub.date}>
 <header className="planning-hero"><div><span className="ux-eyebrow">{hub.label} · 검토 기준 {hub.date}</span><h1>{hub.title}</h1><p>{hub.lead}</p><nav aria-label="기획 시작"><Link className="ux-primary" to={hub.journey[0][3]}>ISP 검토부터 시작 <ArrowRight size={18}/></Link><a href="#planning-candidates">사업 후보 찾기</a><Link to="planning-documents.html">한글 계획서 다운로드</Link></nav></div><aside><ShieldCheck size={23}/><h2>현재 단계</h2><p>{hub.status}</p><small>기존 AI 플랫폼·로컬 LLM 활용<br/>신규 인프라 투자 0원 전제<br/>2027년 단년도 사업 범위 검토</small></aside></header>
 <div className="planning-summary" aria-label="현재 조사·작성 범위">{[['작성된 처',hub.counts.departments,'처'],['검토할 업무',hub.counts.projects,'항목'],['현재 연결 문서',hub.counts.documents,'개'],['보안·윤리 검토',hub.counts.controls,'항목']].map(([label,n,unit])=><div key={label}><span>{label}</span><strong>{n}<small>{unit}</small></strong></div>)}</div><p className="planning-scope-note">{hub.notice}</p>
 <section className="ux-identity" aria-labelledby="ux-identity-heading"><div><span className="ux-eyebrow">기획의 출발점 · TS는 어떤 기관인가</span><h2 id="ux-identity-heading">{h.definition}</h2><ul>{h.identity.map(t=><li key={t}>{t}</li>)}</ul><p className="ux-source"><Out url={h.definitionSource.to}>{h.definitionSource.label}</Out><small>{h.definitionDate}</small></p><nav className="planning-background" aria-label="기관과 법정업무 이해"><Link to="about.html">기관의 존재 의의</Link><Link to="legal/mapping.html">법령·업무·담당 처</Link><Link to="vision.html">공식 2026–2030 전략</Link><Link to="index.html?view=map">조직 연결지도</Link></nav></div></section>
 <section className="ux-start" aria-labelledby="ux-start-heading"><div className="ux-section-title"><h2 id="ux-start-heading">후속사업기획의 검토 순서</h2><p>목적·근거 확인 → 업무 묶음 → 처별 설계 → 발주 문서</p></div><nav className="ux-journey" aria-label="사업기획 읽는 순서">{hub.journey.map(([n,title,desc,to])=><Link to={to} key={n}><span>{n}</span><h3>{title}</h3><p>{desc}</p><ArrowRight size={18}/></Link>)}</nav></section>
 <section className="planning-section" id="planning-bundles" tabIndex={-1}><div className="ux-section-title"><h2>어떤 단위로 사업을 묶을 것인가</h2><p>공통 코어 1회 산정 + 업무별 추가 작업·조건 검토</p></div>{hub.bundles.filter(b=>b.id==='B00').map(b=><div className="planning-core" data-planning-bundle={b.id} key={b.id}><Layers size={27}/><div><span>{b.id} · 공통 기반</span><h3>{b.title}</h3><p>{b.initial}</p></div><Link to={b.to}>공통 범위·중복 비용 확인 <ArrowRight size={16}/></Link></div>)}<div className="planning-bundles">{hub.bundles.filter(b=>b.id!=='B00').map(b=><article data-planning-bundle={b.id} key={b.id}><span>{b.id} · 조사 후보 {b.count}항목</span><h3>{b.title}</h3><p>{b.initial}</p><dl><dt>검토 진입조건</dt><dd>{b.entry}</dd></dl><nav><Link to={b.to}>범위·수락·RFP 확인 <ArrowRight size={15}/></Link><a href="#planning-candidates" onClick={()=>change('',b.id,'all')}>해당 업무 찾기</a></nav></article>)}</div><p className="planning-scope-note">업무 묶음은 편성 검토안. 후보 수를 발주 건수로 사용하지 않으며, 부서별 계약·권한·자료·운영 책임 확인 후 범위 결정.</p></section>
 <section className="planning-section" id="planning-candidates" tabIndex={-1}><div className="ux-section-title"><h2>담당 처와 사업 후보를 함께 검토</h2><p>제안 → 요구사항·아키텍처 → 비용·RFP → 한글 문서 연결</p></div>
 <div className="ux-find planning-finder"><form role="search" onSubmit={e=>{e.preventDefault();navigate('solutions.html'+(q.trim()?'?q='+encodeURIComponent(q.trim()):''))}}><label htmlFor="ux-home-search">처·사업·문제 검색</label><div className="planning-search-row"><input ref={input} id="ux-home-search" type="search" value={q} onChange={e=>change(e.target.value)} placeholder="예: 모빌리티연구처, DRT, 검정, 철도" aria-describedby="planning-search-hint"/><button type="submit"><Search size={18}/>처별 제안 목록으로</button></div><p id="planning-search-hint">입력 시 아래 42개 업무 후보 필터링. 버튼 선택 시 처별 전체 제안·기관 업무 목록으로 이동.</p></form></div>
 <div className="planning-filters" role="group" aria-label="업무 후보 필터"><div aria-label="업무 묶음">{[['all','전체'],...hub.bundles.map(b=>[b.id,b.id+' · '+(b.id==='B00'?'공통':b.title)])].map(([id,label])=><button type="button" key={id} aria-pressed={bundle===id} onClick={()=>change(q,id,status)}>{label}</button>)}</div><label>이전 구현 검토 분류<select value={status} onChange={e=>change(q,bundle,e.target.value)}>{hub.classificationOptions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div>
 <div className="planning-results"><p role="status" aria-live="polite">현재 {rows.length}항목 · {new Set(rows.map(p=>p.code)).size}처 · 연결 문서 {new Set(rows.flatMap(p=>p.documents.map(d=>d.path))).size}개</p><div><button type="button" onClick={()=>{change('','all','all');input.current?.focus()}}>필터 초기화</button><button type="button" onClick={()=>all(true)}>결과 모두 펼치기</button><button type="button" onClick={()=>all(false)}>결과 모두 접기</button></div></div><p className="planning-scope-note">분류: {hub.projects[0]?.classificationDate} 구현 가능성 검토 이력. 최신 ISP 상태는 모든 항목 ‘조사 후보’이며 사업 선정·착수 확정과 구분. 3개 문서를 공유하는 복수 과업은 문서 중복 산정 제외.</p>
 {notice&&<p className="planning-filter-notice" role="status">{notice}</p>}<div className="planning-projects">{rows.map(p=><details key={p.id} id={'planning-project-'+p.id} tabIndex={-1} data-planning-project={p.id} open={!!expanded[p.id]} onToggle={e=>{const open=e.currentTarget.open;setExpanded(v=>!!v[p.id]===open?v:{...v,[p.id]:open})}}><summary><span className="planning-owner"><small>{p.id} · {p.bundle}</small><strong>{p.department}</strong></span><span className="planning-project-title">{p.title}</span><span className={'planning-classification '+p.classification}>{p.classificationLabel}<small>현재 ISP: 조사 후보</small></span><ChevronDown size={19}/></summary><div className="planning-project-body"><div className="planning-project-reading"><dl>{[['달성할 업무 목적',p.purpose],['확인할 현행 한계',p.gap],['CCK로 수행할 처리',p.how],['처음 검증할 범위',p.scope],['필요한 업무 자료',<ul>{p.inputs.map((t,i)=><li key={i}>{t}</li>)}</ul>],['공식 판단·책임 경계',p.decisionBoundary]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><aside><h3>착수 전 확인할 조건</h3><p>{p.status} · {hub.date}</p><p>이전 구현 검토: {p.classificationLabel} · {p.classificationDate}</p><p><b>현행 기준선:</b> {p.baseline??'실측 미확인'}</p><p><b>목표·비용:</b> {p.target??'목표 미설정'} · {p.cost??'대가 미확정'}</p>{p.sharedDocuments&&<p>같은 처의 복수 과업과 3개 계획·산정·도식 문서 공유. 과업별 범위는 상세제안에서 확인.</p>}<nav><Link to={p.ispRoute}>처별 ISP 확인사항</Link><Link to={p.implementationRoute}>제품·자료·운영 조건</Link><Link to={p.costRoute}>대가 산정·검증 조건</Link></nav></aside></div>
 <p className="planning-scope-note">설명 연결: {p.descriptionOrigin} · {p.descriptionDate}. 문제·HOW는 기존 기획 가설. 현업 수요·기능 미지원·구현·효과 검증 완료와 구분.</p><details className="planning-project-evaluation"><summary>이 업무에서 측정할 효과 · {p.metrics.length}개 산식</summary><p>기준선·목표·인수 임계값은 실제 자료와 현업 합의 후 결정. 지표 등록은 달성 또는 인수 확정을 의미하지 않음.</p><dl>{p.metrics.map(m=><div key={m.name}><dt>{m.name}</dt><dd>{m.formula}{m.records&&<p>관측 자료: {m.records}</p>}{m.note&&<p>측정 조건: {m.note}</p>}</dd></div>)}</dl><Link to={p.designLinks.find(d=>/효과|측정|요구사항/.test(d.label))?.to||p.proposalRoute}>업무별 측정·검증 상세 →</Link></details><details className="planning-project-evaluation"><summary>묶음 공통조건 · 업무별 인수기준과 구분</summary><dl>{[['자료·권한의 진입조건',p.entry],['공통 실패·수락 확인',p.acceptance],['추가 개발 경계',p.boundary]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><p>위 내용은 {p.bundle} 묶음의 공통 검토조건. 실제 업무의 대상·규칙·예외·시험자료에 맞춰 조정 후 확정.</p><Link to={p.rfpRoute}>요구사항·RFP 편성 상세 →</Link></details><details className="planning-project-evaluation"><summary>기존 조사 출처·적용 한계</summary><p>원장 인용·열람 이력의 연결. 이번 UI 보완에서 전체 원문을 재검증한 결과가 아니며, 현행 판본·잔여 문제는 적용 전 확인.</p><ul>{p.sources.map(s=><li key={s.id}><Out url={s.url}>{s.title}</Out><small>{s.id} · {s.published||s.date||'발행일 미확인'} · 확인이력 {s.checkedAt||s.accessed||'미확인'}{s.source_level?' · '+s.source_level+' 자료':''}{s.grade?' · 원장 판정 '+s.grade:''}</small>{[...new Set([s.note,s.limit,s.verification_scope].filter(Boolean))].map(t=><p key={t}>{t}</p>)}</li>)}</ul></details><nav className="planning-design-links" aria-label={p.id+' 상세 설계'}><Link className="ux-primary" to={p.proposalRoute}>사업 정의·근거·HOW <ArrowRight size={16}/></Link>{p.designLinks.map(d=><Link key={d.to} to={d.to}>{d.label} ↗</Link>)}<Link to={p.rfpRoute}>묶음 RFP 요구사항</Link></nav>
 <div className="planning-native" aria-label={p.id+' 한글 파일'}>{p.documents.map(d=><div key={d.path}><Link to={d.path} download><FileText size={18}/>{d.title||d.label||d.kind} ↓</Link><small>{d.version} · {d.date||d.updatedAt}</small><p>{d.status}</p></div>)}</div><p className="planning-rfp-trace">요구사항 연결 후보: {p.rfpCandidates.join(' · ')} / 적용 보안·윤리 검토 {p.controls.length}항목. 검토 항목 등록은 시험 통과·법적 승인 완료와 구분.</p></div></details>)}</div>{rows.length===0&&<div className="ux-empty"><h3>조건에 맞는 업무 후보 없음</h3><p>처 이름 또는 더 짧은 업무 키워드로 재검색하거나 필터 초기화.</p><button onClick={()=>{change('','all','all');input.current?.focus()}}>전체 업무 후보 보기</button></div>}</section>
 <section className="planning-section" id="planning-measurement" tabIndex={-1}><div className="ux-section-title"><h2>효과를 어떤 자료로 검증할 것인가</h2><p>동일 사건의 A 현행 / B 정형 개선 / C B+NOA 비교</p></div><p className="planning-scope-note">기준선·목표·표본·중단기준을 평가 전에 합의. 검수·재작업·오탐·권리 피해를 함께 측정하며, 시간 절감을 감축 인원으로 환산하지 않음.</p><div className="planning-measurements">{hub.metrics.map(m=><details key={m.id} data-planning-metric={m.id}><summary><b>{m.id} · {m.name}</b><span>산식·자료·비교방법 확인</span></summary><dl>{[['산식',m.formula],['관측 자료',m.data],['측정방법',m.method],['해석 한계',m.boundary]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></details>)}</div><Link to="research-library.html?view=planning#implementation-metrics">측정 책임·대가·운영검증 상세 →</Link></section><section className="planning-section" id="planning-readiness" tabIndex={-1}><div className="ux-section-title"><h2>다음 협의에서 확인할 사항</h2><p>피드백 미확보 → 확인 질문·증거·담당자 중심으로 구체화</p></div><div className="planning-readiness">{hub.readiness.map((x,i)=><article key={x.id||i}><small>{x.id||String(i+1).padStart(2,'0')} · {x.state||x.status}</small><h3>{x.title||x.item}</h3><p>{x.evidence||x.question||x.condition}</p><p className="planning-scope-note">{x.owner}</p></article>)}</div><details className="planning-project-evaluation"><summary>현업·개발팀에 확인할 14개 질문 · 요청·회신 전</summary><p>현재 외부 피드백 미확보. 아래는 발송·협의 준비용이며 현업 회신·수락으로 사용하지 않음.</p><ol>{hub.feedbackQuestions.map(q=><li key={q.id}><strong>{q.id} · {q.owner}</strong><p>{q.question}</p><small>확인할 증거: {q.evidence} / {q.status}</small></li>)}</ol><Link to="research-library.html?view=planning#implementation-feedback">질문서·미회신 상태 상세 →</Link></details><nav className="planning-next"><Link to={hub.journey[0][3]}>ISP 원문 검토·처별 질문</Link><Link to="research-library.html?view=planning#isp-assurance">보안·개인정보·AI 윤리</Link><Link to="research-library.html?view=planning#implementation-metrics">정량효과·측정조건</Link><Link to="skill-pms.html#pms-direction">기구축 AI 플랫폼의 확장 방식</Link></nav></section>
 <nav className="planning-resources" aria-label="작성 문서와 조사 근거"><Link to="planning-documents.html"><FolderOpen size={23}/><h2>정보화사업계획서·대가·도식</h2><p>현재 판본·이전 판본 구분 / HWPX 개별 다운로드</p></Link><Link to="research-library.html"><FileText size={23}/><h2>조사자료실·공식 출처</h2><p>법령·정책·선행사례·기사·민원 조사 근거</p></Link><Link to="solutions.html"><Network size={23}/><h2>처별 전체 업무·제안</h2><p>공식 조직 대조 / 작성 완료와 자료 보완 필요 구분</p></Link></nav>
 <details className="planning-missing"><summary>조직 대조 시 추가 자료가 필요한 12처</summary><p>현재 39처 문서와 별도. 공식 공개 조직 대조 범위 51처에서 연결 문서가 없는 KATRI 12처이며, 전국 지역 조직 모집단 확정을 뜻하지 않음.</p><ul>{hub.missing.map(d=><li key={d.id}><Link to={d.to}>{d.name} · {d.parent}</Link></li>)}</ul></details>
 </div>
}
