const fs=require('fs'),path=require('path'),assert=require('assert');
const {pathToFileURL}=require('url');
const {marked}=require('C:/Users/김희섭/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/marked');
const root='G:/내 드라이브/1. 업무영역/6. CCK/1. 사업관리/TS/bizops/[TS 사업기획]';
const prev=path.join(root,'05_통합사업기획/TS_22개업무_사업기획_2026-09-14');
const out=path.join(root,'05_통합사업기획/TS_22개업무_사업기획_2026-09-15_v0.2');
const policy=path.join(root,'00_기획지침/기구축사업_CCK_AI_적용과_중복판정.md');
const review=require('./ts22_v02_data.cjs');
const prior=JSON.parse(fs.readFileSync(path.join(prev,'03_사업기획_원장.json'),'utf8'));
const lookup=new Map(review.items.map(x=>[x.n,x]));
const plans=prior.plans.map(p=>({...p,previous_status:p.status,previous_reason:p.reason,...lookup.get(p.n),registered_as_new_opportunity:false}));
assert(plans.length===22&&lookup.size===22);
for(const d of ['개별기획서','검증','기준_변경전'])fs.mkdirSync(path.join(out,d),{recursive:true});
const historyFiles=['AGENTS.md','README.md','00_기획지침/신규사업_범위와_중복배제.md','00_기획지침/TS_신규사업기획_지침.md','00_기획지침/CCK_로컬LLM_적용범위.md','00_기획지침/국민체감형_AX_선정기준.md','04_기관리서치/기관업무_원장.json'];
for(const f of historyFiles){const t=path.join(out,'기준_변경전',f);if(!fs.existsSync(t)){fs.mkdirSync(path.dirname(t),{recursive:true});fs.copyFileSync(path.join(root,f),t);}}
const src=JSON.parse(fs.readFileSync(path.join(prev,'근거원장.json'),'utf8'));
src.as_of='2026-09-15';
for(const s of src.sources){if([8,9,33,43,31,48].includes(s.number)){s.previous_accessed_at=s.accessed_at;s.accessed_at='2026-09-15';s.recheck_status=[8,9,33].includes(s.number)?'공식 소개 본문 재확인; 운영 시스템·제품 실행 시험 아님':'내부 문서 관련 범위 확인; 계약 확정·제품 성능 증거 아님';}if(s.number===31){s.title='사업 범위와 중복판정 v2.0';s.publication_or_effective_date='2026-09-15 사용자 정정';s.verified_scope='기구축 업무·시스템·AI 후속 적용 허용, 동일 계약 기능의 이중 계상 구분';}if(s.number===48){s.verified_scope='기구축 업무 CCK AI 적용 포함. 로컬 LLM·주관 수행·신규 인프라 0원 유지';}}
src.sources.push({number:49,id:'TS22-S49',title:'기구축 사업의 CCK AI 적용과 중복판정',publisher:'현재 사용자 지시를 반영한 프로젝트 기획 기준',url:pathToFileURL(policy).href,publication_or_effective_date:'2026-09-15',accessed_at:'2026-09-15',verified_scope:'기구축 사업도 CCK AI 적용 대상에 포함한다는 사용자 정정; 기관 승인 아님',recheck_status:'이번 기획 개정의 기준'});
src.limitations.push('22개 설계안 간 비교이며 실제 구축·계약 기능의 동일성 확정 아님. 231쌍은 규칙에 따른 전개 결과이며 231개 독립 현장 검증이 아님');
const sm=new Map(src.sources.map(s=>[s.number,s]));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const link=(t,h)=>`[${t}](<${h}>)`;
function foot(ns){return '\n## 출처\n\n'+[...new Set(ns)].map(n=>{const s=sm.get(n);assert(s);return `[^${n}]: ${s.publisher}. [${s.title}](${s.url}). ${s.publication_or_effective_date}. 열람 ${s.accessed_at}. ${s.verified_scope}. ${s.recheck_status}.`;}).join('\n\n')+'\n';}
const oldHTML=fs.readFileSync(path.join(prev,'00_사업기획_통합보기.html'),'utf8');
const style=oldHTML.match(/<style>([\s\S]*?)<\/style>/)[1]+'.revision{padding:15px 18px;border-left:3px solid #333;background:#f5f5f5;margin:22px 0}td:first-child{min-width:75px}summary{cursor:pointer}';
function render(md){const defs={};md=md.replace(/^\[\^(\d+)\]: (.+)$/gm,(_,n,t)=>{defs[n]=t;return '';});md=md.replace(/\[\^(\d+)\]/g,(_,n)=>`<sup><a href="#source-${n}" aria-label="출처 ${n}">[${n}]</a></sup>`);let h=marked.parse(md),i=0;h=h.replace(/<h2>/g,()=>`<h2 id="chapter-${++i}">`);h=h.replace(/<table>/g,'<div class="table-wrap" role="region" aria-label="표, 좌우 스크롤" tabindex="0"><table>').replace(/<\/table>/g,'</table></div>');return h+'<ol class="sources">'+Object.entries(defs).map(([n,t])=>`<li id="source-${n}" value="${n}">${marked.parseInline(t)}</li>`).join('')+'</ol>';}
function html(title,md,nav=''){const chapters=[...md.matchAll(/^## (.+)$/gm)];const toc=chapters.length>7?'<details class="contents"><summary>기획서 목차</summary><ol>'+chapters.map((m,i)=>`<li><a href="#chapter-${i+1}">${esc(m[1])}</a></li>`).join('')+'</ol></details>':'';return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><style>${style}</style></head><body><a class="skip" href="#main">본문 바로가기</a><main id="main" tabindex="-1">${nav}${toc}${render(md)}</main></body></html>`;}
const pairMap=new Map(review.relations.map(x=>[x.a+'-'+x.b,x]));
const pairs=[];
for(let i=0;i<plans.length;i++)for(let j=i+1;j<plans.length;j++){const a=plans[i],b=plans[j],manual=pairMap.get(a.n+'-'+b.n);pairs.push({a:a.id,b:b.id,a_title:a.title,b_title:b.title,type:manual?.type||(a.family===b.family?'공통 구성요소':'별도 업무 범위'),shared:manual?.shared||(a.family===b.family?a.family+'의 처리·근거·검토 구조':'공통 NOA 실행·인증·검색·감사 기반'),difference:manual?.difference||a.output+' / '+b.output,action:manual?.action||(a.family===b.family?'엔진·공통 화면은 공유하고 업무별 지식·연계·검수만 별도 산정':'각 업무 모듈을 유지. 공통 기반 비용은 중복 산정하지 않음'),basis:manual?'개별 설계의 대상·입력·기능·산출물 비교 후 명시한 관계':'22개 설계의 기능군·입출력에 따른 규칙 전개; 계약·현장 확인 아님',confirmed_contract_duplicate:false});}
assert(pairs.length===231);
for(const p of plans){const old=prior.plans.find(x=>x.n===p.n);let md=fs.readFileSync(path.join(prev,p.document),'utf8');
md=md.replaceAll(old.status,p.status).replaceAll(old.reason,p.reason);
md=md.replace(old.overlap,old.overlap+'; 기구축 업무의 존재는 제외 사유가 아니며 기존 기능 재사용과 추가 AI 적용분을 구별');
md=md.replace('SFR-001~009 정리자료는 기존 플랫폼·자동차검사/자격시험/안전단속 특화·민원·전세버스 공시 기능을 명시한다. 계약 원문·승인된 직무 시나리오와 같은 범위이면 신규로 제안하지 않는다.','SFR-001~009 정리자료에는 공통 기반·직무 특화·민원·전세버스 AI 요구가 기재되어 있다. 동일 납품 기능은 기존 계약 이행·재사용으로 묶고, 새 적용 업무·변경 기능·연계·지식 정비·평가 등 추가 수행분을 사업 범위로 산정한다. 기구축 또는 같은 업무라는 이유로 적용 대상을 제외하지 않는다.');
md=md.replace('비중복·제품·수요 검증 전에는 확정 후보나 발주 가능 사업으로 승격하지 않는다.','이번 판정은 CCK AI 적용 검토 방향이다. 최종 계약의 추가 범위·제품·수요·견적을 확인한 뒤 실제 발주·수행 범위를 확정한다.');
md=md.replace('독립 사업의 구축·예산을 책정하지 않고 관련 기획서에 부속 과업으로 연결한다.','해당 업무를 CCK AI 적용 대상에 포함하고 관련 기획서와 공통 기능 1회분·업무별 추가분으로 연결한다. 별도 발주 여부는 실제 사업 단위가 정해진 뒤 판단한다.');
md=md.replaceAll('비중복 미입증','이미 계약된 동일 납품 범위만 반복 계상').replaceAll('최종 계약 비중복','기존 계약 대비 추가 수행분');
md=md.replace('업무 재확인 2026-09-14. 개별 출처의 최초 조사일·재열람 여부는 각주 참조','기획 개정 2026-09-15 / 업무 조사 2026-09-14 중심, COSAS·ETAS·NOA 및 내부 RTM은 9월 15일 재확인. 세부 출처별 날짜 참조');
if(p.n===9){md=md.replaceAll('안내를 넘는 신규 처리 단계·기존 계약 비중복·API·본인확인','현재 안내·신고 기능, 적용할 CCK 문진·자료 점검·인계 범위, API·본인확인');p.gate='현재 안내·신고 기능, 적용할 CCK 문진·자료 점검·인계 범위, API·본인확인';}
if(p.n===10)md=md.replaceAll('TS-BIZ-003 유보 유지','TS-BIZ-003의 과거 유보는 이력이며 이번 AI 추가 적용 기준으로 재검토');
if(p.n===15){p.gate='공통 상담 내 적용할 질문·공식 안내·예외 사례와 업무별 추가 공수·효과';md=md.replaceAll(old.gate,p.gate);}
const insert=`## 0. 기구축 기반의 CCK AI 적용·중복 재판정\n\n2026-09-15 사용자 정정에 따라 기존 시스템·업무·안내·AI 사업의 후속 적용도 기획 대상에 포함했다. 이전의 **${p.previous_status}**를 **${p.status}**로 재판정했다. 이번 기획 판정이며 제품 동작·계약 중복을 확정한 결과는 아니다.[^49]\n\n| 구분 | 이번 적용안 |\n|---|---|\n| 기존 기반 | ${p.existing} |\n| CCK AI 추가 적용 | ${p.ai} |\n| 22개 기획 사이 관계 | ${p.relationship} |\n| 별도로 산정할 추가 작업 | ${p.delta} |\n| 유지·재사용 | 기존 DB·업무규칙·조회/접수 시스템·사용 가능한 NOA 기능 |\n| 비용 처리 | 기존 자산 구매비·이미 계약된 동일 납품분은 추가 개발비에서 제외. 실제 설치·설정·지식 정비·연계·검증·운영 추가 작업은 산정 가능 |\n\n**판정 이유:** ${p.reason}.\n\n`;
md=md.replace('## 1. 실제 업무와 기획 대상',insert+'## 1. 실제 업무와 기획 대상');
const nums=[...new Set([...md.matchAll(/\[\^(\d+)\]/g)].map(m=>+m[1]))];md=md.slice(0,md.lastIndexOf('\n## 출처'))+foot(nums);
md=md.replace('[통합 기획 비교표](../00_사업기획_통합보기.html)','[중복 검토·추가 적용](../00_중복검토_및_AI추가적용.html) · [통합 기획 비교표](../00_사업기획_통합보기.html)');
fs.writeFileSync(path.join(out,p.document),md);fs.writeFileSync(path.join(out,p.html),html(p.id+' '+p.title,md,`<div class="actions"><a href="../00_중복검토_및_AI추가적용.html">중복·AI 적용 판단</a><a href="../00_사업기획_통합보기.html">22개 기획 비교</a><a download href="${esc(p.filename)}.md">Markdown</a></div>`));
}
let report='# TS 22개 기획 중복 검토와 CCK AI 추가 적용\n\n';
report+='**기구축 사업도 CCK AI 적용 대상이다.** 기존 기능과 같은 이름의 업무라도 AI 안내·문서 검토·결과 해석·처리 지원을 추가하거나 개선하는 사업으로 검토한다. 이전 문서에서 기존 사업·안내라는 이유로 지나치게 좁힌 판단을 수정했다. `cckal ai`는 문맥상 CCK AI, 즉 기존에 합의한 NOA·로컬 LLM 적용으로 해석했다.[^49]\n\n';
report+='## 1. 중복을 세 가지로 구분\n\n| 구분 | 이번 판단 | 사업·비용 처리 |\n|---|---|---|\n| 이미 구축된 업무·시스템이 있음 | CCK AI를 적용할 기반 | 기존 DB·화면·규칙·접수·분석 결과를 활용하고 AI 적용·연계 추가 작업 산정 |\n| 22개 기획끼리 기능·산출물이 겹침 | 통합 또는 구성요소 재사용 | 공통 기능 1회 + 업무별 지식·연계·평가 증분 |\n| 이미 계약된 동일 AI 기능·납품물이 있음 | 계약 이행·재사용과 새 추가 범위를 구분 | 같은 납품분을 다시 새 개발비로 계상하지 않음. 새 적용·변경·시험·운영은 확인된 추가 공수 산정 |\n\n';
report+='기존과 다른 완전한 신규 업무여야만 한다는 조건은 제거했다. 절차 안내·상담도 CCK AI 적용 대상이며, 실제 효과와 적정 규모는 검증한다. 기존에 AI가 있다고 해도 적용 대상·성능 목표·업무 연결·배포 방식이 달라지는 고도화는 비교 가능한 추가 과업으로 정의할 수 있다. 동일성은 업무·대상자·입력·기능·산출물·성과·납품 버전을 함께 비교한다.\n\n';
report+='## 2. 통합·공유할 주요 관계\n\n아래는 **기획안 문면 비교로 확인한 중첩과 재사용 판단**이다. 기존 운영 시스템의 모든 기능이나 최종 계약을 확인한 판정은 아니다.\n\n| 기획 | 관계 | 겹치는 부분 | 유지할 차이·처리 |\n|---|---|---|---|\n';
for(const x of review.relations)report+=`| P${String(x.a).padStart(2,'0')} · P${String(x.b).padStart(2,'0')} | ${x.type} | ${x.shared} | ${x.difference}. ${x.action} |\n`;
report+='\nP01·P17은 같은 점검 흐름의 업무 기능과 시스템 연계이므로 한 적용 사업으로 구성하는 것이 타당하다. P21·P22는 교육 공통 기능과 이륜차 과정 모듈로 묶는다. 나머지는 기능의 일부가 겹치거나 기술을 공유하는 관계이며 업무 자체를 지우지 않는다. 22개 업무 ID는 유지하며 이를 확정 발주 건수로 환산하지 않는다.\n\n';
report+='## 3. 기구축 기반과 추가할 CCK AI — 22개 전체\n\n| 기획서 | 기존 기반 | CCK AI로 추가할 일 | 별도 산정할 추가 작업 | 현재 방향 |\n|---|---|---|---|---|\n';
for(const p of plans)report+=`| ${link(p.id+' '+p.title,p.html)} | ${p.existing} | ${p.ai} | ${p.delta} | ${p.status} |\n`;
report+='\n각 문서의 0절에 이번 재판정을, 이후 절에 기존 실제 업무·요구사항·자료·책임·예외·지표·원가 입력을 연결했다. 과거 TS-BIZ 후보대장 5건 검토·2건 유보·1건 제외는 과거 집계로 보존하고, 현재 적용 판단은 이 22개 재판정 원장으로 본다. 전세버스 등 현재 수행 중인 동일 납품 과업을 새 비용으로 중복 산정하지 않는다. 완료된 시스템이나 별도 후속 AI 적용이라는 이유만으로 일괄 제외하지 않는다.\n\n';
report+='## 4. 기존 서비스·AI 계약 대조\n\nCOSAS는 운수회사·지자체·공단 협업과 안전정보·진행상황 기능을 안내한다. 이를 활용해 P01의 증빙 대조와 P17의 기존 화면 연결을 CCK AI 추가 적용 범위로 잡았다. 추가 AI 기능이 실제 현행 COSAS에 없다는 사실까지 확인한 것은 아니다.[^8]\n\nETAS는 위험운전 분석·교육 개선 전후 비교·진단표를 안내한다. P16은 확정된 결과를 이해하고 질문·교육에 활용하는 AI 기능으로 정의한다. 통계·분석 엔진 재개발과 구분한다.[^9]\n\nNOA 공개 소개는 폐쇄망 자체 LLM, 문서·업무 연결과 사람 검토를 설명한다. 이번에는 사용자 범위에 맞는 텍스트·지식·업무 지원만 적용하며, 설치 버전·사용권·로컬 동작은 별도로 확인한다.[^33]\n\n| 기존 RTM 범위 | 이번 대조 대상 | 가능한 추가 적용 | 동일 비용을 다시 잡지 않을 부분 |\n|---|---|---|---|\n| SFR-001~005 공통 기반·직무 특화·대화형 지원 | 22개 공통, 특히 P01·02·03·07·10·16 | 새 업무 지식·AI 모듈·기존 화면 연결·품질개선·평가 | 이미 계약된 동일 플랫폼·파이프라인·대화 기능 |\n| SFR-006~007 상담·답변 생성/검토 | 자격·드론·검사·K-패스 등 | 특정 업무의 안내·문진·서류/상태 지원, 기존 AI 확장 | 이미 계약된 동일 상담·신문고 기능·자료 범위 |\n| SFR-008~009 전세버스 공시 AI | 현 수행 범위·후속 아이디어 대조 | 별도 추가 적용분이 있으면 범위·납품 버전·공수로 정의 | 현재 이행해야 할 동일 공시 평가·보고서 납품분 |\n\nRTM의 요구사항 기재를 구현 완료로 보지 않았다. 최종 계약·변경합의·실제 기능·사용권을 확보해야 동일 계약 범위를 확정할 수 있다.[^43]\n\n';
report+='## 5. 비용·범위와 다음 판단\n\n**공통 NOA 활용·구성 1회 + 업무별 지식/규칙/화면/연계/시험의 추가 공수 + 실제 필요한 증분 사용료·운영비**로 산정한다. 기존 제품을 활용하더라도 설치·설정·튜닝·데이터 정비·통합·검증이 새로 필요하면 수행비를 산정할 수 있다. 기존 시스템 원가 전체나 같은 계약의 납품분을 다시 개발비로 잡지 않는다.\n\nCCK 주관·로컬 LLM·기존 서버·신규 인프라 0원, 1차 7억·2차 추가 5억의 목표 상한은 유지한다. 이는 22개 전체 견적이 아니다. P15는 공통 상담의 작은 지식 모듈로 검토할 수 있으며 독립 대형 구축을 전제하지 않는다. 추가 적용 가능성과 CCK의 납품·운영 능력 확정은 별개다.[^48]\n\n';
report+='## 6. 검토 범위와 자료\n\n- 22개 기획의 대상·입력·기능·산출물·기존 판정을 읽고 주요 관계 9쌍을 구체적으로 기록했다.\n- 전체 231쌍은 해당 관계와 공통 기능군 규칙을 전개한 설계 비교표다. 231개 계약·현장 검증이나 자동 의미 유사도 실측이 아니다.\n- [22개 개별기획 통합 목록](00_사업기획_통합보기.html) · [공통 수행설계](01_공통_수행설계.html)\n- [231쌍 비교표](06_기획간_전체비교.md) · [비교 데이터](06_기획간_전체비교.json)\n- [현재 재판정 원장](07_AI추가적용_재판정.json) · [문서 검증 기록](검증기록.md)\n\n';
report+=foot([49,8,9,33,43,48]);
fs.writeFileSync(path.join(out,'00_중복검토_및_AI추가적용.md'),report);fs.writeFileSync(path.join(out,'00_중복검토_및_AI추가적용.html'),html('TS 중복 검토와 CCK AI 추가 적용',report,'<div class="actions"><a href="00_사업기획_통합보기.html">22개 기획서</a><a href="#chapter-2">주요 중복 관계</a><a href="#chapter-3">업무별 AI 적용</a><a download href="00_중복검토_및_AI추가적용.md">Markdown</a></div>'));
let index='# TS 22개 업무별 CCK AI 적용 기획 v0.2\n\n기구축 사업·기존 안내·기존 AI의 후속 적용까지 포함한 2026-09-15 개정본이다. [중복 검토 결과와 적용 기준](00_중복검토_및_AI추가적용.html)에서 달라진 판단을 먼저 볼 수 있다. 22개 업무 ID를 유지하며 사업 선정·계약·예산 확정 건수는 아니다.[^49]\n\n## 적용 방향\n\n기존 시스템은 재사용 기반으로 보고 CCK AI 추가 기능·연계·지식·검증의 수행비를 산정한다. P01+P17, P21+P22는 공통 기능과 업무 모듈로 통합한다. 로컬 LLM·기존 서버·신규 인프라 0원 조건을 유지한다.\n\n## 22개 기획 비교\n\n| ID | 대분류·업무 | 사업기획 | 현재 판단 | 추가 적용 |\n|---|---|---|---|---|\n';
for(const p of plans)index+=`| ${p.id} | ${p.category} / ${p.title} | ${link(p.title,p.html)} · ${link('MD',p.document)} | ${p.status} | ${p.ai} |\n`;
index+='\n## 관련 자료\n\n- [공통 수행설계](01_공통_수행설계.html)\n- [업무 확인 원장](02_업무별_확인원장.json) · [기획 원장](03_사업기획_원장.json)\n- [요구사항 추적](04_요구사항_추적표.json) · [후속 확인](05_후속확인_대기열.md)\n- [231쌍 비교](06_기획간_전체비교.md) · [재판정 원장](07_AI추가적용_재판정.json)\n- [검증 기록](검증기록.md)\n';index+=foot([49]);
fs.writeFileSync(path.join(out,'00_사업기획_통합보기.md'),index);
let ih=html('TS 22개 CCK AI 적용 기획 v0.2',index,'<div class="actions"><a href="00_중복검토_및_AI추가적용.html">중복·AI 적용 검토</a><a href="#chapter-2">22개 비교표</a><a download href="00_사업기획_통합보기.md">Markdown</a></div>');
const cats=[...new Set(plans.map(p=>p.category))],states=[...new Set(plans.map(p=>p.status))];
const control='<div class="filters"><label for="cat">대분류</label><select id="cat"><option value="">전체</option>'+cats.map(c=>'<option>'+esc(c)+'</option>').join('')+'</select><label for="state">판단</label><select id="state"><option value="">전체</option>'+states.map(c=>'<option>'+esc(c)+'</option>').join('')+'</select><label for="q">검색</label><input id="q" type="search" placeholder="업무·AI 적용·ID 검색"><button id="reset">초기화</button><span id="count" role="status" aria-live="polite">22개 기획</span></div>';
ih=ih.replace(/(<h2[^>]+>22개 기획 비교<\/h2>)/,'$1'+control).replace('<table>','<table id="index-table">');
const js=oldHTML.match(/<script>([\s\S]*?)<\/script>/)[1];ih=ih.replace('</body>','<script>'+js+'</script></body>');fs.writeFileSync(path.join(out,'00_사업기획_통합보기.html'),ih);
let common='# 기구축 사업 CCK AI 적용 공통 수행설계\n\n2026-09-15 v0.2. 기존 구축 업무와 AI 기능의 후속 적용·개선을 포함한다.[^49]\n\n## 1. 적용 방식\n\n기존 문서·DB·서비스 화면 → 허용된 조회/자료 연결 → CCK NOA·로컬 LLM의 설명·검토·초안 → 사용자/담당자 확인 → 공식 시스템 인계·결과 확인으로 구성한다. 기존 자료를 쓰는 독립 보조 화면, 기존 화면 내 AI 기능, 허용 API를 통한 처리 지원 중 현재 연계 조건에 맞춰 선택한다. API가 없으면 승인 자료 업로드·내보내기와 공식 화면 인계로 범위를 정할 수 있다.\n\n## 2. 공통 기능과 업무별 추가 작업\n\n| 공통화할 부분 | 각 업무에서 추가할 부분 |\n|---|---|\n| 사용 가능한 NOA 실행·접근권한·근거 UI·감사 | 설치 환경·업무 권한·모델 설정 차이 검증 |\n| 증빙 대조 P01·03·04·05·11·12·17 | 문서 구조·식별자·법정 기준·검토 사례·커넥터 |\n| 안내/처리 P02·07·09·10·15·18·19·20 | 질문·지식·규칙·조회·접수/배차/지급 상태·본인확인 |\n| 보호된 사례 P06·08 | 제도별 분류·보호 규칙·저장/접근 영역·전파 승인 |\n| 기준 변경 P13·14 | 기준군·영향 문서·제작자/시험기관의 승인 절차 |\n| 교육 P16·21·22 | 분석결과·과정·교재·강사 역할·학습 평가 |\n\n공통 기능군은 발주 사업 수가 아니다. P01/P17과 P21/P22의 통합은 중복 개발을 피하는 구성 제안이며 사업 영역을 제외하는 판정이 아니다.\n\n## 3. CCK의 수행·검수\n\nCCK는 사용권이 확인된 솔루션의 구성, 업무 지식·규칙, 화면·연계, 실제 자료 평가, 배포 설정·교육·운영 인수를 총괄하는 역할안이다. 기존 운영사는 조회·변경 인터페이스와 권한·상태 호환을 협의한다. 담당기관이 자격·접수·공개·안전·지급의 최종 권한을 갖는다. 제품 소개가 실제 해당 버전의 구현·품질 증거를 대신하지 않는다.[^33][^48]\n\n## 4. 비용 산식과 계약 대조\n\n기존 구축비 전체를 재산정하지 않고 공통 구성 1회 + 업무별 설정·지식·화면·연계·시험 추가 공수 + 확인된 증분 사용료·운영비로 산정한다. 새 적용을 위한 데이터 정비·설치·설정·튜닝·시험은 수행비 대상이다. 이미 계약된 같은 납품물은 기존 이행 또는 재사용으로 표시한다. 기존 AI의 기능 개선은 전후 기능·수용기준·작업량으로 증분을 설명한다.[^43]\n\n1차 7억·2차 추가 5억은 VAT 포함 해석의 프로그램 목표 상한이며 22개 전체 견적이 아니다. 신규 GPU·서버·저장/백업/망 구매·증설·임차·클라우드 자원비는 0원이다. 기존 환경의 응용 SW 구성·통합·검증 공수는 별도다. 공식 단가·가용인력·물량 확인 전 금액을 확정하지 않는다.[^48]\n\n## 5. 운영·품질\n\n원본·검색 인덱스·로그·백업·라이선스 호출을 포함해 로컬 처리와 접근권한을 확인한다. 변경된 원문·권한을 검색·초안에 반영하고 근거가 없으면 미확인으로 표시한다. 실제 접수 응답 전에 완료라고 하지 않는다. 문서 제안 기능을 중단해도 기존 업무로 복귀할 수 있도록 버전·설정과 원 시스템을 보존한다.\n\n## 6. 적용 규모 결정\n\n기존 기능표 → CCK 적용 단위 → 추가 작업 물량 → 현업 사례·품질/효과 비교 → 공수·견적 → 단계 확대 순서로 본다. 비AI 비교는 적용 규모·효과를 확인하는 방법이며 기구축 업무를 일괄 제외하는 조건이 아니다. P15처럼 작은 안내는 공통 상담 모듈로, P01/P17처럼 같은 업무는 통합 적용으로 구성한다.\n';common+=foot([49,33,48,43]);
fs.writeFileSync(path.join(out,'01_공통_수행설계.md'),common);fs.writeFileSync(path.join(out,'01_공통_수행설계.html'),html('기구축 사업 CCK AI 적용 공통 수행설계',common,'<div class="actions"><a href="00_중복검토_및_AI추가적용.html">검토 결과</a><a href="00_사업기획_통합보기.html">22개 기획</a></div>'));
let pairMD='# 22개 기획 사이 전체 비교표\n\n22×21÷2 = 231쌍. 개별 설계 검토에서 기록한 주요 관계 9쌍과 기능군·입출력 규칙을 전개한 비교표다. 231개 독립 실증·계약 검증이 아니며 계약상 동일성은 모두 미확정이다. 공통 NOA를 사용한다는 이유만으로 사업 중복으로 판정하지 않았다.\n\n| 기획 A | 기획 B | 관계 | 공유 부분 | 구분되는 산출물·업무 | 처리 |\n|---|---|---|---|---|---|\n';for(const x of pairs)pairMD+=`| ${x.a} | ${x.b} | ${x.type} | ${x.shared} | ${x.difference} | ${x.action} |\n`;
fs.writeFileSync(path.join(out,'06_기획간_전체비교.md'),pairMD);fs.writeFileSync(path.join(out,'06_기획간_전체비교.json'),JSON.stringify({date:'2026-09-15',count:231,method:'명시 관계 9쌍 + 기능군·입출력 규칙 전개',contract_verification:false,pairs},null,2));
fs.writeFileSync(path.join(out,'07_AI추가적용_재판정.json'),JSON.stringify({date:'2026-09-15',user_direction:'기구축 사업도 CCK AI 적용 대상으로 포함',history_register_is_not_current_rejection:true,confirmed_contract_duplicates:0,confirmed_contract_duplicates_interpretation:'중복 없음이 아니라 최종 계약상 중복으로 확정한 건수가 없음',items:plans.map(p=>({id:p.id,previous_status:p.previous_status,status:p.status,existing:p.existing,ai:p.ai,delta:p.delta,relationship:p.relationship,reason:p.reason})),key_relations:review.relations},null,2));
const b={...prior,version:'0.2',prepared_at:'2026-09-15',previous_version:'../TS_22개업무_사업기획_2026-09-14/03_사업기획_원장.json',current_scope:'기구축 업무·기존 AI의 추가 적용·고도화 포함',previous_candidate_count_note:'5검토·2유보·1제외는 이전 집계; 이번 개정은 22개 적용 방향 원장에서 관리',plans};fs.writeFileSync(path.join(out,'03_사업기획_원장.json'),JSON.stringify(b,null,2));
for(const f of ['02_업무별_확인원장.json','04_요구사항_추적표.json']){const x=JSON.parse(fs.readFileSync(path.join(prev,f),'utf8'));x.planning_revision='2026-09-15 v0.2';x.revision_note='업무 근거·요구사항 ID 유지. 기구축 AI 적용·중복 판단은 07_AI추가적용_재판정.json 참조';fs.writeFileSync(path.join(out,f),JSON.stringify(x,null,2));}
let queue='# 업무별 AI 추가 적용 확인 목록\n\n기구축 여부를 배제 조건으로 삼지 않는다. 각 업무의 현재 기능·추가 적용·수행비를 확인한다.\n\n| 기획 | 현재 방향 | 현업·운영사와 확인할 자료 |\n|---|---|---|\n';for(const p of plans)queue+=`| ${p.id} | ${p.status} | ${p.gate}; 기존 기능 대비 ${p.delta}의 실제 추가 공수·납품 경계 |\n`;fs.writeFileSync(path.join(out,'05_후속확인_대기열.md'),queue);
fs.writeFileSync(path.join(out,'근거원장.json'),JSON.stringify(src,null,2));
fs.writeFileSync(path.join(out,'README.md'),'# TS 기구축 업무 CCK AI 적용 기획 v0.2\n\n- [중복 검토·AI 추가 적용 HTML](00_중복검토_및_AI추가적용.html) · [Markdown](00_중복검토_및_AI추가적용.md)\n- [22개 기획서 목록](00_사업기획_통합보기.html) · [MD](00_사업기획_통합보기.md)\n- [공통 수행설계](01_공통_수행설계.html)\n- [현재 재판정](07_AI추가적용_재판정.json) · [231쌍 비교](06_기획간_전체비교.md)\n- [검증 기록](검증기록.md)\n\n기존 사업에도 CCK AI 적용을 검토한다. 기존 계약의 동일 납품분 재계상과 실제 추가 적용 수행비를 구분한다. 기존 후보 집계는 이력, 현재 22개 적용 판단은 이 개정본 기준이다. 인프라 0원·로컬 LLM·CCK 주관 조건 유지.\n');
fs.writeFileSync(path.join(out,'검증기록.md'),'# 검증 기록\n\n2026-09-15 기획 개정. 실제 제품·계약 전수검증은 미수행. 문서·화면 검증 결과를 추가 기록한다.\n');
for(const f of ['ts22_v02_data.cjs','ts22_v02_build.cjs'])fs.copyFileSync(path.join(__dirname,f),path.join(out,f));
console.log(JSON.stringify({out,plans:plans.length,pairs:pairs.length,relations:review.relations.length,sources:src.sources.length,statuses:plans.reduce((a,p)=>(a[p.status]=(a[p.status]||0)+1,a),{})},null,2));
