const fs=require('node:fs/promises'),path=require('node:path');
const {pathToFileURL,fileURLToPath}=require('node:url');
const {chromium}=require('C:/Users/김희섭/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{
 const base=__dirname,out=path.join(base,'검증');await fs.mkdir(out,{recursive:true});
 const model=JSON.parse(await fs.readFile(path.join(base,'후보별_검토결과.json'),'utf8'));
 const sources=JSON.parse(await fs.readFile(path.join(base,'근거원장.json'),'utf8')).sources;
 const md=await fs.readFile(path.join(base,'00_NOA_병렬조사_통합보고서.md'),'utf8');
 const checks=[],bad=[],errors=[];
 function check(name,pass,detail=''){checks.push({name,pass,detail});if(!pass)throw Error(name+': '+detail);}
 check('7개 후보 전체·중복 없음',model.services.length===7&&new Set(model.services.map(s=>s.id)).size===7);
 check('두 서비스 축 3개·4개',model.services.filter(x=>x.axis==='A').length===3&&model.services.filter(x=>x.axis==='B').length===4);
 check('기존 36개 메뉴 고유 ID',model.menu_mapping.length===36&&new Set(model.menu_mapping.map(s=>s.id)).size===36);
 check('36개 근거 고유 ID',sources.length===36&&new Set(sources.map(s=>s.id)).size===36);
 check('모든 후보 근거 ID 유효',model.services.every(s=>s.refs.every(r=>sources.some(x=>x.id===r))));
 check('모든 후보 검토항목 완성',model.services.every(s=>['problem','existing','minimum','data','reuse','build','split','compare','gate','stop','case'].every(k=>s[k]&&s[k].length>10)));
 check('인프라0·KoROAD·미검증 경계',model.infrastructure_investment===0&&model.institution==='ORG-0002'&&model.status.includes('검증 전'));
 check('핵심 정정 사항 MD 포함',['R01','계약','R02','재배포','수집건수','인증 호출','NL2SQL','비AI','2024-07-31'].every(s=>md.includes(s)));
 const browser=await chromium.launch({channel:'msedge',headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1050}});page.on('pageerror',e=>errors.push(String(e)));
 const url=pathToFileURL(path.join(base,'00_NOA_병렬조사_통합보고서.html')).href;
 await page.goto(url);await page.addStyleTag({content:'html{scroll-behavior:auto!important}'});
 const links=await page.locator('a[href]').evaluateAll(xs=>xs.map(x=>x.getAttribute('href')));
 for(const link of links){if(/^https?:/.test(link))continue;if(link.startsWith('#')){if(!await page.evaluate(id=>!!document.getElementById(decodeURIComponent(id)),link.slice(1)))bad.push(link);continue;}try{await fs.access(link.startsWith('file:')?fileURLToPath(link):path.resolve(base,decodeURIComponent(link.split('#')[0])));}catch{bad.push(link);}}
 check('로컬 문서·앵커 링크',bad.length===0,bad.join(', '));
 check('HTML 고유 ID',await page.locator('[id]').evaluateAll(xs=>new Set(xs.map(x=>x.id)).size===xs.length));
 check('본문 언어·제목',await page.locator('html').getAttribute('lang')==='ko'&&await page.locator('h1').count()===1);
 await page.keyboard.press('Tab');check('첫 키보드 포커스 본문 건너뛰기',await page.locator('.skip').evaluate(x=>x===document.activeElement));
 await page.evaluate(()=>document.activeElement.blur());await page.screenshot({path:path.join(out,'데스크톱.png')});
 await page.locator('.architecture').screenshot({path:path.join(out,'공통기반_두축.png')});
 await page.locator('#axis').selectOption('A');check('범용 축 필터',await page.locator('.candidate:visible').count()===3);
 await page.locator('#axis').selectOption('B');check('안전 축 필터',await page.locator('.candidate:visible').count()===4);
 await page.locator('#reset').click();await page.locator('#query').fill('N04');check('후보 ID 검색',await page.locator('.candidate:visible').count()===1&&await page.locator('#N04').isVisible());
 await page.locator('#query').fill('없는후보XYZ123');check('빈 검색 결과',await page.locator('#empty').isVisible()&&await page.locator('.candidate:visible').count()===0);
 await page.locator('#reset').click();check('필터 초기화',await page.locator('.candidate:visible').count()===7);
 await page.locator('#expand').click();check('전체 펼침',await page.locator('.candidate[open]').count()===7);
 await page.locator('#collapse').click();check('전체 접기',await page.locator('.candidate[open]').count()===0);
 await page.goto(url+'#N04');check('후보 직접 링크 펼침',await page.locator('#N04').getAttribute('open')!==null);
 await page.locator('#N04').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'N04_상세.png')});
 await page.goto(url+'#src-R01');check('근거 직접 링크 펼침',await page.locator('#src-R01').getAttribute('open')!==null);
 check('데스크톱 문서 가로 넘침 없음',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.setViewportSize({width:390,height:844});await page.goto(url);await page.screenshot({path:path.join(out,'모바일.png')});
 check('390px 문서 가로 넘침 없음',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.goto(url+'#N04');await page.waitForFunction(()=>{const r=document.querySelector('#N04').getBoundingClientRect();return r.top>=45&&r.top<160;});check('모바일 직접 링크 실제 위치',await page.locator('#N04').evaluate(x=>x.getBoundingClientRect().top<160));await page.screenshot({path:path.join(out,'모바일_N04.png')});
 check('390px 상세 가로 넘침 없음',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.setViewportSize({width:320,height:800});check('320px 문서 가로 넘침 없음',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.evaluate(()=>window.dispatchEvent(new Event('beforeprint')));check('인쇄 시 후보·근거 전체 펼침',await page.locator('details[open]:visible').count()===43);
 await page.evaluate(()=>window.dispatchEvent(new Event('afterprint')));check('인쇄 후 상태 복원',await page.locator('.candidate[open]').count()===1);
 check('브라우저 스크립트 오류 없음',errors.length===0);
 await fs.writeFile(path.join(out,'검증결과.json'),JSON.stringify({date:'2026-09-11',checks,errors,bad,limits:'설명문서 구조·브라우저 기능 검사. 실제 NOA·기관 시스템·API·전체 WCAG 검수 아님.'},null,2));
 await browser.close();console.log(JSON.stringify({checks:checks.length,passed:checks.filter(x=>x.pass).length,errors,bad}));
})().catch(e=>{console.error(e);process.exit(1)});
