const fs=require('fs'),path=require('path'),{pathToFileURL,fileURLToPath}=require('url');const {chromium}=require('C:/Users/김희섭/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const out='G:/내 드라이브/1. 업무영역/6. CCK/1. 사업관리/TS/bizops/[TS 사업기획]/05_통합사업기획/P23_정책기획_예산요구_발주전환_v1.1_2026-09-15/시각설계_v1.2';const qdir=path.join(out,'검증');fs.mkdirSync(qdir,{recursive:true});const model=JSON.parse(fs.readFileSync(path.join(out,'원장_도식과_서비스.json'),'utf8'));const checks=[],fail=[];const ck=(name,ok,detail)=>{checks.push({name,pass:!!ok,detail});if(!ok)fail.push({name,detail});};
const files=fs.readdirSync(out).filter(f=>f.endsWith('.html'));let links=0;for(const f of files){const html=fs.readFileSync(path.join(out,f),'utf8');ck(f+' 주제목 1개',(html.match(/<h1>/g)||[]).length===1);for(const m of html.matchAll(/(?:href|src)="([^"]+)"/g)){if(/^(https?:|data:|blob:)/.test(m[1]))continue;const u=new URL(m[1],pathToFileURL(path.join(out,f)));if(u.protocol==='file:'){links++;ck('연결 '+f+' '+m[1],fs.existsSync(fileURLToPath(u)));}}}
const crosses=[];for(const g of model.graphs){for(const e of g.edges){ck('선 끝점 '+g.id+' '+e.from+'→'+e.to,g.nodes.some(n=>n.id===e.from)&&g.nodes.some(n=>n.id===e.to));for(const n of g.nodes.filter(n=>![e.from,e.to].includes(n.id))){for(let i=1;i<e.points.length;i++){const a=e.points[i-1],b=e.points[i],inX=a[0]===b[0]&&a[0]>n.x+5&&a[0]<n.x+n.w-5&&Math.max(a[1],b[1])>n.y+5&&Math.min(a[1],b[1])<n.y+n.h-5,inY=a[1]===b[1]&&a[1]>n.y+5&&a[1]<n.y+n.h-5&&Math.max(a[0],b[0])>n.x+5&&Math.min(a[0],b[0])<n.x+n.w-5;if(inX||inY)crosses.push({graph:g.id,edge:e.from+'→'+e.to,node:n.id,segment:[a,b]});}}}}
ck('연결선이 무관한 노드를 관통하지 않음',crosses.length===0,crosses);
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage();const errors=[],network=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))network.push(r.url());});let nodes=0,viewports=0;for(const f of files){for(const width of [1440,768,390]){await page.setViewportSize({width,height:1050});await page.goto(pathToFileURL(path.join(out,f)).href);await page.evaluate(()=>document.fonts.ready);const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);ck('문서 가로넘침 '+f+' '+width,!overflow);viewports++;}}
for(const g of model.graphs){await page.setViewportSize({width:1440,height:1050});await page.goto(pathToFileURL(path.join(out,model.names[g.id]+'.html')).href);for(const n of g.nodes){await page.locator('#nodeSelect').selectOption(n.id);const expected=model.defs[n.key];const text=await page.locator('#detail').innerText();ck('노드 입출력 '+g.id+' '+n.id,text.includes(expected.input)&&text.includes(expected.output)&&text.includes(expected.human)&&text.includes(expected.exception));nodes++;}const bounds=await page.evaluate(()=>{const m=window.P23Visual.graphs.find(g=>g.id===document.body.dataset.page);return [...document.querySelectorAll('.node')].flatMap(el=>{const n=m.nodes.find(n=>n.id===el.dataset.node);return [...el.querySelectorAll('text')].flatMap(t=>{const b=t.getBBox();return b.x<n.x+7||b.x+b.width>n.x+n.w-7||b.y<n.y+5||b.y+b.height>n.y+n.h-5?[{node:n.id,text:t.textContent,b:{x:b.x,y:b.y,w:b.width,h:b.height},box:n}]:[];});});});ck('노드 글자 경계 '+g.id,bounds.length===0,bounds);const edgeBounds=await page.evaluate(()=>{const svg=document.querySelector('.canvas svg'),v=svg.viewBox.baseVal;return [...svg.querySelectorAll('.edge text')].flatMap(t=>{const b=t.getBBox();return b.x<0||b.x+b.width>v.width||b.y<0||b.y+b.height>v.height?[{text:t.textContent,x:b.x,y:b.y,w:b.width,h:b.height}]:[];});});ck('연결 설명 잘림 없음 '+g.id,edgeBounds.length===0,edgeBounds);const labelOverlaps=await page.evaluate(()=>{const m=window.P23Visual.graphs.find(g=>g.id===document.body.dataset.page);return [...document.querySelectorAll('.edge text')].flatMap(t=>{const b=t.getBBox();return m.nodes.filter(n=>b.x<n.x+n.w&&b.x+b.width>n.x&&b.y<n.y+n.h&&b.y+b.height>n.y).map(n=>({label:t.textContent,node:n.id}));});});ck('연결 설명·상자 겹침 없음 '+g.id,labelOverlaps.length===0,labelOverlaps);
for(const scenario of Object.keys(model.scenarios)){await page.locator('[data-scenario="'+scenario+'"]').click();ck('시나리오 설명 '+g.id+' '+scenario,(await page.locator('#scenario-message').innerText()).includes(model.scenarios[scenario].message));if(scenario!=='normal'){const expected=g.nodes.filter(n=>model.scenarios[scenario].keys.includes(n.key)).length;ck('시나리오 노드 강조 '+g.id+' '+scenario,await page.locator('.node.scenario').count()===expected);}}
await page.locator('[data-scenario="normal"]').click();await page.locator('#zoomIn').click();ck('확대 '+g.id,(await page.locator('#zoomValue').innerText())==='120%');await page.locator('#zoomReset').click();ck('기본 배율 '+g.id,(await page.locator('#zoomValue').innerText())==='100%');const first=g.nodes[0];const node=page.locator('[data-node="'+first.id+'"]');await node.focus();await page.keyboard.press('Enter');ck('키보드 노드 선택 '+g.id,(await page.locator('#nodeSelect').inputValue())===first.id);
await page.screenshot({path:path.join(qdir,g.id+'_데스크톱.png'),fullPage:true});if(g.id==='service'||g.id==='logic'){await page.screenshot({path:'C:/Users/Public/Documents/ESTsoft/CreatorTemp/p23v12_'+g.id+'.png'});}}
await page.goto(pathToFileURL(path.join(out,model.names.screens+'.html')).href);for(let i=0;i<model.stages.length;i++){await page.locator('[data-stage="'+i+'"]').click();const text=await page.locator('#screenContent').innerText();ck('사용자 화면 '+i,text.includes(model.stages[i].title)&&text.includes(model.stages[i].result));ck('화면·로직 연결 '+i,(await page.locator('#detail').innerText()).includes(model.defs[model.stages[i].key].action));}ck('마지막 다음 버튼 비활성',await page.locator('#nextStage').isDisabled());await page.locator('[data-stage="0"]').click();ck('첫 화면 이전 비활성',await page.locator('#previousStage').isDisabled());await page.locator('#nextStage').click();ck('다음 화면 전환',(await page.locator('#screenContent').innerText()).includes(model.stages[1].title));await page.screenshot({path:'C:/Users/Public/Documents/ESTsoft/CreatorTemp/p23v12_screens.png'});await page.screenshot({path:path.join(qdir,'사용자화면_데스크톱.png'),fullPage:true});await page.setViewportSize({width:390,height:844});await page.goto(pathToFileURL(path.join(out,model.names.concept+'.html')).href);await page.locator('#nodeSelect').selectOption('C04');await page.screenshot({path:'C:/Users/Public/Documents/ESTsoft/CreatorTemp/p23v12_mobile.png'});await page.screenshot({path:path.join(qdir,'모바일_컨셉.png'),fullPage:true});
await page.goto(pathToFileURL(path.join(out,model.names.concept+'.html')).href);await page.keyboard.press('Tab');ck('본문 이동 포커스',await page.evaluate(()=>document.activeElement.classList.contains('skip')));await page.keyboard.press('Enter');ck('본문 이동',await page.evaluate(()=>document.activeElement.id==='main'));ck('브라우저 오류 없음',!errors.length,errors);ck('외부 네트워크 요청 없음',!network.length,network);await browser.close();
const report={date:'2026-09-15',pages:files.length,graphs:model.graphs.length,nodes,screen_stages:model.stages.length,links,viewports,checks:checks.length,failures:fail,results:checks,product_tests_run:0};fs.writeFileSync(path.join(qdir,'자동검증.json'),JSON.stringify(report,null,2));fs.copyFileSync(__filename,path.join(out,'작성자료/p23v12_qa.cjs'));console.log(JSON.stringify({...report,results:undefined},null,2));if(fail.length)process.exitCode=1;
})();
